import type { LocaleDefinition } from '@stacksjs/ts-faker'

export const no: LocaleDefinition = {
  title: 'Norwegian',
  person: {
    firstNameMale: [
      'Jakob',
      'Emil',
      'Noah',
      'Oliver',
      'Filip',
      'William',
      'Lucas',
      'Liam',
      'Henrik',
      'Aksel',
      'Kasper',
      'Mathias',
      'Oskar',
      'Magnus',
      'Tobias',
      'Isak',
      'Jonas',
      'Sander',
      'Viktor',
      'Håkon',
      'Lars',
      'Ole',
      'Per',
      'Bjørn',
      'Erik',
      'Gunnar',
      'Knut',
      'Svein',
      'Arne',
      'Thor',
      'Eirik',
      'Kristian',
      'Andreas',
      'Martin',
      'Daniel',
      'Alexander',
      'Sebastian',
      'Elias',
      'Adrian',
      'Johannes',
    ],
    firstNameFemale: [
      'Emma',
      'Nora',
      'Sofie',
      'Ella',
      'Emilie',
      'Olivia',
      'Leah',
      'Ingrid',
      'Maja',
      'Tiril',
      'Sara',
      'Thea',
      'Alma',
      'Kari',
      'Anne',
      'Marit',
      'Astrid',
      'Solveig',
      'Greta',
      'Signe',
      'Frida',
      'Ida',
      'Julie',
      'Maria',
      'Kristine',
      'Hanna',
      'Lisa',
      'Hilde',
      'Tone',
      'Line',
      'Silje',
      'Marte',
      'Helene',
      'Vilde',
      'Amalie',
      'Aurora',
      'Hedda',
      'Selma',
      'Agnes',
      'Mathilde',
    ],
    firstNameNeutral: [
      'Kim',
      'Andrea',
      'Robin',
      'Alex',
      'Charlie',
      'Mika',
      'Remi',
      'Sasha',
      'Ariel',
      'Morgan',
    ],
    lastName: ['Hansen', 'Johansen', 'Olsen', 'Larsen', 'Andersen', 'Pedersen', 'Nilsen', 'Kristiansen', 'Jensen', 'Karlsen', 'Johnsen', 'Pettersen', 'Eriksen', 'Berg', 'Haugen', 'Hagen', 'Bakke', 'Lie', 'Dahl', 'Solberg', 'Lund', 'Moen', 'Nguyen', 'Sørensen', 'Rasmussen', 'Strand', 'Holm', 'Kristoffersen', 'Myhre', 'Andresen', 'Jacobsen', 'Halvorsen', 'Bjørklund', 'Søberg', 'Amundsen', 'Isaksen', 'Knutsen', 'Nilssen', 'Rønning', 'Evensen'],
    gender: ['Mann', 'Kvinne', 'Annet'],
    jobTitle: ['Programvareutvikler', 'Prosjektleder', 'Designer', 'Markedssjef', 'Salgssjef', 'Regnskapsfører', 'Advokat', 'Lege', 'Sykepleier', 'Lærer', 'Professor', 'Forsker', 'Dataanalytiker', 'Produktsjef', 'HR-sjef', 'Konsulent', 'Arkitekt', 'Ingeniør', 'Tekniker', 'Kokk', 'Forfatter', 'Journalist', 'Fotograf', 'Kunstner', 'Musiker'],
    prefix: ['Hr.', 'Fru', 'Frk.', 'Dr.', 'Prof.', 'Ing.'],
    suffix: ['Jr.', 'Sr.', 'II', 'III', 'IV'],
  },
  address: {
    street: ['Karl Johans gate', 'Storgata', 'Torggata', 'Bogstadveien', 'Grensen', 'Prinsens gate', 'Kirkegata', 'Tollbugata', 'Møllergata', 'Torgallmenningen', 'Nordre gate', 'Sørgate', 'Parkveien', 'Skolegata', 'Havnegata', 'Fjordgata', 'Strandveien', 'Kongens gate', 'Dronningens gate', 'Slottsveien', 'Bygdøy allé', 'Frognerveien', 'Holtegata', 'Rådhusgata', 'Jernbanetorget', 'Youngstorget', 'Sørenga', 'Aker brygge', 'Tjuvholmen', 'Grünerløkka'],
    city: ['Oslo', 'Bergen', 'Stavanger', 'Trondheim', 'Drammen', 'Fredrikstad', 'Kristiansand', 'Sandnes', 'Tromsø', 'Sarpsborg', 'Skien', 'Ålesund', 'Sandefjord', 'Haugesund', 'Tønsberg', 'Moss', 'Porsgrunn', 'Bodø', 'Arendal', 'Hamar', 'Larvik', 'Halden', 'Askøy', 'Lillehammer', 'Mo i Rana', 'Molde', 'Kongsberg', 'Harstad', 'Horten', 'Gjøvik'],
    state: ['Oslo', 'Viken', 'Innlandet', 'Vestfold og Telemark', 'Agder', 'Rogaland', 'Vestland', 'Møre og Romsdal', 'Trøndelag', 'Nordland', 'Troms og Finnmark'],
    country: ['Norge', 'Sweden', 'Danmark', 'Finland', 'Island'],
    zipCode: ['####'],
    direction: ['Nord', 'Sør', 'Øst', 'Vest', 'Nordøst', 'Nordvest', 'Sørøst', 'Sørvest'],
  },
  company: {
    name: ['Equinor', 'DNB', 'Telenor', 'Norsk Hydro', 'Yara', 'Aker', 'Schibsted', 'Orkla', 'Storebrand', 'Gjensidige', 'Mowi', 'Salmar', 'Kongsberg Gruppen', 'Tomra', 'Norske Skog', 'Subsea 7', 'Wilh. Wilhelmsen', 'Posten Norge', 'Rema 1000', 'Kiwi', 'Coop', 'NorgesGruppen', 'XXL', 'Komplett', 'Finn.no', 'Vipps', 'Kahoot', 'Opera', 'Zwipe', 'AutoStore'],
    industry: ['Olje og gass', 'Skipsfart', 'Fiskeri', 'Akvakultur', 'Energi', 'Teknologi', 'Telekommunikasjon', 'Bank og finans', 'Forsikring', 'Detaljhandel', 'Eiendom', 'Bygg og anlegg', 'Industri', 'Helsevesen', 'Utdanning', 'Transport', 'Turisme', 'Medier', 'Reklame', 'Konsulentvirksomhet'],
    buzzword: ['innovasjon', 'bærekraft', 'digitalisering', 'grønn omstilling', 'havvind', 'hydrogen', 'karbonfangst', 'elektrifisering', 'sirkulærøkonomi', 'kunstig intelligens', 'automatisering', 'dataanalyse', 'smidig utvikling', 'velferdsteknologi', 'smart by', 'deleøkonomi', 'plattformøkonomi', 'fintech', 'martech', 'cleantech', 'bioøkonomi', 'presisjonsmedisin', 'Industry 4.0', 'tingenes internett', 'blokkjede'],
  },
  internet: {
    domainName: ['vg.no', 'nrk.no', 'aftenposten.no', 'finn.no', 'nav.no', 'yr.no', 'tv2.no', 'dagbladet.no', 'dn.no', 'bt.no', 'e24.no', 'klikk.no', 'adressa.no', 'sol.no', 'digi.no', 'tek.no', 'komplett.no', 'elkjop.no', 'power.no', 'xxl.no', 'zalando.no', 'boozt.com', 'spotify.com', 'netflix.com'],
  },
  phone: {
    number: ['## ## ## ##', '+47 ## ## ## ##', '9## ## ###', '4## ## ###', '9#######', '4#######'],
  },
  food: {
    dish: ['Fårikål', 'Raspeballer', 'Pinnekjøtt', 'Lutefisk', 'Rakfisk', 'Smalahove', 'Fenalår', 'Klippfisk', 'Fiskesuppe', 'Fiskeburger', 'Fiskekaker', 'Kjøttkaker', 'Lapskaus', 'Sodd', 'Rømmegrøt', 'Flatbrød', 'Lefse', 'Krumkake', 'Vafler', 'Brunost', 'Pølse med lompe', 'Grandiosa', 'Tacos', 'Bacalao', 'Reker', 'Kjøttboller', 'Svineribba', 'Medisterkaker', 'Børek', 'Makrell i tomat'],
    ingredient: ['Torsk', 'Laks', 'Makrell', 'Sild', 'Reker', 'Krabbe', 'Lam', 'Reinsdyr', 'Elg', 'Røkt kjøtt', 'Brunost', 'Rømme', 'Melk', 'Smør', 'Egg', 'Poteter', 'Kål', 'Gulrøtter', 'Løk', 'Erter', 'Bønner', 'Havre', 'Bygg', 'Rug', 'Hvete', 'Tyttebær', 'Blåbær', 'Multer', 'Bringebær', 'Kanel'],
    cuisine: ['Norsk', 'Skandinavisk', 'Italiensk', 'Fransk', 'Asiatisk', 'Thai', 'Indisk', 'Kinesisk', 'Japansk', 'Meksikansk', 'Amerikansk', 'Gresk', 'Tyrkisk', 'Spansk', 'Portugisisk', 'Vegetar', 'Vegan', 'Glutenfri', 'Sjømat', 'Grill'],
    dessert: ['Bløtkake', 'Kransekake', 'Tørrhjul', 'Berlinerkranser', 'Krumkake', 'Goro', 'Vafler', 'Tilslørte bondepiker', 'Riskrem', 'Is', 'Sjokolademousse', 'Eplekake', 'Blåbærpai', 'Jordbærkake', 'Karamellpudding', 'Panna cotta', 'Tiramisu', 'Brownies', 'Cookies', 'Ostekake'],
    fruit: ['Eple', 'Pære', 'Plomme', 'Kirsebær', 'Jordbær', 'Bringebær', 'Blåbær', 'Tyttebær', 'Multer', 'Solbær', 'Rips', 'Stikkelsbær', 'Banan', 'Appelsin', 'Sitron', 'Lime', 'Mango', 'Ananas', 'Druer', 'Vannmelon'],
    vegetable: ['Poteter', 'Gulrøtter', 'Kålrot', 'Hodekål', 'Blomkål', 'Brokkoli', 'Rosenkål', 'Løk', 'Hvitløk', 'Purre', 'Selleri', 'Paprika', 'Tomat', 'Agurk', 'Salat', 'Spinat', 'Grønnkål', 'Squash', 'Gresskar', 'Erter', 'Bønner', 'Mais', 'Reddik', 'Asparges', 'Sopp'],
    meat: ['Lammekjøtt', 'Svinekjøtt', 'Storfekjøtt', 'Kylling', 'Kalkun', 'And', 'Reinsdyr', 'Elg', 'Hjort', 'Rådyr', 'Koteletter', 'Entrecôte', 'Mørbrad', 'Indrefilet', 'Ytrefilet', 'Ryggstykke', 'Bog', 'Skank', 'Kjøttdeig', 'Pølse'],
    spice: ['Salt', 'Pepper', 'Karri', 'Paprika', 'Chili', 'Ingefær', 'Hvitløk', 'Løk', 'Persille', 'Dill', 'Timian', 'Rosmarin', 'Basilikum', 'Oregano', 'Revet muskatnøtt', 'Nellik', 'Kardemomme', 'Kanel', 'Vanilje', 'Laurbærblad'],
  },
  animal: {
    dog: ['Norsk elghund', 'Norsk lundehund', 'Norsk buhund', 'Norsk moosehund', 'Haldenstøver', 'Dunker', 'Hygenhund', 'Labrador', 'Golden retriever', 'Schæfer', 'Rottweiler', 'Boxer', 'Beagle', 'Cocker spaniel', 'Jack Russell terrier', 'Border collie', 'Sheltie', 'Cavalier King Charles spaniel', 'Chihuahua', 'Pudel', 'Dachs', 'Yorkshire terrier', 'Bichon frisé', 'Mops', 'Bulldog'],
    cat: ['Norsk skogkatt', 'Husskatt', 'Perser', 'Maine coon', 'Ragdoll', 'Birma', 'Siamese', 'Bengalkatt', 'Abessiner', 'Russisk blå', 'Sphynx', 'British shorthair', 'Scottish fold', 'Burmeserkatt', 'Chartreux', 'Devon rex', 'Cornish rex', 'Singapura', 'Tonkineser', 'Korat'],
    bird: ['Lunde', 'Alke', 'Lomvi', 'Teist', 'Ørn', 'Haukugle', 'Hornugle', 'Tjeld', 'Rype', 'Orrfugl', 'Storfugl', 'Jerpe', 'Måke', 'Terne', 'Skarv', 'Hegre', 'Svane', 'Gjess', 'And', 'Trane', 'Stork', 'Spett', 'Lerke', 'Trost', 'Stær'],
    fish: ['Torsk', 'Sei', 'Hyse', 'Lyr', 'Lange', 'Brosme', 'Laks', 'Sjøørret', 'Ørret', 'Røye', 'Harr', 'Sik', 'Gjedde', 'Abbor', 'Lake', 'Gullbust', 'Mort', 'Ål', 'Flyndre', 'Kveite', 'Rødspette', 'Steinbit', 'Uer', 'Breiflabb', 'Makrell'],
    horse: ['Fjordhest', 'Dølahest', 'Norsk kallblodig traver', 'Nordlandshest', 'Araber', 'Islandshest', 'Shetlandspony', 'Welsh pony', 'Varmblods', 'Fullblods', 'Kaldblods', 'Lipizzaner', 'Friese', 'Andalusier', 'Hannoveraner'],
    rabbit: ['Norsk hvitkanin', 'Huskanin', 'Harkanin', 'Villkanin', 'Dvergkanin', 'Løvehodekanin', 'Angora', 'Rex', 'Lop', 'Chinchilla', 'Flemish giant', 'Himalaya', 'Holland lop', 'Mini lop', 'Nederlandsk dverg'],
    insect: ['Sommerfugl', 'Øyenstikker', 'Gresshoppe', 'Bille', 'Bumblebier', 'Bie', 'Veps', 'Humle', 'Maur', 'Midd', 'Edderkopp', 'Mygg', 'Flue', 'Knott', 'Lus', 'Loppe', 'Vårflue', 'Døgnflue', 'Viklere', 'Mølls'],
  },
  sport: {
    sport: ['Fotball', 'Håndball', 'Ishockey', 'Langrenn', 'Skiskyting', 'Alpint', 'Hopp', 'Kombinert', 'Snowboard', 'Friidrett', 'Svømming', 'Sykling', 'Ski', 'Orientering', 'Golf', 'Tennis', 'Volleyball', 'Basketball', 'Bordtennis', 'Badminton', 'Klatring', 'Seiling', 'Roing', 'Padling', 'Bryting'],
    team: ['Rosenborg BK', 'Molde FK', 'Bodø/Glimt', 'Brann', 'Vålerenga', 'Viking FK', 'Strømsgodset', 'Lillestrøm SK', 'Odd', 'Tromsø IL', 'Stabæk', 'Fredrikstad FK', 'Aalesunds FK', 'Sandefjord', 'HamKam', 'Fram Larvik', 'Elverum Håndball', 'Kolstad Håndball', 'Vipers Kristiansand', 'Larvik HK'],
    athlete: ['Therese Johaug', 'Johannes Høsflot Klæbo', 'Marit Bjørgen', 'Ole Einar Bjørndalen', 'Aksel Lund Svindal', 'Kjetil André Aamodt', 'Bjørn Dæhlie', 'Tiril Eckhoff', 'Karsten Warholm', 'Jakob Ingebrigtsen', 'Henrik Ingebrigtsen', 'Erling Haaland', 'Martin Ødegaard', 'Ada Hegerberg', 'Caroline Graham Hansen', 'Magnus Carlsen', 'Casper Ruud', 'Viktor Hovland', 'Nora Mørk', 'Sander Sagosen'],
  },
  music: {
    genre: ['Pop', 'Rock', 'Elektronisk', 'Hip-hop', 'Jazz', 'Klassisk', 'Folk', 'Country', 'Blues', 'Metal', 'Punk', 'Indie', 'R&B', 'Soul', 'Reggae', 'Techno', 'House', 'Trance', 'Drum and bass', 'Dubstep', 'Visepop', 'Russ', 'Trap', 'EDM', 'Ambient'],
    artist: ['a-ha', 'Kygo', 'Alan Walker', 'Sigrid', 'Aurora', 'Nico & Vinz', 'Röyksopp', 'Kings of Convenience', 'Madcon', 'Karpe', 'Gabrielle', 'Ina Wroldsen', 'Highasakite', 'Todd Terje', 'Wardruna', 'Mayhem', 'Dimmu Borgir', 'Kaizers Orchestra', 'Marit Larsen', 'Maria Mena', 'Marcus & Martinus', 'Julie Bergan', 'Astrid S', 'Dagny', 'Girl in Red'],
    song: ['Take On Me', 'The Sun Always Shines on TV', 'Firestone', 'Faded', 'Strangers', 'Running to the Sea', 'Am I Wrong', 'Happy', 'Poor Leno', 'In My Mind', 'Tusen Tegninger', 'Five Months', 'Since We Were Five', 'Inspector Norse', 'Omen', 'Jumpstart', 'Forever Yours', 'Used to Have It All', 'Silence', 'So Am I'],
    instrument: ['Gitar', 'Bass', 'Trommer', 'Piano', 'Keyboard', 'Synthesizer', 'Fiolin', 'Cello', 'Bratsj', 'Kontrabass', 'Fløyte', 'Klarinett', 'Obo', 'Fagott', 'Saksofon', 'Trompet', 'Trombone', 'Tuba', 'Horn', 'Hardingfele', 'Munnharpe', 'Trekkspill', 'Harmonika', 'Ukulele', 'Banjo'],
  },
  commerce: {
    productName: ['Smartphone', 'Laptop', 'Nettbrett', 'Hodetelefoner', 'Høyttaler', 'Mus', 'Tastatur', 'Skjerm', 'Webkamera', 'Lader', 'Kabel', 'Powerbank', 'Smartklokke', 'Sko', 'Veske', 'Lommebok', 'Belte', 'Klokke', 'Solbriller', 'Caps', 'T-skjorte', 'Hettegenser', 'Jeans', 'Jakke', 'Frakk'],
    productAdjective: ['Smart', 'Premium', 'Luksus', 'Best', 'Populær', 'Ny', 'Limitert', 'Tilbud', 'Rabatt', 'Salg', 'Anbefalt', 'Bestselger', 'Nyhet', 'Siste', 'Eksklusiv', 'Praktisk', 'Rimelig', 'Merkevare', 'Original', 'Import', 'Norsk', 'Miljøvennlig', 'Gratis frakt', 'Levering samme dag'],
    productMaterial: ['Lær', 'Bomull', 'Polyester', 'Nylon', 'Silikon', 'Plast', 'Metall', 'Rustfritt stål', 'Aluminium', 'Titan', 'Keramikk', 'Glass', 'Tre', 'Bambus', 'Papir', 'Gummi', 'Skum', 'Latex', 'Ull', 'Cashmere'],
    department: ['Elektronikk', 'Klær', 'Skjønnhet', 'Mat og helse', 'Hjem og kjøkken', 'Møbler', 'Sport', 'Bøker', 'Leker', 'Digital', 'Baby', 'Kjæledyr', 'Bil', 'Verktøy', 'Reise', 'Gaver', 'Barn', 'Data og gaming', 'Foto og lyd', 'Smykker'],
    color: ['Rød', 'Oransje', 'Gul', 'Grønn', 'Blå', 'Lilla', 'Rosa', 'Svart', 'Hvit', 'Grå', 'Brun', 'Beige', 'Marine', 'Khaki', 'Mint', 'Lavendel', 'Korall', 'Burgunder', 'Vin', 'Krem'],
  },
  book: {
    title: ['Sult', 'Mysterier', 'Victoria', 'Pan', 'Kristin Lavransdatter', 'Sofies verden', 'Beatles', 'Naiv. Super', 'Doppler', 'Ut og stjæle hester', 'Mannen som elsket Yngve', 'Sju dager for Elizabeth', 'Margarin', 'Tredje riket', 'De dødes tjern', 'Jernvognen', 'Kimen', 'Under høststjerne', 'Amatørene', 'Min kamp'],
    author: ['Knut Hamsun', 'Sigrid Undset', 'Henrik Ibsen', 'Bjørnstjerne Bjørnson', 'Jostein Gaarder', 'Jo Nesbø', 'Anne Holt', 'Erlend Loe', 'Per Petterson', 'Dag Solstad', 'Karl Ove Knausgård', 'Lars Saabye Christensen', 'Herbjørg Wassmo', 'Roy Jacobsen', 'Vigdis Hjorth', 'Maja Lunde', 'Tore Renberg', 'Stig Sæterbakken', 'Jon Fosse', 'Tarjei Vesaas'],
    publisher: ['Cappelen Damm', 'Gyldendal', 'Aschehoug', 'Forlaget Oktober', 'Flamme', 'Tiden', 'Vigmostad & Bjørke', 'Kagge', 'Samlaget', 'Spartacus', 'Juritzen', 'Pax', 'Solum Bokvennen', 'Font', 'Schibsted', 'Mangschou', 'Strawberry', 'Press', 'Norli', 'Ark'],
    genre: ['Roman', 'Krim', 'Thriller', 'Fantasy', 'Sci-fi', 'Historisk', 'Biografisk', 'Dikt', 'Essay', 'Fagbok', 'Sakprosa', 'Selvbiografi', 'Reise', 'Mat', 'Helse', 'Barn', 'Ungdom', 'Tegneserie', 'Humor', 'Drama'],
    series: ['Harry Hole', 'Kommisær Holt', 'Doppler', 'Min kamp', 'Klimakvartetten', 'Skalpehjellen', 'Jernvognen', 'Sirkus Slottet', 'Doktor Proktor', 'Karsten og Petra', 'Stompa', 'Folk og røvere i Kardemomme by', 'Klatremus', 'Bukkene Bruse', 'Solan og Ludvig', 'Nils Karlsson Pyssling', 'Kaptein Sabeltann', 'Flåklypa', 'Karius og Baktus', 'Gnomene'],
    review: ['Sterkt anbefalt', 'Fantastisk', 'Må leses', 'Rørende', 'Uforglemmelig', 'Gripende', 'Fengslende', 'Mesterverk', 'Briljant', 'Solid', 'Underholdende', 'Spennende', 'Morsom', 'Trist', 'Tankevekkende', 'Imponerende', 'Interessant', 'Kjedelig', 'Forvirrende', 'Overraskende'],
  },
  vehicle: {
    manufacturer: ['Tesla', 'Volkswagen', 'BMW', 'Mercedes-Benz', 'Audi', 'Volvo', 'Toyota', 'Nissan', 'Kia', 'Hyundai', 'Ford', 'Peugeot', 'Renault', 'Skoda', 'Mazda', 'Honda', 'Mitsubishi', 'Subaru', 'Jaguar', 'Land Rover', 'Porsche', 'Ferrari', 'Lamborghini', 'Polestar', 'BYD'],
    model: ['Model 3', 'Model Y', 'ID.4', 'e-Golf', 'i3', 'iX3', 'EQC', 'e-tron', 'XC40', 'XC60', 'XC90', 'Leaf', 'Ariya', 'e-Niro', 'Kona Electric', 'Ioniq 5', 'Mach-E', 'e-208', 'Zoe', 'Enyaq', 'MX-30', 'e', 'Outlander PHEV', 'Solterra', 'I-Pace'],
    type: ['Sedan', 'SUV', 'Stasjonsvogn', 'Coupé', 'Cabriolet', 'Kombi', 'Varebil', 'Pickup', 'Sportsbil', 'Elbil', 'Hybrid', 'Plug-in hybrid', 'Hydrogenbil', 'Småbil', 'Mellomklasse', 'Stor', 'Liten SUV', 'Mellomklasse SUV', 'Stor SUV', 'Minibuss'],
    fuel: ['Bensin', 'Diesel', 'Elektrisk', 'Hydrogen', 'Hybrid', 'Plug-in hybrid', 'Biodiesel', 'Gass', 'Etanol', 'Biogass'],
    bicycle: ['Terrengsykkel', 'Landeveissykkel', 'Hybrid', 'Bysykkel', 'BMX', 'Fixie', 'Cruiser', 'Elsykkel', 'Sammenleggbar sykkel', 'Barn sykkel', 'Touring', 'Gravel', 'Cyclocross', 'Bane', 'Liggesykkel', 'Tandem', 'Barnesykkel', 'Trehjulssykkel', 'Sparkesykkel', 'El-sparkesykkel'],
  },
  word: {
    adjective: ['vakker', 'stor', 'liten', 'god', 'dårlig', 'rask', 'langsom', 'høy', 'lav', 'ny', 'gammel', 'varm', 'kald', 'lys', 'mørk', 'lykkelig', 'trist', 'glad', 'sint', 'redd', 'modig', 'sterk', 'svak', 'smart', 'dum', 'pen', 'stygg', 'ren', 'skitten', 'rik'],
    adverb: ['raskt', 'sakte', 'stille', 'høyt', 'lavt', 'mye', 'lite', 'alltid', 'aldri', 'ofte', 'sjelden', 'kanskje', 'sikkert', 'virkelig', 'veldig', 'ganske', 'litt', 'svært', 'ekstremt', 'nesten', 'omtrent', 'akkurat', 'plutselig', 'gradvis', 'umiddelbart', 'straks', 'senere', 'tidligere', 'nå', 'da'],
    conjunction: ['og', 'eller', 'men', 'dog', 'fordi', 'hvis', 'når', 'mens', 'siden', 'selv om', 'enten', 'eller', 'både', 'så', 'derfor', 'dermed', 'likevel', 'imidlertid', 'dessuten', 'derimot'],
    interjection: ['Å', 'Oi', 'Au', 'Uff', 'Huff', 'Puh', 'Hurra', 'Juhu', 'Jøss', 'Fy', 'Hei', 'Ha', 'Hm', 'Å ja', 'Å nei', 'Jasså', 'Joho', 'Jada', 'Neida', 'Jøss'],
    noun: ['person', 'hus', 'tre', 'blomst', 'vann', 'ild', 'vind', 'himmel', 'jord', 'fjell', 'elv', 'hav', 'sol', 'måne', 'stjerne', 'sky', 'regn', 'snø', 'lyn', 'torden', 'bok', 'skole', 'lærer', 'elev', 'venn', 'familie', 'far', 'mor', 'søster', 'bror'],
    preposition: ['i', 'på', 'til', 'fra', 'med', 'uten', 'for', 'over', 'under', 'ved', 'hos', 'mellom', 'blant', 'gjennom', 'rundt', 'mot', 'om', 'av', 'etter', 'før'],
    verb: ['gå', 'komme', 'spise', 'drikke', 'sove', 'våkne', 'sitte', 'stå', 'ligge', 'løpe', 'hoppe', 'snakke', 'høre', 'se', 'lese', 'skrive', 'lære', 'undervise', 'tenke', 'vite', 'kjenne', 'like', 'elske', 'hate', 'le', 'gråte', 'leke', 'jobbe', 'hvile'],
  },
  hacker: {
    abbreviation: ['AI', 'ML', 'IoT', 'API', 'SDK', 'IDE', 'OS', 'DB', 'SQL', 'HTTP', 'HTTPS', 'REST', 'JSON', 'XML', 'HTML', 'CSS', 'JS', 'UI', 'UX', 'CI/CD', 'DevOps', 'AWS', 'GCP', 'Azure', 'K8s', 'Docker', 'Git', 'SVN', 'FTP', 'SSH'],
    adjective: ['distribuert', 'sky-basert', 'kvante', 'nevral', 'dyp læring', 'maskinlæring', 'blokkjede', 'kryptert', 'hashet', 'komprimert', 'optimalisert', 'skalerbar', 'høytilgjengelig', 'feiltolerant', 'sanntid', 'asynkron', 'synkron', 'parallell', 'distribuert', 'sentralisert'],
    noun: ['algoritme', 'datastruktur', 'protokoll', 'grensesnitt', 'modul', 'pakke', 'bibliotek', 'rammeverk', 'mellomvare', 'database', 'server', 'klient', 'nettverk', 'sikkerhet', 'kryptering', 'hash', 'token', 'økt', 'informasjonskapsel', 'hurtiglager', 'kø', 'stabel', 'heap', 'tre', 'graf', 'array', 'liste', 'map', 'set'],
    verb: ['kjøre', 'kompilere', 'debugge', 'deploye', 'bygge', 'teste', 'optimalisere', 'refaktorere', 'integrere', 'synkronisere', 'kryptere', 'dekryptere', 'hashe', 'komprimere', 'dekomprimere', 'serialisere', 'deserialisere', 'parse', 'validere', 'autentisere'],
    ingverb: ['koding', 'programmering', 'utvikling', 'design', 'analyse', 'testing', 'debugging', 'deployment', 'overvåking', 'logging', 'profilering', 'benchmarking', 'skalering', 'migrering', 'refaktorering', 'optimalisering', 'dokumentasjon', 'review', 'integrasjon', 'automatisering'],
    phrase: ['AI vil endre fremtiden', 'Big data gir innsikt', 'Skyen gir uendelige muligheter', 'Blokkjede bygger tillit', 'Kvante databehandling kommer', 'Maskinlæring predikerer', 'Dyp læring lærer', 'IoT kobler alt sammen', '5G endrer alt', 'Metaverse venter', 'Web3 leder veien', 'NFT er digitale eiendeler', 'Smarte kontrakter automatiserer', 'DeFi innoverer finans', 'DAO desentraliserer', 'Kryssplattform gir effektivitet', 'Mikrotjenester gir skalerbarhet', 'Containere forenkler deployment', 'CI/CD for rask levering', 'DevOps styrker samarbeid'],
  },
  system: {
    fileName: ['dokument', 'rapport', 'presentasjon', 'regneark', 'bilde', 'video', 'lyd', 'arkiv', 'kjørbar', 'konfigurasjon', 'logg', 'sikkerhetskopi', 'midlertidig', 'cache', 'data', 'installasjon', 'oppdatering', 'driver', 'bibliotek', 'skript'],
    fileType: ['dokument', 'bilde', 'video', 'lyd', 'arkiv', 'kjørbar', 'konfigurasjon', 'data', 'sikkerhetskopi', 'logg', 'cache', 'midlertidig', 'system', 'bibliotek', 'driver', 'oppdatering', 'installasjon', 'skrifttype', 'tema', 'plugin'],
  },
  science: {
    chemicalElement: ['Hydrogen', 'Helium', 'Litium', 'Beryllium', 'Bor', 'Karbon', 'Nitrogen', 'Oksygen', 'Fluor', 'Neon', 'Natrium', 'Magnesium', 'Aluminium', 'Silisium', 'Fosfor', 'Svovel', 'Klor', 'Argon', 'Kalium', 'Kalsium', 'Jern', 'Kobber', 'Sink', 'Sølv', 'Gull', 'Kvikksølv', 'Bly', 'Uran', 'Plutonium', 'Radon'],
    unit: ['meter', 'kilogram', 'sekund', 'ampere', 'kelvin', 'mol', 'kandela', 'newton', 'pascal', 'joule', 'watt', 'coulomb', 'volt', 'ohm', 'hertz', 'liter', 'gram', 'centimeter', 'millimeter', 'kilometer', 'millisekund', 'mikrosekund', 'nanosekund'],
    constant: ['lysets hastighet', 'gravitasjonskonstanten', 'Plancks konstant', 'Boltzmanns konstant', 'Avogadros tall', 'gasskonstanten', 'permittiviteten i vakuum', 'permeabiliteten i vakuum', 'elementærladningen', 'protonmassen', 'elektronmassen', 'nøytronmassen', 'finstrukturkonstanten', 'Rydbergs konstant', 'Stefan-Boltzmanns konstant'],
    field: ['Fysikk', 'Kjemi', 'Biologi', 'Astronomi', 'Geologi', 'Meteorologi', 'Oseanografi', 'Økologi', 'Genetikk', 'Molekylærbiologi', 'Cellebiologi', 'Nevrovitenskap', 'Psykologi', 'Matematikk', 'Statistikk', 'Datavitenskap', 'Ingeniørfag', 'Medisin', 'Farmasi', 'Veterinærmedisin', 'Landbruk', 'Miljøvitenskap', 'Nanoteknologi', 'Materialvitenskap', 'Energiforskning'],
  },
  color: {
    name: ['rød', 'oransje', 'gul', 'grønn', 'blå', 'indigo', 'fiolett', 'rosa', 'svart', 'hvit', 'grå', 'brun', 'beige', 'krem', 'elfenbenshvit', 'gull', 'sølv', 'bronse', 'kobber', 'oliven', 'khaki', 'marine', 'mint', 'turkis', 'magenta', 'lilla', 'limegrønn', 'himmelblå', 'marineblå', 'kastanjebrun'],
  },
}
