import type { LocaleDefinition } from '@stacksjs/ts-faker'

export const pl: LocaleDefinition = {
  title: 'Polish',
  person: {
    firstNameMale: [
      'Jan',
      'Andrzej',
      'Piotr',
      'Krzysztof',
      'Stanisław',
      'Tomasz',
      'Paweł',
      'Józef',
      'Marcin',
      'Marek',
      'Michał',
      'Grzegorz',
      'Jerzy',
      'Tadeusz',
      'Adam',
      'Łukasz',
      'Zbigniew',
      'Ryszard',
      'Kazimierz',
      'Mateusz',
      'Dariusz',
      'Henryk',
      'Mariusz',
      'Janusz',
      'Wojciech',
      'Robert',
      'Rafał',
      'Jacek',
      'Waldemar',
      'Bogdan',
      'Damian',
      'Sebastian',
      'Artur',
      'Sławomir',
      'Kamil',
      'Bartosz',
      'Mirosław',
      'Filip',
      'Jakub',
      'Maciej',
      'Kacper',
      'Hubert',
      'Adrian',
      'Szymon',
      'Dominik',
      'Patryk',
      'Dawid',
      'Wiktor',
      'Oskar',
      'Igor',
    ],
    firstNameFemale: [
      'Maria',
      'Anna',
      'Katarzyna',
      'Małgorzata',
      'Agnieszka',
      'Barbara',
      'Ewa',
      'Elżbieta',
      'Krystyna',
      'Zofia',
      'Teresa',
      'Joanna',
      'Magdalena',
      'Monika',
      'Jadwiga',
      'Danuta',
      'Irena',
      'Halina',
      'Helena',
      'Beata',
      'Aleksandra',
      'Marta',
      'Dorota',
      'Marianna',
      'Grażyna',
      'Jolanta',
      'Stanisława',
      'Renata',
      'Natalia',
      'Paulina',
      'Karolina',
      'Wiktoria',
      'Justyna',
      'Zuzanna',
      'Julia',
      'Martyna',
      'Alicja',
      'Iwona',
      'Sylwia',
      'Urszula',
      'Klaudia',
      'Weronika',
      'Aneta',
      'Izabela',
      'Patrycja',
      'Agata',
      'Monika',
      'Emilia',
      'Oliwia',
      'Lena',
    ],
    firstNameNeutral: [
      'Alex',
      'Sasha',
      'Noa',
      'Kim',
      'Dominique',
      'Jordan',
      'Kris',
      'Nikola',
      'Andrea',
      'Michał',
    ],
    lastName: ['Nowak', 'Kowalski', 'Wiśniewski', 'Wójcik', 'Kowalczyk', 'Kamiński', 'Lewandowski', 'Zieliński', 'Szymański', 'Woźniak', 'Dąbrowski', 'Kozłowski', 'Jankowski', 'Mazur', 'Kwiatkowski', 'Krawczyk', 'Kaczmarek', 'Piotrowski', 'Grabowski', 'Nowakowski', 'Pawłowski', 'Michalski', 'Nowicki', 'Adamczyk', 'Dudek', 'Zając', 'Wieczorek', 'Jabłoński', 'Król', 'Majewski', 'Olszewski', 'Jaworski', 'Wróbel', 'Malinowski', 'Pawlak', 'Witkowski', 'Walczak', 'Stępień', 'Górski', 'Rutkowski'],
    prefix: ['Pan', 'Pani', 'Dr', 'Prof.', 'Mgr', 'Inż.', 'Adw.', 'Sędzia'],
    suffix: ['Jr.', 'Sr.', 'II', 'III', 'IV'],
    gender: ['Mężczyzna', 'Kobieta', 'Inna'],
    jobTitle: ['Programista', 'Kierownik Projektu', 'Projektant', 'Kierownik Marketingu', 'Kierownik Sprzedaży', 'Księgowy', 'Prawnik', 'Lekarz', 'Pielęgniarka', 'Nauczyciel', 'Profesor', 'Badacz', 'Analityk Danych', 'Product Manager', 'Kierownik HR', 'Konsultant', 'Architekt', 'Inżynier', 'Technik', 'Szef Kuchni', 'Pisarz', 'Dziennikarz', 'Fotograf', 'Artysta', 'Muzyk'],
  },
  address: {
    street: ['Marszałkowska', 'Nowy Świat', 'Aleje Jerozolimskie', 'Piotrkowska', 'Floriańska', 'Długa', 'Krakowskie Przedmieście', 'Grodzka', 'Szewska', 'Chmielna', 'Mokotowska', 'Puławska', 'Wiślana', 'Solidarności', 'Jana Pawła II', 'Mickiewicza', 'Piłsudskiego', 'Kościuszki', 'Słowackiego', 'Sienkiewicza', 'Paderewskiego', 'Chopina', 'Żeromskiego', 'Reymonta', 'Norwida', 'Mickiewicza', 'Ogrodowa', 'Poznańska', 'Gdańska', 'Wrocławska'],
    city: ['Warszawa', 'Kraków', 'Łódź', 'Wrocław', 'Poznań', 'Gdańsk', 'Szczecin', 'Bydgoszcz', 'Lublin', 'Katowice', 'Białystok', 'Gdynia', 'Częstochowa', 'Radom', 'Sosnowiec', 'Toruń', 'Kielce', 'Gliwice', 'Zabrze', 'Bytom', 'Olsztyn', 'Bielsko-Biała', 'Rzeszów', 'Ruda Śląska', 'Rybnik', 'Tychy', 'Dąbrowa Górnicza', 'Płock', 'Elbląg', 'Opole'],
    state: ['Mazowieckie', 'Małopolskie', 'Łódzkie', 'Dolnośląskie', 'Wielkopolskie', 'Pomorskie', 'Zachodniopomorskie', 'Kujawsko-Pomorskie', 'Lubelskie', 'Śląskie', 'Podlaskie', 'Warmińsko-Mazurskie', 'Świętokrzyskie', 'Podkarpackie', 'Opolskie', 'Lubuskie'],
    country: ['Polska', 'Niemcy', 'Francja', 'Wielka Brytania', 'Włochy', 'Hiszpania', 'Ukraina', 'Czechy', 'Słowacja', 'Litwa'],
    zipCode: ['##-###'],
    direction: ['Północ', 'Południe', 'Wschód', 'Zachód', 'Północny Wschód', 'Północny Zachód', 'Południowy Wschód', 'Południowy Zachód'],
  },
  company: {
    name: ['PKN Orlen', 'PZU', 'PGE', 'PKO Bank Polski', 'KGHM', 'Grupa Lotos', 'Orange Polska', 'PGNiG', 'Tauron', 'Enea', 'Allegro', 'CD Projekt', 'InPost', 'Poczta Polska', 'LOT Polish Airlines', 'Żabka', 'Biedronka', 'Lidl Polska', 'Kaufland', 'Carrefour Polska', 'Auchan', 'Leroy Merlin', 'Castorama', 'Media Markt', 'Empik', 'Reserved', 'CCC', 'LPP', 'Dino', 'Eurocash'],
    suffix: ['Sp. z o.o.', 'S.A.', 'Sp. k.', 'Spółdzielnia', 'Fundacja', 'Stowarzyszenie', 'Grupa', 'Holding', 'i Spółka', 'Przedsiębiorstwo'],
    industry: ['Technologia', 'Telekomunikacja', 'Motoryzacja', 'Tekstylia', 'Spożywcza', 'Budownictwo', 'Energia', 'Turystyka', 'Zdrowie', 'Edukacja', 'Finanse', 'Bankowość', 'Ubezpieczenia', 'Handel Detaliczny', 'E-commerce', 'Logistyka', 'Transport', 'Media', 'Reklama', 'Doradztwo', 'Oprogramowanie', 'Górnictwo', 'Rolnictwo', 'Hodowla', 'Rybołówstwo'],
    buzzword: ['transformacja cyfrowa', 'innowacja', 'zrównoważony rozwój', 'przedsiębiorczość', 'technologia', 'sztuczna inteligencja', 'analiza danych', 'chmura', 'Internet rzeczy', 'blockchain', 'automatyzacja', 'cyfryzacja', 'e-transformacja', 'startup', 'scale-up', 'unicorn', 'fintech', 'edtech', 'healthtech', 'agritech', 'martech', 'adtech', 'regtech', 'insurtech', 'proptech'],
    adjective: ['innowacyjny', 'zrównoważony', 'cyfrowy', 'zwinny', 'wydajny', 'niezawodny', 'dynamiczny', 'nowoczesny', 'postępowy', 'wiodący'],
    descriptor: ['rozwiązanie', 'usługa', 'produkt', 'system', 'platforma', 'aplikacja', 'technologia', 'koncepcja', 'sieć', 'ekosystem'],
    noun: ['biznes', 'innowacja', 'przyszłość', 'partner', 'klient', 'współpraca', 'sukces', 'wzrost', 'rozwój', 'możliwość'],
    buzzwords: ['transformacja cyfrowa', 'innowacja', 'zrównoważony rozwój', 'przedsiębiorczość', 'technologia', 'sztuczna inteligencja', 'analiza danych', 'chmura', 'IoT', 'blockchain', 'automatyzacja', 'cyfryzacja', 'startup', 'synergia', 'optymalizacja'],
  },
  internet: {
    domainName: ['onet.pl', 'wp.pl', 'interia.pl', 'gazeta.pl', 'tvn24.pl', 'tvp.pl', 'polsatnews.pl', 'rmf24.pl', 'fakt.pl', 'o2.pl', 'money.pl', 'poczta.onet.pl', 'allegro.pl', 'olx.pl', 'gratka.pl', 'otomoto.pl', 'otodom.pl', 'morele.net', 'komputronik.pl', 'x-kom.pl', 'ceneo.pl', 'orange.pl', 'play.pl', 't-mobile.pl', 'plus.pl'],
    domainSuffix: ['.pl', '.com.pl', '.com', '.net', '.org'],
    freeEmail: ['gmail.com', 'outlook.com', 'hotmail.com', 'yahoo.com', 'onet.pl', 'wp.pl', 'interia.pl', 'o2.pl'],
  },
  phone: {
    format: ['+48 ### ### ###', '+48 ## ### ## ##', '### ### ###', '## ### ## ##'],
  },
  food: {
    dish: ['Pierogi', 'Bigos', 'Żurek', 'Kotlet schabowy', 'Gołąbki', 'Flaki', 'Rosół', 'Zupa pomidorowa', 'Barszcz czerwony', 'Kluski śląskie', 'Pyzy', 'Kopytka', 'Placki ziemniaczane', 'Kiełbasa', 'Krakowska', 'Oscypek', 'Sernik', 'Makowiec', 'Pączki', 'Faworki', 'Szarlotka', 'Piernik', 'Racuchy', 'Naleśniki', 'Krokiety', 'Golonka', 'Karkowka', 'Kaszanka', 'Łazanki', 'Kopytka'],
    ingredient: ['Kapusta', 'Ziemniaki', 'Grzyby', 'Ogórki', 'Śmietana', 'Twaróg', 'Cebula', 'Marchew', 'Pietruszka', 'Seler', 'Czosnek', 'Koperek', 'Śliwki', 'Jabłka', 'Wiśnie', 'Maliny', 'Mąka', 'Mak', 'Mięso wieprzowe', 'Kiełbasa', 'Boczek', 'Jajka', 'Masło', 'Mleko', 'Kwaśna kapusta', 'Buraki', 'Chrzun', 'Kiszony ogórek', 'Śledź', 'Fasola'],
    cuisine: ['Polska', 'Włoska', 'Francuska', 'Japońska', 'Chińska', 'Tajska', 'Meksykańska', 'Turecka', 'Grecka', 'Hiszpańska', 'Amerykańska', 'Indyjska', 'Koreańska', 'Wietnamska', 'Arabska'],
    dessert: ['Sernik', 'Makowiec', 'Pączki', 'Faworki', 'Szarlotka', 'Piernik', 'Mazurek', 'Babka wielkanocna', 'Tort', 'Ciasto drożdżowe', 'Kołacz', 'Rurki z kremem', 'Napoleonka', 'Ptasie mleczko', 'Krem z białej czekolady'],
    fruit: ['Jabłko', 'Gruszka', 'Śliwka', 'Wiśnia', 'Czereśnia', 'Truskawka', 'Malina', 'Poziomka', 'Borówka', 'Agrest', 'Porzeczka', 'Aronia', 'Pigwa', 'Morela', 'Brzoskwinia', 'Banan', 'Pomarańcza', 'Cytryna', 'Grejpfrut', 'Kiwi'],
    vegetable: ['Ziemniak', 'Kapusta', 'Marchew', 'Pietruszka', 'Seler', 'Cebula', 'Czosnek', 'Por', 'Burak', 'Ogórek', 'Pomidor', 'Papryka', 'Cukinia', 'Dynia', 'Brokuł', 'Kalafior', 'Szpinak', 'Sałata', 'Rzodkiewka', 'Fasola'],
    meat: ['Wieprzowina', 'Wołowina', 'Kurczak', 'Indyk', 'Kaczka', 'Gęś', 'Cielęcina', 'Baranina', 'Zając', 'Dziczyzna', 'Kiełbasa', 'Boczek', 'Schab', 'Polędwica', 'Golonka'],
    spice: ['Pieprz', 'Sól', 'Papryka', 'Majeranek', 'Kminek', 'Ziele angielskie', 'Cynamon', 'Gałka muszkatołowa', 'Imbir', 'Bazylia', 'Oregano', 'Tymianek', 'Rozmaryn', 'Majeranek', 'Lubczyk'],
  },
  animal: {
    dog: ['Owczarek niemiecki', 'Labrador retriever', 'Golden retriever', 'Buldog francuski', 'Chart polski', 'Owczarek podhalański', 'Jamnik', 'Cocker spaniel', 'York', 'Husky syberyjski', 'Bernardyn', 'Bokser', 'Rottweiler', 'Owczarek belgijski', 'Doberman'],
    cat: ['Kot europejski', 'Kot perski', 'Kot brytyjski', 'Maine Coon', 'Syberyjski', 'Ragdoll', 'Syjamski', 'Rosyjski niebieski', 'Norweski leśny', 'Sfinks'],
    bird: ['Wróbel', 'Sroka', 'Wrona', 'Kawka', 'Jaskółka', 'Gil', 'Zięba', 'Sikora', 'Dzięcioł', 'Bocian', 'Gołąb', 'Sokół', 'Myszołów', 'Kos', 'Rudzik'],
    fish: ['Karp', 'Pstrąg', 'Szczupak', 'Okoń', 'Sandacz', 'Sum', 'Leszcz', 'Lin', 'Płoć', 'Węgorz', 'Łosoś', 'Dorsz', 'Śledź', 'Sardynka', 'Makrela'],
    horse: ['Huculski', 'Konik polski', 'Wielkopolski', 'Śląski', 'Małopolski', 'Polski koń zimnokrwisty', 'Arab', 'Fryzyjski', 'Andaluzyjski', 'Angloarab'],
    rabbit: ['Kalifornijski', 'Nowozelandzki biały', 'Baran', 'Belg', 'Szynszyla mała', 'Alaska', 'Wiedeński niebieski', 'Termondzki', 'Polski biały uszak', 'Szary olbrzym'],
    insect: ['Biedronka', 'Mrówka', 'Pszczoła', 'Trzmiel', 'Osa', 'Motyl', 'Ćma', 'Chrząszcz', 'Karaluch', 'Konik polny', 'Świerszcz', 'Mucha', 'Komar', 'Pchła', 'Wszy'],
  },
  sport: {
    sport: ['Piłka nożna', 'Siatkówka', 'Koszykówka', 'Piłka ręczna', 'Lekkoatletyka', 'Pływanie', 'Narciarstwo', 'Skoki narciarskie', 'Biathlon', 'Boks', 'Szermierka', 'Kajakarstwo', 'Wioślarstwo', 'Kolarstwo', 'Tenis', 'Tenis stołowy', 'Żużel', 'Hokej na lodzie', 'Wspinaczka', 'MMA'],
    team: ['Legia Warszawa', 'Wisła Kraków', 'Lech Poznań', 'Górnik Zabrze', 'Cracovia', 'Śląsk Wrocław', 'Pogoń Szczecin', 'Jagiellonia Białystok', 'Raków Częstochowa', 'Lechia Gdańsk', 'Reprezentacja Polski', 'PGE Skra Bełchatów', 'ZAKSA Kędzierzyn-Koźle', 'Jastrzębski Węgiel', 'Asseco Resovia', 'Trefl Gdańsk'],
    athlete: ['Robert Lewandowski', 'Kamil Stoch', 'Adam Małysz', 'Justyna Kowalczyk', 'Anita Włodarczyk', 'Wojciech Szczęsny', 'Tomasz Majewski', 'Irena Szewińska', 'Otylia Jędrzejczak', 'Piotr Żyła', 'Dawid Kubacki', 'Jan Błachowicz', 'Joanna Jędrzejczyk', 'Ewa Swoboda', 'Jakub Przygoński'],
  },
  music: {
    genre: ['Rock', 'Pop', 'Hip-hop', 'Jazz', 'Blues', 'Reggae', 'Disco polo', 'Muzyka elektroniczna', 'Punk', 'Metal', 'Folk', 'Country', 'R&B', 'Soul', 'Klasyczna'],
    artist: ['Czesław Niemen', 'Czerwone Gitary', 'Budka Suflera', 'Perfect', 'Lady Pank', 'Dżem', 'Maanam', 'Kult', 'T.Love', 'Myslovitz', 'Hey', 'O.N.A', 'Dawid Podsiadło', 'Sanah', 'Taco Hemingway', 'Margaret', 'Sarsa', 'Edyta Górniak', 'Kayah', 'Maryla Rodowicz'],
    song: ['Dziwny jest ten świat', 'Niebo', 'Sen o Victorii', 'Autobiografia', 'Mniej niż zero', 'Whisky', 'Wehikuł czasu', 'Kryzysowa narzeczona', 'Nie pytaj o Polskę', 'Nieważne jak wysoko', 'Teksański', 'Chłopcy radarowcy', 'Passerby', 'Małomiasteczkowy', 'Trójkąty i kwadraty', 'Wehikuł czasu', 'Skazany na bluesa', 'Kocham wolność', 'List do M.', 'Ballada o Janku Wiśniewskim'],
    instrument: ['Gitara', 'Fortepian', 'Perkusja', 'Skrzypce', 'Flet', 'Saksofon', 'Trąbka', 'Kontrabas', 'Altówka', 'Wiolonczela', 'Harmonijka', 'Akordeon', 'Organy', 'Keyboard', 'Gitara basowa'],
  },
  commerce: {
    product: ['Komputer', 'Laptop', 'Telefon', 'Tablet', 'Słuchawki', 'Monitor', 'Klawiatura', 'Mysz', 'Drukarka', 'Aparat', 'Telewizor', 'Konsola', 'Smartwatch', 'Router', 'Dysk twardy', 'Pamięć USB', 'Powerbank', 'Ładowarka', 'Kabel', 'Etui'],
    adjective: ['Nowoczesny', 'Elegancki', 'Stylowy', 'Funkcjonalny', 'Wydajny', 'Kompaktowy', 'Luksusowy', 'Praktyczny', 'Wygodny', 'Trwały'],
    material: ['Metal', 'Plastik', 'Drewno', 'Szkło', 'Skóra', 'Tkanina', 'Bawełna', 'Len', 'Wełna', 'Jedwab', 'Aluminium', 'Stal', 'Miedź', 'Brąz', 'Kamień'],
    department: ['Elektronika', 'Odzież', 'Obuwie', 'Spożywcze', 'AGD', 'RTV', 'Zabawki', 'Sport', 'Dom i ogród', 'Zdrowie i uroda', 'Motoryzacja', 'Książki', 'Muzyka', 'Filmy', 'Gry'],
    color: ['Czerwony', 'Niebieski', 'Zielony', 'Żółty', 'Czarny', 'Biały', 'Szary', 'Brązowy', 'Różowy', 'Fioletowy', 'Pomarańczowy', 'Turkusowy', 'Granatowy', 'Beżowy', 'Srebrny'],
  },
  book: {
    title: ['Pan Tadeusz', 'Quo Vadis', 'Krzyżacy', 'Lalka', 'Chłopi', 'Wesele', 'Ferdydurke', 'Solaris', 'Wiedźmin', 'Mistrz i Małgorzata', 'Zbrodnia i kara', 'Wojna i pokój', 'Sto lat samotności', '1984', 'Buszujący w zbożu', 'Wielki Gatsby', 'Harry Potter', 'Władca Pierścieni', 'Hobbit', 'Gra o tron'],
    author: ['Adam Mickiewicz', 'Henryk Sienkiewicz', 'Bolesław Prus', 'Władysław Reymont', 'Stanisław Wyspiański', 'Witold Gombrowicz', 'Stanisław Lem', 'Andrzej Sapkowski', 'Olga Tokarczuk', 'Wisława Szymborska', 'Czesław Miłosz', 'Ryszard Kapuściński', 'Bruno Schulz', 'Zofia Nałkowska', 'Maria Dąbrowska', 'Stefan Żeromski', 'Eliza Orzeszkowa', 'Juliusz Słowacki', 'Cyprian Kamil Norwid', 'Jan Kochanowski'],
    publisher: ['Znak', 'Wydawnictwo Literackie', 'PWN', 'Nasza Księgarnia', 'Prószyński i S-ka', 'Albatros', 'Egmont', 'Świat Książki', 'W.A.B.', 'Muza', 'Rebis', 'Marginesy', 'Czarne', 'Karakter', 'Amber'],
    genre: ['Fantastyka', 'Science Fiction', 'Kryminał', 'Thriller', 'Romans', 'Horror', 'Dramat', 'Komedia', 'Powieść historyczna', 'Biografia', 'Reportaż', 'Poradnik', 'Esej', 'Poezja', 'Literatura faktu'],
    series: ['Wiedźmin', 'Trylogia', 'Tetralogia', 'Kroniki', 'Saga', 'Cykl', 'Seria', 'Pentalog', 'Heptalog'],
    review: ['Wspaniała książka!', 'Nie mogłem oderwać się od lektury', 'Obowiązkowa pozycja', 'Polecam każdemu', 'Rewelacyjna historia', 'Wciągająca fabuła', 'Pięknie napisane', 'Poruszające', 'Inspirujące', 'Nie spełniła moich oczekiwań', 'Przeciętna', 'Rozczarowująca', 'Nudna', 'Niezbyt ciekawa', 'Ambitna próba'],
  },
  vehicle: {
    manufacturer: ['Fiat', 'Opel', 'Volkswagen', 'Škoda', 'Ford', 'Renault', 'Toyota', 'Honda', 'Nissan', 'Mazda', 'Hyundai', 'Kia', 'BMW', 'Mercedes-Benz', 'Audi', 'Peugeot', 'Citroën', 'Volvo', 'Seat', 'Dacia'],
    model: ['126p', 'Maluch', 'Polonez', 'Warszawa', 'Syrena', 'Golf', 'Passat', 'Octavia', 'Fabia', 'Corsa', 'Astra', 'Insignia', 'Fiesta', 'Focus', 'Mondeo', 'Clio', 'Megane', 'Scenic', 'Corolla', 'Yaris', 'Auris', 'Civic', 'Accord', 'CR-V', 'Qashqai', 'Juke', 'X-Trail', 'i30', 'i40', 'Tucson'],
    type: ['Sedan', 'Hatchback', 'Kombi', 'SUV', 'Crossover', 'Coupe', 'Kabriolet', 'Minivan', 'Pickup', 'Van'],
    fuel: ['Benzyna', 'Diesel', 'LPG', 'CNG', 'Hybryda', 'Elektryczny', 'Wodór', 'Etanol', 'Biodiesel'],
    bicycle: ['Górski', 'Szosowy', 'Miejski', 'Trekkingowy', 'BMX', 'Składak', 'Elektryczny', 'Damka', 'Cruiser', 'Gravel'],
  },
  word: {
    adjective: ['Piękny', 'Duży', 'Mały', 'Szybki', 'Wolny', 'Silny', 'Słaby', 'Wysoki', 'Niski', 'Szeroki', 'Wąski', 'Długi', 'Krótki', 'Ciężki', 'Lekki', 'Jasny', 'Ciemny', 'Głośny', 'Cichy', 'Nowy', 'Stary', 'Młody', 'Bogaty', 'Biedny', 'Dobry', 'Zły'],
    adverb: ['Szybko', 'Wolno', 'Dobrze', 'Źle', 'Głośno', 'Cicho', 'Wcześnie', 'Późno', 'Teraz', 'Jutro', 'Wczoraj', 'Zawsze', 'Nigdy', 'Często', 'Rzadko', 'Tutaj', 'Tam', 'Wszędzie', 'Nigdzie', 'Bardzo'],
    conjunction: ['I', 'Lub', 'Ale', 'Lecz', 'Jednak', 'Więc', 'Zatem', 'Ponieważ', 'Że', 'Jeśli', 'Gdyby', 'Choć', 'Chociaż', 'Mimo że', 'Podczas gdy'],
    interjection: ['Och!', 'Ach!', 'Oj!', 'Ał!', 'Au!', 'Wow!', 'Hej!', 'Cześć!', 'Aha!', 'No!', 'Hm...', 'Eee...', 'Ups!', 'Jejku!', 'Kurczę!'],
    noun: ['Dom', 'Samochód', 'Książka', 'Stół', 'Krzesło', 'Komputer', 'Telefon', 'Drzewo', 'Kwiat', 'Pies', 'Kot', 'Słońce', 'Księżyc', 'Gwiazda', 'Morze', 'Góra', 'Rzeka', 'Las', 'Miasto', 'Wieś'],
    preposition: ['W', 'Na', 'Pod', 'Nad', 'Przed', 'Za', 'Do', 'Od', 'Z', 'O', 'Dla', 'Bez', 'Przez', 'Przy', 'Między', 'Poza', 'Wobec', 'Wokół', 'Obok', 'Koło'],
    verb: ['Być', 'Mieć', 'Robić', 'Iść', 'Jechać', 'Mówić', 'Wiedzieć', 'Chcieć', 'Móc', 'Musieć', 'Dawać', 'Brać', 'Patrzeć', 'Widzieć', 'Słyszeć', 'Myśleć', 'Czuć', 'Kochać', 'Nienawidzić', 'Pracować'],
  },
  hacker: {
    abbreviation: ['API', 'CPU', 'GPU', 'RAM', 'ROM', 'SSD', 'HDD', 'USB', 'HDMI', 'WiFi', 'LAN', 'WAN', 'VPN', 'DNS', 'IP', 'TCP', 'UDP', 'HTTP', 'HTTPS', 'FTP', 'SSH', 'SQL', 'HTML', 'CSS', 'JS'],
    adjective: ['Cyfrowy', 'Wirtualny', 'Mobilny', 'Bezprzewodowy', 'Kwantowy', 'Neuronowy', 'Redundantny', 'Skalowalny', 'Optymalizowany', 'Zaszyfrowany'],
    noun: ['Protokół', 'Port', 'Interfejs', 'Komponent', 'Bajt', 'Packet', 'Firewall', 'Bandwidth', 'System', 'Algorytm', 'Matryca', 'Węzeł', 'Sieć', 'Baza danych', 'Serwer'],
    verb: ['Kompresować', 'Generować', 'Parsować', 'Kalkulować', 'Nadpisać', 'Obejść', 'Hackować', 'Przesyłać', 'Indeksować', 'Renderować', 'Navigować', 'Programować', 'Syntetyzować', 'Transmitować', 'Łączyć'],
    ingverb: ['Kompresowanie', 'Generowanie', 'Parsowanie', 'Kalkulowanie', 'Nadpisywanie', 'Obchodzenie', 'Hackowanie', 'Przesyłanie', 'Indeksowanie', 'Renderowanie', 'Navigowanie', 'Programowanie', 'Syntetyzowanie', 'Transmitowanie', 'Łączenie'],
    phrase: [
      'Jeśli skompresujemy port, możemy dostać się do panelu przez redundantny interfejs!',
      'Musimy obejść firewall aby uzyskać dostęp!',
      'Spróbuj skompresować protokół TCP, może to rozblokuje serwer!',
      'Nie możemy hackować systemu bez obejścia bezprzewodowego protokołu!',
      'Użyj wirtualnego interfejsu, a następnie możesz zhackować wszystkie sieci!',
    ],
  },
  system: {
    fileName: ['raport.pdf', 'dokument.docx', 'prezentacja.pptx', 'arkusz.xlsx', 'obraz.jpg', 'zdjęcie.png', 'muzyka.mp3', 'film.mp4', 'strona.html', 'skrypt.js', 'styl.css', 'kod.py', 'program.exe', 'biblioteka.dll', 'konfiguracja.ini', 'dane.json', 'tekst.txt', 'archiwum.zip', 'backup.tar.gz', 'instalator.msi'],
    fileType: ['pdf', 'docx', 'pptx', 'xlsx', 'jpg', 'png', 'gif', 'mp3', 'mp4', 'avi', 'html', 'css', 'js', 'py', 'java', 'cpp', 'exe', 'dll', 'zip', 'rar'],
  },
  science: {
    chemicalElement: ['Wodór', 'Hel', 'Lit', 'Beryl', 'Bor', 'Węgiel', 'Azot', 'Tlen', 'Fluor', 'Neon', 'Sód', 'Magnez', 'Glin', 'Krzem', 'Fosfor', 'Siarka', 'Chlor', 'Argon', 'Potas', 'Wapń', 'Żelazo', 'Miedź', 'Cynk', 'Srebro', 'Złoto'],
    unit: ['Metr', 'Kilogram', 'Sekunda', 'Amper', 'Kelvin', 'Mol', 'Kandela', 'Litr', 'Newton', 'Pascal', 'Joule', 'Wat', 'Wolt', 'Om', 'Herc', 'Grad Celsjusza'],
    constant: ['Prędkość światła', 'Stała Plancka', 'Stała grawitacji', 'Stała Avogadra', 'Stała Boltzmanna', 'Ładunek elementarny', 'Masa elektronu', 'Masa protonu'],
    field: ['Fizyka', 'Chemia', 'Biologia', 'Matematyka', 'Astronomia', 'Geologia', 'Meteorologia', 'Oceanografia', 'Ekologia', 'Genetyka', 'Mikrobiologia', 'Botanika', 'Zoologia', 'Biochemia', 'Biofizyka'],
  },
  color: {
    human: ['Czerwony', 'Niebieski', 'Zielony', 'Żółty', 'Czarny', 'Biały', 'Szary', 'Brązowy', 'Różowy', 'Fioletowy', 'Pomarańczowy', 'Turkusowy', 'Granatowy', 'Beżowy', 'Srebrny', 'Złoty', 'Bordowy', 'Limonkowy', 'Cyjan', 'Magenta'],
  },
}
