import type { DeepPartial, LocaleDefinition } from '@stacksjs/ts-faker'

/**
 * Chinese (Simplified, China) locale
 * Extends the base 'zh' locale with China-specific data
 */
export const zh_CN: DeepPartial<LocaleDefinition> = {
  title: 'Chinese (Simplified, China)',

  // China-specific address data (Simplified Chinese)
  address: {
    city: [
      '北京',
      '上海',
      '广州',
      '深圳',
      '天津',
      '重庆',
      '成都',
      '武汉',
      '杭州',
      '南京',
      '西安',
      '苏州',
      '郑州',
      '长沙',
      '沈阳',
      '青岛',
      '济南',
      '哈尔滨',
      '大连',
      '福州',
      '厦门',
      '昆明',
      '南昌',
      '石家庄',
      '长春',
      '合肥',
      '太原',
      '南宁',
      '贵阳',
      '乌鲁木齐',
      '兰州',
      '呼和浩特',
      '银川',
      '西宁',
      '拉萨',
      '海口',
      '三亚',
      '珠海',
      '汕头',
      '佛山',
      '东莞',
      '中山',
      '温州',
      '宁波',
      '无锡',
      '常州',
      '徐州',
      '扬州',
      '南通',
      '镇江',
    ],
    state: [
      '北京市',
      '上海市',
      '天津市',
      '重庆市',
      '河北省',
      '山西省',
      '辽宁省',
      '吉林省',
      '黑龙江省',
      '江苏省',
      '浙江省',
      '安徽省',
      '福建省',
      '江西省',
      '山东省',
      '河南省',
      '湖北省',
      '湖南省',
      '广东省',
      '海南省',
      '四川省',
      '贵州省',
      '云南省',
      '陕西省',
      '甘肃省',
      '青海省',
      '广西壮族自治区',
      '内蒙古自治区',
      '西藏自治区',
      '宁夏回族自治区',
      '新疆维吾尔自治区',
    ],
    country: ['中国', '中华人民共和国'],
    countryCode: ['CN'],
    zipCode: ['######'],
  },

  // China phone formats
  phone: {
    formats: [
      '1##-####-####',
      '+86 1##-####-####',
      '###-########',
      '+86-###-########',
    ],
  },

  // Chinese cuisine (Simplified)
  food: {
    dish: [
      '北京烤鸭',
      '麻婆豆腐',
      '宫保鸡丁',
      '红烧肉',
      '鱼香肉丝',
      '糖醋里脊',
      '回锅肉',
      '小笼包',
      '饺子',
      '馄饨',
      '拉面',
      '炒面',
      '炒饭',
      '粥',
      '火锅',
      '烤串',
      '煎饼',
      '包子',
      '油条',
      '豆浆',
      '春卷',
      '锅贴',
      '烧卖',
      '肠粉',
      '粽子',
      '月饼',
      '麻辣烫',
      '臭豆腐',
      '烤鱼',
      '水煮鱼',
    ],
    ingredient: [
      '大米',
      '面粉',
      '酱油',
      '醋',
      '糖',
      '盐',
      '味精',
      '葱',
      '姜',
      '蒜',
      '辣椒',
      '花椒',
      '八角',
      '桂皮',
      '香菜',
      '芝麻',
      '花生',
      '豆腐',
      '鸡蛋',
      '猪肉',
      '牛肉',
      '鸡肉',
      '鱼',
      '虾',
      '蔬菜',
    ],
    cuisine: [
      '川菜',
      '粤菜',
      '鲁菜',
      '苏菜',
      '浙菜',
      '闽菜',
      '湘菜',
      '徽菜',
      '京菜',
      '东北菜',
      '西北菜',
      '清真菜',
      '素菜',
    ],
  },

  // China internet domains
  internet: {
    domainSuffix: ['cn', 'com.cn', 'net.cn', 'org.cn', 'gov.cn', 'edu.cn'],
    freeEmail: ['qq.com', '163.com', '126.com', 'sina.com', 'sohu.com', 'yeah.net', 'gmail.com'],
  },
}
