import type { DeepPartial, LocaleDefinition } from '@stacksjs/ts-faker'

/**
 * Spanish (Mexico) locale
 * Extends the base 'es' locale with Mexico-specific data
 */
export const es_MX: DeepPartial<LocaleDefinition> = {
  title: 'Spanish (Mexico)',

  // Mexico-specific person names
  person: {
    firstNameMale: [
      'Miguel',
      'José',
      'Luis',
      'Juan',
      'Carlos',
      'Jesús',
      'Antonio',
      'Pedro',
      'Fernando',
      'Manuel',
      'Jorge',
      'Alberto',
      'Roberto',
      'Ricardo',
      'Daniel',
      'Francisco',
      'Rafael',
      'Alejandro',
      'Eduardo',
      'Javier',
    ],
    firstNameFemale: [
      'María',
      'Guadalupe',
      'Juana',
      'Margarita',
      'Josefina',
      'Verónica',
      'Leticia',
      'Rosa',
      'Francisca',
      'Teresa',
      'Patricia',
      'Laura',
      'Elizabeth',
      'Ana',
      'Carmen',
      'Lucía',
      'Gabriela',
      'Daniela',
      'Andrea',
      'Fernanda',
    ],
    lastName: [
      'García',
      'Rodríguez',
      'Martínez',
      'Hernández',
      'López',
      'González',
      'Pérez',
      'Sánchez',
      'Ramírez',
      'Torres',
      'Flores',
      'Rivera',
      'Gómez',
      'Díaz',
      'Cruz',
      'Morales',
      'Reyes',
      'Gutiérrez',
      'Ortiz',
      'Chávez',
    ],
  },

  // Mexico-specific address data
  address: {
    city: [
      'Ciudad de México',
      'Guadalajara',
      'Monterrey',
      'Puebla',
      'Tijuana',
      'León',
      'Juárez',
      'Zapopan',
      'Mérida',
      'San Luis Potosí',
      'Querétaro',
      'Aguascalientes',
      'Cancún',
      'Toluca',
      'Chihuahua',
      'Morelia',
      'Saltillo',
      'Mexicali',
      'Culiacán',
      'Acapulco',
    ],
    state: [
      'Aguascalientes',
      'Baja California',
      'Baja California Sur',
      'Campeche',
      'Chiapas',
      'Chihuahua',
      'Coahuila',
      'Colima',
      'Durango',
      'Guanajuato',
      'Guerrero',
      'Hidalgo',
      'Jalisco',
      'México',
      'Michoacán',
      'Morelos',
      'Nayarit',
      'Nuevo León',
      'Oaxaca',
      'Puebla',
      'Querétaro',
      'Quintana Roo',
      'San Luis Potosí',
      'Sinaloa',
      'Sonora',
      'Tabasco',
      'Tamaulipas',
      'Tlaxcala',
      'Veracruz',
      'Yucatán',
      'Zacatecas',
    ],
    country: ['México', 'Mexico'],
    zipCode: ['#####'],
  },

  // Mexico phone number formats
  phone: {
    formats: [
      '### ### ####',
      '(###) ### ####',
      '+52 ### ### ####',
      '+52 # ### ### ####',
    ],
  },

  // Mexican cuisine
  food: {
    dish: [
      'Tacos al Pastor',
      'Tacos de Carnitas',
      'Quesadillas',
      'Enchiladas',
      'Tamales',
      'Pozole',
      'Mole Poblano',
      'Chiles Rellenos',
      'Cochinita Pibil',
      'Birria',
      'Barbacoa',
      'Menudo',
      'Sopes',
      'Tostadas',
      'Tlacoyos',
      'Gorditas',
      'Huaraches',
      'Flautas',
      'Chilaquiles',
      'Molletes',
      'Pan Dulce',
      'Conchas',
      'Churros',
      'Tres Leches Cake',
      'Flan',
      'Arroz con Leche',
      'Buñuelos',
      'Elote',
      'Esquites',
      'Guacamole',
    ],
    ingredient: [
      'Maíz',
      'Frijoles',
      'Chiles',
      'Aguacate',
      'Tomate',
      'Cilantro',
      'Cebolla',
      'Ajo',
      'Limón',
      'Tortilla',
      'Queso Oaxaca',
      'Queso Fresco',
      'Crema',
      'Epazote',
      'Nopal',
      'Tomatillo',
      'Jalapeño',
      'Habanero',
      'Chipotle',
      'Masa',
      'Piloncillo',
      'Canela Mexicana',
      'Chocolate',
    ],
    cuisine: [
      'Mexicana',
      'Tex-Mex',
      'Oaxaqueña',
      'Yucateca',
      'Norteña',
      'Veracruzana',
      'Poblana',
      'Jaliscience',
    ],
  },
}
