import type { LocaleDefinition } from '@stacksjs/ts-faker'

export const zu: LocaleDefinition = {
  title: 'Zulu',
  person: {
    firstNameMale: [
      'Sipho',
      'Thabo',
      'Mandla',
      'Bongani',
      'Siyabonga',
      'Mthunzi',
      'Nhlanhla',
      'Khethiwe',
      'Sbusiso',
      'Lungelo',
      'Senzo',
      'Sandile',
      'Mduduzi',
      'Nkosinathi',
      'Themba',
      'Vusi',
      'Jabulani',
      'Bheki',
      'Zweli',
      'Sfiso',
      'Mlungisi',
      'Phila',
      'Muzikayise',
      'Simphiwe',
      'Xolani',
      'Dumisani',
      'Khulekani',
      'Mpumelelo',
      'Ayanda',
      'Siphiwe',
      'Musa',
      'Buhle',
    ],
    firstNameFemale: [
      'Nomsa',
      'Thandi',
      'Zanele',
      'Nokuthula',
      'Lindiwe',
      'Zinhle',
      'Ntombifuthi',
      'Nonhlanhla',
      'Sibongile',
      'Nompumelelo',
      'Thandeka',
      'Ntokozo',
      'Mbali',
      'Thembi',
      'Nosipho',
      'Sizakele',
      'Bongi',
      'Gugu',
      'Ntombi',
      'Nolwazi',
      'Nandi',
      'Thandiwe',
      'Nokukhanya',
      'Nonjabulo',
      'Nombuso',
      'Siphokazi',
      'Ayanda',
      'Zandile',
      'Buhle',
      'Simphiwe',
      'Nonkululeko',
      'Noxolo',
    ],
    firstNameNeutral: [
      'Ayanda',
      'Buhle',
      'Simphiwe',
      'Khanyisile',
      'Nhlanhla',
      'Siyabonga',
      'Thando',
      'Mpilo',
    ],
    lastName: [
      'Zulu',
      'Dlamini',
      'Nkosi',
      'Khumalo',
      'Mkhize',
      'Ndlovu',
      'Ngcobo',
      'Mthembu',
      'Ntuli',
      'Zondi',
      'Cele',
      'Buthelezi',
      'Bhengu',
      'Hlongwane',
      'Nguyen',
      'Khoza',
      'Gumede',
      'Sibiya',
      'Zungu',
      'Nxumalo',
      'Shange',
      'Gama',
      'Mdlalose',
      'Hadebe',
      'Ngubane',
      'Sithole',
      'Vilakazi',
      'Mhlongo',
      'Mabuza',
      'Msibi',
      'Shezi',
      'Ntshangase',
      'Dube',
      'Zwane',
      'Khanyile',
      'Mvelase',
      'Ngwenya',
      'Radebe',
      'Nzuza',
      'Majola',
    ],
    prefix: ['Mnu', 'Nkk', 'Dkt', 'Prof', 'Injiniyela', 'Umhlengikazi'],
    suffix: [],
    gender: ['Owesilisa', 'Owesifazane', 'Akubonakali', 'Okuphakathi'],
    jobTitle: [
      'Unjiniyela Wesofthiwe',
      'Umphathi Womkhiqizo',
      'Umdwebi',
      'Usosayensi Wedatha',
      'Umphathi Wokumaketha',
      'Ummeli Wokuthengisa',
      'I-accountant',
      'Umphathi Wezabasebenzi',
      'Umqondisi Ophethe',
      'Umphathi Wezobuchwepheshe',
      'Umphathi Wezezimali',
      'Umphathi Wephrojekthi',
      'Umhleli Webhizinisi',
      'Unjiniyela',
      'Umcwaningi',
      'Umeluleki',
      'Umhloli',
      'Umxhumanisi',
      'Uchwepheshe',
      'Umsizi',
    ],
  },
  address: {
    street: [
      'Main',
      'Inanda',
      'KwaMashu',
      'Umlazi',
      'Phoenix',
      'Chatsworth',
      'Pinetown',
      'Westville',
      'Durban North',
      'Glenwood',
      'Berea',
      'Morningside',
      'Musgrave',
      'Church',
      'Market',
      'Victoria',
      'Albert',
      'Smith',
      'West',
      'Station',
    ],
    city: [
      'Durban',
      'Pietermaritzburg',
      'Ulundi',
      'Richards Bay',
      'Empangeni',
      'Newcastle',
      'Ladysmith',
      'Vryheid',
      'Eshowe',
      'Stanger',
      'Port Shepstone',
      'Kokstad',
      'Dundee',
      'Greytown',
      'Estcourt',
      'Howick',
      'Mooi River',
      'Underberg',
      'Mtubatuba',
      'Hluhluwe',
      'Mkuze',
      'Nongoma',
      'Pongola',
      'Paulpietersburg',
    ],
    state: [
      'KwaZulu-Natal',
      'Gauteng',
      'Mpumalanga',
      'Free State',
      'Limpopo',
      'Eastern Cape',
      'Western Cape',
      'Northern Cape',
      'North West',
    ],
    stateAbbr: ['KZN', 'GP', 'MP', 'FS', 'LP', 'EC', 'WC', 'NC', 'NW'],
    country: [
      'Ningizimu Afrika',
      'South Africa',
      'iNingizimu Afrika',
      'Afrika',
      'Botswana',
      'Zimbabwe',
      'Mozambique',
      'Swaziland',
      'Lesotho',
    ],
    countryCode: ['ZA', 'BW', 'ZW', 'MZ', 'SZ', 'LS'],
    zipCode: ['####'],
    buildingNumber: ['###', '##', '#'],
    direction: ['Enyakatho', 'Eningizimu', 'Empumalanga', 'Entshonalanga'],
    streetSuffix: [
      'Road',
      'Street',
      'Avenue',
      'Drive',
      'Lane',
      'Way',
      'Place',
      'Crescent',
      'Umgwaqo',
      'Indlela',
    ],
  },
  company: {
    name: [
      'Zulu Tech',
      'Ubuntu Systems',
      'Mzansi Digital',
      'Afrika Solutions',
      'Inkosi Tech',
      'Nguni Software',
      'Sawubona Digital',
      'Bayede Systems',
      'Indlela Tech',
      'Phambili Solutions',
    ],
    suffix: ['(Pty) Ltd', 'Ltd', 'CC', 'Inc', 'Technologies', 'Solutions', 'Systems', 'Group'],
    industry: [
      'Ubuchwepheshe',
      'Ezezimali',
      'Ezempilo',
      'Imfundo',
      'Ukuthengisa',
      'Ukukhiqiza',
      'Ezokuxhumana',
      'Amandla',
      'Izindlu',
      'Ezokuthutha',
    ],
    buzzwords: [
      'sebenzisa',
      'guqula',
      'nika amandla',
      'lungiselela',
      'hlanganisa',
      'khulisa',
      'thuthukisa',
      'nikeza',
      'yenza lula',
      'qondisa',
    ],
    adjective: [
      'okusha',
      'okukhulu',
      'okuphezulu',
      'okuhle',
      'okusebenzayo',
      'okunobuchwepheshe',
      'okuphethe',
      'okuqinile',
      'okushesha',
      'okuphelele',
    ],
    descriptor: [
      'emhlabeni wonke',
      'edijithali',
      'esefini',
      'eneAI',
      'edateni',
      'okugxile kumakhasimende',
      'okuzenzakalelayo',
      'okuxhunyanisiwe',
      'okuhlakaniphile',
      'okwenzelwe wena',
      'okusimeme',
    ],
    noun: [
      'isisombululo',
      'inkundla',
      'isistimu',
      'insizakalo',
      'ubuchwepheshe',
      'uhlaka',
      'ingqalasizinda',
      'uhlelo lokusebenza',
      'inethiwekhi',
      'iphothali',
    ],
  },
  internet: {
    domainSuffix: ['za', 'co.za', 'org.za', 'gov.za', 'ac.za', 'net.za', 'com'],
    freeEmail: ['gmail.com', 'yahoo.co.za', 'webmail.co.za', 'mweb.co.za', 'vodamail.co.za'],
  },
  phone: {
    formats: [
      '0##-###-####',
      '+27 ## ### ####',
      '0### ### ###',
      '+27 ### ### ###',
    ],
  },
  food: {
    dish: [
      'Pap',
      'Amasi',
      'Umngqusho',
      'Isijingi',
      'Uphuthu',
      'Amadumbe',
      'Inyama yenkomo',
      'Inyama yenkukhu',
      'Shisa nyama',
      'Boerewors',
      'Bunny chow',
      'Vetkoek',
      'Koeksisters',
      'Melktert',
      'Bobotie',
      'Sosatie',
      'Biltong',
      'Droewors',
      'Chakalaka',
      'Morogo',
    ],
    ingredient: [
      'Ummbila',
      'Izinkobe',
      'Amasi',
      'Inyama',
      'Ubisi',
      'Amaqanda',
      'Utamatisi',
      'U-anyanisi',
      'Igalikhi',
      'Upelepele',
      'Usawoti',
      'Ushukela',
      'Amafutha',
      'Ubhontshisi',
      'Amazambane',
      'Imifino',
    ],
    cuisine: [
      'IsiZulu',
      'i-African',
      'i-South African',
      'i-Indian',
      'i-Cape Malay',
      'i-Portuguese',
      'i-British',
      'i-Dutch',
      'i-Fusion',
    ],
    dessert: [
      'Koeksisters',
      'Melktert',
      'Malva pudding',
      'Peppermint crisp tart',
      'Hertzoggies',
      'Crunchies',
      'Vetkoek with jam',
      'Milk tart',
    ],
    fruit: [
      'I-apple',
      'I-banana',
      'I-orange',
      'Iwolintshi',
      'I-mango',
      'Uphapayi',
      'I-grape',
      'Umpikiwane',
      'I-litchi',
      'Ukhiwani',
      'I-guava',
    ],
    vegetable: [
      'Amazambane',
      'Utamatisi',
      'U-anyanisi',
      'Ikhabhishi',
      'Amakherothi',
      'Ubhitirusi',
      'Upelepele',
      'Usipinashi',
      'Ubhulukosi',
      'Ipelephele',
    ],
    meat: [
      'Inyama yenkomo',
      'Inyama yenkukhu',
      'Inyama yengulube',
      'Inyama yemvu',
      'Inyama yebhokwe',
      'Inhlanzi',
      'Izinkukhu',
      'I-sausage',
    ],
    spice: [
      'Upelepele',
      'Usawoti',
      'Igalikhi',
      'I-curry',
      'Upaprika',
      'I-ginger',
      'I-cinnamon',
      'I-cardamom',
      'I-coriander',
      'I-cumin',
    ],
  },
  animal: {
    dog: ['Inja', 'Umkhovu', 'I-German Shepherd', 'I-Labrador', 'I-Boerboel', 'I-Bull Terrier'],
    cat: ['Ikati', 'I-Persian', 'I-Siamese'],
    bird: ['Inyoni', 'Ukhozi', 'Inqe', 'Isigwaca', 'Uthekwane', 'Ijuba'],
    fish: ['Inhlanzi', 'I-goldfish', 'I-tilapia', 'I-bass', 'I-trout'],
    horse: ['Ihhashi', 'I-Arabian', 'I-Thoroughbred'],
    rabbit: ['Unogwaja', 'I-bunny'],
    insect: ['Isibungu', 'Inyosi', 'Intuthane', 'Igundane', 'Ujeqe'],
    type: ['Inja', 'Ikati', 'Inyoni', 'Inhlanzi', 'Unogwaja', 'Ihhashi', 'Inkomo', 'Imvu'],
  },
  sport: {
    sport: [
      'Ibhola',
      'I-rugby',
      'I-cricket',
      'I-soccer',
      'I-athletics',
      'I-swimming',
      'I-netball',
      'I-boxing',
      'I-golf',
      'I-tennis',
    ],
    team: [
      'AmaZulu FC',
      'Golden Arrows',
      'Royal AM',
      'Maritzburg United',
      'Kaizer Chiefs',
      'Orlando Pirates',
      'Mamelodi Sundowns',
      'Sharks',
      'Cell C Sharks',
    ],
    athlete: [
      'Siya Kolisi',
      'Caster Semenya',
      'Wayde van Niekerk',
      'Chad le Clos',
      'AB de Villiers',
      'Kagiso Rabada',
      'Benni McCarthy',
      'Lucas Radebe',
    ],
  },
  music: {
    genre: [
      'Maskandi',
      'Mbaqanga',
      'Kwaito',
      'Gqom',
      'Amapiano',
      'Isicathamiya',
      'Gospel',
      'Afro-pop',
      'House',
      'Hip Hop',
      'Jazz',
    ],
    artist: [
      'Ladysmith Black Mambazo',
      'Brenda Fassie',
      'Miriam Makeba',
      'Lucky Dube',
      'Johnny Clegg',
      'Mahlathini',
      'Phuzekhemisi',
      'Shwi Nomtekhala',
      'Kabza De Small',
    ],
    song: [
      'Shosholoza',
      'Mbube',
      'Pata Pata',
      'Bring Him Back Home',
      'Homeless',
      'Savuka',
      'Woza Moya',
      'Nomathemba',
      'Hello My Baby',
    ],
    instrument: [
      'Ugubhu',
      'Umakhweyana',
      'Isitolotolo',
      'Amakhweshini',
      'I-guitar',
      'I-piano',
      'Izigubhu',
      'I-saxophone',
      'I-trumpet',
    ],
  },
  commerce: {
    product: [
      'Isihlalo',
      'Itafula',
      'Isibani',
      'Isofa',
      'Umbhede',
      'Ikhompyutha',
      'Ucingo',
      'Iwashi',
      'Izicathulo',
      'Isikhwama',
      'Izipho',
    ],
    productAdjective: [
      'Omncane',
      'Omkhulu',
      'Omusha',
      'Osezingeni eliphezulu',
      'Osebenzayo',
      'Omuhle',
      'Onamandla',
      'Okhululekile',
      'Oshesha',
      'Ophelele',
    ],
    productMaterial: [
      'Insimbi',
      'Ukhuni',
      'Iplastiki',
      'Ukotini',
      'Isikhumba',
      'Ingilazi',
      'I-aluminium',
      'Insimbi',
      'Isilika',
      'Uboya',
    ],
    department: [
      'Ezikagesi',
      'Izingubo',
      'Ikhaya Nensimu',
      'Ezemidlalo',
      'Izincwadi',
      'Izinto zokudlala',
      'Ukuziphatha Nobuhle',
      'Ukudla',
      'Imfashini',
    ],
    color: [
      'Bomvu',
      'Okuluhlaza okwesibhakabhaka',
      'Okuluhlaza',
      'Ophuzi',
      'Omnyama',
      'Omhlophe',
      'Ompunga',
      'Owolintshi',
      'Onsundu',
      'Opiniki',
    ],
  },
  book: {
    title: [
      'Long Walk to Freedom',
      'Cry, the Beloved Country',
      'Disgrace',
      'The Conservationist',
      'Burger\'s Daughter',
      'The Heart of Redness',
      'Ways of Dying',
      'Mother to Mother',
      'Coconut',
      'Fiela\'s Child',
      'Chaka',
      'The Hairdresser of Harare',
    ],
    author: [
      'Nelson Mandela',
      'Alan Paton',
      'J.M. Coetzee',
      'Nadine Gordimer',
      'Zakes Mda',
      'Sindiwe Magona',
      'Kopano Matlwa',
      'Dalene Matthee',
      'Thomas Mofolo',
      'Tendai Huchu',
    ],
    publisher: [
      'Penguin Random House SA',
      'Jonathan Ball Publishers',
      'Jacana Media',
      'Pan Macmillan SA',
      'NB Publishers',
      'Kwela Books',
      'Modjaji Books',
    ],
    genre: [
      'Umlando',
      'I-Fiction',
      'I-Non-fiction',
      'I-Biography',
      'I-Poetry',
      'I-Drama',
      'Izindaba',
      'I-Romance',
      'I-Thriller',
      'I-Science Fiction',
    ],
    series: [],
    review: [
      'Incwadi emangalisayo',
      'Okufanele ufunde',
      'Okuhle kakhulu',
      'Incwadi ebalulekile',
      'Indlela yokufunda emangalisayo',
    ],
  },
  vehicle: {
    manufacturer: [
      'Toyota',
      'Volkswagen',
      'BMW',
      'Mercedes-Benz',
      'Ford',
      'Nissan',
      'Hyundai',
      'Kia',
      'Mazda',
      'Isuzu',
      'Chevrolet',
      'Renault',
    ],
    model: [
      'Hilux',
      'Ranger',
      'Polo',
      'Corolla',
      'Fortuner',
      'Navara',
      'i10',
      'Rio',
      'CX-5',
      'D-Max',
      'Captiva',
      'Duster',
    ],
    type: [
      'I-Sedan',
      'I-SUV',
      'I-Bakkie',
      'I-Hatchback',
      'I-Double Cab',
      'I-Single Cab',
      'I-Minibus',
      'I-Van',
      'I-Taxi',
    ],
    fuel: ['I-Petrol', 'I-Diesel', 'I-Electric', 'I-Hybrid'],
    bicycle: ['Ibhayisikili', 'I-Mountain Bike', 'I-Road Bike', 'I-BMX'],
  },
  word: {
    adjective: [
      'hle',
      'khulu',
      'ncane',
      'sha',
      'dala',
      'de',
      'mfishane',
      'ningi',
      'balulekile',
      'futhi',
      'sheshayo',
      'shesha',
      'shisayo',
      'bandayo',
    ],
    adverb: [
      'kakhulu',
      'kancane',
      'kahle',
      'kabi',
      'ngokushesha',
      'ngokucacile',
      'njalo',
      'ngokuvamile',
      'mhlawumbe',
      'impela',
      'ngempela',
    ],
    conjunction: ['futhi', 'noma', 'kodwa', 'ngoba', 'ukuze', 'lapho', 'uma', 'ngaphambi'],
    interjection: ['Hawu', 'Yebo', 'Cha', 'Hayi', 'Eish', 'Heyi', 'Aikona'],
    noun: [
      'umuntu',
      'indlu',
      'imali',
      'usuku',
      'isikhathi',
      'indawo',
      'izinto',
      'umsebenzi',
      'inkathi',
      'izwe',
      'umndeni',
      'ingane',
      'umama',
      'ubaba',
    ],
    preposition: ['ku', 'e', 'nga', 'nge', 'kwa', 'phambi', 'ngemva', 'phakathi', 'ngaphandle'],
    verb: [
      'hamba',
      'fika',
      'dla',
      'phuza',
      'lala',
      'vuka',
      'sebenza',
      'funda',
      'thanda',
      'bona',
      'lalela',
      'khuluma',
      'azi',
      'cela',
      'nika',
    ],
  },
  hacker: {
    abbreviation: [
      'TCP',
      'UDP',
      'IP',
      'HTTP',
      'HTTPS',
      'FTP',
      'SSH',
      'DNS',
      'API',
      'SQL',
      'XML',
      'JSON',
      'HTML',
      'CSS',
      'JS',
    ],
    adjective: [
      'esisodwa',
      'esibalulekile',
      'esidijithali',
      'esivulekile',
      'esiphuzayo',
      'esabelwanayo',
      'esisheshayo',
      'esivikelekile',
      'esihlakaniphile',
    ],
    noun: [
      'i-driver',
      'i-protocol',
      'i-bandwidth',
      'i-panel',
      'i-application',
      'i-firewall',
      'i-interface',
      'i-system',
      'i-program',
      'i-pixel',
    ],
    verb: [
      'browse',
      'hack',
      'override',
      'program',
      'generate',
      'index',
      'transmit',
      'copy',
      'parse',
      'calculate',
      'compile',
    ],
    ingverb: [
      'browsing',
      'hacking',
      'overriding',
      'programming',
      'generating',
      'indexing',
      'transmitting',
      'copying',
      'parsing',
      'calculating',
    ],
    phrase: [
      'Uma sibambelela ku-protocol, singakwazi ukufinyelela ku-TCP port nge-firewall',
      'Kudingeka si-index i-SSD pixel ukuze siqhagamshelane ne-HTTP server',
      'Sebenzisa i-wireless SSL driver ukuvula i-online sensor',
    ],
  },
  system: {
    fileName: [
      'umbiko',
      'idokhumenti',
      'ukwethulwa',
      'ispredishithi',
      'isithombe',
      'ividiyo',
      'umculo',
      'ifayela',
      'idatha',
      'i-backup',
      'ukumisa',
    ],
    fileType: [
      'ividiyo',
      'umculo',
      'isithombe',
      'umbhalo',
      'ifonti',
      'idokhumenti',
      'ispredishithi',
      'okuqalisiwe',
      'kucindezelwe',
      'ikhodi',
      'idatha',
    ],
  },
  science: {
    chemicalElement: [
      'Hydrogen',
      'Helium',
      'Lithium',
      'Carbon',
      'Nitrogen',
      'Oxygen',
      'Fluorine',
      'Neon',
      'Sodium',
      'Magnesium',
      'Aluminium',
      'Silicon',
    ],
    unit: [
      'imitha',
      'ikhilogremu',
      'umzuzwana',
      'i-ampere',
      'i-kelvin',
      'i-mole',
      'i-candela',
      'i-hertz',
      'i-newton',
      'i-joule',
    ],
    constant: [
      'Ijubane Lokukhanya',
      'I-Planck Constant',
      'I-Gravitational Constant',
      'Inombolo ka-Avogadro',
      'I-Boltzmann Constant',
    ],
    field: [
      'I-Physics',
      'I-Chemistry',
      'I-Biology',
      'I-Astronomy',
      'I-Geology',
      'I-Mathematics',
      'I-Medicine',
      'Engineering',
      'I-Computer Science',
    ],
  },
}
