import type { LocaleDefinition } from '@stacksjs/ts-faker'

export const tr: LocaleDefinition = {
  title: 'Turkish',
  person: {
    firstNameMale: [
      'Mehmet',
      'Ahmet',
      'Mustafa',
      'Ali',
      'Hasan',
      'Hüseyin',
      'İbrahim',
      'Mahmut',
      'Ömer',
      'Yusuf',
      'Murat',
      'Kemal',
      'Süleyman',
      'Salih',
      'Abdullah',
      'Recep',
      'İsmail',
      'Osman',
      'Ramazan',
      'Halil',
      'Cem',
      'Can',
      'Emre',
      'Burak',
      'Serkan',
      'Barış',
      'Deniz',
      'Koray',
      'Onur',
      'Eren',
      'Kaan',
      'Arda',
      'Emir',
      'Yiğit',
      'Efe',
      'Çağlar',
      'Alper',
      'Mert',
      'Berkay',
      'Engin',
      'Volkan',
      'Tuncay',
      'Erkan',
      'Gökhan',
      'Özgür',
      'Sinan',
      'Tolga',
      'Uğur',
      'Fatih',
      'Selim',
    ],
    firstNameFemale: [
      'Fatma',
      'Ayşe',
      'Emine',
      'Hatice',
      'Zeynep',
      'Elif',
      'Meryem',
      'Hanife',
      'Şerife',
      'Havva',
      'Ayten',
      'Aysel',
      'Özlem',
      'Gül',
      'Gülşen',
      'Fadime',
      'Hacer',
      'Sultan',
      'Nuriye',
      'Rabia',
      'Merve',
      'Selin',
      'Deniz',
      'Ebru',
      'Ceren',
      'Burcu',
      'Aylin',
      'Pınar',
      'Esra',
      'Derya',
      'Melis',
      'Ece',
      'Defne',
      'Nehir',
      'Işıl',
      'Yağmur',
      'Aslı',
      'Duygu',
      'Nazlı',
      'Damla',
      'Tuğçe',
      'Gizem',
      'Nisa',
      'Şeyma',
      'Büşra',
      'İrem',
      'Sıla',
      'Ada',
      'Azra',
      'Ela',
    ],
    firstNameNeutral: [
      'Deniz',
      'Evren',
      'Ege',
      'Nehir',
      'Umut',
      'Işık',
      'Derya',
      'Güneş',
      'Yıldız',
      'Özge',
    ],
    lastName: ['Yılmaz', 'Kaya', 'Demir', 'Şahin', 'Çelik', 'Yıldız', 'Yıldırım', 'Öztürk', 'Aydın', 'Özdemir', 'Arslan', 'Doğan', 'Kılıç', 'Aslan', 'Çetin', 'Kara', 'Koç', 'Kurt', 'Özkan', 'Şimşek', 'Erdoğan', 'Güneş', 'Korkmaz', 'Acar', 'Çakır', 'Duman', 'Aksoy', 'Türk', 'Polat', 'Güler', 'Tekin', 'Aktaş', 'Karaca', 'Tan', 'Ünal', 'Sarı', 'Çevik', 'Toprak', 'Demirci', 'Bayram'],
    prefix: ['Bay', 'Bayan', 'Dr.', 'Prof.', 'Doç.', 'Mühendis', 'Avukat', 'Hâkim'],
    suffix: ['Jr.', 'Sr.', 'II', 'III', 'IV'],
    gender: ['Erkek', 'Kadın', 'Diğer'],
    jobTitle: ['Yazılım Geliştirici', 'Proje Yöneticisi', 'Tasarımcı', 'Pazarlama Müdürü', 'Satış Müdürü', 'Muhasebeci', 'Avukat', 'Doktor', 'Hemşire', 'Öğretmen', 'Profesör', 'Araştırmacı', 'Veri Analisti', 'Ürün Müdürü', 'İK Müdürü', 'Danışman', 'Mimar', 'Mühendis', 'Teknisyen', 'Aşçı', 'Yazar', 'Gazeteci', 'Fotoğrafçı', 'Sanatçı', 'Müzisyen'],
  },
  address: {
    street: ['İstiklal Caddesi', 'Bağdat Caddesi', 'Cumhuriyet Caddesi', 'Atatürk Bulvarı', 'Gazi Mustafa Kemal Bulvarı', 'Kızılay Meydanı', 'Taksim Meydanı', 'Kadıköy', 'Beşiktaş', 'Şişli', 'Bakırköy', 'Üsküdar', 'Fatih', 'Beyoğlu', 'Karşıyaka', 'Alsancak', 'Konak', 'Kızılay', 'Çankaya', 'Keçiören', 'Mamak', 'Bornova', 'Balçova', 'Gaziemir', 'Karaköy', 'Galata', 'Sultanahmet', 'Emirgan', 'Bebek', 'Nişantaşı'],
    city: ['İstanbul', 'Ankara', 'İzmir', 'Bursa', 'Antalya', 'Adana', 'Konya', 'Gaziantep', 'Şanlıurfa', 'Kocaeli', 'Mersin', 'Diyarbakır', 'Hatay', 'Manisa', 'Kayseri', 'Samsun', 'Balıkesir', 'Kahramanmaraş', 'Van', 'Aydın', 'Denizli', 'Sakarya', 'Tekirdağ', 'Muğla', 'Eskişehir', 'Mardin', 'Malatya', 'Erzurum', 'Trabzon', 'Elazığ'],
    state: ['İstanbul', 'Ankara', 'İzmir', 'Bursa', 'Antalya', 'Adana', 'Konya', 'Gaziantep', 'Şanlıurfa', 'Kocaeli', 'Mersin', 'Diyarbakır', 'Hatay', 'Manisa', 'Kayseri', 'Samsun', 'Balıkesir', 'Kahramanmaraş', 'Van', 'Aydın', 'Denizli', 'Sakarya', 'Tekirdağ', 'Muğla', 'Eskişehir', 'Mardin', 'Malatya', 'Erzurum', 'Trabzon', 'Elazığ', 'Ağrı', 'Aksaray', 'Amasya', 'Artvin', 'Bartın', 'Batman', 'Bayburt', 'Bilecik', 'Bingöl', 'Bitlis'],
    country: ['Türkiye', 'Almanya', 'Fransa', 'İngiltere', 'İtalya', 'Yunanistan', 'Bulgaristan', 'Suriye', 'Irak', 'İran'],
    zipCode: ['#####'],
    direction: ['Kuzey', 'Güney', 'Doğu', 'Batı', 'Kuzeydoğu', 'Kuzeybatı', 'Güneydoğu', 'Güneybatı'],
  },
  company: {
    name: ['Türk Telekom', 'Turkcell', 'Vodafone', 'Arçelik', 'Vestel', 'Beko', 'Turkish Airlines', 'Pegasus', 'Koç Holding', 'Sabancı Holding', 'Ülker', 'Eti', 'Migros', 'Carrefour', 'BİM', 'A101', 'Şok', 'LC Waikiki', 'Mavi', 'Defacto', 'Ziraat Bankası', 'İş Bankası', 'Garanti BBVA', 'Yapı Kredi', 'Akbank', 'Halkbank', 'Vakıfbank', 'Denizbank', 'QNB Finansbank', 'TEB'],
    suffix: ['A.Ş.', 'Ltd. Şti.', 'Holding', 'San. ve Tic. A.Ş.', 'Tic. A.Ş.', 'San. A.Ş.', 'İnş. A.Ş.', 'Paz. A.Ş.', 'Gıda A.Ş.', 'Tekstil A.Ş.'],
    industry: ['Teknoloji', 'Telekomünikasyon', 'Otomotiv', 'Tekstil', 'Gıda', 'İnşaat', 'Enerji', 'Turizm', 'Sağlık', 'Eğitim', 'Finans', 'Bankacılık', 'Sigorta', 'Perakende', 'E-ticaret', 'Lojistik', 'Taşımacılık', 'Medya', 'Reklam', 'Danışmanlık', 'Yazılım', 'Madencilik', 'Tarım', 'Hayvancılık', 'Su Ürünleri'],
    buzzword: ['dijital dönüşüm', 'inovasyon', 'sürdürülebilirlik', 'girişimcilik', 'teknoloji', 'yapay zeka', 'veri analizi', 'bulut', 'nesnelerin interneti', 'blok zincir', 'otomasyon', 'dijitalleşme', 'e-dönüşüm', 'startup', 'scale-up', 'unicorn', 'fintech', 'edtech', 'healthtech', 'agritech', 'martech', 'adtech', 'regtech', 'insurtech', 'proptech'],
    adjective: ['yenilikçi', 'sürdürülebilir', 'dijital', 'çevik', 'verimli', 'güvenilir', 'dinamik', 'modern', 'ilerici', 'lider'],
    descriptor: ['çözüm', 'hizmet', 'ürün', 'sistem', 'platform', 'uygulama', 'teknoloji', 'konsept', 'ağ', 'ekosistem'],
    noun: ['iş', 'inovasyon', 'gelecek', 'ortak', 'müşteri', 'işbirliği', 'başarı', 'büyüme', 'gelişim', 'fırsat'],
    buzzwords: ['dijital dönüşüm', 'inovasyon', 'sürdürülebilirlik', 'girişimcilik', 'teknoloji', 'yapay zeka', 'veri analizi', 'bulut', 'IoT', 'blok zincir', 'otomasyon', 'dijitalleşme', 'startup', 'sinerji', 'optimizasyon'],
  },
  internet: {
    domainName: ['hurriyet.com.tr', 'sabah.com.tr', 'milliyet.com.tr', 'haberturk.com', 'ntv.com.tr', 'trt.net.tr', 'cnnturk.com', 'sozcu.com.tr', 'ensonhaber.com', 'mynet.com', 'haber7.com', 'sahibinden.com', 'arabam.com', 'hepsiburada.com', 'trendyol.com', 'gittigidiyor.com', 'n11.com', 'yemeksepeti.com', 'getir.com', 'turkcell.com.tr', 'vodafone.com.tr', 'turktelekom.com.tr', 'thy.com', 'pegasus.com.tr'],
    domainSuffix: ['.com.tr', '.com', '.net', '.org', '.tr'],
    freeEmail: ['gmail.com', 'outlook.com', 'hotmail.com', 'yahoo.com', 'yandex.com.tr', 'mynet.com'],
  },
  phone: {
    number: ['0### ### ## ##', '+90 ### ### ## ##', '0(###) ### ## ##', '(0###) ### ## ##'],
  },
  food: {
    dish: ['Kebap', 'Döner', 'Lahmacun', 'Pide', 'Köfte', 'Mantı', 'Karnıyarık', 'İmam Bayıldı', 'Dolma', 'Sarma', 'Menemen', 'Çılbır', 'Börek', 'Gözleme', 'Simit', 'Poğaça', 'Çorba', 'Mercimek Çorbası', 'İşkembe Çorbası', 'Tarhana Çorbası', 'Pilav', 'Bulgur Pilavı', 'Kısır', 'Çiğ Köfte', 'Patlıcan Musakka', 'Hünkar Beğendi', 'Ali Nazik', 'Kuru Fasulye', 'Nohut', 'Zeytinyağlı'],
    ingredient: ['Ekmek', 'Pirinç', 'Bulgur', 'Un', 'Yoğurt', 'Peynir', 'Beyaz Peynir', 'Kaşar', 'Tereyağı', 'Zeytinyağı', 'Domates', 'Biber', 'Patlıcan', 'Kabak', 'Soğan', 'Sarımsak', 'Maydanoz', 'Dereotu', 'Nane', 'Kekik', 'Kimyon', 'Sumak', 'Pul Biber', 'Salça', 'Et', 'Kuzu Eti', 'Dana Eti', 'Tavuk', 'Balık', 'Yumurta'],
    cuisine: ['Türk Mutfağı', 'Osmanlı Mutfağı', 'Ege Mutfağı', 'Akdeniz Mutfağı', 'Güneydoğu Mutfağı', 'Karadeniz Mutfağı', 'İtalyan', 'Fransız', 'Çin', 'Japon', 'Hint', 'Meksika', 'Amerikan', 'Yunan', 'Arap', 'Vejetaryen', 'Vegan', 'Glutensiz', 'Balık', 'Et Yemekleri'],
    dessert: ['Baklava', 'Künefe', 'Kadayıf', 'Tulumba', 'Lokma', 'Revani', 'Şekerpare', 'İrmik Helvası', 'Un Helvası', 'Sütlaç', 'Kazandibi', 'Keşkül', 'Tavuk Göğsü', 'Güllaç', 'Aşure', 'Lokum', 'Cezerye', 'Şambali', 'Profiterol', 'Tiramisu', 'Cheesecake', 'Mozaik Pasta', 'Magnolia', 'San Sebastian'],
    fruit: ['Elma', 'Armut', 'Portakal', 'Mandalina', 'Limon', 'Greyfurt', 'Muz', 'Üzüm', 'Kiraz', 'Vişne', 'Çilek', 'Ahudulu', 'Böğürtlen', 'Dut', 'Erik', 'Şeftali', 'Kayısı', 'Karpuz', 'Kavun', 'İncir', 'Nar', 'Hurma', 'Kivi', 'Ananas', 'Mango'],
    vegetable: ['Domates', 'Salatalık', 'Biber', 'Patlıcan', 'Kabak', 'Soğan', 'Sarımsak', 'Havuç', 'Patates', 'Lahana', 'Karnabahar', 'Brokoli', 'Ispanak', 'Marul', 'Roka', 'Semizotu', 'Taze Fasulye', 'Bezelye', 'Bamya', 'Pırasa', 'Kereviz', 'Turp', 'Pancar', 'Mantar', 'Enginar'],
    meat: ['Kuzu Eti', 'Dana Eti', 'Kıyma', 'Pirzola', 'Bonfile', 'Antrikot', 'But', 'Kol', 'Tavuk', 'Hindi', 'Sosis', 'Sucuk', 'Pastırma', 'Kavurma', 'Köfte', 'Ciğer', 'Böbrek', 'Kalp', 'Dil', 'Kelle'],
    spice: ['Tuz', 'Karabiber', 'Kırmızı Biber', 'Pul Biber', 'Kimyon', 'Kekik', 'Nane', 'Fesleğen', 'Biberiye', 'Defne Yaprağı', 'Kakule', 'Tarçın', 'Vanilya', 'Zencefil', 'Zerdeçal', 'Sumak', 'Çörek Otu', 'Susam', 'Haşhaş', 'Safran'],
  },
  animal: {
    dog: ['Kangal', 'Akbaş', 'Çoban Köpeği', 'Kopay', 'Tazı', 'Golden Retriever', 'Labrador', 'Alman Kurdu', 'Rottweiler', 'Doberman', 'Husky', 'Bulldog', 'Beagle', 'Pug', 'Chihuahua', 'Yorkshire Terrier', 'Poodle', 'Pomeranian', 'Shih Tzu', 'Maltese Terrier', 'Cocker Spaniel', 'Jack Russell', 'Border Collie', 'Corgi', 'Dalmaçyalı'],
    cat: ['Van Kedisi', 'Ankara Kedisi', 'Tekir', 'Sarman', 'Persian', 'British Shorthair', 'Scottish Fold', 'Siyam', 'Maine Coon', 'Ragdoll', 'Bengal', 'Sphynx', 'Russian Blue', 'Abyssinian', 'Birman', 'Norwegian Forest', 'Exotic Shorthair', 'Devon Rex', 'American Shorthair', 'Munchkin'],
    bird: ['Martı', 'Güvercin', 'Serçe', 'Karga', 'Saksağan', 'Kırlangıç', 'Şahin', 'Kartal', 'Atmaca', 'Doğan', 'Leylek', 'Turna', 'Flamingo', 'Pelikan', 'Karabatak', 'Ördek', 'Kaz', 'Tavuk', 'Hindi', 'Kumru', 'Bülbül', 'Saka', 'Muhabbet Kuşu', 'Kanarya', 'Papağan'],
    fish: ['Hamsi', 'İstavrit', 'Çupra', 'Levrek', 'Lüfer', 'Palamut', 'Torik', 'Uskumru', 'Mezgit', 'Barbunya', 'Kalamar', 'Ahtapot', 'Midye', 'İstiridye', 'Karides', 'İstakoz', 'Yengeç', 'Sazan', 'Alabalık', 'Turna', 'Som Balığı', 'Kefal', 'Tekir', 'Dil Balığı', 'Kalkan'],
    horse: ['Arap Atı', 'Rahvan', 'Türk Atı', 'Anadolu Atı', 'Safkan İngiliz', 'Pony', 'Shetland Pony', 'Mustang', 'Akhal-Teke', 'Appaloosa', 'Andalusian', 'Friesian', 'Clydesdale', 'Tennessee Walker', 'Quarter Horse'],
    rabbit: ['Tavşan', 'Angora Tavşanı', 'Hollanda Tavşanı', 'Lop Tavşan', 'Rex Tavşan', 'Flamenko Dev', 'Mini Lop', 'Hollanda Cücesi', 'Himalaya Tavşanı', 'Fransız Lop', 'İngiliz Lop', 'Lion Head', 'Jersey Wooly', 'Flemish Giant', 'Californian'],
    insect: ['Kelebek', 'Arı', 'Yusufçuk', 'Çekirge', 'Böcek', 'Karınca', 'Uğurböceği', 'Ateşböceği', 'Gece Kelebeği', 'Sinek', 'Sivrisinek', 'Pire', 'Bit', 'Kene', 'Örümcek', 'Akrep', 'Çıyan', 'Kırkayak', 'Hamam Böceği', 'Gövelek'],
  },
  sport: {
    sport: ['Futbol', 'Basketbol', 'Voleybol', 'Güreş', 'Halter', 'Atletizm', 'Yüzme', 'Bisiklet', 'Tenis', 'Masa Tenisi', 'Badminton', 'Hentbol', 'Jimnastik', 'Boks', 'Judo', 'Karate', 'Taekwondo', 'Okçuluk', 'Atıcılık', 'Eskrim', 'Kayak', 'Snowboard', 'Su Sporları', 'Yelken', 'Dalış'],
    team: ['Galatasaray', 'Fenerbahçe', 'Beşiktaş', 'Trabzonspor', 'Başakşehir', 'Alanyaspor', 'Sivasspor', 'Konyaspor', 'Kasımpaşa', 'Gaziantep FK', 'Anadolu Efes', 'Fenerbahçe Beko', 'Galatasaray Nef', 'Türk Telekom', 'Darüşşafaka', 'Eczacıbaşı', 'Vakıfbank', 'Fenerbahçe Opet', 'THY'],
    athlete: ['Hakan Şükür', 'Rüştü Reçber', 'Emre Belözoğlu', 'Arda Turan', 'Nuri Şahin', 'Burak Yılmaz', 'Yusuf Dikeç', 'Naim Süleymanoğlu', 'Hidayet Türkoğlu', 'Semih Erden', 'Elvan Abeylegesse', 'Merve Aydın', 'Ramil Guliyev', 'İrem Yaman', 'Berkay Özcan', 'Aslı Çakır', 'Ferhat Arıcan', 'Eda Erdem', 'Neslihan Demir', 'Gözde Kırdar'],
  },
  music: {
    genre: ['Türk Sanat Müziği', 'Türk Halk Müziği', 'Arabesk', 'Pop', 'Rock', 'Rap', 'Hip-hop', 'R&B', 'Jazz', 'Klasik', 'Elektronik', 'House', 'Techno', 'Trance', 'Metal', 'Punk', 'Indie', 'Alternative', 'Blues', 'Reggae'],
    artist: ['Tarkan', 'Sezen Aksu', 'Ajda Pekkan', 'Barış Manço', 'Cem Karaca', 'Erkin Koray', 'Teoman', 'Şebnem Ferah', 'Athena', 'Manga', 'Mor ve Ötesi', 'Duman', 'Sertab Erener', 'Kenan Doğulu', 'Mustafa Sandal', 'Hadise', 'Gülşen', 'Aleyna Tilki', 'Edis', 'Mabel Matiz', 'Semicenk', 'Ceza', 'Sagopa Kajmer', 'Ezhel', 'Murda'],
    song: ['Şımarık', 'Şıkıdım', 'Gülümse', 'Masum Değiliz', 'Her Şey Fani', 'Affet', 'Manifesto', 'Bu Böyle', 'Vazgeçtim', 'Deli', 'Şarkıların Gücü', 'Elveda', 'Yerine Sevemem', 'Sevdim', 'İstanbul', 'Aşk', 'Hayat', 'Seni Dert Etmeler', 'Unutursun', 'Yine Mi Çiçek'],
    instrument: ['Gitar', 'Bas Gitar', 'Davul', 'Piyano', 'Klavye', 'Saz', 'Bağlama', 'Ud', 'Kanun', 'Ney', 'Kemençe', 'Keman', 'Viyola', 'Çello', 'Kontrbas', 'Trompet', 'Trombon', 'Saksofon', 'Klarnet', 'Flüt', 'Darbuka', 'Def', 'Bendir', 'Zurna', 'Harmonika'],
  },
  commerce: {
    productName: ['Akıllı Telefon', 'Dizüstü Bilgisayar', 'Tablet', 'Kulaklık', 'Hoparlör', 'Mouse', 'Klavye', 'Monitör', 'Webcam', 'Şarj Aleti', 'Kablo', 'Powerbank', 'Akıllı Saat', 'Ayakkabı', 'Çanta', 'Cüzdan', 'Kemer', 'Saat', 'Güneş Gözlüğü', 'Şapka', 'Tişört', 'Sweatshirt', 'Kot Pantolon', 'Ceket', 'Mont'],
    productAdjective: ['Akıllı', 'Premium', 'Lüks', 'En İyi', 'Popüler', 'Yeni', 'Limitli', 'Kampanya', 'İndirim', 'İndirimli', 'Önerilen', 'Çok Satan', 'Yeni Ürün', 'En Son', 'Özel', 'Pratik', 'Uygun Fiyatlı', 'Marka', 'Orijinal', 'İthal', 'Yerli', 'Çevre Dostu', 'Ücretsiz Kargo', 'Aynı Gün Teslimat'],
    productMaterial: ['Deri', 'Pamuk', 'Polyester', 'Naylon', 'Silikon', 'Plastik', 'Metal', 'Paslanmaz Çelik', 'Alüminyum', 'Titanyum', 'Seramik', 'Cam', 'Ahşap', 'Bambu', 'Kağıt', 'Kauçuk', 'Sünger', 'Lateks', 'Yün', 'Kaşmir'],
    department: ['Elektronik', 'Giyim', 'Kozmetik', 'Gıda ve Sağlık', 'Ev ve Yaşam', 'Mobilya', 'Spor', 'Kitap', 'Oyuncak', 'Dijital', 'Bebek', 'Evcil Hayvan', 'Otomotiv', 'Yapı Market', 'Seyahat', 'Hediye', 'Çocuk', 'Bilgisayar ve Oyun', 'Fotoğraf ve Ses', 'Takı'],
    color: ['Kırmızı', 'Turuncu', 'Sarı', 'Yeşil', 'Mavi', 'Mor', 'Pembe', 'Siyah', 'Beyaz', 'Gri', 'Kahverengi', 'Bej', 'Lacivert', 'Haki', 'Mint', 'Lavanta', 'Mercan', 'Bordo', 'Şarap Kırmızısı', 'Krem'],
  },
  book: {
    title: ['İnce Memed', 'Tutunamayanlar', 'Huzur', 'Saatleri Ayarlama Enstitüsü', 'Yaban', 'Kürk Mantolu Madonna', 'Sinekli Bakkal', 'Kuyucaklı Yusuf', 'Bir İdam Mahkumunun Son Günü', 'İstanbul Hatırası', 'Beyaz Kale', 'Sessiz Ev', 'Kara Kitap', 'Yeni Hayat', 'Kar', 'Benim Adım Kırmızı', 'Masumiyet Müzesi', 'Kafamda Bir Tuhaflık', 'Şu Çılgın Türkler', 'Çalıkuşu'],
    author: ['Orhan Pamuk', 'Yaşar Kemal', 'Sabahattin Ali', 'Oğuz Atay', 'Ahmet Hamdi Tanpınar', 'Nazım Hikmet', 'Aziz Nesin', 'Zülfü Livaneli', 'Elif Şafak', 'Ahmet Ümit', 'İskender Pala', 'Zülfü Livaneli', 'Ayşe Kulin', 'Buket Uzuner', 'Oya Baydar', 'Murathan Mungan', 'İhsan Oktay Anar', 'Hakan Günday', 'Burhan Sönmez', 'Aslı Erdoğan'],
    publisher: ['Can Yayınları', 'Yapı Kredi Yayınları', 'İletişim Yayınları', 'Türkiye İş Bankası Kültür Yayınları', 'Doğan Kitap', 'Everest Yayınları', 'Remzi Kitabevi', 'Kırmızı Kedi', 'Destek Yayınları', 'Pegasus Yayınları', 'Alfa Yayınları', 'İnkılap Kitabevi', 'Altın Kitaplar', 'Timaş Yayınları', 'Epsilon Yayınları'],
    genre: ['Roman', 'Polisiye', 'Gerilim', 'Fantastik', 'Bilim Kurgu', 'Tarihî', 'Biyografi', 'Şiir', 'Deneme', 'Araştırma', 'Otobiyografi', 'Gezi', 'Yemek Kitabı', 'Sağlık', 'Çocuk', 'Genç', 'Çizgi Roman', 'Mizah', 'Drama', 'Deneme'],
    series: ['Kara Kitap Serisi', 'İstanbul Serisi', 'Komiseri Nevzat Serisi', 'Behzat Ç.', 'İstanbul Hatırası', 'Tutunamayanlar', 'Saatleri Ayarlama Enstitüsü', 'Beş Şehir', 'Kar', 'Masumiyet Müzesi', 'Harry Potter', 'Yüzüklerin Efendisi', 'Açlık Oyunları', 'Percy Jackson', 'Hobbit'],
    review: ['Şiddetle tavsiye edilir', 'Harika', 'Mutlaka okunmalı', 'Dokunaklı', 'Unutulmaz', 'Sürükleyici', 'Başyapıt', 'Mükemmel', 'Sağlam', 'Eğlenceli', 'Heyecan verici', 'Komik', 'Üzücü', 'Düşündürücü', 'Etkileyici', 'İlginç', 'Sıkıcı', 'Karmaşık', 'Şaşırtıcı'],
  },
  vehicle: {
    manufacturer: ['Tofaş', 'Ford Otosan', 'Oyak Renault', 'Honda', 'Toyota', 'Volkswagen', 'BMW', 'Mercedes-Benz', 'Audi', 'Hyundai', 'Kia', 'Nissan', 'Peugeot', 'Renault', 'Fiat', 'Opel', 'Skoda', 'Seat', 'Mazda', 'Mitsubishi', 'Subaru', 'Volvo', 'Land Rover', 'Jeep', 'Porsche'],
    model: ['Egea', 'Karsan Atak', 'Doblo', 'Linea', 'Punto', 'Corolla', 'Yaris', 'Auris', 'C-HR', 'RAV4', 'Civic', 'Accord', 'CR-V', 'Golf', 'Passat', 'Polo', 'Tiguan', 'i20', 'i30', 'Tucson', 'Sportage', 'Ceed', 'Qashqai', 'Juke', 'X-Trail'],
    type: ['Sedan', 'SUV', 'Station Wagon', 'Coupe', 'Cabrio', 'Minivan', 'Pickup', 'Spor Araba', 'Elektrikli', 'Hibrit', 'Plug-in Hibrit', 'Hidrojen', 'Kompakt', 'Orta Sınıf', 'Büyük', 'Küçük SUV', 'Orta Boy SUV', 'Büyük SUV', 'MPV', 'Kamyonet'],
    fuel: ['Benzin', 'Dizel', 'Elektrik', 'Hidrojen', 'Hibrit', 'Plug-in Hibrit', 'Biyodizel', 'Etanol', 'LPG', 'CNG'],
    bicycle: ['Dağ Bisikleti', 'Yol Bisikleti', 'Hibrit', 'Şehir Bisikleti', 'BMX', 'Fixie', 'Cruiser', 'Elektrikli Bisiklet', 'Katlanır Bisiklet', 'Çocuk Bisikleti', 'Tur Bisikleti', 'Gravel', 'Cyclocross', 'Track', 'Yatay Bisiklet', 'Tandem', 'Üç Tekerlekli', 'Scooter', 'Elektrikli Scooter', 'Kargo Bisikleti'],
  },
  word: {
    adjective: ['güzel', 'büyük', 'küçük', 'iyi', 'kötü', 'hızlı', 'yavaş', 'yüksek', 'alçak', 'yeni', 'eski', 'sıcak', 'soğuk', 'aydınlık', 'karanlık', 'mutlu', 'üzgün', 'neşeli', 'kızgın', 'korkmuş', 'cesur', 'güçlü', 'zayıf', 'akıllı', 'aptal', 'hoş', 'çirkin', 'temiz', 'kirli', 'zengin'],
    adverb: ['hızlıca', 'yavaşça', 'sessizce', 'yüksek sesle', 'alçak', 'çok', 'az', 'her zaman', 'asla', 'sık sık', 'nadiren', 'belki', 'kesinlikle', 'gerçekten', 'oldukça', 'biraz', 'son derece', 'neredeyse', 'yaklaşık', 'tam', 'aniden', 'yavaş yavaş', 'hemen', 'derhal', 'sonra', 'önce', 'şimdi', 'o zaman'],
    conjunction: ['ve', 'veya', 'ama', 'fakat', 'çünkü', 'eğer', 'zaman', 'iken', 'sonra', 'rağmen', 'ya', 'hem', 'öyleyse', 'bu yüzden', 'dolayısıyla', 'yine de', 'ancak', 'ayrıca', 'oysa', 'yani'],
    interjection: ['Ah', 'Oh', 'Ay', 'Uf', 'Puf', 'Yaşasın', 'Aa', 'Vay', 'Haydi', 'Of', 'Merhaba', 'Ha', 'Hmm', 'Evet', 'Hayır', 'Tamam', 'Vay be', 'Eyvah', 'Hop', 'Hadi'],
    noun: ['kişi', 'ev', 'ağaç', 'çiçek', 'su', 'ateş', 'rüzgar', 'gökyüzü', 'toprak', 'dağ', 'nehir', 'deniz', 'güneş', 'ay', 'yıldız', 'bulut', 'yağmur', 'kar', 'gök gürültüsü', 'şimşek', 'kitap', 'okul', 'öğretmen', 'öğrenci', 'arkadaş', 'aile', 'baba', 'anne', 'kız kardeş', 'erkek kardeş'],
    preposition: ['içinde', 'üzerinde', 'ile', 'için', 'üzerinden', 'altında', 'yanında', 'arasında', 'boyunca', 'etrafında', 'doğru', 'hakkında', 'sonra', 'önce'],
    verb: ['gitmek', 'gelmek', 'yemek', 'içmek', 'uyumak', 'uyanmak', 'oturmak', 'ayakta durmak', 'yatmak', 'koşmak', 'atlamak', 'konuşmak', 'dinlemek', 'görmek', 'okumak', 'yazmak', 'öğrenmek', 'öğretmek', 'düşünmek', 'bilmek', 'hissetmek', 'sevmek', 'nefret etmek', 'gülmek', 'ağlamak', 'oynamak', 'çalışmak', 'dinlenmek'],
  },
  hacker: {
    abbreviation: ['AI', 'ML', 'IoT', 'API', 'SDK', 'IDE', 'OS', 'DB', 'SQL', 'HTTP', 'HTTPS', 'REST', 'JSON', 'XML', 'HTML', 'CSS', 'JS', 'UI', 'UX', 'CI/CD', 'DevOps', 'AWS', 'GCP', 'Azure', 'K8s', 'Docker', 'Git', 'SVN', 'FTP', 'SSH'],
    adjective: ['dağıtık', 'bulut tabanlı', 'kuantum', 'sinirsel', 'derin öğrenme', 'makine öğrenmesi', 'blok zincir', 'şifreli', 'hash', 'sıkıştırılmış', 'optimize edilmiş', 'ölçeklenebilir', 'yüksek erişilebilir', 'hata toleranslı', 'gerçek zamanlı', 'asenkron', 'senkron', 'paralel', 'dağıtık', 'merkezi'],
    noun: ['algoritma', 'veri yapısı', 'protokol', 'arayüz', 'modül', 'paket', 'kütüphane', 'framework', 'middleware', 'veritabanı', 'sunucu', 'istemci', 'ağ', 'güvenlik', 'şifreleme', 'hash', 'token', 'oturum', 'çerez', 'önbellek', 'kuyruk', 'yığın', 'heap', 'ağaç', 'graf', 'dizi', 'liste', 'harita', 'küme'],
    verb: ['çalıştırmak', 'derlemek', 'hata ayıklamak', 'yayınlamak', 'oluşturmak', 'test etmek', 'optimize etmek', 'refactor etmek', 'entegre etmek', 'senkronize etmek', 'şifrelemek', 'şifre çözmek', 'hash', 'sıkıştırmak', 'açmak', 'serialize etmek', 'deserialize etmek', 'parse etmek', 'doğrulamak', 'kimlik doğrulamak'],
    ingverb: ['kodlama', 'programlama', 'geliştirme', 'tasarım', 'analiz', 'test', 'hata ayıklama', 'dağıtım', 'izleme', 'günlükleme', 'profilleme', 'kıyaslama', 'ölçekleme', 'taşıma', 'refactor', 'optimizasyon', 'dokümantasyon', 'inceleme', 'entegrasyon', 'otomasyon'],
    phrase: ['AI geleceği değiştiriyor', 'Big data通içgörü sağlıyor', 'Bulut sınırsız fırsatlar sunuyor', 'Blok zincir güven inşa ediyor', 'Kuantum bilgisayarlar geliyor', 'Makine öğrenmesi tahmin ediyor', 'Derin öğrenme öğreniyor', 'IoT her şeyi bağlıyor', '5G her şeyi değiştiriyor', 'Metaverse bekliyor', 'Web3 yol gösteriyor', 'NFT dijital varlık', 'Akıllı sözleşmeler otomatikleştiriyor', 'DeFi finansı yenilikçileştiriyor', 'DAO merkeziyetsizleştiriyor', 'Çapraz platform verimlilik getiriyor', 'Mikro hizmetler ölçeklenebilirlik getiriyor', 'Konteynerlar dağıtımı basitleştiriyor', 'CI/CD hızlı teslimat için', 'DevOps işbirliğini güçlendiriyor'],
  },
  system: {
    fileName: ['belge', 'rapor', 'sunum', 'elektronik tablo', 'resim', 'video', 'ses', 'arşiv', 'yürütülebilir', 'yapılandırma', 'günlük', 'yedek', 'geçici', 'önbellek', 'veri', 'kurulum', 'güncelleme', 'sürücü', 'kütüphane', 'betik'],
    fileType: ['belge', 'resim', 'video', 'ses', 'arşiv', 'yürütülebilir', 'yapılandırma', 'veri', 'yedek', 'günlük', 'önbellek', 'geçici', 'sistem', 'kütüphane', 'sürücü', 'güncelleme', 'kurulum', 'yazı tipi', 'tema', 'eklenti'],
  },
  science: {
    chemicalElement: ['Hidrojen', 'Helyum', 'Lityum', 'Berilyum', 'Bor', 'Karbon', 'Azot', 'Oksijen', 'Flor', 'Neon', 'Sodyum', 'Magnezyum', 'Alüminyum', 'Silisyum', 'Fosfor', 'Kükürt', 'Klor', 'Argon', 'Potasyum', 'Kalsiyum', 'Demir', 'Bakır', 'Çinko', 'Gümüş', 'Altın', 'Cıva', 'Kurşun', 'Uranyum', 'Plütonyum', 'Radon'],
    unit: ['metre', 'kilogram', 'saniye', 'amper', 'kelvin', 'mol', 'kandela', 'newton', 'paskal', 'joule', 'watt', 'coulomb', 'volt', 'ohm', 'hertz', 'litre', 'gram', 'santimetre', 'milimetre', 'kilometre', 'milisaniye', 'mikrosaniye', 'nanosaniye'],
    constant: ['ışık hızı', 'yerçekimi sabiti', 'Planck sabiti', 'Boltzmann sabiti', 'Avogadro sayısı', 'gaz sabiti', 'vakumun geçirgenliği', 'vakumun manyetik geçirgenliği', 'temel yük', 'proton kütlesi', 'elektron kütlesi', 'nötron kütlesi', 'ince yapı sabiti', 'Rydberg sabiti', 'Stefan-Boltzmann sabiti'],
    field: ['Fizik', 'Kimya', 'Biyoloji', 'Astronomi', 'Jeoloji', 'Meteoroloji', 'Oşinografi', 'Ekoloji', 'Genetik', 'Moleküler Biyoloji', 'Hücre Biyolojisi', 'Sinirbilim', 'Psikoloji', 'Matematik', 'İstatistik', 'Bilgisayar Bilimi', 'Mühendislik', 'Tıp', 'Eczacılık', 'Veterinerlik', 'Tarım', 'Çevre Bilimi', 'Nanoteknoloji', 'Malzeme Bilimi', 'Enerji Araştırması'],
  },
  color: {
    name: ['kırmızı', 'turuncu', 'sarı', 'yeşil', 'mavi', 'çivit', 'mor', 'pembe', 'siyah', 'beyaz', 'gri', 'kahverengi', 'bej', 'krem', 'fildişi', 'altın', 'gümüş', 'bronz', 'bakır', 'zeytin', 'haki', 'lacivert', 'nane', 'turkuaz', 'macenta', 'mor', 'çimen yeşili', 'gök mavisi', 'lacivert', 'kestane'],
  },
}
