import type { LocaleDefinition } from '@stacksjs/ts-faker'

export const es: LocaleDefinition = {
  title: 'Spanish',
  person: {
    firstNameMale: [
      'Antonio',
      'José',
      'Manuel',
      'Francisco',
      'Juan',
      'David',
      'Carlos',
      'Miguel',
      'Pedro',
      'Luis',
      'Jesús',
      'Javier',
      'Fernando',
      'Daniel',
      'Pablo',
      'Rafael',
      'Alejandro',
      'Ángel',
      'Sergio',
      'Alberto',
      'Diego',
      'Jorge',
      'Andrés',
      'Rubén',
      'Adrián',
      'Raúl',
      'Enrique',
      'Óscar',
      'Marcos',
      'Iván',
      'Santiago',
      'Mateo',
      'Sebastián',
      'Nicolás',
      'Gabriel',
      'Lucas',
      'Martín',
      'Hugo',
      'Bruno',
      'Leo',
    ],
    firstNameFemale: [
      'María',
      'Carmen',
      'Josefa',
      'Isabel',
      'Dolores',
      'Pilar',
      'Teresa',
      'Ana',
      'Francisca',
      'Laura',
      'Rosa',
      'Cristina',
      'Marta',
      'Elena',
      'Patricia',
      'Raquel',
      'Beatriz',
      'Sara',
      'Silvia',
      'Mercedes',
      'Sofía',
      'Isabella',
      'Valentina',
      'Camila',
      'Valeria',
      'Lucía',
      'Martina',
      'Emma',
      'Victoria',
      'Gabriela',
      'Paula',
      'Claudia',
      'Natalia',
      'Andrea',
      'Lorena',
      'Mónica',
      'Ángela',
      'Rocío',
      'Verónica',
      'Alicia',
    ],
    firstNameNeutral: [
      'Ariel',
      'Alex',
      'Cruz',
      'Guadalupe',
      'Jesús María',
      'Trinidad',
      'Asunción',
      'Montserrat',
      'Azul',
      'Mar',
    ],
    lastName: [
      'García',
      'Martínez',
      'López',
      'González',
      'Rodríguez',
      'Fernández',
      'Pérez',
      'Sánchez',
      'Ramírez',
      'Torres',
      'Flores',
      'Rivera',
      'Gómez',
      'Díaz',
      'Cruz',
      'Morales',
      'Reyes',
      'Gutiérrez',
      'Ortiz',
      'Jiménez',
    ],
    prefix: ['Sr.', 'Sra.', 'Srta.', 'Dr.', 'Dra.', 'Prof.'],
    suffix: ['Jr.', 'Sr.', 'I', 'II', 'III', 'IV', 'V'],
    gender: ['Masculino', 'Femenino', 'No binario', 'Agénero', 'Bigénero', 'Género fluido'],
    jobTitle: [
      'Ingeniero de Software',
      'Gerente de Producto',
      'Diseñador',
      'Científico de Datos',
      'Ingeniero DevOps',
      'Gerente de Marketing',
      'Representante de Ventas',
      'Contador',
      'Gerente de Recursos Humanos',
      'Director',
    ],
  },
  address: {
    street: [
      'Principal',
      'Central',
      'Mayor',
      'Real',
      'Nueva',
      'San José',
      'Las Flores',
      'Del Sol',
      'La Paz',
      'Libertad',
      'Independencia',
      'Reforma',
      'Juárez',
      'Hidalgo',
    ],
    city: [
      'Madrid',
      'Barcelona',
      'Valencia',
      'Sevilla',
      'Zaragoza',
      'Málaga',
      'Murcia',
      'Palma',
      'Las Palmas',
      'Bilbao',
      'Alicante',
      'Córdoba',
      'Valladolid',
      'Vigo',
      'Gijón',
    ],
    state: [
      'Andalucía',
      'Cataluña',
      'Madrid',
      'Comunidad Valenciana',
      'Galicia',
      'Castilla y León',
      'País Vasco',
      'Canarias',
      'Castilla-La Mancha',
      'Murcia',
      'Aragón',
      'Extremadura',
    ],
    stateAbbr: [
      'AN',
      'CT',
      'MD',
      'VC',
      'GA',
      'CL',
      'PV',
      'CN',
      'CM',
      'MU',
      'AR',
      'EX',
    ],
    country: [
      'España',
      'México',
      'Argentina',
      'Colombia',
      'Perú',
      'Venezuela',
      'Chile',
      'Ecuador',
      'Guatemala',
      'Cuba',
      'República Dominicana',
      'Honduras',
      'Bolivia',
      'Paraguay',
    ],
    countryCode: ['ES', 'MX', 'AR', 'CO', 'PE', 'VE', 'CL', 'EC', 'GT', 'CU', 'DO', 'HN', 'BO', 'PY'],
    zipCode: ['#####'],
    buildingNumber: ['###', '##', '#'],
    direction: ['Norte', 'Sur', 'Este', 'Oeste', 'Noreste', 'Noroeste', 'Sureste', 'Suroeste'],
    streetSuffix: [
      'Calle',
      'Avenida',
      'Plaza',
      'Paseo',
      'Camino',
      'Ronda',
      'Travesía',
      'Vía',
      'Glorieta',
      'Callejón',
      'Pasaje',
      'Carretera',
    ],
  },
  company: {
    name: [
      'TechnoSoft',
      'IberiaTech',
      'GlobalSol',
      'DataMex',
      'InnovaHispana',
      'SoluDigital',
      'NuevaTech',
      'FuturoSoft',
      'SistemaSmart',
      'CoreTech España',
    ],
    suffix: ['S.A.', 'S.L.', 'S.R.L.', 'Ltda.', 'Corp', 'Tecnologías', 'Soluciones', 'Sistemas'],
    industry: [
      'Tecnología',
      'Finanzas',
      'Salud',
      'Educación',
      'Comercio',
      'Manufactura',
      'Telecomunicaciones',
      'Energía',
      'Inmobiliaria',
      'Transporte',
      'Medios',
      'Hostelería',
    ],
    buzzwords: [
      'sinergizar',
      'aprovechar',
      'innovar',
      'revolucionar',
      'optimizar',
      'transformar',
      'potenciar',
      'habilitar',
      'facilitar',
      'orquestar',
      'integrar',
    ],
    adjective: [
      'revolucionario',
      'innovador',
      'avanzado',
      'líder',
      'premier',
      'empresarial',
      'escalable',
      'robusto',
      'ágil',
      'seguro',
      'eficiente',
      'inteligente',
    ],
    descriptor: [
      'global',
      'digital',
      'en la nube',
      'con IA',
      'basado en datos',
      'centrado en el usuario',
      'automatizado',
      'integrado',
      'moderno',
      'innovador',
    ],
    noun: [
      'solución',
      'plataforma',
      'sistema',
      'servicio',
      'tecnología',
      'marco',
      'infraestructura',
      'aplicación',
      'red',
      'portal',
      'ecosistema',
      'arquitectura',
    ],
  },
  internet: {
    domainSuffix: ['es', 'com', 'net', 'org', 'mx', 'ar', 'co', 'cl'],
    freeEmail: ['gmail.com', 'yahoo.es', 'hotmail.es', 'outlook.es', 'correo.es'],
  },
  phone: {
    formats: [
      '###-###-###',
      '(+34) ###-###-###',
      '6##-###-###',
      '7##-###-###',
    ],
  },
  food: {
    dish: [
      'Paella',
      'Tortilla Española',
      'Gazpacho',
      'Jamón Ibérico',
      'Croquetas',
      'Patatas Bravas',
      'Pulpo a la Gallega',
      'Fabada Asturiana',
      'Cochinillo',
      'Churros',
      'Empanada',
      'Pisto',
      'Albóndigas',
      'Calamares',
      'Gambas al Ajillo',
      'Arroz con Pollo',
      'Sopa de Ajo',
      'Migas',
      'Bacalao',
      'Rabo de Toro',
      'Tacos',
      'Enchiladas',
      'Quesadillas',
      'Burritos',
      'Tamales',
    ],
    ingredient: [
      'Ajo',
      'Cebolla',
      'Tomate',
      'Pimentón',
      'Azafrán',
      'Aceite de Oliva',
      'Jamón',
      'Chorizo',
      'Arroz',
      'Patata',
      'Pimiento',
      'Pollo',
      'Cerdo',
      'Pescado',
      'Mariscos',
      'Queso',
      'Huevos',
      'Harina',
      'Sal',
      'Pimienta',
      'Cilantro',
      'Perejil',
      'Limón',
      'Naranja',
    ],
    cuisine: [
      'Española',
      'Mexicana',
      'Argentina',
      'Peruana',
      'Colombiana',
      'Chilena',
      'Venezolana',
      'Cubana',
      'Italiana',
      'Francesa',
      'China',
      'Japonesa',
      'Mediterránea',
      'Latinoamericana',
    ],
    dessert: [
      'Flan',
      'Churros con Chocolate',
      'Tarta de Santiago',
      'Crema Catalana',
      'Torrijas',
      'Natillas',
      'Arroz con Leche',
      'Polvorones',
      'Turrón',
      'Brazo de Gitano',
      'Magdalenas',
      'Rosquillas',
      'Tres Leches',
      'Dulce de Leche',
      'Alfajores',
      'Suspiros',
      'Buñuelos',
    ],
    fruit: [
      'Naranja',
      'Limón',
      'Manzana',
      'Pera',
      'Uva',
      'Sandía',
      'Melón',
      'Fresa',
      'Plátano',
      'Melocotón',
      'Albaricoque',
      'Cereza',
      'Piña',
      'Mango',
      'Papaya',
      'Guayaba',
      'Maracuyá',
    ],
    vegetable: [
      'Tomate',
      'Patata',
      'Cebolla',
      'Ajo',
      'Pimiento',
      'Zanahoria',
      'Lechuga',
      'Espinaca',
      'Calabacín',
      'Berenjena',
      'Brócoli',
      'Coliflor',
      'Guisantes',
      'Judías',
      'Pepino',
    ],
    meat: [
      'Cerdo',
      'Pollo',
      'Ternera',
      'Cordero',
      'Jamón',
      'Chorizo',
      'Morcilla',
      'Lomo',
      'Costilla',
      'Pavo',
      'Conejo',
      'Pato',
      'Salchichón',
      'Cecina',
    ],
    spice: [
      'Pimentón',
      'Azafrán',
      'Comino',
      'Orégano',
      'Tomillo',
      'Romero',
      'Laurel',
      'Perejil',
      'Cilantro',
      'Canela',
      'Clavo',
      'Nuez Moscada',
      'Pimienta',
      'Curry',
      'Jengibre',
    ],
  },
  animal: {
    dog: [
      'Pastor Alemán',
      'Labrador',
      'Golden Retriever',
      'Bulldog',
      'Chihuahua',
      'Caniche',
      'Yorkshire Terrier',
      'Bóxer',
      'Dálmata',
      'Beagle',
      'Galgo Español',
      'Mastín',
      'Cocker Spaniel',
      'San Bernardo',
      'Husky Siberiano',
      'Rottweiler',
      'Doberman',
    ],
    cat: [
      'Persa',
      'Siamés',
      'Maine Coon',
      'Bengala',
      'Ragdoll',
      'Angora',
      'Británico de Pelo Corto',
      'Azul Ruso',
      'Esfinge',
      'Birmano',
      'Abisinio',
      'Siberiano',
      'Bosque de Noruega',
    ],
    bird: [
      'Águila',
      'Halcón',
      'Búho',
      'Loro',
      'Canario',
      'Jilguero',
      'Paloma',
      'Gorrión',
      'Pájaro Carpintero',
      'Colibrí',
      'Flamenco',
      'Cisne',
      'Pato',
      'Ganso',
      'Garza',
    ],
    fish: [
      'Pez Dorado',
      'Betta',
      'Guppy',
      'Tetra',
      'Carpa',
      'Pez Ángel',
      'Pez Payaso',
      'Trucha',
      'Salmón',
      'Atún',
      'Bacalao',
      'Merluza',
      'Lubina',
      'Dorada',
    ],
    horse: [
      'Pura Raza Española',
      'Árabe',
      'Pura Sangre',
      'Quarter Horse',
      'Appaloosa',
      'Mustang',
      'Andaluz',
      'Lusitano',
      'Frisón',
      'Percherón',
      'Caballo Azteca',
      'Criollo',
    ],
    rabbit: [
      'Holland Lop',
      'Enano Holandés',
      'Mini Rex',
      'Gigante de Flandes',
      'Angora',
      'Belier',
      'Cabeza de León',
      'Rex',
      'Californiano',
      'Neozelandés',
    ],
    insect: [
      'Mariposa',
      'Abeja',
      'Hormiga',
      'Escarabajo',
      'Mariquita',
      'Libélula',
      'Saltamontes',
      'Grillo',
      'Luciérnaga',
      'Mantis Religiosa',
      'Mosca',
      'Mosquito',
      'Avispa',
    ],
    type: [
      'Perro',
      'Gato',
      'Pájaro',
      'Pez',
      'Conejo',
      'Hámster',
      'Cobaya',
      'Ratón',
      'Tortuga',
      'Lagarto',
      'Serpiente',
      'Rana',
      'Hurón',
      'Chinchilla',
    ],
  },
  sport: {
    sport: [
      'Fútbol',
      'Baloncesto',
      'Tenis',
      'Pádel',
      'Ciclismo',
      'Natación',
      'Atletismo',
      'Voleibol',
      'Balonmano',
      'Béisbol',
      'Golf',
      'Hockey',
      'Rugby',
      'Boxeo',
      'Artes Marciales',
      'Esquí',
      'Surf',
      'Escalada',
      'Motociclismo',
      'Fórmula 1',
      'Gimnasia',
      'Esgrima',
    ],
    team: [
      'Real Madrid',
      'Barcelona',
      'Atlético de Madrid',
      'Sevilla',
      'Valencia',
      'Athletic Bilbao',
      'Boca Juniors',
      'River Plate',
      'Chivas',
      'América',
      'Nacional',
      'Peñarol',
      'Colo-Colo',
    ],
    athlete: [
      'Rafael Nadal',
      'Pau Gasol',
      'Fernando Alonso',
      'Iker Casillas',
      'Andrés Iniesta',
      'Sergio Ramos',
      'Lionel Messi',
      'Diego Maradona',
      'Pelé',
      'Ronaldinho',
      'Carlos Sainz',
    ],
  },
  music: {
    genre: [
      'Flamenco',
      'Salsa',
      'Reggaeton',
      'Bachata',
      'Merengue',
      'Cumbia',
      'Tango',
      'Mariachi',
      'Rock en Español',
      'Pop Latino',
      'Bolero',
      'Ranchera',
      'Rumba',
      'Son Cubano',
      'Bossa Nova',
    ],
    artist: [
      'Rosalía',
      'Shakira',
      'Enrique Iglesias',
      'Alejandro Sanz',
      'Juanes',
      'Maná',
      'Mecano',
      'Héroes del Silencio',
      'Soda Stereo',
      'Los Fabulosos Cadillacs',
      'Café Tacvba',
      'Calle 13',
    ],
    song: [
      'Despacito',
      'Bailando',
      'La Bamba',
      'Vivir Mi Vida',
      'Oye Como Va',
      'Bésame Mucho',
      'Cielito Lindo',
      'Guantanamera',
      'La Macarena',
      'Amor Eterno',
      'Como La Flor',
    ],
    instrument: [
      'Guitarra',
      'Piano',
      'Batería',
      'Bajo',
      'Violín',
      'Saxofón',
      'Trompeta',
      'Flauta',
      'Castañuelas',
      'Cajón',
      'Bongó',
      'Conga',
      'Maracas',
      'Charango',
      'Bandoneón',
    ],
  },
  commerce: {
    product: [
      'Silla',
      'Mesa',
      'Lámpara',
      'Sofá',
      'Cama',
      'Escritorio',
      'Ordenador',
      'Teléfono',
      'Reloj',
      'Zapatos',
      'Camisa',
      'Pantalón',
      'Chaqueta',
      'Gafas',
      'Bolso',
      'Cartera',
    ],
    productAdjective: [
      'Pequeño',
      'Grande',
      'Ergonómico',
      'Rústico',
      'Moderno',
      'Elegante',
      'Práctico',
      'Increíble',
      'Fantástico',
      'Genérico',
      'Artesanal',
      'Premium',
      'Duradero',
      'Ligero',
    ],
    productMaterial: [
      'Acero',
      'Madera',
      'Plástico',
      'Algodón',
      'Cuero',
      'Vidrio',
      'Aluminio',
      'Metal',
      'Seda',
      'Lana',
      'Lino',
      'Terciopelo',
      'Caucho',
      'Cerámica',
      'Hormigón',
    ],
    department: [
      'Electrónica',
      'Ropa',
      'Hogar y Jardín',
      'Deportes',
      'Libros',
      'Juguetes',
      'Salud y Belleza',
      'Alimentación',
      'Joyería',
      'Herramientas',
      'Bebé',
      'Mascotas',
    ],
    color: [
      'Rojo',
      'Azul',
      'Verde',
      'Amarillo',
      'Negro',
      'Blanco',
      'Gris',
      'Rosa',
      'Naranja',
      'Morado',
      'Marrón',
      'Dorado',
      'Plateado',
      'Turquesa',
      'Beige',
      'Violeta',
    ],
  },
  book: {
    title: [
      'Cien Años de Soledad',
      'Don Quijote de la Mancha',
      'El Amor en los Tiempos del Cólera',
      'La Sombra del Viento',
      'Rayuela',
      'Pedro Páramo',
      'La Casa de los Espíritus',
      'El Túnel',
      'Ficciones',
      'El Aleph',
      'Crónica de una Muerte Anunciada',
      'Los Detectives Salvajes',
      'La Ciudad y los Perros',
      'El Laberinto de la Soledad',
      'Como Agua para Chocolate',
      'La Colmena',
      'Tres Tristes Tigres',
      'El Otoño del Patriarca',
      'La Tregua',
      'El Llano en Llamas',
      'Doña Bárbara',
      'Los de Abajo',
      'La Vorágine',
      'El Señor Presidente',
      'Hopscotch',
      'Aura',
      'La Muerte de Artemio Cruz',
      'El Reino de Este Mundo',
      'Los Pasos Perdidos',
      'La Fiesta del Chivo',
    ],
    author: [
      'Gabriel García Márquez',
      'Miguel de Cervantes',
      'Jorge Luis Borges',
      'Isabel Allende',
      'Carlos Ruiz Zafón',
      'Mario Vargas Llosa',
      'Julio Cortázar',
      'Pablo Neruda',
      'Octavio Paz',
      'Juan Rulfo',
      'Laura Esquivel',
      'Roberto Bolaño',
      'Ernesto Sábato',
      'Arturo Pérez-Reverte',
      'Camilo José Cela',
      'Miguel Delibes',
      'Federico García Lorca',
      'Rafael Alberti',
      'Antonio Machado',
      'Gustavo Adolfo Bécquer',
      'Sor Juana Inés de la Cruz',
      'Gabriela Mistral',
      'César Vallejo',
      'Rubén Darío',
      'José Martí',
      'Horacio Quiroga',
      'Jorge Amado',
      'Alejo Carpentier',
      'Carlos Fuentes',
      'Elena Poniatowska',
    ],
    publisher: [
      'Editorial Planeta',
      'Alfaguara',
      'Anagrama',
      'Tusquets',
      'Seix Barral',
      'Destino',
      'Random House Mondadori',
      'Ediciones Salamandra',
      'Editorial Sudamericana',
      'Fondo de Cultura Económica',
      'Galaxia Gutenberg',
      'Ediciones B',
      'Penguin Random House',
      'Santillana',
      'Editorial Crítica',
      'Acantilado',
      'Impedimenta',
      'Sexto Piso',
      'Pre-Textos',
      'Siruela',
    ],
    genre: [
      'Realismo Mágico',
      'Novela',
      'Poesía',
      'Ensayo',
      'Cuento',
      'Teatro',
      'Biografía',
      'Ficción Histórica',
      'Misterio',
      'Thriller',
      'Ciencia Ficción',
      'Fantasía',
      'Romance',
      'Aventura',
      'Terror',
      'No Ficción',
      'Autobiografía',
      'Crónica',
      'Literatura Contemporánea',
      'Clásico',
      'Drama',
      'Sátira',
      'Policiaco',
    ],
    series: [
      'El Cementerio de los Libros Olvidados',
      'Las Aventuras del Capitán Alatriste',
      'Episodios Nacionales',
      'La Saga de los Confines',
      'Crónicas Vampíricas',
      'La Trilogía de la Ciudad Blanca',
      'Los Casos del Comisario Carvalho',
      'El Club Dumas',
      'La Serie Falcó',
      'El Barco de Vapor',
      'Las Crónicas de Narnia',
      'El Internado Laguna Negra',
      'Los Cinco',
      'Torres de Malory',
      'Los Hollister',
    ],
    review: [
      'Una obra maestra del realismo mágico que cautiva desde la primera página.',
      'Un relato magistral que explora las profundidades del alma humana.',
      'Una narrativa brillante llena de giros inesperados y personajes inolvidables.',
      'Una lectura imprescindible para los amantes de la literatura latinoamericana.',
      'Un libro que te atrapa desde el principio y no puedes soltar.',
      'Una historia conmovedora que refleja la complejidad de la condición humana.',
      'Prosa elegante y emotiva que permanece en la memoria mucho después de leerla.',
      'Una exploración profunda de temas universales con un estilo único.',
      'Un clásico moderno que redefine los límites de la narrativa.',
      'Una lectura fascinante que combina historia, cultura y ficción de manera magistral.',
    ],
  },
  vehicle: {
    manufacturer: [
      'SEAT',
      'Renault',
      'Peugeot',
      'Citroën',
      'Volkswagen',
      'Opel',
      'Ford',
      'Nissan',
      'Toyota',
      'Mercedes-Benz',
      'BMW',
      'Audi',
      'Fiat',
      'Kia',
      'Hyundai',
      'Mazda',
      'Honda',
      'Volvo',
      'Skoda',
      'Dacia',
      'Suzuki',
      'Mitsubishi',
      'Subaru',
      'Jeep',
    ],
    model: [
      'Ibiza',
      'León',
      'Ateca',
      'Arona',
      'Tarraco',
      'Clio',
      'Mégane',
      'Captur',
      'Kadjar',
      '208',
      '308',
      '2008',
      '3008',
      'C3',
      'C4',
      'Berlingo',
      'Golf',
      'Polo',
      'Tiguan',
      'Passat',
      'Corsa',
      'Astra',
      'Fiesta',
      'Focus',
      'Kuga',
      'Qashqai',
      'Juke',
      'X-Trail',
      'Corolla',
      'Yaris',
      'RAV4',
      'Clase A',
      'Clase C',
      'GLA',
      'Serie 1',
      'Serie 3',
      'X1',
      'A3',
      'A4',
      'Q3',
      'Panda',
      '500',
      'Tipo',
      'Sportage',
      'Niro',
      'Tucson',
      'i30',
    ],
    type: [
      'Sedán',
      'SUV',
      'Monovolumen',
      'Utilitario',
      'Deportivo',
      'Familiar',
      'Coupé',
      'Todoterreno',
      'Cabrio',
      'Pick-up',
      'Furgoneta',
      'Compacto',
      'Berlina',
      'Crossover',
      'Hatchback',
      'Roadster',
      'Microcar',
    ],
    fuel: [
      'Gasolina',
      'Diésel',
      'Eléctrico',
      'Híbrido',
      'Híbrido Enchufable',
      'GLP',
      'GNC',
      'Biodiésel',
      'E85',
      'Hidrógeno',
      'Flex',
    ],
    bicycle: [
      'Bicicleta de Montaña',
      'Bicicleta de Carretera',
      'Bicicleta Urbana',
      'Bicicleta Eléctrica',
      'BMX',
      'Bicicleta Plegable',
      'Bicicleta Híbrida',
      'Bicicleta de Paseo',
      'Bicicleta Gravel',
      'Bicicleta de Descenso',
      'Bicicleta Cruiser',
      'Tandem',
      'Triciclo',
      'Bicicleta de Trial',
    ],
  },
  word: {
    adjective: [
      'bueno',
      'grande',
      'pequeño',
      'nuevo',
      'viejo',
      'joven',
      'feliz',
      'triste',
      'alto',
      'bajo',
      'rápido',
      'lento',
      'fuerte',
      'débil',
      'claro',
      'oscuro',
      'caliente',
      'frío',
      'dulce',
      'amargo',
      'hermoso',
      'feo',
      'rico',
      'pobre',
      'fácil',
      'difícil',
      'largo',
      'corto',
      'ancho',
      'estrecho',
      'pesado',
      'ligero',
      'limpio',
      'sucio',
      'lleno',
      'vacío',
      'suave',
      'duro',
      'blando',
      'áspero',
      'brillante',
      'opaco',
      'alegre',
      'serio',
      'simpático',
      'antipático',
      'inteligente',
      'tonto',
      'valiente',
      'cobarde',
      'generoso',
      'tacaño',
      'honesto',
      'deshonesto',
      'paciente',
      'impaciente',
    ],
    adverb: [
      'bien',
      'mal',
      'muy',
      'poco',
      'mucho',
      'más',
      'menos',
      'también',
      'tampoco',
      'siempre',
      'nunca',
      'ahora',
      'después',
      'antes',
      'luego',
      'todavía',
      'ya',
      'aquí',
      'allí',
      'allá',
      'cerca',
      'lejos',
      'arriba',
      'abajo',
      'adelante',
      'atrás',
      'dentro',
      'fuera',
      'encima',
      'debajo',
      'rápidamente',
      'lentamente',
      'fácilmente',
      'difícilmente',
      'claramente',
      'exactamente',
      'probablemente',
      'posiblemente',
      'quizás',
      'tal vez',
      'ciertamente',
      'realmente',
      'verdaderamente',
      'solamente',
      'apenas',
      'casi',
      'totalmente',
      'completamente',
      'absolutamente',
    ],
    conjunction: [
      'y',
      'e',
      'o',
      'u',
      'pero',
      'mas',
      'sino',
      'aunque',
      'porque',
      'pues',
      'si',
      'que',
      'cuando',
      'mientras',
      'como',
      'según',
      'donde',
      'ni',
      'tanto',
      'ya que',
      'puesto que',
      'dado que',
      'a fin de que',
      'para que',
      'con tal de que',
      'sin embargo',
      'no obstante',
      'por lo tanto',
      'por consiguiente',
      'así que',
      'de modo que',
      'de manera que',
    ],
    interjection: [
      '¡Ay!',
      '¡Oh!',
      '¡Ah!',
      '¡Eh!',
      '¡Uf!',
      '¡Bah!',
      '¡Caramba!',
      '¡Hola!',
      '¡Adiós!',
      '¡Bravo!',
      '¡Olé!',
      '¡Hurra!',
      '¡Viva!',
      '¡Socorro!',
      '¡Cuidado!',
      '¡Atención!',
      '¡Silencio!',
      '¡Ánimo!',
      '¡Enhorabuena!',
      '¡Felicidades!',
      '¡Salud!',
      '¡Chin chin!',
      '¡Ojo!',
      '¡Vale!',
      '¡Claro!',
      '¡Por supuesto!',
      '¡Ojalá!',
      '¡Qué va!',
      '¡Vaya!',
      '¡Hombre!',
      '¡Mujer!',
      '¡Chico!',
    ],
    noun: [
      'casa',
      'hombre',
      'mujer',
      'niño',
      'agua',
      'tiempo',
      'día',
      'noche',
      'mano',
      'pie',
      'cabeza',
      'ojo',
      'boca',
      'corazón',
      'vida',
      'muerte',
      'amor',
      'odio',
      'paz',
      'guerra',
      'sol',
      'luna',
      'estrella',
      'cielo',
      'tierra',
      'mar',
      'río',
      'montaña',
      'árbol',
      'flor',
      'libro',
      'mesa',
      'silla',
      'puerta',
      'ventana',
      'calle',
      'ciudad',
      'país',
      'mundo',
      'gente',
      'familia',
      'padre',
      'madre',
      'hijo',
      'hermano',
      'amigo',
      'trabajo',
      'escuela',
      'comida',
      'dinero',
      'música',
      'arte',
      'historia',
      'futuro',
      'pasado',
      'presente',
      'palabra',
      'pensamiento',
      'idea',
    ],
    preposition: [
      'a',
      'ante',
      'bajo',
      'con',
      'contra',
      'de',
      'desde',
      'durante',
      'en',
      'entre',
      'hacia',
      'hasta',
      'mediante',
      'para',
      'por',
      'según',
      'sin',
      'sobre',
      'tras',
      'versus',
      'vía',
    ],
    verb: [
      'ser',
      'estar',
      'haber',
      'tener',
      'hacer',
      'decir',
      'ir',
      'venir',
      'ver',
      'dar',
      'saber',
      'poder',
      'querer',
      'poner',
      'llevar',
      'llegar',
      'pasar',
      'deber',
      'dejar',
      'seguir',
      'encontrar',
      'llamar',
      'volver',
      'tomar',
      'conocer',
      'vivir',
      'sentir',
      'tratar',
      'mirar',
      'contar',
      'empezar',
      'parecer',
      'quedar',
      'creer',
      'hablar',
      'llevar',
      'dejar',
      'seguir',
      'trabajar',
      'estudiar',
      'aprender',
      'enseñar',
      'escribir',
      'leer',
      'escuchar',
      'pensar',
      'recordar',
      'olvidar',
      'buscar',
      'encontrar',
      'perder',
      'ganar',
      'comprar',
      'vender',
    ],
  },
  hacker: {
    abbreviation: [
      'SQL',
      'HTML',
      'CSS',
      'HTTP',
      'HTTPS',
      'FTP',
      'SSH',
      'API',
      'JSON',
      'XML',
      'URL',
      'IP',
      'TCP',
      'UDP',
      'DNS',
      'VPN',
      'SSL',
      'TLS',
      'RAM',
      'ROM',
      'CPU',
      'GPU',
      'SSD',
      'HDD',
      'USB',
      'LAN',
      'WAN',
      'WiFi',
      'OS',
      'GUI',
      'CLI',
      'IDE',
      'SDK',
      'DDOS',
      'XSS',
    ],
    adjective: [
      'digital',
      'virtual',
      'encriptado',
      'descifrado',
      'hackeado',
      'infectado',
      'protegido',
      'vulnerable',
      'seguro',
      'inseguro',
      'online',
      'offline',
      'remoto',
      'local',
      'inalámbrico',
      'abierto',
      'cerrado',
      'bloqueado',
      'desbloqueado',
      'conectado',
      'desconectado',
      'cifrado',
      'codificado',
      'compilado',
      'ejecutable',
      'malicioso',
      'benigno',
      'recursivo',
      'distribuido',
    ],
    noun: [
      'firewall',
      'servidor',
      'base de datos',
      'contraseña',
      'algoritmo',
      'código',
      'programa',
      'aplicación',
      'sistema',
      'red',
      'protocolo',
      'puerto',
      'paquete',
      'byte',
      'bit',
      'pixel',
      'archivo',
      'carpeta',
      'directorio',
      'script',
      'shell',
      'terminal',
      'consola',
      'kernel',
      'daemon',
      'proceso',
      'hilo',
      'caché',
      'cookie',
      'token',
      'sesión',
      'malware',
      'virus',
      'troyano',
      'gusano',
      'backdoor',
      'rootkit',
      'exploit',
      'payload',
      'vulnerabilidad',
      'parche',
    ],
    verb: [
      'hackear',
      'cifrar',
      'descifrar',
      'encriptar',
      'desencriptar',
      'compilar',
      'ejecutar',
      'debugear',
      'programar',
      'codificar',
      'decodificar',
      'parsear',
      'renderizar',
      'cachear',
      'loguear',
      'autenticar',
      'autorizar',
      'validar',
      'sanitizar',
      'inyectar',
      'explotar',
      'parchear',
      'actualizar',
      'migrar',
      'deployar',
      'escalar',
      'optimizar',
      'refactorizar',
    ],
    ingverb: [
      'hackeando',
      'cifrando',
      'descifrando',
      'encriptando',
      'desencriptando',
      'compilando',
      'ejecutando',
      'debugeando',
      'programando',
      'codificando',
      'decodificando',
      'parseando',
      'renderizando',
      'cacheando',
      'logueando',
      'autenticando',
      'autorizando',
      'validando',
      'sanitizando',
      'inyectando',
      'explotando',
      'parcheando',
      'actualizando',
      'migrando',
      'deployando',
      'escalando',
      'optimizando',
      'refactorizando',
      'monitoreando',
      'analizando',
    ],
    phrase: [
      'fuerza bruta',
      'inyección SQL',
      'ataque DDoS',
      'phishing',
      'ingeniería social',
      'hombre en el medio',
      'día cero',
      'escalada de privilegios',
      'denegación de servicio',
      'cross-site scripting',
      'desbordamiento de búfer',
      'autenticación de dos factores',
      'certificado digital',
      'clave pública',
      'clave privada',
      'hash criptográfico',
      'puerto trasero',
      'caballo de Troya',
      'red zombi',
      'sombrero blanco',
      'sombrero negro',
    ],
  },
  system: {
    fileName: [
      'documento',
      'informe',
      'presentacion',
      'datos',
      'archivo',
      'imagen',
      'video',
      'audio',
      'proyecto',
      'tarea',
      'borrador',
      'final',
      'copia',
      'respaldo',
      'temporal',
      'configuracion',
      'script',
      'programa',
      'instalador',
      'actualizacion',
      'parche',
      'registro',
      'log',
      'cache',
      'indice',
      'base_datos',
      'exportacion',
      'importacion',
      'plantilla',
      'muestra',
      'ejemplo',
    ],
    fileType: [
      'pdf',
      'doc',
      'docx',
      'txt',
      'rtf',
      'odt',
      'xls',
      'xlsx',
      'csv',
      'ppt',
      'pptx',
      'jpg',
      'jpeg',
      'png',
      'gif',
      'bmp',
      'svg',
      'mp3',
      'mp4',
      'avi',
      'mov',
      'wmv',
      'flv',
      'zip',
      'rar',
      '7z',
      'tar',
      'gz',
      'exe',
      'dmg',
      'iso',
      'sql',
      'db',
      'html',
      'css',
      'js',
      'json',
      'xml',
      'py',
      'java',
      'cpp',
      'c',
      'php',
      'rb',
      'go',
      'rs',
      'ts',
      'sh',
      'bat',
    ],
  },
  science: {
    chemicalElement: [
      'Hidrógeno',
      'Helio',
      'Litio',
      'Berilio',
      'Boro',
      'Carbono',
      'Nitrógeno',
      'Oxígeno',
      'Flúor',
      'Neón',
      'Sodio',
      'Magnesio',
      'Aluminio',
      'Silicio',
      'Fósforo',
      'Azufre',
      'Cloro',
      'Argón',
      'Potasio',
      'Calcio',
      'Hierro',
      'Cobre',
      'Zinc',
      'Plata',
      'Oro',
      'Mercurio',
      'Plomo',
      'Uranio',
      'Plutonio',
      'Radio',
      'Radón',
      'Tecnecio',
      'Prometio',
    ],
    unit: [
      'metro',
      'kilómetro',
      'centímetro',
      'milímetro',
      'micrómetro',
      'nanómetro',
      'litro',
      'mililitro',
      'gramo',
      'kilogramo',
      'tonelada',
      'segundo',
      'minuto',
      'hora',
      'día',
      'año',
      'amperio',
      'voltio',
      'vatio',
      'ohmio',
      'julio',
      'newton',
      'pascal',
      'hertz',
      'kelvin',
      'celsius',
      'fahrenheit',
      'mol',
      'candela',
      'lux',
      'becquerel',
      'gray',
    ],
    constant: [
      'Velocidad de la Luz',
      'Constante de Planck',
      'Constante de Gravitación Universal',
      'Constante de Avogadro',
      'Constante de Boltzmann',
      'Carga Elemental',
      'Masa del Electrón',
      'Masa del Protón',
      'Permitividad del Vacío',
      'Permeabilidad del Vacío',
      'Número Pi',
      'Número de Euler',
      'Proporción Áurea',
      'Constante de Faraday',
      'Constante de los Gases',
    ],
    field: [
      'Física',
      'Química',
      'Biología',
      'Matemáticas',
      'Astronomía',
      'Geología',
      'Ecología',
      'Botánica',
      'Zoología',
      'Genética',
      'Microbiología',
      'Neurociencia',
      'Paleontología',
      'Oceanografía',
      'Meteorología',
      'Sismología',
      'Vulcanología',
      'Cristalografía',
      'Termodinámica',
      'Mecánica Cuántica',
      'Relatividad',
      'Astrofísica',
      'Bioquímica',
      'Biofísica',
      'Geofísica',
      'Informática',
      'Robótica',
      'Nanotecnología',
      'Biotecnología',
    ],
  },
}
