import type { LocaleDefinition } from '@stacksjs/ts-faker'

export const pt: LocaleDefinition = {
  title: 'Portuguese',
  person: {
    firstNameMale: [
      'Miguel',
      'João',
      'Francisco',
      'Rodrigo',
      'Gabriel',
      'Santiago',
      'Tomás',
      'Afonso',
      'Gonçalo',
      'Diogo',
      'Pedro',
      'Tiago',
      'Martim',
      'Lucas',
      'Rafael',
      'Henrique',
      'Guilherme',
      'Duarte',
      'Vicente',
      'Dinis',
      'André',
      'Bernardo',
      'Eduardo',
      'Felipe',
      'Bruno',
      'Carlos',
      'Daniel',
      'Fernando',
      'Gustavo',
      'Hugo',
      'Igor',
      'José',
      'Leonardo',
      'Manuel',
      'Nuno',
      'Paulo',
      'Ricardo',
      'Sérgio',
      'Vítor',
      'Alexandre',
      'António',
      'Cristiano',
      'David',
      'Fábio',
      'Gonçalo',
      'Ivo',
      'Joaquim',
      'Lourenço',
      'Marco',
      'Mateus',
      'Nelson',
      'Renato',
      'Rui',
      'Samuel',
      'Simão',
      'Telmo',
      'Vasco',
      'Xavier',
    ],
    firstNameFemale: [
      'Maria',
      'Leonor',
      'Matilde',
      'Beatriz',
      'Carolina',
      'Mariana',
      'Ana',
      'Inês',
      'Sofia',
      'Lara',
      'Francisca',
      'Alice',
      'Joana',
      'Laura',
      'Marta',
      'Rita',
      'Sara',
      'Diana',
      'Catarina',
      'Isabel',
      'Gabriela',
      'Juliana',
      'Patrícia',
      'Raquel',
      'Teresa',
      'Vera',
      'Adriana',
      'Carla',
      'Cristina',
      'Helena',
      'Luísa',
      'Mónica',
      'Paula',
      'Sandra',
      'Sónia',
      'Susana',
      'Andreia',
      'Cláudia',
      'Filipa',
      'Ines',
      'Lúcia',
      'Margarida',
      'Melissa',
      'Olivia',
      'Rafaela',
      'Tatiana',
      'Vanessa',
      'Vitória',
      'Yara',
      'Zara',
      'Amélia',
      'Benedita',
      'Camila',
      'Daniela',
      'Emília',
      'Fátima',
      'Graça',
      'Joana',
      'Lídia',
      'Manuela',
      'Natália',
      'Piedade',
      'Rosa',
      'Sílvia',
      'Tânia',
      'Vânia',
    ],
    firstNameNeutral: [
      'Alex',
      'Ariel',
      'Casey',
      'Dominique',
      'Eden',
      'Gabi',
      'Jô',
      'Kim',
      'Lou',
      'Morgan',
      'Nico',
      'Pat',
      'Quinn',
      'Rafa',
      'Sam',
      'Taylor',
      'Val',
    ],
    lastName: [
      'Silva',
      'Santos',
      'Ferreira',
      'Pereira',
      'Oliveira',
      'Costa',
      'Rodrigues',
      'Martins',
      'Jesus',
      'Sousa',
      'Fernandes',
      'Gonçalves',
      'Gomes',
      'Lopes',
      'Marques',
      'Alves',
      'Almeida',
      'Ribeiro',
      'Pinto',
      'Carvalho',
      'Teixeira',
      'Moreira',
      'Correia',
      'Mendes',
      'Nunes',
      'Soares',
      'Vieira',
      'Monteiro',
      'Cardoso',
      'Rocha',
      'Neto',
      'Barbosa',
      'Dias',
      'Castro',
      'Campos',
      'Freitas',
      'Antunes',
      'Cunha',
      'Fonseca',
      'Macedo',
      'Melo',
      'Batista',
      'Ramos',
      'Barros',
      'Coelho',
      'Cruz',
      'Lima',
      'Pires',
      'Reis',
      'Pacheco',
      'Azevedo',
      'Miranda',
      'Araújo',
      'Farias',
      'Tavares',
      'Moura',
      'Duarte',
      'Magalhães',
      'Nogueira',
      'Nascimento',
      'Brito',
      'Matos',
      'Guedes',
      'Morais',
      'Brandão',
      'Carneiro',
      'Henriques',
      'Simões',
      'Vaz',
      'Guerreiro',
    ],
    prefix: ['Sr.', 'Sra.', 'Dr.', 'Dra.', 'Prof.', 'Prof.ª', 'Eng.', 'Arq.'],
    suffix: ['Júnior', 'Filho', 'Neto', 'I', 'II', 'III'],
    gender: ['Masculino', 'Feminino', 'Não-binário', 'Agênero', 'Gênero fluido'],
    jobTitle: [
      'Engenheiro de Software',
      'Gerente de Produto',
      'Designer',
      'Cientista de Dados',
      'Engenheiro DevOps',
      'Gerente de Marketing',
      'Representante de Vendas',
      'Contador',
      'Gerente de RH',
      'Diretor Executivo',
      'Diretor Técnico',
      'Diretor Financeiro',
      'Gerente de Projetos',
      'Analista de Negócios',
      'Desenvolvedor',
      'Arquiteto de Software',
      'Consultor',
      'Analista',
      'Coordenador',
      'Especialista',
      'Técnico',
      'Assistente',
      'Gerente de Operações',
      'Gerente Comercial',
      'Supervisor',
    ],
  },
  address: {
    street: [
      'Principal',
      'Central',
      'da Liberdade',
      'da República',
      'do Comércio',
      'da Independência',
      'da Paz',
      'das Flores',
      'do Sol',
      'da Praia',
      'do Porto',
      'da Igreja',
      'da Estação',
      'dos Navegadores',
      'dos Descobrimentos',
      'Vasco da Gama',
      'Infante D. Henrique',
    ],
    city: [
      'Lisboa',
      'Porto',
      'Amadora',
      'Braga',
      'Setúbal',
      'Coimbra',
      'Queluz',
      'Funchal',
      'Cacém',
      'Vila Nova de Gaia',
      'Algueirão-Mem Martins',
      'Loures',
      'Évora',
      'Rio de Mouro',
      'Odivelas',
      'Aveiro',
      'Gondomar',
      'Viseu',
      'Guimarães',
      'Matosinhos',
      'Leiria',
      'Faro',
      'Almada',
      'Barreiro',
      'Seixal',
      'Barcelos',
      'Penafiel',
      'São Paulo',
      'Rio de Janeiro',
      'Brasília',
      'Salvador',
      'Fortaleza',
      'Belo Horizonte',
      'Manaus',
      'Curitiba',
      'Recife',
      'Porto Alegre',
      'Belém',
      'Goiânia',
      'Guarulhos',
      'Campinas',
      'São Luís',
      'Maceió',
    ],
    state: [
      'Lisboa',
      'Porto',
      'Faro',
      'Braga',
      'Aveiro',
      'Coimbra',
      'Setúbal',
      'Viseu',
      'Leiria',
      'Santarém',
      'Açores',
      'Madeira',
      'Évora',
      'Beja',
      'Viana do Castelo',
      'Vila Real',
      'Bragança',
      'Guarda',
      'São Paulo',
      'Rio de Janeiro',
      'Minas Gerais',
      'Bahia',
      'Paraná',
      'Rio Grande do Sul',
      'Pernambuco',
      'Ceará',
      'Pará',
      'Maranhão',
      'Goiás',
      'Amazonas',
      'Espírito Santo',
    ],
    stateAbbr: [
      'LSB',
      'PRT',
      'FAR',
      'BRG',
      'AVR',
      'CBR',
      'STB',
      'VIS',
      'LRA',
      'SNT',
      'SP',
      'RJ',
      'MG',
      'BA',
      'PR',
      'RS',
      'PE',
      'CE',
      'PA',
      'MA',
      'GO',
      'AM',
      'ES',
    ],
    country: [
      'Portugal',
      'Brasil',
      'Angola',
      'Moçambique',
      'Cabo Verde',
      'Guiné-Bissau',
      'Timor-Leste',
      'São Tomé e Príncipe',
      'Espanha',
      'França',
      'Luxemburgo',
      'Suíça',
      'Alemanha',
    ],
    countryCode: ['PT', 'BR', 'AO', 'MZ', 'CV', 'GW', 'TL', 'ST', 'ES', 'FR', 'LU', 'CH', 'DE'],
    zipCode: ['####-###'],
    buildingNumber: ['###', '##', '#'],
    direction: ['Norte', 'Sul', 'Este', 'Oeste', 'Nordeste', 'Noroeste', 'Sudeste', 'Sudoeste'],
    streetSuffix: [
      'Rua',
      'Avenida',
      'Praça',
      'Travessa',
      'Alameda',
      'Largo',
      'Estrada',
      'Calçada',
      'Beco',
      'Rodovia',
      'Via',
      'Ladeira',
      'Viela',
      'Marginal',
      'Parque',
    ],
  },
  company: {
    name: [
      'LusoTech',
      'PortoSoft',
      'GlobalLuso',
      'DataBrasil',
      'InovaPortugal',
      'SoluDigital',
      'NovaTech',
      'FuturoSoft',
      'SistemaSmart',
      'CoreTech Lisboa',
      'AtlânticoTech',
      'IbériaSoft',
    ],
    suffix: ['S.A.', 'Lda.', 'Unipessoal Lda.', 'Technologies', 'Solutions', 'Systems', 'Group'],
    industry: [
      'Tecnologia',
      'Finanças',
      'Saúde',
      'Educação',
      'Comércio',
      'Manufatura',
      'Telecomunicações',
      'Energia',
      'Imobiliário',
      'Transportes',
      'Media',
      'Hospitalidade',
      'Turismo',
      'Agricultura',
    ],
    buzzwords: [
      'sinergizar',
      'aproveitar',
      'inovar',
      'revolucionar',
      'otimizar',
      'transformar',
      'potencializar',
      'habilitar',
      'facilitar',
      'orquestrar',
      'integrar',
      'digitalizar',
    ],
    adjective: [
      'revolucionário',
      'inovador',
      'avançado',
      'líder',
      'premium',
      'empresarial',
      'escalável',
      'robusto',
      'ágil',
      'seguro',
      'eficiente',
      'inteligente',
      'moderno',
    ],
    descriptor: [
      'global',
      'digital',
      'em nuvem',
      'com IA',
      'baseado em dados',
      'centrado no usuário',
      'automatizado',
      'integrado',
      'conectado',
      'inteligente',
      'personalizado',
      'sustentável',
    ],
    noun: [
      'solução',
      'plataforma',
      'sistema',
      'serviço',
      'tecnologia',
      'framework',
      'infraestrutura',
      'aplicação',
      'rede',
      'portal',
      'ecossistema',
      'arquitetura',
      'motor',
    ],
  },
  internet: {
    domainSuffix: ['pt', 'com', 'net', 'org', 'br', 'eu', 'info'],
    freeEmail: ['gmail.com', 'sapo.pt', 'hotmail.com', 'outlook.pt', 'yahoo.com.br', 'uol.com.br', 'bol.com.br'],
  },
  phone: {
    formats: [
      '2## ### ###',
      '+351 2## ### ###',
      '9## ### ###',
      '+351 9## ### ###',
      '(##) ####-####',
      '+55 (##) ####-####',
      '+55 (##) #####-####',
    ],
  },
  food: {
    dish: ['Bacalhau à Brás', 'Francesinha', 'Cozido à Portuguesa', 'Arroz de Marisco', 'Feijoada', 'Caldo Verde', 'Pastéis de Nata', 'Sardinhas Assadas', 'Alheira', 'Açorda', 'Cataplana', 'Polvo à Lagareiro', 'Arroz de Pato', 'Bifana', 'Prego', 'Carne de Porco à Alentejana', 'Caldeirada', 'Arroz Doce', 'Bolo de Arroz', 'Pastel de Belém', 'Pão de Ló', 'Queijadas', 'Acarajé', 'Pão de Queijo', 'Moqueca'],
    ingredient: ['Bacalhau', 'Azeite', 'Alho', 'Cebola', 'Tomate', 'Batata', 'Arroz', 'Feijão', 'Ovos', 'Queijo', 'Presunto', 'Chouriço', 'Piri-Piri', 'Coentros', 'Salsa', 'Louro', 'Colorau', 'Vinho', 'Açúcar', 'Canela', 'Farinha', 'Sal', 'Pimenta', 'Limão', 'Laranja'],
    cuisine: ['Portuguesa', 'Brasileira', 'Mediterrânea', 'Italiana', 'Chinesa', 'Japonesa', 'Indiana', 'Francesa', 'Espanhola', 'Mexicana'],
    dessert: ['Pastéis de Nata', 'Arroz Doce', 'Pudim Flan', 'Bolo de Bolacha', 'Bolo Rei', 'Pão de Ló', 'Ovos Moles', 'Queijadas', 'Toucinho do Céu', 'Brigadeiro', 'Beijinho', 'Pudim de Leite', 'Manjar Branco', 'Quindim', 'Cocada'],
    fruit: ['Maçã', 'Pera', 'Laranja', 'Banana', 'Uva', 'Morango', 'Cereja', 'Pêssego', 'Melancia', 'Melão', 'Kiwi', 'Ananás', 'Manga', 'Maracujá', 'Goiaba'],
    vegetable: ['Tomate', 'Alface', 'Cebola', 'Alho', 'Batata', 'Cenoura', 'Couve', 'Espinafre', 'Brócolos', 'Couve-flor', 'Pimento', 'Beringela', 'Courgette', 'Feijão Verde', 'Cogumelos'],
    meat: ['Vaca', 'Porco', 'Frango', 'Peru', 'Cordeiro', 'Coelho', 'Pato', 'Vitela', 'Chouriço', 'Presunto', 'Alheira', 'Morcela'],
    spice: ['Alho', 'Cebola', 'Louro', 'Salsa', 'Coentros', 'Piri-Piri', 'Colorau', 'Canela', 'Noz-Moscada', 'Cominho', 'Açafrão', 'Orégãos'],
  },
  animal: {
    dog: ['Pastor Alemão', 'Labrador', 'Golden Retriever', 'Bulldog', 'Beagle', 'Chihuahua', 'Caniche', 'Boxer', 'Rottweiler', 'Dálmata', 'Pastor Belga', 'Pointer', 'Serra da Estrela', 'Perdigueiro Português', 'Cão de Água Português'],
    cat: ['Persa', 'Siamês', 'Maine Coon', 'Bengal', 'Ragdoll', 'British Shorthair', 'Sphynx', 'Abissínio', 'Birmanês', 'Europeu'],
    bird: ['Águia', 'Falcão', 'Coruja', 'Papagaio', 'Canário', 'Pardal', 'Pombo', 'Pomba', 'Rouxinol', 'Melro', 'Cegonha', 'Andorinha'],
    fish: ['Peixe Dourado', 'Betta', 'Guppy', 'Tetra', 'Carpa', 'Truta', 'Salmão', 'Atum', 'Robalo', 'Dourada', 'Sardinha', 'Bacalhau'],
    horse: ['Árabe', 'Puro-sangue', 'Quarter Horse', 'Frisão', 'Lusitano', 'Mustang', 'Appaloosa', 'Andaluz', 'Lipizzano'],
    rabbit: ['Mini Lop', 'Anão', 'Rex', 'Angora', 'Gigante de Flandres', 'Holandês', 'Californiano'],
    insect: ['Borboleta', 'Abelha', 'Formiga', 'Besouro', 'Joaninha', 'Libélula', 'Gafanhoto', 'Grilo', 'Pirilampo', 'Louva-a-Deus'],
    type: ['Cão', 'Gato', 'Pássaro', 'Peixe', 'Coelho', 'Hamster', 'Porquinho-da-Índia', 'Rato', 'Tartaruga', 'Lagarto'],
  },
  sport: {
    sport: ['Futebol', 'Basquetebol', 'Voleibol', 'Ténis', 'Atletismo', 'Natação', 'Ciclismo', 'Andebol', 'Futsal', 'Surf', 'Rugby', 'Hóquei em Patins', 'Judo', 'Golfe', 'Vela'],
    team: ['Benfica', 'Porto', 'Sporting', 'Braga', 'Vitória de Guimarães', 'Boavista', 'Sporting de Braga', 'Flamengo', 'Corinthians', 'Palmeiras', 'São Paulo', 'Santos'],
    athlete: ['Cristiano Ronaldo', 'Eusébio', 'Luís Figo', 'José Mourinho', 'Nuno Gomes', 'Rui Costa', 'João Félix', 'Bernardo Silva', 'Pelé', 'Ronaldo', 'Ronaldinho', 'Neymar'],
  },
  music: {
    genre: ['Fado', 'Samba', 'Bossa Nova', 'MPB', 'Forró', 'Sertanejo', 'Funk Carioca', 'Rock', 'Pop', 'Jazz', 'Eletrônica', 'Hip Hop', 'Reggae'],
    artist: ['Amália Rodrigues', 'Carlos do Carmo', 'Mariza', 'António Variações', 'Madredeus', 'Dulce Pontes', 'Carminho', 'Ana Moura', 'João Gilberto', 'Tom Jobim', 'Caetano Veloso', 'Gilberto Gil'],
    song: ['Fado Português', 'Gaivota', 'Meu Amor de Longe', 'Canção do Mar', 'Garota de Ipanema', 'Águas de Março', 'Chega de Saudade', 'Mas Que Nada'],
    instrument: ['Piano', 'Guitarra', 'Guitarra Portuguesa', 'Violino', 'Bateria', 'Saxofone', 'Trompete', 'Flauta', 'Acordeão', 'Harpa', 'Violoncelo', 'Cavaquinho'],
  },
  commerce: {
    product: ['Cadeira', 'Mesa', 'Candeeiro', 'Sofá', 'Cama', 'Secretária', 'Computador', 'Telemóvel', 'Relógio', 'Sapatos', 'Mala', 'Mochila', 'Óculos'],
    productAdjective: ['Pequeno', 'Grande', 'Ergonómico', 'Rústico', 'Moderno', 'Elegante', 'Prático', 'Incrível', 'Fantástico', 'Durável', 'Luxuoso', 'Profissional'],
    productMaterial: ['Aço', 'Madeira', 'Plástico', 'Algodão', 'Pele', 'Vidro', 'Alumínio', 'Metal', 'Seda', 'Lã', 'Cerâmica', 'Mármore'],
    department: ['Eletrónica', 'Roupa', 'Casa e Jardim', 'Desporto', 'Livros', 'Brinquedos', 'Saúde e Beleza', 'Alimentação', 'Moda', 'Decoração'],
    color: ['Vermelho', 'Azul', 'Verde', 'Amarelo', 'Preto', 'Branco', 'Cinzento', 'Rosa', 'Laranja', 'Roxo', 'Castanho', 'Bege'],
  },
  book: {
    title: ['Os Lusíadas', 'Mensagem', 'Memorial do Convento', 'O Ano da Morte de Ricardo Reis', 'A Cidade e as Serras', 'Capitães da Areia', 'Grande Sertão: Veredas', 'Gabriela, Cravo e Canela', 'Dom Casmurro', 'Memórias Póstumas de Brás Cubas', 'A Hora da Estrela', 'O Cortiço', 'O Primo Basílio', 'Os Maias', 'A Relíquia', 'Viagens na Minha Terra', 'O Crime do Padre Amaro', 'Ensaio sobre a Cegueira', 'Levantado do Chão', 'A Jangada de Pedra', 'História do Cerco de Lisboa', 'Quincas Borba', 'São Bernardo', 'Vidas Secas', 'A Bagaceira'],
    author: ['Fernando Pessoa', 'José Saramago', 'Eça de Queirós', 'Camilo Castelo Branco', 'Luís de Camões', 'Almeida Garrett', 'Sophia de Mello Breyner', 'António Lobo Antunes', 'Lídia Jorge', 'Jorge Amado', 'Machado de Assis', 'Clarice Lispector', 'João Guimarães Rosa', 'Graciliano Ramos', 'Rachel de Queiroz', 'José de Alencar', 'Carlos Drummond de Andrade', 'Cecília Meireles', 'Vinícius de Moraes', 'Paulo Coelho', 'Mia Couto', 'Pepetela', 'José Eduardo Agualusa', 'Valter Hugo Mãe', 'Gonçalo M. Tavares'],
    publisher: ['Porto Editora', 'Leya', 'Presença', 'Dom Quixote', 'Bertrand', 'Relógio d\'Água', 'Gradiva', 'Tinta da China', 'Companhia das Letras', 'Record', 'Rocco', 'Objetiva', 'Globo Livros', 'Planeta', 'Saraiva', 'Cosac Naify', 'Boitempo', 'L&PM', 'Nova Fronteira', 'Alfaguara'],
    genre: ['Romance', 'Poesia', 'Drama', 'Ficção', 'Não-ficção', 'Biografia', 'Ensaio', 'Crónica', 'Conto', 'Novela', 'Fantasia', 'Suspense', 'Policial', 'Aventura', 'História', 'Filosofia', 'Autoajuda', 'Ciência', 'Tecnologia', 'Literatura Infantil'],
    series: ['Os Descobrimentos', 'Crónicas do Tempo', 'A História de Portugal', 'Memórias de África', 'Saga Familiar', 'Mistérios do Douro', 'Aventuras no Atlântico', 'Contos do Mar', 'A Trilogia Lusitana', 'As Vidas Secretas', 'Os Navegadores', 'Crônicas Brasileiras', 'A Série do Sertão', 'Os Clássicos Modernos', 'Literatura Contemporânea'],
    review: ['Uma obra-prima da literatura portuguesa', 'Um livro fascinante e envolvente', 'Leitura obrigatória', 'Profundamente comovente', 'Escrita magnífica', 'Uma narrativa brilhante', 'Impossível largar', 'Um clássico atemporal', 'Extraordinariamente bem escrito', 'Uma história inesquecível', 'Prosa poética admirável', 'Retrata magnificamente a alma portuguesa', 'Uma joia literária', 'Belamente construído', 'Uma leitura transformadora'],
  },
  vehicle: {
    manufacturer: ['Renault', 'Peugeot', 'Citroën', 'Volkswagen', 'Opel', 'Fiat', 'Mercedes-Benz', 'BMW', 'Audi', 'Toyota', 'Nissan', 'Ford', 'Seat', 'Hyundai', 'Kia', 'Dacia', 'Skoda', 'Volvo', 'Mazda', 'Honda', 'Chevrolet'],
    model: ['Clio', 'Megane', '208', '308', 'Golf', 'Polo', 'Corsa', 'Astra', 'Ibiza', 'Leon', 'Punto', '500', 'Panda', 'Classe A', 'Série 3', 'A3', 'A4', 'Corolla', 'Civic', 'Sandero', 'Duster'],
    type: ['Sedan', 'Hatchback', 'SUV', 'Carrinha', 'Coupé', 'Descapotável', 'Monovolume', 'Pick-up', 'Citadino', 'Familiar', 'Crossover', 'Van', 'Desportivo', 'Comercial Ligeiro'],
    fuel: ['Gasolina', 'Gasóleo', 'Elétrico', 'Híbrido', 'Híbrido Plug-in', 'GPL', 'GNV', 'Hidrogénio', 'Flex'],
    bicycle: ['Bicicleta de Estrada', 'BTT', 'Bicicleta Urbana', 'Bicicleta Elétrica', 'Bicicleta Dobrável', 'Bicicleta de Montanha', 'BMX', 'Bicicleta de Passeio', 'Gravel', 'Bicicleta Híbrida', 'Triciclo', 'Tandem'],
  },
  word: {
    adjective: ['bom', 'grande', 'novo', 'velho', 'pequeno', 'jovem', 'importante', 'público', 'mau', 'alto', 'baixo', 'difícil', 'fácil', 'forte', 'fraco', 'livre', 'rico', 'pobre', 'feliz', 'triste', 'bonito', 'feio', 'rápido', 'lento', 'quente', 'frio', 'claro', 'escuro', 'doce', 'amargo', 'largo', 'estreito', 'pesado', 'leve', 'duro', 'mole', 'limpo', 'sujo', 'cheio', 'vazio', 'certo', 'errado', 'próximo', 'distante', 'simples', 'complexo', 'natural', 'artificial', 'verdadeiro', 'falso'],
    adverb: ['muito', 'pouco', 'bastante', 'bem', 'mal', 'melhor', 'pior', 'mais', 'menos', 'ainda', 'já', 'sempre', 'nunca', 'talvez', 'certamente', 'provavelmente', 'possivelmente', 'obviamente', 'naturalmente', 'simplesmente', 'completamente', 'totalmente', 'parcialmente', 'apenas', 'somente', 'também', 'nem', 'sim', 'não', 'aqui', 'ali', 'aí', 'lá', 'cá', 'onde', 'quando', 'como', 'porquê', 'rapidamente', 'lentamente', 'cuidadosamente', 'facilmente', 'dificilmente', 'claramente', 'realmente', 'verdadeiramente', 'atualmente', 'antiguamente', 'finalmente'],
    conjunction: ['e', 'ou', 'mas', 'porém', 'contudo', 'todavia', 'entretanto', 'portanto', 'logo', 'pois', 'porque', 'que', 'se', 'caso', 'quando', 'enquanto', 'como', 'conforme', 'embora', 'ainda que', 'mesmo que', 'conquanto', 'nem', 'seja', 'quer', 'ora', 'logo que', 'assim que', 'à medida que', 'tanto que', 'de modo que', 'para que', 'a fim de que'],
    interjection: ['ah', 'oh', 'ui', 'oba', 'eba', 'uau', 'tchau', 'olá', 'adeus', 'bravo', 'bis', 'arre', 'eta', 'opa', 'nossa', 'caramba', 'puxa', 'epa', 'irra', 'ué', 'xi', 'oxalá', 'tomara', 'ai', 'ui', 'hum', 'psiu', 'atenção', 'cuidado', 'socorro', 'viva', 'hurra'],
    noun: ['tempo', 'pessoa', 'ano', 'vez', 'dia', 'coisa', 'homem', 'vida', 'mão', 'país', 'vez', 'mundo', 'casa', 'parte', 'lugar', 'caso', 'governo', 'empresa', 'grupo', 'trabalho', 'problema', 'fim', 'força', 'mulher', 'criança', 'olho', 'cabeça', 'vez', 'palavra', 'porta', 'cidade', 'água', 'noite', 'amor', 'guerra', 'paz', 'terra', 'mar', 'céu', 'sol', 'lua', 'estrela', 'livro', 'escola', 'amigo', 'família', 'filho', 'pai', 'mãe', 'irmão'],
    preposition: ['a', 'ante', 'após', 'até', 'com', 'contra', 'de', 'desde', 'em', 'entre', 'para', 'per', 'perante', 'por', 'sem', 'sob', 'sobre', 'trás', 'durante', 'mediante', 'segundo', 'conforme', 'consoante', 'excepto', 'salvo', 'através', 'dentro', 'fora', 'perto', 'longe', 'debaixo', 'acima', 'abaixo', 'atrás', 'diante', 'junto', 'além'],
    verb: ['ser', 'estar', 'ter', 'haver', 'fazer', 'ir', 'poder', 'dizer', 'dar', 'ficar', 'ver', 'saber', 'querer', 'chegar', 'passar', 'dever', 'pôr', 'parecer', 'deixar', 'encontrar', 'falar', 'vir', 'sentir', 'pensar', 'tomar', 'conhecer', 'pedir', 'viver', 'acreditar', 'trazer', 'acontecer', 'seguir', 'começar', 'levar', 'acabar', 'precisar', 'usar', 'manter', 'tratar', 'existir', 'chamar', 'continuar', 'perder', 'receber', 'entender', 'correr', 'andar', 'comer', 'dormir', 'trabalhar'],
  },
  hacker: {
    abbreviation: ['TCP', 'UDP', 'IP', 'HTTP', 'HTTPS', 'FTP', 'SSH', 'DNS', 'API', 'SQL', 'XML', 'JSON', 'HTML', 'CSS', 'JS', 'PHP', 'RAM', 'ROM', 'CPU', 'GPU', 'SSD', 'HDD', 'USB', 'LAN', 'WAN', 'VPN', 'SSL', 'TLS', 'DOS', 'DDoS', 'IoT', 'AI', 'ML', 'GB', 'TB', 'MHz', 'GHz'],
    adjective: ['auxiliar', 'primário', 'secundário', 'digital', 'aberto', 'virtual', 'distribuído', 'redundante', 'online', 'offline', 'sem fio', 'móvel', 'neural', 'ótico', 'sólido', 'multicore', 'de 1080p', 'cross-platform', 'ágil', 'encriptado', 'escalável', 'robusto', 'modular', 'seguro', 'hackável', 'configurável', 'programável', 'automatizado', 'inteligente', 'preditivo'],
    noun: ['driver', 'protocolo', 'largura de banda', 'painel', 'aplicação', 'firewall', 'interface', 'sistema', 'programa', 'pixel', 'porta', 'matriz', 'feed', 'sensor', 'algoritmo', 'servidor', 'cliente', 'cache', 'thread', 'processo', 'daemon', 'kernel', 'shell', 'script', 'código', 'bug', 'patch', 'hack', 'exploit', 'malware', 'vírus', 'backdoor', 'endpoint', 'gateway', 'roteador', 'switch', 'hub', 'modem', 'chipset', 'microchip'],
    verb: ['navegar', 'hackear', 'sobrescrever', 'programar', 'gerar', 'indexar', 'transmitir', 'copiar', 'analisar', 'calcular', 'compilar', 'compactar', 'conectar', 'desconectar', 'criptografar', 'descriptografar', 'debugar', 'deployar', 'desenvolver', 'baixar', 'fazer upload', 'executar', 'filtrar', 'sincronizar', 'processar', 'renderizar', 'escanear', 'validar', 'verificar', 'monitorar'],
    ingverb: ['navegando', 'hackeando', 'sobrescrevendo', 'programando', 'gerando', 'indexando', 'transmitindo', 'copiando', 'analisando', 'calculando', 'compilando', 'compactando', 'conectando', 'desconectando', 'criptografando', 'descriptografando', 'debugando', 'deployando', 'desenvolvendo', 'baixando', 'fazendo upload', 'executando', 'filtrando', 'sincronizando', 'processando', 'renderizando', 'escaneando', 'validando', 'verificando', 'monitorando'],
    phrase: ['Se compactarmos o protocolo, podemos aceder à porta TCP através do firewall redundante', 'Preciso indexar o pixel SSD para conectar ao servidor HTTP', 'Use o driver SSL sem fio para desbloquear o sensor online', 'A matriz IP está offline, hackeia o feed virtual para navegar no sistema', 'Tenta transmitir o programa JSON, talvez ele indexe o painel multicore', 'Se conectarmos o sensor, podemos obter a largura de banda GB através da interface auxiliar', 'Bypass do firewall não vai funcionar, precisamos programar o driver móvel', 'O sistema está encriptado, usa o algoritmo neural para descriptografar', 'Precisamos fazer deploy do código no servidor de produção', 'A largura de banda está saturada, otimiza o cache para melhor performance'],
  },
  system: {
    fileName: ['relatorio', 'documento', 'apresentacao', 'planilha', 'imagem', 'video', 'musica', 'arquivo', 'dados', 'backup', 'config', 'setup', 'instalador', 'atualizacao', 'patch', 'manual', 'readme', 'licenca', 'contrato', 'fatura', 'recibo', 'nota_fiscal', 'projeto', 'proposta', 'orcamento', 'curriculo', 'portfolio', 'foto', 'captura_tela', 'gravacao'],
    fileType: ['video', 'audio', 'imagem', 'texto', 'fonte', 'documento', 'planilha', 'apresentação', 'executável', 'compactado', 'código-fonte', 'dados', 'backup', 'configuração', 'sistema', 'temporário', 'log'],
  },
  science: {
    chemicalElement: ['Hidrogénio', 'Hélio', 'Lítio', 'Berílio', 'Boro', 'Carbono', 'Azoto', 'Oxigénio', 'Flúor', 'Néon', 'Sódio', 'Magnésio', 'Alumínio', 'Silício', 'Fósforo', 'Enxofre', 'Cloro', 'Árgon', 'Potássio', 'Cálcio', 'Ferro', 'Cobre', 'Zinco', 'Prata', 'Ouro', 'Mercúrio', 'Chumbo', 'Urânio', 'Plutónio', 'Rádio'],
    unit: ['metro', 'quilograma', 'segundo', 'ampere', 'kelvin', 'mole', 'candela', 'radiano', 'hertz', 'newton', 'pascal', 'joule', 'watt', 'coulomb', 'volt', 'ohm', 'siemens', 'farad', 'weber', 'tesla', 'henry', 'grau Celsius', 'lúmen', 'lux', 'becquerel', 'gray', 'sievert', 'litro', 'tonelada', 'hectare'],
    constant: ['Velocidade da Luz', 'Constante de Planck', 'Constante Gravitacional', 'Número de Avogadro', 'Constante de Boltzmann', 'Carga Elementar', 'Massa do Eletrão', 'Massa do Protão', 'Constante dos Gases', 'Constante de Faraday', 'Permissividade do Vácuo', 'Permeabilidade do Vácuo', 'Constante de Rydberg', 'Constante de Stefan-Boltzmann', 'Pi'],
    field: ['Física', 'Química', 'Biologia', 'Astronomia', 'Geologia', 'Matemática', 'Medicina', 'Engenharia', 'Computação', 'Ecologia', 'Genética', 'Neurociência', 'Paleontologia', 'Climatologia', 'Oceanografia', 'Botânica', 'Zoologia', 'Microbiologia', 'Bioquímica', 'Astrofísica', 'Mecânica Quântica', 'Termodinâmica', 'Eletromagnetismo', 'Nanotecnologia', 'Biotecnologia'],
  },
}
