import type { LocaleDefinition } from '@stacksjs/ts-faker'

export const da: LocaleDefinition = {
  title: 'Danish',
  person: {
    firstNameMale: [
      'William',
      'Oliver',
      'Noah',
      'Lucas',
      'Oscar',
      'Emil',
      'Victor',
      'Magnus',
      'Frederik',
      'Malthe',
      'Alfred',
      'Aksel',
      'August',
      'Elias',
      'Carl',
      'Christian',
      'Mads',
      'Rasmus',
      'Mikkel',
      'Kasper',
      'Simon',
      'Anders',
      'Nikolaj',
      'Mathias',
      'Søren',
      'Peter',
      'Lars',
      'Thomas',
      'Jens',
      'Henrik',
      'Niels',
      'Jesper',
      'Martin',
      'Jakob',
      'Kristian',
      'Daniel',
      'Jonas',
      'Sebastian',
      'Benjamin',
      'Alexander',
      'Marcus',
      'Anton',
      'Tobias',
      'Lasse',
      'Phillip',
      'Marcus',
      'Casper',
      'David',
      'Emil',
      'Johan',
    ],
    firstNameFemale: [
      'Emma',
      'Ida',
      'Clara',
      'Laura',
      'Anna',
      'Sofie',
      'Freja',
      'Ella',
      'Isabella',
      'Alma',
      'Sofia',
      'Karla',
      'Josefine',
      'Caroline',
      'Maja',
      'Maria',
      'Anne',
      'Mette',
      'Louise',
      'Camilla',
      'Julie',
      'Katrine',
      'Line',
      'Sarah',
      'Mathilde',
      'Nanna',
      'Cecilie',
      'Rebecca',
      'Emilie',
      'Natasha',
      'Lærke',
      'Signe',
      'Liv',
      'Agnes',
      'Ellen',
      'Katrine',
      'Eva',
      'Rikke',
      'Hanne',
      'Charlotte',
      'Maja',
      'Victoria',
      'Filippa',
      'Olivia',
      'Alberte',
      'Astrid',
      'Nora',
      'Vigga',
      'Frida',
      'Lea',
    ],
    firstNameNeutral: [
      'Andrea',
      'Kim',
      'Mika',
      'Alex',
      'Robin',
      'Sasha',
      'Jamie',
      'Charlie',
      'Morgan',
      'Ari',
      'Sage',
      'River',
      'Kai',
      'Phoenix',
      'Skyler',
      'Riley',
      'Casey',
      'Taylor',
      'Jordan',
      'Quinn',
    ],
    lastName: ['Nielsen', 'Jensen', 'Hansen', 'Pedersen', 'Andersen', 'Christensen', 'Larsen', 'Sørensen', 'Rasmussen', 'Jørgensen', 'Petersen', 'Madsen', 'Kristensen', 'Olsen', 'Thomsen', 'Christiansen', 'Poulsen', 'Johansen', 'Møller', 'Mortensen', 'Knudsen', 'Jacobsen', 'Laursen', 'Lund', 'Schmidt', 'Eriksen', 'Holm', 'Berg', 'Frederiksen', 'Jakobsen', 'Kjær', 'Simonsen', 'Mogensen', 'Iversen', 'Jeppesen', 'Mikkelsen', 'Frandsen', 'Koch', 'Vestergaard', 'Jespersen'],
    gender: ['Mand', 'Kvinde', 'Andet'],
    jobTitle: ['Softwareudvikler', 'Projektleder', 'Designer', 'Marketingchef', 'Salgschef', 'Revisor', 'Advokat', 'Læge', 'Sygeplejerske', 'Lærer', 'Professor', 'Forsker', 'Dataanalytiker', 'Produktchef', 'HR-chef', 'Konsulent', 'Arkitekt', 'Ingeniør', 'Tekniker', 'Kok', 'Forfatter', 'Journalist', 'Fotograf', 'Kunstner', 'Musiker'],
    prefix: ['Hr.', 'Fru', 'Frk.', 'Dr.', 'Prof.', 'Ing.'],
    suffix: ['Jr.', 'Sr.', 'II', 'III', 'IV'],
  },
  address: {
    street: ['Strøget', 'Nørrebrogade', 'Vesterbrogade', 'Amagerbrogade', 'Frederiksberg Allé', 'Østerbrogade', 'H.C. Andersens Boulevard', 'Rådhuspladsen', 'Kongens Nytorv', 'Nyhavn', 'Bredgade', 'Store Kongensgade', 'Gothersgade', 'Langelinie', 'Strandvejen', 'Gammel Kongevej', 'Roskildevej', 'Lyngbyvej', 'Jagtvej', 'Tagensvej', 'Frederikssundsvej', 'Brønshøj Torv', 'Hvidovre Torv', 'Glostrup Shoppingcenter', 'Rødovre Centrum', 'Lyngby Hovedgade', 'Søndergade', 'Nørregade', 'Algade', 'Storegade'],
    city: ['København', 'Aarhus', 'Odense', 'Aalborg', 'Esbjerg', 'Randers', 'Kolding', 'Horsens', 'Vejle', 'Roskilde', 'Herning', 'Silkeborg', 'Næstved', 'Fredericia', 'Viborg', 'Køge', 'Holstebro', 'Taastrup', 'Slagelse', 'Hillerød', 'Holbæk', 'Sønderborg', 'Svendborg', 'Hjørring', 'Frederikshavn', 'Nørresundby', 'Ringsted', 'Ølstykke', 'Skive', 'Korsør'],
    state: ['Hovedstaden', 'Sjælland', 'Syddanmark', 'Midtjylland', 'Nordjylland'],
    country: ['Danmark', 'Norge', 'Sverige', 'Tyskland', 'Island'],
    zipCode: ['####'],
    direction: ['Nord', 'Syd', 'Øst', 'Vest', 'Nordøst', 'Nordvest', 'Sydøst', 'Sydvest'],
  },
  company: {
    name: ['Mærsk', 'Novo Nordisk', 'Carlsberg', 'Vestas', 'Danfoss', 'Arla', 'Grundfos', 'LEGO', 'Pandora', 'Coloplast', 'ISS', 'Danske Bank', 'Nordea', 'DSV', 'FLSmidth', 'Novozymes', 'TDC', 'Tryg', 'ECCO', 'BESTSELLER', 'Jysk', 'Coop', 'Salling Group', 'Saxo Bank', 'Just Eat', 'Zendesk', 'Unity', 'SimCorp', 'Trustpilot', 'Vivino'],
    industry: ['Shipping', 'Farmaceutisk', 'Bryggeri', 'Vindenergi', 'Teknologi', 'Landbrug', 'Pumper', 'Legetøj', 'Smykker', 'Medicoteknologi', 'Facility services', 'Bank', 'Forsikring', 'Logistik', 'Industri', 'Biotek', 'Telekommunikation', 'Detailhandel', 'Møbler', 'Mode', 'E-handel', 'IT', 'Fintech', 'Software', 'Design'],
    buzzword: ['innovation', 'bæredygtighed', 'digitalisering', 'grøn omstilling', 'vindenergi', 'biotek', 'life science', 'cleantech', 'cirkulær økonomi', 'kunstig intelligens', 'automatisering', 'dataanalyse', 'smidig udvikling', 'velfærdsteknologi', 'smart city', 'deleøkonomi', 'platformøkonomi', 'fintech', 'healthtech', 'foodtech', 'agritech', 'industri 4.0', 'IoT', 'blockchain', 'AI'],
  },
  internet: {
    domainName: ['dr.dk', 'tv2.dk', 'bt.dk', 'eb.dk', 'politiken.dk', 'jyllands-posten.dk', 'berlingske.dk', 'dba.dk', 'bilbasen.dk', 'boligsiden.dk', 'jobindex.dk', 'ofir.dk', 'tjek.dk', 'pricerunner.dk', 'komputer.dk', 'computerworld.dk', 'version2.dk', 'b.dk', 'jp.dk', 'information.dk', 'sport.tv2.dk', 'bold.dk', 'sporten.dk', 'euroman.dk'],
  },
  phone: {
    number: ['## ## ## ##', '+45 ## ## ## ##', '2# ## ## ##', '3# ## ## ##', '4# ## ## ##', '5# ## ## ##'],
  },
  food: {
    dish: ['Frikadeller', 'Stegt flæsk med persillesovs', 'Flæskesteg', 'Rødgrød med fløde', 'Smørrebrød', 'Stjerneskud', 'Sol over Gudhjem', 'Rugbrød', 'Leverpostej', 'Sild', 'Kartofler', 'Brændende kærlighed', 'Biksemad', 'Hakkebøf', 'Tarteletter', 'Kylling i karry', 'Hønsekødssuppe', 'Gule ærter', 'Forloren hare', 'Fiskefrikadeller', 'Pandekager', 'Æbleskiver', 'Risalamande', 'Medisterpølse', 'Rødkål', 'Brunede kartofler', 'Agurkesalat', 'Remoulade', 'Hotdog', 'Pølsemix'],
    ingredient: ['Rugbrød', 'Smør', 'Ost', 'Skinke', 'Leverpostej', 'Sild', 'Laks', 'Rejer', 'Æg', 'Flæsk', 'Svinekød', 'Kartofler', 'Gulerødder', 'Løg', 'Persille', 'Dild', 'Fløde', 'Mælk', 'Kærnemælk', 'Grønne bønner', 'Ærter', 'Rødkål', 'Hvidkål', 'Agurk', 'Tomat', 'Peber', 'Salt', 'Sennep', 'Remoulade', 'Ketchup'],
    cuisine: ['Dansk', 'Skandinavisk', 'Italiensk', 'Fransk', 'Asiatisk', 'Thai', 'Indisk', 'Kinesisk', 'Japansk', 'Mexicansk', 'Amerikansk', 'Græsk', 'Tyrkisk', 'Spansk', 'Vegetarisk', 'Vegansk', 'Glutenfri', 'Fisk og skaldyr', 'Grill', 'Smørrebrød'],
    dessert: ['Lagkage', 'Æbleskiver', 'Risalamande', 'Rødgrød med fløde', 'Brunsviger', 'Kringle', 'Spandauer', 'Wienerbrød', 'Fastelavnsboller', 'Kanelsnegl', 'Tebirkes', 'Romkugler', 'Chokoladekage', 'Drømmekage', 'Gulerodskage', 'Is', 'Panna cotta', 'Tiramisu', 'Cheesecake', 'Brownie'],
    fruit: ['Æble', 'Pære', 'Blomme', 'Kirsebær', 'Jordbær', 'Hindbær', 'Blåbær', 'Solbær', 'Ribs', 'Stikkelsbær', 'Banan', 'Appelsin', 'Citron', 'Lime', 'Mango', 'Ananas', 'Druer', 'Vandmelon', 'Melon', 'Kiwi'],
    vegetable: ['Kartofler', 'Gulerødder', 'Løg', 'Hvidløg', 'Porre', 'Selleri', 'Peberfrugt', 'Tomat', 'Agurk', 'Salat', 'Spinat', 'Grønkål', 'Hvidkål', 'Rødkål', 'Blomkål', 'Broccoli', 'Rosenkål', 'Squash', 'Græskar', 'Ærter', 'Bønner', 'Majs', 'Radiser', 'Asparges', 'Svampe'],
    meat: ['Svinekød', 'Oksekød', 'Kylling', 'Kalkun', 'And', 'Lam', 'Kalv', 'Vildt', 'Rådyr', 'Hjort', 'Koteletter', 'Filet', 'Mørbrad', 'Kamsteg', 'Bryst', 'Lår', 'Skinke', 'Bacon', 'Pølse', 'Medister'],
    spice: ['Salt', 'Peber', 'Karry', 'Paprika', 'Chili', 'Ingefær', 'Hvidløg', 'Løg', 'Persille', 'Dild', 'Timian', 'Rosmarin', 'Basilikum', 'Oregano', 'Muskatnød', 'Nellike', 'Kardemomme', 'Kanel', 'Vanilje', 'Laurbærblade'],
  },
  animal: {
    dog: ['Dansk-svensk gårdshund', 'Broholmer', 'Gammel dansk hønsehund', 'Labrador', 'Golden retriever', 'Schæferhund', 'Rottweiler', 'Boxer', 'Beagle', 'Cocker spaniel', 'Jack Russell terrier', 'Border collie', 'Sheltie', 'Cavalier King Charles spaniel', 'Chihuahua', 'Puddel', 'Gravhund', 'Yorkshire terrier', 'Bichon frisé', 'Mops', 'Bulldog', 'Berner sennen', 'Flatcoated retriever', 'Springerspaniel', 'Vizsla'],
    cat: ['Huskat', 'Perser', 'Maine coon', 'Ragdoll', 'Birma', 'Siameser', 'Bengalkat', 'Abessinier', 'Russisk blå', 'Sphynx', 'British shorthair', 'Scottish fold', 'Burmeser', 'Chartreaux', 'Devon rex', 'Cornish rex', 'Singapura', 'Tonkineser', 'Korat', 'Europæisk korthår'],
    bird: ['Måge', 'Terne', 'Skarv', 'Hejre', 'Svane', 'Gås', 'And', 'Trane', 'Stork', 'Spætte', 'Lærke', 'Solsort', 'Stær', 'Krage', 'Skade', 'Spætmejse', 'Mejse', 'Dompap', 'Bogfinke', 'Grønirisk', 'Musvit', 'Blåmejse', 'Rødhals', 'Vipstjert', 'Tårnfalk'],
    fish: ['Aborrer', 'Gedde', 'Sandart', 'Ål', 'Brasen', 'Skalle', 'Karusse', 'Karpe', 'Torsk', 'Sej', 'Kuller', 'Sild', 'Makrel', 'Tunfisk', 'Laks', 'Ørred', 'Rødspætte', 'Pighvar', 'Tunge', 'Hornfisk', 'Havkat', 'Havtaske', 'Rødtunge', 'Multe', 'Jomfruhummer'],
    horse: ['Frederiksborger', 'Knabstrupper', 'Dansk varmblod', 'Jysk hest', 'Islandsk hest', 'Shetlandspony', 'Welsh pony', 'Araber', 'Fuldblod', 'Koldblod', 'Lipizzaner', 'Frieser', 'Andalusier', 'Hannoveraner', 'Oldenborger'],
    rabbit: ['Huskanin', 'Vildkanin', 'Hare', 'Dværgkanin', 'Løvehoved kanin', 'Angora', 'Rex', 'Lop', 'Chinchilla', 'Belgisk kæmpe', 'Himalaya', 'Holland lop', 'Mini lop', 'Hollandsk dværg', 'Fransk vædder'],
    insect: ['Sommerfugl', 'Guldsmed', 'Græshoppe', 'Bille', 'Humlebi', 'Bi', 'Hveps', 'Myre', 'Mide', 'Edderkop', 'Myg', 'Flue', 'Lus', 'Loppe', 'Vårflue', 'Døgnflue', 'Billerbasse', 'Mariehøne', 'Tæge', 'Møl'],
  },
  sport: {
    sport: ['Fodbold', 'Håndbold', 'Badminton', 'Cykling', 'Roning', 'Sejlads', 'Svømning', 'Atletik', 'Tennis', 'Golf', 'Basketball', 'Volleyball', 'Bordtennis', 'Ishockey', 'Klatring', 'Ridesport', 'Skydning', 'Bueskydning', 'Brydning', 'Boksning', 'Karate', 'Taekwondo', 'Judo', 'Gymnastik', 'Triatlon'],
    team: ['FC København', 'Brøndby IF', 'FC Midtjylland', 'AGF', 'AaB', 'OB', 'Randers FC', 'FC Nordsjælland', 'Silkeborg IF', 'Viborg FF', 'SønderjyskE', 'Lyngby BK', 'Aalborg Håndbold', 'GOG', 'TTH Holstebro', 'Bjerringbro-Silkeborg', 'FC Helsingør', 'Esbjerg fB', 'Vejle BK', 'HB Køge'],
    athlete: ['Caroline Wozniacki', 'Viktor Axelsen', 'Mads Pedersen', 'Jonas Vingegaard', 'Simon Kjær', 'Christian Eriksen', 'Kasper Schmeichel', 'Pernille Harder', 'Mikkel Hansen', 'Niklas Landin', 'Sarah Mahfoud', 'Joachim B. Olsen', 'Sara Slott Petersen', 'Anne-Marie Rindom', 'Katrine Fruelund', 'Jan Ø. Jørgensen', 'Anders Antonsen', 'Mathias Christiansen', 'Emilie Andersen', 'Lasse Norman Hansen'],
  },
  music: {
    genre: ['Pop', 'Rock', 'Elektronisk', 'Hip-hop', 'Jazz', 'Klassisk', 'Folkemusik', 'Country', 'Blues', 'Metal', 'Punk', 'Indie', 'R&B', 'Soul', 'Reggae', 'Techno', 'House', 'Trance', 'Drum and bass', 'Dubstep', 'Schlager', 'Viser', 'EDM', 'Ambient', 'Disco'],
    artist: ['Aqua', 'Lukas Graham', 'MØ', 'Volbeat', 'The Raveonettes', 'Kashmir', 'Nephew', 'D-A-D', 'Kim Larsen', 'Gasolin', 'TV-2', 'Shu-bi-dua', 'Anne Linnet', 'Medina', 'Alphabeat', 'Dizzy Mizz Lizzy', 'Oh Land', 'Mew', 'Christopher', 'Natasja', 'Suspekt', 'L.O.C.', 'Gilli', 'Kesi', 'Joakim Ingversen'],
    song: ['Barbie Girl', '7 Years', 'Lean On', 'Lollipop', 'Final Countdown', 'Rasmus Seebach', 'The Show Must Go On', 'Still Falling', 'This Is Who We Are', 'Fascination', 'Dybt vand', 'Motorcykel Mama', 'Hvor små vi er', 'You and I', 'CPH Girls', 'Selvmordsforestilling', 'Waiting in Vain', 'Against the Grain', 'Ensom', 'Gulddreng'],
    instrument: ['Guitar', 'Bas', 'Trommer', 'Klaver', 'Keyboard', 'Synthesizer', 'Violin', 'Cello', 'Bratsch', 'Kontrabas', 'Fløjte', 'Klarinet', 'Obo', 'Fagot', 'Saxofon', 'Trompet', 'Trombone', 'Tuba', 'Horn', 'Harmonika', 'Mundharmonika', 'Ukulele', 'Banjo', 'Mandolin', 'Harmonium'],
  },
  commerce: {
    productName: ['Smartphone', 'Bærbar', 'Tablet', 'Hovedtelefoner', 'Højttaler', 'Mus', 'Tastatur', 'Skærm', 'Webcam', 'Oplader', 'Kabel', 'Powerbank', 'Smartwatch', 'Sko', 'Taske', 'Pung', 'Bælte', 'Ur', 'Solbriller', 'Kasket', 'T-shirt', 'Hættetrøje', 'Jeans', 'Jakke', 'Frakke'],
    productAdjective: ['Smart', 'Premium', 'Luksus', 'Bedst', 'Populær', 'Ny', 'Limiteret', 'Tilbud', 'Rabat', 'Udsalg', 'Anbefalet', 'Bestseller', 'Nyhed', 'Seneste', 'Eksklusiv', 'Praktisk', 'Billig', 'Mærke', 'Original', 'Import', 'Dansk', 'Miljøvenlig', 'Fri fragt', 'Levering samme dag'],
    productMaterial: ['Læder', 'Bomuld', 'Polyester', 'Nylon', 'Silikone', 'Plastik', 'Metal', 'Rustfrit stål', 'Aluminium', 'Titan', 'Keramik', 'Glas', 'Træ', 'Bambus', 'Papir', 'Gummi', 'Skum', 'Latex', 'Uld', 'Kashmir'],
    department: ['Elektronik', 'Tøj', 'Skønhed', 'Mad og sundhed', 'Hjem og køkken', 'Møbler', 'Sport', 'Bøger', 'Legetøj', 'Digitalt', 'Baby', 'Kæledyr', 'Bil', 'Værktøj', 'Rejse', 'Gaver', 'Børn', 'Computer og gaming', 'Foto og lyd', 'Smykker'],
    color: ['Rød', 'Orange', 'Gul', 'Grøn', 'Blå', 'Lilla', 'Pink', 'Sort', 'Hvid', 'Grå', 'Brun', 'Beige', 'Marineblå', 'Khaki', 'Mint', 'Lavendel', 'Koral', 'Bordeaux', 'Vinrød', 'Creme'],
  },
  book: {
    title: ['Fædrelandssang', 'Lykke-Per', 'De røde enge', 'Pelle erobreren', 'Ditte Menneskebarn', 'Den kroniske uskyld', 'Hærværk', 'Vi, de druknede', 'Frøken Smillas fornemmelse for sne', 'De skriger på dig, mor', 'Fasandræberne', 'Kvinden i buret', 'Flaskepost fra P', 'Sorg og glæde', 'Det forsømte forår', 'Barndom', 'Unge', 'Gift', 'Tro, håb og kærlighed', 'Pigen der legede med ilden'],
    author: ['Hans Christian Andersen', 'Karen Blixen', 'Henrik Pontoppidan', 'Martin Andersen Nexø', 'Tom Kristensen', 'Carsten Jensen', 'Peter Høeg', 'Jussi Adler-Olsen', 'Ib Michael', 'Tove Ditlevsen', 'Johannes V. Jensen', 'Jeppe Aakjær', 'Jakob Ejersbo', 'Helle Helle', 'Dorthe Nors', 'Sara Blædel', 'Anna Grue', 'Sissel-Jo Gazan', 'Jonas T. Bengtsson', 'Ida Jessen'],
    publisher: ['Gyldendal', 'Politikens Forlag', 'Lindhardt og Ringhof', 'People\'s Press', 'Forlaget Carlsen', 'Rosinante', 'Gads Forlag', 'Informations Forlag', 'Tiderne Skifter', 'Kbh.', 'Turbine', 'Saxo Publish', 'Modtryk', 'Borgen', 'Høst & Søn'],
    genre: ['Roman', 'Krimi', 'Thriller', 'Fantasy', 'Sci-fi', 'Historisk', 'Biografisk', 'Digte', 'Essay', 'Faglitteratur', 'Selvbiografi', 'Rejse', 'Madlavning', 'Sundhed', 'Børn', 'Ungdom', 'Tegneserie', 'Humor', 'Drama', 'Noveller'],
    series: ['Afdeling Q', 'Smillas fornemmelse for sne', 'De syv søstre', 'Krøniken', 'Kampen om Troja', 'Solstik', 'Besættelse', 'DNA-trilogien', 'Louise Rick', 'Schäferhunden', 'Dicte Svendsen', 'Eventyrbogen', 'Brødrene Løvehjerte', 'Pippi Langstrømpe', 'Karlsson på taget', 'Rasmus Klump', 'Cirkeline', 'Valhalla', 'Bamse', 'Asterix'],
    review: ['Stærkt anbefalet', 'Fantastisk', 'Skal læses', 'Rørende', 'Uforglemmelig', 'Gribende', 'Fængslende', 'Mesterværk', 'Brilliant', 'Solid', 'Underholdende', 'Spændende', 'Sjov', 'Trist', 'Tankevækkende', 'Imponerende', 'Interessant', 'Kedelig', 'Forvirrende', 'Overraskende'],
  },
  vehicle: {
    manufacturer: ['Tesla', 'Volkswagen', 'BMW', 'Mercedes-Benz', 'Audi', 'Volvo', 'Toyota', 'Nissan', 'Kia', 'Hyundai', 'Ford', 'Peugeot', 'Renault', 'Skoda', 'Mazda', 'Honda', 'Mitsubishi', 'Subaru', 'Jaguar', 'Land Rover', 'Porsche', 'Polestar', 'BYD', 'MG', 'Cupra'],
    model: ['Model 3', 'Model Y', 'ID.4', 'e-Golf', 'i3', 'iX3', 'EQC', 'e-tron', 'XC40', 'XC60', 'XC90', 'Leaf', 'Ariya', 'e-Niro', 'Kona Electric', 'Ioniq 5', 'Mach-E', 'e-208', 'Zoe', 'Enyaq', 'MX-30', 'e', 'Outlander PHEV', 'Solterra', 'I-Pace'],
    type: ['Sedan', 'SUV', 'Stationcar', 'Coupé', 'Cabriolet', 'Kombi', 'Varebil', 'Pickup', 'Sportsvogn', 'Elbil', 'Hybrid', 'Plug-in hybrid', 'Brintbil', 'Minibil', 'Mellemklasse', 'Stor', 'Lille SUV', 'Mellem SUV', 'Stor SUV', 'Minibus'],
    fuel: ['Benzin', 'Diesel', 'El', 'Brint', 'Hybrid', 'Plug-in hybrid', 'Biodiesel', 'Gas', 'Etanol', 'Biogas'],
    bicycle: ['Mountainbike', 'Landevejscykel', 'Hybrid', 'Bycykel', 'BMX', 'Fixie', 'Cruiser', 'Elcykel', 'Foldecykel', 'Børnecykel', 'Touring', 'Gravel', 'Cyclocross', 'Bane', 'Ligge cykel', 'Tandem', 'Trehjulet', 'Løbehjul', 'El-løbehjul', 'Ladcykel'],
  },
  word: {
    adjective: ['smuk', 'stor', 'lille', 'god', 'dårlig', 'hurtig', 'langsom', 'høj', 'lav', 'ny', 'gammel', 'varm', 'kold', 'lys', 'mørk', 'glad', 'trist', 'lykkelig', 'vred', 'bange', 'modig', 'stærk', 'svag', 'klog', 'dum', 'pæn', 'grim', 'ren', 'beskidt', 'rig'],
    adverb: ['hurtigt', 'langsomt', 'stille', 'højt', 'lavt', 'meget', 'lidt', 'altid', 'aldrig', 'ofte', 'sjældent', 'måske', 'sikkert', 'virkelig', 'meget', 'temmelig', 'lidt', 'ekstremt', 'næsten', 'cirka', 'præcis', 'pludselig', 'gradvis', 'øjeblikkeligt', 'straks', 'senere', 'tidligere', 'nu', 'da'],
    conjunction: ['og', 'eller', 'men', 'dog', 'fordi', 'hvis', 'når', 'mens', 'siden', 'selvom', 'enten', 'både', 'så', 'derfor', 'dermed', 'alligevel', 'imidlertid', 'desuden', 'derimod', 'nemlig'],
    interjection: ['Å', 'Ov', 'Av', 'Uf', 'Puh', 'Hurra', 'Hej', 'Ha', 'Hm', 'Åh ja', 'Åh nej', 'Nå', 'Jo', 'Nej', 'Ja', 'Øv', 'Ups', 'Hov', 'Ih', 'Åh'],
    noun: ['person', 'hus', 'træ', 'blomst', 'vand', 'ild', 'vind', 'himmel', 'jord', 'bjerg', 'flod', 'hav', 'sol', 'måne', 'stjerne', 'sky', 'regn', 'sne', 'lyn', 'torden', 'bog', 'skole', 'lærer', 'elev', 'ven', 'familie', 'far', 'mor', 'søster', 'bror'],
    preposition: ['i', 'på', 'til', 'fra', 'med', 'uden', 'for', 'over', 'under', 'ved', 'hos', 'mellem', 'blandt', 'gennem', 'rundt', 'mod', 'om', 'af', 'efter', 'før'],
    verb: ['gå', 'komme', 'spise', 'drikke', 'sove', 'vågne', 'sidde', 'stå', 'ligge', 'løbe', 'hoppe', 'snakke', 'lytte', 'se', 'læse', 'skrive', 'lære', 'undervise', 'tænke', 'vide', 'kende', 'kunne lide', 'elske', 'hade', 'le', 'græde', 'lege', 'arbejde', 'hvile'],
  },
  hacker: {
    abbreviation: ['AI', 'ML', 'IoT', 'API', 'SDK', 'IDE', 'OS', 'DB', 'SQL', 'HTTP', 'HTTPS', 'REST', 'JSON', 'XML', 'HTML', 'CSS', 'JS', 'UI', 'UX', 'CI/CD', 'DevOps', 'AWS', 'GCP', 'Azure', 'K8s', 'Docker', 'Git', 'SVN', 'FTP', 'SSH'],
    adjective: ['distribueret', 'cloud-baseret', 'kvante', 'neural', 'dyb læring', 'maskinlæring', 'blockchain', 'krypteret', 'hashet', 'komprimeret', 'optimeret', 'skalerbar', 'højtilgængelig', 'fejltolerant', 'realtid', 'asynkron', 'synkron', 'parallel', 'distribueret', 'centraliseret'],
    noun: ['algoritme', 'datastruktur', 'protokol', 'grænseflade', 'modul', 'pakke', 'bibliotek', 'framework', 'middleware', 'database', 'server', 'klient', 'netværk', 'sikkerhed', 'kryptering', 'hash', 'token', 'session', 'cookie', 'cache', 'kø', 'stak', 'heap', 'træ', 'graf', 'array', 'liste', 'kort', 'mængde'],
    verb: ['køre', 'kompilere', 'debugge', 'deploye', 'bygge', 'teste', 'optimere', 'refaktorere', 'integrere', 'synkronisere', 'kryptere', 'dekryptere', 'hashe', 'komprimere', 'dekomprimere', 'serialisere', 'deserialisere', 'parse', 'validere', 'autentificere'],
    ingverb: ['kodning', 'programmering', 'udvikling', 'design', 'analyse', 'testning', 'debugging', 'deployment', 'overvågning', 'logning', 'profilering', 'benchmarking', 'skalering', 'migrering', 'refaktorering', 'optimering', 'dokumentation', 'review', 'integration', 'automatisering'],
    phrase: ['AI ændrer fremtiden', 'Big data giver indsigt', 'Cloud giver uendelige muligheder', 'Blockchain opbygger tillid', 'Kvante computing kommer', 'Maskinlæring forudsiger', 'Dyb læring lærer', 'IoT forbinder alt', '5G ændrer alt', 'Metaverse venter', 'Web3 fører an', 'NFT er digitale aktiver', 'Smart contracts automatiserer', 'DeFi innoverer finans', 'DAO decentraliserer', 'Krydsplatform giver effektivitet', 'Mikrotjenester giver skalerbarhed', 'Containere forenkler deployment', 'CI/CD for hurtig levering', 'DevOps styrker samarbejde'],
  },
  system: {
    fileName: ['dokument', 'rapport', 'præsentation', 'regneark', 'billede', 'video', 'lyd', 'arkiv', 'eksekverbar', 'konfiguration', 'log', 'backup', 'midlertidig', 'cache', 'data', 'installation', 'opdatering', 'driver', 'bibliotek', 'script'],
    fileType: ['dokument', 'billede', 'video', 'lyd', 'arkiv', 'eksekverbar', 'konfiguration', 'data', 'backup', 'log', 'cache', 'midlertidig', 'system', 'bibliotek', 'driver', 'opdatering', 'installation', 'skrifttype', 'tema', 'plugin'],
  },
  science: {
    chemicalElement: ['Brint', 'Helium', 'Lithium', 'Beryllium', 'Bor', 'Kulstof', 'Kvælstof', 'Ilt', 'Fluor', 'Neon', 'Natrium', 'Magnesium', 'Aluminium', 'Silicium', 'Fosfor', 'Svovl', 'Klor', 'Argon', 'Kalium', 'Calcium', 'Jern', 'Kobber', 'Zink', 'Sølv', 'Guld', 'Kviksølv', 'Bly', 'Uran', 'Plutonium', 'Radon'],
    unit: ['meter', 'kilogram', 'sekund', 'ampere', 'kelvin', 'mol', 'candela', 'newton', 'pascal', 'joule', 'watt', 'coulomb', 'volt', 'ohm', 'hertz', 'liter', 'gram', 'centimeter', 'millimeter', 'kilometer', 'millisekund', 'mikrosekund', 'nanosekund'],
    constant: ['lysets hastighed', 'gravitationskonstanten', 'Plancks konstant', 'Boltzmanns konstant', 'Avogadros tal', 'gaskonstanten', 'permittiviteten i vakuum', 'permeabiliteten i vakuum', 'elementærladningen', 'protonmassen', 'elektronmassen', 'neutronmassen', 'finstrukturkonstanten', 'Rydbergs konstant', 'Stefan-Boltzmanns konstant'],
    field: ['Fysik', 'Kemi', 'Biologi', 'Astronomi', 'Geologi', 'Meteorologi', 'Oceanografi', 'Økologi', 'Genetik', 'Molekylærbiologi', 'Cellebiologi', 'Neurovidenskab', 'Psykologi', 'Matematik', 'Statistik', 'Datalogi', 'Ingeniørvidenskab', 'Medicin', 'Farmaci', 'Veterinærmedicin', 'Landbrug', 'Miljøvidenskab', 'Nanoteknologi', 'Materialevidenskab', 'Energiforskning'],
  },
  color: {
    name: ['rød', 'orange', 'gul', 'grøn', 'blå', 'indigo', 'violet', 'pink', 'sort', 'hvid', 'grå', 'brun', 'beige', 'creme', 'elfenben', 'guld', 'sølv', 'bronze', 'kobber', 'oliven', 'khaki', 'marineblå', 'mint', 'turkis', 'magenta', 'lilla', 'limegrøn', 'himmelblå', 'mørkeblå', 'kastanjebrun'],
  },
}
