import type { LocaleDefinition } from '@stacksjs/ts-faker'

export const tl: LocaleDefinition = {
  title: 'Filipino',
  person: {
    firstNameMale: [
      'Jose',
      'Juan',
      'Pedro',
      'Antonio',
      'Francisco',
      'Jesus',
      'Manuel',
      'Carlos',
      'Miguel',
      'Angelo',
      'Gabriel',
      'Rafael',
      'Luis',
      'Diego',
      'Andres',
      'Daniel',
      'Roberto',
      'Fernando',
      'Ricardo',
      'Eduardo',
      'Ramon',
      'Emilio',
      'Alejandro',
      'Enrique',
      'Pablo',
      'Jorge',
      'Raul',
      'Sergio',
      'John',
      'Mark',
      'Paul',
      'James',
      'Joshua',
      'Christian',
      'Carlo',
      'Ryan',
      'Michael',
      'Kenneth',
      'Kevin',
      'Adrian',
      'Carl',
      'Emmanuel',
      'Joseph',
      'Anthony',
      'Jonathan',
      'Christopher',
      'Francis',
      'Marlon',
      'Ronaldo',
      'Ferdinand',
      'Rodrigo',
      'Benigno',
      'Manny',
      'Lorenzo',
      'Vicente',
      'Mateo',
      'Sebastian',
      'Joaquin',
      'Salvador',
      'Ignacio',
      'Gregorio',
      'Benito',
      'Tomas',
      'Alfonso',
      'Domingo',
      'Marcos',
      'Felipe',
      'Esteban',
      'Nestor',
      'Renato',
      'Ruben',
      'Romeo',
      'Gilbert',
    ],
    firstNameFemale: [
      'Maria',
      'Ana',
      'Rosa',
      'Carmen',
      'Luz',
      'Cristina',
      'Isabel',
      'Teresa',
      'Lourdes',
      'Gloria',
      'Mercedes',
      'Rosario',
      'Josefina',
      'Angela',
      'Beatriz',
      'Elena',
      'Patricia',
      'Sofia',
      'Catalina',
      'Remedios',
      'Dolores',
      'Esperanza',
      'Mary',
      'Princess',
      'Angelica',
      'Michelle',
      'Nicole',
      'Stephanie',
      'Christine',
      'Clarisse',
      'Kristine',
      'April',
      'Mae',
      'Joy',
      'Grace',
      'Faith',
      'Hope',
      'Love',
      'Precious',
      'Divine',
      'Lovely',
      'Corazon',
      'Imelda',
      'Lea',
      'Concepcion',
      'Pilar',
      'Milagros',
      'Soledad',
      'Estrella',
      'Aida',
      'Norma',
      'Violeta',
      'Clarita',
      'Marina',
      'Rosalinda',
      'Luisa',
      'Caridad',
      'Trinidad',
      'Victoria',
      'Presentacion',
      'Francisca',
      'Felicidad',
      'Aurora',
      'Lucia',
    ],
    firstNameNeutral: [
      'Angel',
      'Alex',
      'Kim',
      'Rae',
      'Sam',
      'Jesse',
      'Jordan',
      'Casey',
      'Pat',
      'Drew',
      'Riley',
      'Kai',
      'Quinn',
      'Reese',
      'Morgan',
      'Sky',
      'Dominique',
      'Jamie',
      'Chris',
      'Nikki',
    ],
    lastName: [
      'Santos',
      'Reyes',
      'Cruz',
      'Bautista',
      'Ocampo',
      'Garcia',
      'Mendoza',
      'Torres',
      'Gonzales',
      'Lopez',
      'Flores',
      'Rivera',
      'Ramos',
      'De Leon',
      'Aquino',
      'Fernandez',
      'Valdez',
      'Castillo',
      'Navarro',
      'Villanueva',
      'Tolentino',
      'Pascual',
      'Santiago',
      'Soriano',
      'Domingo',
      'Martinez',
      'Ramirez',
      'Mercado',
      'Salazar',
      'Diaz',
      'Dela Cruz',
      'San Jose',
      'Hernandez',
      'Perez',
      'Morales',
      'Gomez',
      'Aguilar',
      'Miranda',
      'Del Rosario',
      'Jimenez',
      'Manalo',
      'Villarosa',
      'Ignacio',
      'Concepcion',
      'Francisco',
      'Velasco',
      'Castro',
      'Cordero',
      'Bonifacio',
      'Laurel',
      'Roxas',
      'Magpantay',
      'Corpuz',
      'Villena',
      'Cortez',
      'Marquez',
      'Alvarez',
      'Estrada',
      'Medina',
      'Velasquez',
      'Agustin',
      'Sandoval',
      'Calderon',
      'Gutierrez',
      'Sergio',
      'Padilla',
      'Alonzo',
      'Salvador',
      'Sarmiento',
      'Suarez',
    ],
    prefix: ['Ginoo', 'Ginang', 'Bb.', 'G.', 'Gng.', 'Dr.', 'Atty.', 'Engr.', 'Arch.', 'Prof.'],
    suffix: ['Jr.', 'Sr.', 'I', 'II', 'III', 'IV'],
    gender: ['Lalaki', 'Babae', 'Non-binary', 'Bakla', 'Tomboy', 'LGBTQ+'],
    jobTitle: [
      'Software Engineer',
      'Web Developer',
      'Mobile Developer',
      'Data Analyst',
      'IT Support',
      'Business Process Associate',
      'Customer Service Representative',
      'Call Center Agent',
      'Virtual Assistant',
      'Sales Manager',
      'Marketing Officer',
      'HR Manager',
      'Accountant',
      'Auditor',
      'Finance Manager',
      'Project Manager',
      'Operations Manager',
      'Admin Officer',
      'Executive Assistant',
      'Receptionist',
      'Teacher',
      'Professor',
      'Engineer',
      'Architect',
      'Nurse',
      'Doctor',
      'Pharmacist',
      'Graphic Designer',
      'Content Writer',
      'Social Media Manager',
      'Digital Marketer',
      'SEO Specialist',
      'BPO Specialist',
      'Team Leader',
      'Quality Analyst',
      'Technical Support',
      'Database Administrator',
    ],
  },
  address: {
    street: [
      'Rizal',
      'Bonifacio',
      'Quezon',
      'Mabini',
      'Aguinaldo',
      'Luna',
      'Burgos',
      'Roxas',
      'Magsaysay',
      'Osmeña',
      'Recto',
      'Taft',
      'EDSA',
      'Katipunan',
      'Commonwealth',
      'Aurora',
      'Del Pilar',
      'Legarda',
      'España',
      'Lacson',
      'Buendia',
      'Ayala',
      'Makati',
      'Ortigas',
      'Shaw',
      'Boni',
      'Kalayaan',
      'Libertad',
      'Sampaguita',
      'Ylang-Ylang',
      'Rosal',
      'Gumamela',
      'Dama de Noche',
      'Santan',
      'Kamia',
      'Narra',
      'Mahogany',
      'Acacia',
      'Yakal',
      'Molave',
    ],
    city: [
      'Manila',
      'Quezon City',
      'Makati',
      'Pasig',
      'Taguig',
      'Mandaluyong',
      'San Juan',
      'Marikina',
      'Pasay',
      'Parañaque',
      'Las Piñas',
      'Muntinlupa',
      'Caloocan',
      'Malabon',
      'Navotas',
      'Valenzuela',
      'Pateros',
      'Cebu City',
      'Davao City',
      'Cagayan de Oro',
      'General Santos',
      'Zamboanga',
      'Bacolod',
      'Iloilo City',
      'Baguio',
      'Dagupan',
      'Olongapo',
      'Angeles',
      'Tarlac City',
      'Cabanatuan',
      'San Fernando',
      'Batangas City',
      'Lucena',
      'Naga',
      'Legazpi',
      'Tacloban',
      'Ormoc',
      'Dumaguete',
      'Tagbilaran',
      'Butuan',
      'Iligan',
      'Cotabato',
      'Puerto Princesa',
      'Antipolo',
      'Bacoor',
      'Dasmariñas',
      'Imus',
      'Cavite City',
      'San Jose del Monte',
    ],
    state: [
      'Metro Manila',
      'Rizal',
      'Cavite',
      'Laguna',
      'Bulacan',
      'Batangas',
      'Pampanga',
      'Nueva Ecija',
      'Tarlac',
      'Cebu',
      'Bohol',
      'Negros Oriental',
      'Negros Occidental',
      'Iloilo',
      'Leyte',
      'Samar',
      'Davao del Sur',
      'Davao del Norte',
      'Davao Oriental',
      'Davao de Oro',
      'Davao Occidental',
      'Cagayan',
      'Isabela',
      'Nueva Vizcaya',
      'Quirino',
      'Batanes',
      'Ilocos Norte',
      'Ilocos Sur',
      'La Union',
      'Pangasinan',
      'Zambales',
      'Benguet',
      'Ifugao',
      'Kalinga',
      'Mountain Province',
      'Albay',
      'Camarines Norte',
      'Camarines Sur',
      'Catanduanes',
      'Masbate',
      'Sorsogon',
      'Palawan',
      'Mindoro Oriental',
      'Mindoro Occidental',
      'Marinduque',
      'Romblon',
    ],
    stateAbbr: [
      'NCR',
      'RIZ',
      'CAV',
      'LAG',
      'BUL',
      'BTG',
      'PAM',
      'NUE',
      'TAR',
      'CEB',
      'BOH',
      'NER',
      'NEC',
      'ILO',
      'LEY',
      'SAM',
      'DAS',
      'DAN',
      'DAO',
      'COM',
      'DAV',
    ],
    country: [
      'Pilipinas',
      'United States',
      'Canada',
      'Singapore',
      'Japan',
      'China',
      'Malaysia',
      'Thailand',
      'Australia',
      'New Zealand',
      'South Korea',
      'Hong Kong',
      'Taiwan',
      'United Arab Emirates',
    ],
    countryCode: ['PH', 'US', 'CA', 'SG', 'JP', 'CN', 'MY', 'TH', 'AU', 'NZ', 'KR', 'HK', 'TW', 'AE'],
    zipCode: ['####'],
    buildingNumber: ['###', '##', '#', '####'],
    direction: ['Hilaga', 'Timog', 'Silangan', 'Kanluran', 'Hilagang-Silangan', 'Hilagang-Kanluran', 'Timog-Silangan', 'Timog-Kanluran'],
    streetSuffix: [
      'Street',
      'Avenue',
      'Road',
      'Boulevard',
      'Drive',
      'Lane',
      'Extension',
      'Corner',
      'Kalye',
      'Abenida',
      'Daan',
      'Bulevard',
      'Eskinita',
      'Looban',
      'Compound',
      'Subdivision',
    ],
  },
  company: {
    name: [
      'San Miguel Corporation',
      'Jollibee Foods',
      'SM Investments',
      'Ayala Corporation',
      'Manila Electric Company',
      'Philippine Long Distance Telephone',
      'Globe Telecom',
      'Smart Communications',
      'Puregold',
      'Robinsons',
      'Metro Pacific',
      'Aboitiz Equity Ventures',
      'GT Capital',
      'Banco de Oro',
      'Bank of the Philippine Islands',
      'PinoyTech Solutions',
      'Manila Digital Systems',
      'Quezon Tech Hub',
      'Makati Software Group',
      'BGC Innovations',
      'Cebu Tech Center',
      'Davao Digital',
      'Island Solutions',
      'Pacific Systems',
      'Tropical Tech',
    ],
    suffix: ['Inc', 'Corporation', 'Corp', 'Co', 'Ltd', 'Solutions', 'Technologies', 'Systems', 'Group', 'Holdings'],
    industry: [
      'Technology',
      'Business Process Outsourcing',
      'Finance',
      'Healthcare',
      'Education',
      'Retail',
      'Manufacturing',
      'Telecommunications',
      'Real Estate',
      'Transportation',
      'Agriculture',
      'Tourism',
      'Food and Beverage',
      'Construction',
      'Mining',
      'Energy',
      'Banking',
      'Insurance',
    ],
    buzzwords: [
      'synergize',
      'leverage',
      'innovate',
      'transform',
      'optimize',
      'streamline',
      'empower',
      'enable',
      'facilitate',
      'integrate',
      'revolutionize',
      'digitalize',
      'globalize',
    ],
    adjective: [
      'innovative',
      'cutting-edge',
      'world-class',
      'premier',
      'leading',
      'advanced',
      'dynamic',
      'progressive',
      'modern',
      'efficient',
      'strategic',
      'comprehensive',
    ],
    descriptor: [
      'global',
      'digital',
      'cloud-based',
      'AI-powered',
      'data-driven',
      'customer-centric',
      'innovative',
      'scalable',
      'integrated',
      'automated',
      'secure',
      'flexible',
    ],
    noun: [
      'solution',
      'platform',
      'system',
      'service',
      'technology',
      'framework',
      'infrastructure',
      'application',
      'network',
      'portal',
      'ecosystem',
      'architecture',
      'hub',
    ],
  },
  internet: {
    domainSuffix: ['ph', 'com.ph', 'net.ph', 'org.ph', 'edu.ph', 'gov.ph', 'com', 'net', 'org'],
    freeEmail: ['gmail.com', 'yahoo.com', 'yahoo.com.ph', 'hotmail.com', 'outlook.com', 'ymail.com'],
  },
  phone: {
    formats: [
      '02-####-####',
      '(02) #### ####',
      '+63 2 #### ####',
      '09##-###-####',
      '09## ### ####',
      '+63 9## ### ####',
      '(02) 8###-####',
      '+63 2 8### ####',
    ],
  },
  food: {
    dish: ['Adobo', 'Sinigang', 'Lechon', 'Kare-Kare', 'Pancit', 'Lumpia', 'Sisig', 'Bulalo', 'Tinola', 'Bicol Express', 'Laing', 'Pinakbet', 'Dinuguan', 'Caldereta', 'Mechado', 'Afritada', 'Menudo', 'Tapa', 'Longganisa', 'Tocino', 'Bangus', 'Pork BBQ', 'Chicken Inasal', 'Lechon Kawali', 'Crispy Pata'],
    ingredient: ['Suka', 'Toyo', 'Patis', 'Bagoong', 'Calamansi', 'Sili', 'Bawang', 'Sibuyas', 'Luya', 'Kamatis', 'Gata', 'Asin', 'Paminta', 'Kanin', 'Mantika', 'Itlog', 'Bigas', 'Karne', 'Isda', 'Gulay', 'Asukal', 'Tanglad', 'Dahon ng Laurel', 'Atsuwete', 'Tamarind'],
    cuisine: ['Filipino', 'Chinese', 'Japanese', 'Korean', 'American', 'Italian', 'Spanish', 'Thai', 'Vietnamese', 'Mexican'],
    dessert: ['Halo-Halo', 'Leche Flan', 'Bibingka', 'Puto', 'Kutsinta', 'Sapin-Sapin', 'Ube Halaya', 'Turon', 'Buko Pandan', 'Maja Blanca', 'Buko Salad', 'Ginataang Bilo-Bilo', 'Cassava Cake', 'Puto Bumbong', 'Ensaymada'],
    fruit: ['Mangga', 'Saging', 'Pinya', 'Papaya', 'Bayabas', 'Santol', 'Rambutan', 'Lanzones', 'Durian', 'Marang', 'Atis', 'Guyabano', 'Kaimito', 'Chico', 'Siniguelas'],
    vegetable: ['Kangkong', 'Sitaw', 'Talong', 'Ampalaya', 'Kalabasa', 'Labanos', 'Repolyo', 'Patola', 'Malunggay', 'Pechay', 'Mustasa', 'Kamatis', 'Sibuyas', 'Sili', 'Kamote'],
    meat: ['Baboy', 'Manok', 'Baka', 'Tupa', 'Pato', 'Karne ng Baka', 'Liempo', 'Pata', 'Longanisa', 'Chorizo', 'Tocino', 'Tapa'],
    spice: ['Sili', 'Luya', 'Bawang', 'Paminta', 'Tanglad', 'Dahon ng Laurel', 'Oregano', 'Kaningga', 'Luya Powder', 'Atsuwete', 'Vetsin', 'Magic Sarap'],
  },
  animal: {
    dog: ['Aspin', 'Askal', 'German Shepherd', 'Labrador', 'Shih Tzu', 'Pomeranian', 'Chihuahua', 'Beagle', 'Golden Retriever', 'Poodle', 'Bulldog', 'Dachshund', 'Siberian Husky', 'Dalmatian', 'Rottweiler'],
    cat: ['Puspin', 'Persian', 'Siamese', 'Maine Coon', 'British Shorthair', 'Ragdoll', 'Bengal', 'Sphynx', 'American Shorthair', 'Scottish Fold', 'Munchkin'],
    bird: ['Agila', 'Kalapati', 'Maya', 'Loro', 'Kuwago', 'Tikitiki', 'Kilyawan', 'Sarika', 'Manok', 'Pato', 'Gansa', 'Pabo'],
    fish: ['Bangus', 'Tilapia', 'Galunggong', 'Tulingan', 'Lapu-Lapu', 'Tanigue', 'Dalagang Bukid', 'Talakitok', 'Alumahan', 'Hasa-Hasa', 'Kanduli', 'Kitang'],
    horse: ['Kabayo', 'Arabian', 'Thoroughbred', 'Quarter Horse', 'Mustang', 'Appaloosa', 'Andalusian', 'Friesian'],
    rabbit: ['Kuneho', 'Holland Lop', 'Netherland Dwarf', 'Mini Rex', 'Lionhead', 'Flemish Giant', 'Angora'],
    insect: ['Paru-Paro', 'Bubuyog', 'Langgam', 'Salagubang', 'Gagamba', 'Tutubi', 'Tipaklong', 'Kuliglig', 'Alitaptap', 'Uod', 'Ipis', 'Langaw'],
    type: ['Aso', 'Pusa', 'Ibon', 'Isda', 'Kuneho', 'Hamster', 'Guinea Pig', 'Daga', 'Pagong', 'Butiki'],
  },
  sport: {
    sport: ['Basketball', 'Boxing', 'Billiards', 'Volleyball', 'Football', 'Badminton', 'Swimming', 'Athletics', 'Arnis', 'Sepak Takraw', 'Tennis', 'Golf', 'Table Tennis', 'Chess', 'Dragon Boat Racing'],
    team: ['Ginebra', 'San Miguel Beermen', 'TNT Tropang Giga', 'Magnolia Hotshots', 'Rain or Shine', 'NLEX Road Warriors', 'Meralco Bolts', 'Phoenix Super LPG', 'Blackwater Bossing', 'Terrafirma Dyip', 'Converge FiberXers', 'NorthPort Batang Pier'],
    athlete: ['Manny Pacquiao', 'Efren Reyes', 'Paeng Nepomuceno', 'Lydia de Vega', 'Rafael Nepomuceno', 'Nonito Donaire', 'Hidilyn Diaz', 'Carlos Yulo', 'Wesley So', 'Alex Eala', 'June Mar Fajardo', 'Kiefer Ravena'],
  },
  music: {
    genre: ['OPM', 'Kundiman', 'Harana', 'Rock Pinoy', 'Manila Sound', 'Hugot', 'Pop', 'Ballad', 'R&B', 'Hip Hop', 'Reggae', 'Folk'],
    artist: ['Lea Salonga', 'Regine Velasquez', 'Sarah Geronimo', 'Gary Valenciano', 'Sharon Cuneta', 'Martin Nievera', 'Freddie Aguilar', 'Apo Hiking Society', 'Eraserheads', 'Rivermaya', 'Parokya ni Edgar', 'Ben&Ben'],
    song: ['Anak', 'Dahil Sa Iyo', 'Bayan Ko', 'Ikaw', 'Handog', 'Somewhere in My Past', 'The Way We Were', 'Aking Bituin', 'Nandito Ako', 'Tadhana', 'Kathang Isip', 'Ligaya'],
    instrument: ['Gitara', 'Piano', 'Kulintang', 'Bandurria', 'Rondalla', 'Octavina', 'Laud', 'Drums', 'Bass', 'Violin', 'Keyboard', 'Saxophone'],
  },
  commerce: {
    product: ['Upuan', 'Mesa', 'Ilawan', 'Sofa', 'Kama', 'Desk', 'Computer', 'Cellphone', 'Relo', 'Sapatos', 'Bag', 'Backpack', 'Salamin'],
    productAdjective: ['Maliit', 'Malaki', 'Ergonomic', 'Maganda', 'Modernong', 'Elegante', 'Praktikal', 'Kamangha-Mangha', 'Matibay', 'De Kalidad', 'Luho', 'Propesyonal'],
    productMaterial: ['Bakal', 'Kahoy', 'Plastik', 'Cotton', 'Katad', 'Salamin', 'Aluminum', 'Metal', 'Seda', 'Lana', 'Seramika', 'Marmol'],
    department: ['Electronics', 'Damit', 'Bahay at Hardin', 'Sports', 'Libro', 'Laruan', 'Health at Beauty', 'Pagkain', 'Fashion', 'Furniture'],
    color: ['Pula', 'Asul', 'Berde', 'Dilaw', 'Itim', 'Puti', 'Abo', 'Rosas', 'Kahel', 'Lila', 'Kayumanggi', 'Kulay Gatas'],
  },
  book: {
    title: ['Noli Me Tangere', 'El Filibusterismo', 'Florante at Laura', 'Ang Mga Kaibigan ni Mama Susan', 'Mga Ibong Mandaragit', 'Banaag at Sikat', 'Luha ng Buwaya', 'Dekada \'70', 'Smaller and Smaller Circles', 'Ilustrado', 'Po-on', 'Mga Kuwento ni Lola Basyang', 'Ang Kuwento ni Mabuti', 'Ibong Adarna', 'Biag ni Lam-ang'],
    author: ['Jose Rizal', 'Francisco Balagtas', 'Nick Joaquin', 'F. Sionil Jose', 'Lualhati Bautista', 'Bob Ong', 'Jessica Hagedorn', 'Gina Apostol', 'Miguel Syjuco', 'Edith Tiempo', 'Carlos Bulosan', 'Jose Garcia Villa', 'NVM Gonzalez', 'Virgilio Almario', 'Amado Hernandez'],
    publisher: ['Anvil Publishing', 'Ateneo Press', 'University of the Philippines Press', 'Adarna House', 'National Book Store', 'Visprint', 'Summit Books', 'Precious Pages', 'Lampara Books', 'OMF Literature'],
    genre: ['Nobela', 'Tula', 'Maikling Kwento', 'Sanaysay', 'Drama', 'Kasaysayan', 'Talambuhay', 'Pantasya', 'Romanasa', 'Misteryo', 'Alamat', 'Epiko', 'Komiks', 'Sci-Fi'],
    series: ['Mga Kwentong Kalibugan', 'Mga Kuwento ni Lola Basyang', 'Harry Potter (Tagalog)', 'Ang Mga Kaibigan ni Hudas', 'Rosales Saga', 'Mga Kuwento ng Pag-ibig', 'Tales from the 7,000 Isles'],
    review: ['Isang obra maestra ng panitikang Pilipino', 'Napakagandang aklat', 'Kailangang basahin', 'Nakaka-inspire at nakakaantig', 'Mahusay na pagsulat', 'Hindi ko makakalimutan', 'Sulit na sulit basahin', 'Salamin ng lipunang Pilipino'],
  },
  vehicle: {
    manufacturer: ['Toyota', 'Honda', 'Mitsubishi', 'Nissan', 'Isuzu', 'Hyundai', 'Kia', 'Suzuki', 'Mazda', 'Ford', 'Chevrolet', 'BMW', 'Mercedes-Benz', 'Subaru', 'Volkswagen'],
    model: ['Vios', 'Fortuner', 'Innova', 'Wigo', 'Civic', 'City', 'CR-V', 'Montero', 'Mirage', 'Adventure', 'Navara', 'Accent', 'Tucson', 'Eon', 'Sportage'],
    type: ['Sedan', 'SUV', 'MPV', 'Pickup', 'Hatchback', 'Crossover', 'Van', 'AUV', 'Convertible', 'Sports Car', 'Compact Car'],
    fuel: ['Gasoline', 'Diesel', 'Electric', 'Hybrid', 'LPG', 'CNG', 'Flex Fuel'],
    bicycle: ['Mountain Bike', 'Road Bike', 'BMX', 'Folding Bike', 'Electric Bike', 'City Bike', 'Cruiser', 'Fixed Gear', 'Gravel Bike'],
  },
  word: {
    adjective: ['maganda', 'pangit', 'malaki', 'maliit', 'mataas', 'mababa', 'mahaba', 'maikli', 'malawak', 'makitid', 'mabigat', 'magaan', 'maliwanag', 'madilim', 'mainit', 'malamig', 'mabilis', 'mabagal', 'malakas', 'mahina', 'mayaman', 'mahirap', 'bata', 'matanda', 'masaya', 'malungkot', 'magaling', 'masama', 'bago', 'luma'],
    adverb: ['dito', 'doon', 'ngayon', 'mamaya', 'kahapon', 'bukas', 'palagi', 'minsan', 'madalas', 'bihira', 'agad', 'unti-unti', 'bigla', 'marahil', 'tiyak', 'mabilis', 'mabagal', 'mahusay', 'lubha', 'halos', 'totoo', 'talaga', 'marahil', 'siguro', 'dapat', 'kailangan', 'pwede', 'maaari'],
    conjunction: ['at', 'o', 'ngunit', 'pero', 'kaya', 'dahil', 'sapagkat', 'kung', 'kapag', 'habang', 'bagaman', 'kahit', 'upang', 'para', 'subalit', 'datapwat', 'gayunman', 'samantala', 'kundi', 'o kaya'],
    interjection: ['Aba!', 'Naku!', 'Sus!', 'Ay!', 'Wow!', 'Grabe!', 'Talaga!', 'Nako!', 'Aba!', 'Oy!', 'Hoy!', 'Psst!', 'Hala!', 'Yay!', 'Oops!', 'Aray!', 'Sayang!', 'Sige!', 'Oo!', 'Hindi!'],
    noun: ['tao', 'bahay', 'puno', 'araw', 'buwan', 'bituin', 'tubig', 'apoy', 'lupa', 'hangin', 'bundok', 'ilog', 'dagat', 'langit', 'bulaklak', 'hayop', 'pagkain', 'pag-ibig', 'buhay', 'kamatayan', 'pangarap', 'pag-asa', 'takot', 'saya', 'lungkot', 'mundo', 'bayan', 'bansa', 'lungsod', 'nayon'],
    preposition: ['sa', 'ng', 'ni', 'kay', 'para', 'mula', 'tungkol', 'ukol', 'hinggil', 'patungkol', 'dahil', 'bunga', 'sanhi', 'alinsunod', 'ayon', 'laban', 'simula', 'hanggang', 'bukod', 'maliban'],
    verb: ['kumain', 'uminom', 'matulog', 'gumising', 'lumakad', 'tumakbo', 'lumipad', 'lumangoy', 'sumayaw', 'kumanta', 'magsalita', 'makinig', 'tingnan', 'basahin', 'sumulat', 'magtrabaho', 'mag-aral', 'maglaro', 'umibig', 'magmahal', 'magturo', 'matuto', 'bumili', 'magbenta', 'magbigay', 'tumanggap', 'magdala', 'dumating', 'umalis', 'manirahan'],
  },
  hacker: {
    abbreviation: ['TCP', 'IP', 'HTTP', 'HTTPS', 'FTP', 'SSH', 'SSL', 'TLS', 'DNS', 'VPN', 'API', 'SQL', 'HTML', 'CSS', 'JS', 'PHP', 'RAM', 'ROM', 'CPU', 'GPU', 'SSD', 'HDD', 'USB', 'LAN', 'WAN', 'WiFi', 'IoT', 'AI', 'ML', 'DDoS', 'XSS'],
    adjective: ['digital', 'virtual', 'encrypted', 'decrypted', 'secure', 'vulnerable', 'online', 'offline', 'wireless', 'local', 'remote', 'automated', 'manual', 'synchronous', 'asynchronous', 'public', 'private', 'distributed'],
    noun: ['protocol', 'algorithm', 'interface', 'server', 'client', 'network', 'system', 'process', 'thread', 'cache', 'buffer', 'socket', 'port', 'packet', 'firewall', 'router', 'switch', 'virus', 'malware', 'exploit', 'patch', 'bug', 'pixel', 'byte', 'bit'],
    verb: ['compile', 'execute', 'debug', 'encrypt', 'decrypt', 'hash', 'authenticate', 'authorize', 'connect', 'disconnect', 'download', 'upload', 'synchronize', 'backup', 'restore', 'scan', 'monitor', 'deploy', 'patch'],
    ingverb: ['compiling', 'executing', 'debugging', 'encrypting', 'decrypting', 'hashing', 'authenticating', 'authorizing', 'connecting', 'disconnecting', 'downloading', 'uploading', 'synchronizing', 'backing up', 'restoring', 'scanning', 'monitoring', 'deploying', 'patching'],
    phrase: ['Vulnerability detected', 'Access denied', 'Connection established', 'Server compromised', 'Data exfiltrated', 'Firewall bypassed', 'Exploit successful', 'System hacked', 'Zero-day vulnerability', 'SQL injection successful', 'Reverse shell active'],
  },
  system: {
    fileName: ['dokumento', 'ulat', 'presentation', 'spreadsheet', 'larawan', 'video', 'audio', 'archive', 'backup', 'data', 'configuration', 'settings', 'log', 'cache', 'project', 'draft', 'final', 'version'],
    fileType: ['audio', 'image', 'text', 'video', 'application', 'document', 'spreadsheet', 'presentation', 'archive', 'code'],
  },
  science: {
    chemicalElement: ['Hydrogen', 'Helium', 'Lithium', 'Carbon', 'Nitrogen', 'Oxygen', 'Fluorine', 'Neon', 'Sodium', 'Magnesium', 'Aluminum', 'Silicon', 'Phosphorus', 'Sulfur', 'Chlorine', 'Iron', 'Copper', 'Zinc', 'Silver', 'Gold', 'Mercury', 'Lead', 'Uranium', 'Plutonium'],
    unit: ['meter', 'kilogram', 'second', 'ampere', 'kelvin', 'mole', 'candela', 'newton', 'pascal', 'joule', 'watt', 'volt', 'ohm', 'hertz', 'celsius', 'liter', 'gram'],
    constant: ['Speed of Light', 'Gravitational Constant', 'Planck Constant', 'Boltzmann Constant', 'Avogadro Constant', 'Elementary Charge', 'Gas Constant'],
    field: ['Physics', 'Chemistry', 'Biology', 'Astronomy', 'Geology', 'Ecology', 'Genetics', 'Neuroscience', 'Biochemistry', 'Microbiology', 'Botany', 'Zoology', 'Mathematics', 'Computer Science'],
  },
}
