import type { LocaleDefinition } from '@stacksjs/ts-faker'

export const sv: LocaleDefinition = {
  title: 'Swedish',
  person: {
    firstNameMale: [
      'Oscar',
      'William',
      'Liam',
      'Noah',
      'Lucas',
      'Oliver',
      'Elias',
      'Hugo',
      'Alexander',
      'Isak',
      'Leo',
      'Axel',
      'Emil',
      'Vincent',
      'Alfred',
      'Erik',
      'Anton',
      'Viktor',
      'Karl',
      'Johan',
      'Anders',
      'Lars',
      'Per',
      'Mikael',
      'Gustav',
      'Nils',
      'Magnus',
      'Sven',
      'Olle',
      'Fredrik',
      'Henrik',
      'Peter',
      'Daniel',
      'Andreas',
      'Martin',
      'Stefan',
      'Mattias',
      'Niklas',
      'Patrik',
      'Tomas',
      'Jan',
      'Göran',
      'Bengt',
      'Ulf',
      'Björn',
      'Lennart',
      'Christer',
      'Leif',
      'Kjell',
      'Rolf',
    ],
    firstNameFemale: [
      'Alice',
      'Elsa',
      'Maja',
      'Ella',
      'Wilma',
      'Alma',
      'Ebba',
      'Lilly',
      'Astrid',
      'Saga',
      'Agnes',
      'Freja',
      'Stella',
      'Clara',
      'Selma',
      'Anna',
      'Maria',
      'Linnéa',
      'Sofia',
      'Elin',
      'Emma',
      'Hanna',
      'Sara',
      'Ida',
      'Johanna',
      'Lisa',
      'Karin',
      'Eva',
      'Lena',
      'Kristina',
      'Ingrid',
      'Birgitta',
      'Margareta',
      'Elisabeth',
      'Annika',
      'Monica',
      'Gunilla',
      'Susanne',
      'Katarina',
      'Anita',
      'Ylva',
      'Frida',
      'Kerstin',
      'Cecilia',
      'Malin',
      'Viktoria',
      'Therese',
      'Marie',
      'Charlotte',
      'Camilla',
    ],
    firstNameNeutral: [
      'Kim',
      'Alex',
      'Charlie',
      'Sam',
      'Robin',
      'Morgan',
      'Casey',
      'Riley',
      'Jamie',
      'Taylor',
    ],
    lastName: ['Andersson', 'Johansson', 'Karlsson', 'Nilsson', 'Eriksson', 'Larsson', 'Olsson', 'Persson', 'Svensson', 'Gustafsson', 'Pettersson', 'Jonsson', 'Jansson', 'Hansson', 'Bengtsson', 'Jönsson', 'Lindberg', 'Jakobsson', 'Magnusson', 'Olofsson', 'Lindström', 'Lindqvist', 'Lindgren', 'Berg', 'Axelsson', 'Bergström', 'Lundberg', 'Lund', 'Lundgren', 'Mattsson', 'Berglund', 'Fredriksson', 'Sandberg', 'Henriksson', 'Forsberg', 'Sjöberg', 'Wallin', 'Engström', 'Danielsson', 'Håkansson'],
    prefix: ['Herr', 'Fru', 'Fröken', 'Dr.', 'Prof.', 'Ing.'],
    suffix: ['Jr.', 'Sr.', 'II', 'III', 'IV'],
    gender: ['Man', 'Kvinna', 'Annat'],
    jobTitle: ['Mjukvaruutvecklare', 'Projektledare', 'Designer', 'Marknadschef', 'Försäljningschef', 'Revisor', 'Jurist', 'Läkare', 'Sjuksköterska', 'Lärare', 'Professor', 'Forskare', 'Dataanalytiker', 'Produktchef', 'HR-chef', 'Konsult', 'Arkitekt', 'Ingenjör', 'Tekniker', 'Kock', 'Författare', 'Journalist', 'Fotograf', 'Konstnär', 'Musiker'],
  },
  address: {
    street: ['Drottninggatan', 'Kungsgatan', 'Storgatan', 'Sveavägen', 'Götgatan', 'Vasagatan', 'Birger Jarlsgatan', 'Hornsgatan', 'Folkungagatan', 'Kungsholmsgatan', 'Hamngatan', 'Regeringsgatan', 'Karlavägen', 'Strandvägen', 'Narvavägen', 'Valhallavägen', 'Odengatan', 'Östermalmsgatan', 'Norrtullsgatan', 'Södermalmsallén', 'Skånegatan', 'Ringvägen', 'Norrlandsgatan', 'Biblioteksgatan', 'Smålandsgatan', 'Linnégatan', 'Artillerigatan', 'Brahegatan', 'Engelbrektsgatan', 'Rådmansgatan'],
    city: ['Stockholm', 'Göteborg', 'Malmö', 'Uppsala', 'Västerås', 'Örebro', 'Linköping', 'Helsingborg', 'Jönköping', 'Norrköping', 'Lund', 'Umeå', 'Gävle', 'Borås', 'Eskilstuna', 'Södertälje', 'Karlstad', 'Täby', 'Växjö', 'Halmstad', 'Sundsvall', 'Luleå', 'Trollhättan', 'Östersund', 'Borlänge', 'Falun', 'Kalmar', 'Kristianstad', 'Karlskrona', 'Skellefteå'],
    state: ['Stockholm', 'Västra Götaland', 'Skåne', 'Östergötland', 'Uppsala', 'Värmland', 'Örebro', 'Jönköping', 'Kronoberg', 'Kalmar', 'Gotland', 'Blekinge', 'Halland', 'Västmanland', 'Dalarna', 'Gävleborg', 'Västernorrland', 'Jämtland', 'Västerbotten', 'Norrbotten', 'Södermanland'],
    country: ['Sverige', 'Norge', 'Danmark', 'Finland', 'Island'],
    zipCode: ['### ##'],
    direction: ['Nord', 'Syd', 'Öst', 'Väst', 'Nordöst', 'Nordväst', 'Sydöst', 'Sydväst'],
  },
  company: {
    name: ['Volvo', 'IKEA', 'H&M', 'Ericsson', 'Spotify', 'Klarna', 'Skype', 'Electrolux', 'ABB', 'Atlas Copco', 'Sandvik', 'Husqvarna', 'Scania', 'SCA', 'SKF', 'Telia', 'Nordea', 'SEB', 'Swedbank', 'Handelsbanken', 'ICA', 'Coop', 'Axfood', 'Hemköp', 'Willys', 'Media Markt', 'Elgiganten', 'NetOnNet', 'Webhallen', 'King'],
    industry: ['Fordonsindustri', 'Möbler', 'Mode', 'Telekommunikation', 'IT', 'Musik', 'Fintech', 'Bank', 'Försäkring', 'Detaljhandel', 'Fastigheter', 'Bygg', 'Industri', 'Hälsovård', 'Utbildning', 'Transport', 'Turism', 'Media', 'Reklam', 'Konsulttjänster', 'Energi', 'Gruvdrift', 'Skog', 'Papper', 'Stål'],
    buzzword: ['innovation', 'hållbarhet', 'digitalisering', 'omställning', 'automation', 'AI', 'dataanalys', 'moln', 'IoT', 'gig-ekonomi', 'delningsekonomi', 'plattformsekonomi', 'startup', 'scale-up', 'unicorn', 'disruption', 'agil', 'lean', 'scrum', 'DevOps', 'fintech', 'greentech', 'cleantech', 'biotech', 'medtech'],
  },
  internet: {
    domainName: ['aftonbladet.se', 'expressen.se', 'dn.se', 'svd.se', 'svt.se', 'sr.se', 'tv4.se', 'blocket.se', 'tradera.se', 'hemnet.se', 'eniro.se', 'hitta.se', 'flashback.org', 'familjeliv.se', 'fragbite.se', 'sweclockers.se', 'feber.se', 'breakit.se', 'di.se', 'vk.se', 'gp.se', 'sydsvenskan.se', 'unt.se', 'lt.se'],
  },
  phone: {
    number: ['08-### ## ##', '070-### ## ##', '073-### ## ##', '+46 8 ### ## ##', '+46 70 ### ## ##', '08-#######', '070-#######'],
  },
  food: {
    dish: ['Köttbullar', 'Prinsesstårta', 'Janssons frestelse', 'Gravad lax', 'Räksmörgås', 'Toast Skagen', 'Ärtsoppa', 'Pannkakor', 'Kroppkakor', 'Pytt i panna', 'Falukorv', 'Kalops', 'Wallenbergare', 'Blodpudding', 'Isterband', 'Surströmming', 'Lutfisk', 'Sill', 'Smörgåstårta', 'Semla', 'Kanelbullar', 'Pepparkakor', 'Saffransbullar', 'Raggmunk', 'Palt', 'Kåldolmar', 'Gulaschsoppa', 'Fiskgratäng', 'Hasselbackspotatis', 'Räkmacka'],
    ingredient: ['Köttfärs', 'Lax', 'Sill', 'Räkor', 'Kräftor', 'Falukorv', 'Isterband', 'Korv', 'Fläsk', 'Älg', 'Ren', 'Grädde', 'Smör', 'Mjölk', 'Ost', 'Ägg', 'Potatis', 'Kål', 'Morot', 'Lök', 'Ärtor', 'Bönor', 'Lingon', 'Blåbär', 'Hjortron', 'Hallon', 'Jordgubbar', 'Svartvinbär', 'Krusbär', 'Dill'],
    cuisine: ['Svensk', 'Skandinavisk', 'Italiensk', 'Fransk', 'Asiatisk', 'Thai', 'Indisk', 'Kinesisk', 'Japansk', 'Mexikansk', 'Amerikansk', 'Grekisk', 'Turkisk', 'Spansk', 'Vegetarisk', 'Vegansk', 'Glutenfri', 'Skaldjur', 'Grill', 'Husmanskost'],
    dessert: ['Prinsesstårta', 'Semla', 'Kanelbulle', 'Pepparkaka', 'Saffransbulle', 'Chokladboll', 'Kladdkaka', 'Ostkaka', 'Spettekaka', 'Hallongrottor', 'Mazariner', 'Drömmar', 'Budapestbakelse', 'Wienerbröd', 'Glass', 'Panna cotta', 'Tiramisu', 'Cheesecake', 'Brownies', 'Äppelpaj'],
    fruit: ['Äpple', 'Päron', 'Plommon', 'Körsbär', 'Jordgubbar', 'Hallon', 'Blåbär', 'Lingon', 'Hjortron', 'Svartvinbär', 'Röda vinbär', 'Krusbär', 'Banan', 'Apelsin', 'Citron', 'Mango', 'Ananas', 'Druvor', 'Vattenmelon', 'Kiwi'],
    vegetable: ['Potatis', 'Morot', 'Kålrot', 'Vitkål', 'Blomkål', 'Broccoli', 'Brysselkål', 'Lök', 'Vitlök', 'Purjolök', 'Selleri', 'Paprika', 'Tomat', 'Gurka', 'Sallad', 'Spenat', 'Grönkål', 'Squash', 'Pumpa', 'Ärtor', 'Bönor', 'Majs', 'Rädisa', 'Sparris', 'Svamp'],
    meat: ['Lammkött', 'Fläsk', 'Nötkött', 'Kyckling', 'Kalkon', 'Anka', 'Älg', 'Ren', 'Rådjur', 'Vildsvin', 'Kotlett', 'Entrecôte', 'Fläskfilé', 'Innanlår', 'Utanlår', 'Ryggbiff', 'Bog', 'Stek', 'Färs', 'Korv'],
    spice: ['Salt', 'Peppar', 'Curry', 'Paprika', 'Chili', 'Ingefära', 'Vitlök', 'Lök', 'Persilja', 'Dill', 'Timjan', 'Rosmarin', 'Basilika', 'Oregano', 'Muskot', 'Nejlika', 'Kardemumma', 'Kanel', 'Vanilj', 'Lagerblad'],
  },
  animal: {
    dog: ['Tax', 'Drever', 'Hamiltonstövare', 'Schillerstövare', 'Smålandsstövare', 'Svensk lapphund', 'Västgötaspets', 'Jämthund', 'Norrbottenspets', 'Labrador', 'Golden retriever', 'Schäfer', 'Rottweiler', 'Boxer', 'Beagle', 'Cocker spaniel', 'Jack Russell terrier', 'Border collie', 'Sheltie', 'Cavalier King Charles spaniel', 'Chihuahua', 'Pudel', 'Yorkshire terrier', 'Bichon frisé', 'Mops'],
    cat: ['Huskatt', 'Perser', 'Maine coon', 'Ragdoll', 'Birma', 'Siames', 'Bengalkatt', 'Abessinier', 'Rysk blå', 'Sphynx', 'British shorthair', 'Scottish fold', 'Burmesisk', 'Chartreaux', 'Devon rex', 'Cornish rex', 'Singapura', 'Tonkines', 'Korat', 'Europeisk korthår'],
    bird: ['Mås', 'Tärna', 'Skarv', 'Häger', 'Svan', 'Gås', 'And', 'Trana', 'Stork', 'Hackspett', 'Lärka', 'Trast', 'Stare', 'Kråka', 'Skata', 'Nötväcka', 'Mes', 'Domherre', 'Stenknäck', 'Grönsiska', 'Talgoxe', 'Blåmes', 'Rödhake', 'Sädesärla', 'Tornfalk'],
    fish: ['Abborre', 'Gädda', 'Gös', 'Lake', 'Sik', 'Röding', 'Öring', 'Lax', 'Torsk', 'Sej', 'Kolja', 'Sill', 'Strömming', 'Makrill', 'Tonfisk', 'Flundra', 'Rödspätta', 'Piggvar', 'Ål', 'Karpfisk', 'Braxen', 'Id', 'Mört', 'Sarv', 'Sutare'],
    horse: ['Gotlandsruss', 'Nordsvensk brukshäst', 'Svensk kallblod', 'Svensk varmblod', 'Svensk ardennare', 'Islandshäst', 'Shetlandsponny', 'Welsh ponny', 'Araber', 'Fullblod', 'Lipizzaner', 'Fries', 'Andalusier', 'Hannoveranare', 'Oldenburger'],
    rabbit: ['Huskanin', 'Vildkanin', 'Hare', 'Dvärg kanin', 'Lejonhuvud kanin', 'Angora', 'Rex', 'Lop', 'Chinchilla', 'Fläming jätte', 'Himalaya', 'Holland lop', 'Mini lop', 'Nederländsk dvärg', 'Fransk vädur'],
    insect: ['Fjäril', 'Trollslända', 'Gräshoppa', 'Bille', 'Humla', 'Bi', 'Geting', 'Myra', 'Kvalster', 'Spindel', 'Mygga', 'Fluga', 'Knott', 'Lus', 'Loppa', 'Vårtbitare', 'Dagslända', 'Skalbagge', 'Mal', 'Larv'],
  },
  sport: {
    sport: ['Fotboll', 'Ishockey', 'Handboll', 'Bandy', 'Längdskidor', 'Skidskytte', 'Alpin skidåkning', 'Backhoppning', 'Snowboard', 'Friidrott', 'Simning', 'Cykling', 'Golf', 'Tennis', 'Volleyboll', 'Basket', 'Bordtennis', 'Badminton', 'Klättring', 'Segling', 'Rodd', 'Kanotsport', 'Brottning', 'Orientering', 'Innebandy'],
    team: ['AIK', 'Djurgården', 'Hammarby', 'Malmö FF', 'IFK Göteborg', 'Häcken', 'Elfsborg', 'IFK Norrköping', 'Helsingborg', 'Kalmar FF', 'Örebro', 'Sirius', 'HV71', 'Frölunda', 'Färjestad', 'Luleå', 'Skellefteå AIK', 'Växjö Lakers', 'Linköping HC', 'Brynäs'],
    athlete: ['Zlatan Ibrahimović', 'Henrik Larsson', 'Ingemar Stenmark', 'Björn Borg', 'Stefan Edberg', 'Mats Wilander', 'Annika Sörenstam', 'Charlotte Kalla', 'Frida Hansdotter', 'Marcus Kinhult', 'Armand Duplantis', 'Kajsa Bergqvist', 'Carolina Klüft', 'Anja Pärson', 'Jan-Ove Waldner', 'Gunde Svan', 'Thomas Wassberg', 'Sixten Jernberg', 'Sarah Sjöström', 'Therese Alshammar'],
  },
  music: {
    genre: ['Pop', 'Rock', 'Elektronisk', 'Hip-hop', 'Jazz', 'Klassisk', 'Folk', 'Country', 'Blues', 'Metal', 'Punk', 'Indie', 'R&B', 'Soul', 'Reggae', 'Techno', 'House', 'Trance', 'Drum and bass', 'Dubstep', 'Dansband', 'Visa', 'Schlager', 'EDM', 'Ambient'],
    artist: ['ABBA', 'Roxette', 'Ace of Base', 'Europe', 'The Cardigans', 'Robyn', 'Avicii', 'Swedish House Mafia', 'Zara Larsson', 'Tove Lo', 'Icona Pop', 'First Aid Kit', 'José González', 'The Hives', 'Refused', 'In Flames', 'Arch Enemy', 'Opeth', 'Ghost', 'Sabaton', 'Yngwie Malmsteen', 'Max Martin', 'Galantis', 'Alesso', 'Eric Prydz'],
    song: ['Dancing Queen', 'Waterloo', 'Mamma Mia', 'The Winner Takes It All', 'It Must Have Been Love', 'Listen to Your Heart', 'The Sign', 'All That She Wants', 'The Final Countdown', 'Carrie', 'Lovefool', 'My Favourite Game', 'Dancing On My Own', 'With Every Heartbeat', 'Wake Me Up', 'Levels', 'Lush Life', 'Never Forget You', 'Emmylou', 'Heartbeats'],
    instrument: ['Gitarr', 'Bas', 'Trummor', 'Piano', 'Keyboard', 'Synth', 'Fiol', 'Cello', 'Altfiol', 'Kontrabas', 'Flöjt', 'Klarinett', 'Oboe', 'Fagott', 'Saxofon', 'Trumpet', 'Trombon', 'Tuba', 'Horn', 'Dragspel', 'Munspel', 'Ukulele', 'Banjo', 'Mandolin', 'Nyckelharpa'],
  },
  commerce: {
    productName: ['Smartphone', 'Laptop', 'Surfplatta', 'Hörlurar', 'Högtalare', 'Mus', 'Tangentbord', 'Skärm', 'Webbkamera', 'Laddare', 'Kabel', 'Powerbank', 'Smartklocka', 'Skor', 'Väska', 'Plånbok', 'Bälte', 'Klocka', 'Solglasögon', 'Keps', 'T-shirt', 'Hoodie', 'Jeans', 'Jacka', 'Kappa'],
    productAdjective: ['Smart', 'Premium', 'Lyxig', 'Bäst', 'Populär', 'Ny', 'Limiterad', 'Erbjudande', 'Rabatt', 'Rea', 'Rekommenderad', 'Bästsäljare', 'Nyhet', 'Senaste', 'Exklusiv', 'Praktisk', 'Prisvärd', 'Varumärke', 'Original', 'Import', 'Svensk', 'Miljövänlig', 'Fri frakt', 'Leverans samma dag'],
    productMaterial: ['Läder', 'Bomull', 'Polyester', 'Nylon', 'Silikon', 'Plast', 'Metall', 'Rostfritt stål', 'Aluminium', 'Titan', 'Keramik', 'Glas', 'Trä', 'Bambu', 'Papper', 'Gummi', 'Skum', 'Latex', 'Ull', 'Kashmir'],
    department: ['Elektronik', 'Kläder', 'Skönhet', 'Mat och hälsa', 'Hem och kök', 'Möbler', 'Sport', 'Böcker', 'Leksaker', 'Digitalt', 'Baby', 'Husdjur', 'Bil', 'Verktyg', 'Resa', 'Presenter', 'Barn', 'Dator och spel', 'Foto och ljud', 'Smycken'],
    color: ['Röd', 'Orange', 'Gul', 'Grön', 'Blå', 'Lila', 'Rosa', 'Svart', 'Vit', 'Grå', 'Brun', 'Beige', 'Marinblå', 'Khaki', 'Mint', 'Lavendel', 'Korall', 'Burgundy', 'Vinröd', 'Cremefärgad'],
  },
  book: {
    title: ['Pippi Långstrump', 'Bröderna Lejonhjärta', 'Ronja Rövardotter', 'Mio, min Mio', 'Emil i Lönneberga', 'Röda rummet', 'Utvandrarna', 'Invandrarna', 'Nybyggarna', 'Sista brevet till läsaren', 'Almayers dårskap', 'Doktor Glas', 'Fröken Julie', 'Fadren', 'Hemsöborna', 'Gösta Berlings saga', 'Herr Arnes penningar', 'Jerusalem', 'Kejsaren av Portugallien', 'Ondskan'],
    author: ['Astrid Lindgren', 'Selma Lagerlöf', 'August Strindberg', 'Hjalmar Söderberg', 'Vilhelm Moberg', 'Henning Mankell', 'Stieg Larsson', 'Camilla Läckberg', 'Liza Marklund', 'Håkan Nesser', 'Jan Guillou', 'Per Anders Fogelström', 'Karin Boye', 'Tomas Tranströmer', 'Harry Martinson', 'Eyvind Johnson', 'Pär Lagerkvist', 'Sara Lidman', 'Stig Dagerman', 'Kerstin Ekman'],
    publisher: ['Bonniers', 'Norstedts', 'Rabén & Sjögren', 'Natur & Kultur', 'Alfabeta', 'Wahlström & Widstrand', 'Bokförlaget Forum', 'Piratförlaget', 'Modernista', 'Leopard', 'Albert Bonniers', 'Ordfront', 'Historiska Media', 'Lind & Co', 'Romanus & Selling'],
    genre: ['Roman', 'Deckare', 'Thriller', 'Fantasy', 'Science fiction', 'Historisk', 'Biografi', 'Poesi', 'Essä', 'Fackbok', 'Självbiografi', 'Reseberättelse', 'Kokbok', 'Hälsa', 'Barn', 'Ungdom', 'Serietidning', 'Humor', 'Drama', 'Sakprosa'],
    series: ['Millennium', 'Fjällbacka', 'Kurt Wallander', 'Maria Wern', 'Annika Bengtzon', 'Hamilton', 'Van Veeteren', 'Martin Beck', 'Pippi Långstrump', 'Emil i Lönneberga', 'Barnen i Bullerbyn', 'Madicken', 'Rasmus på luffen', 'Kalle Blomkvist', 'Mumin', 'Alfons Åberg', 'Pettson och Findus', 'Bamse', 'Sagan om ringen', 'Harry Potter'],
    review: ['Starkt rekommenderad', 'Fantastisk', 'Måste läsas', 'Rörande', 'Oförglömlig', 'Gripande', 'Fängslande', 'Mästerverk', 'Briljant', 'Solid', 'Underhållande', 'Spännande', 'Rolig', 'Sorglig', 'Tankeväckande', 'Imponerande', 'Intressant', 'Tråkig', 'Förvirrande', 'Överraskande'],
  },
  vehicle: {
    manufacturer: ['Volvo', 'Saab', 'Koenigsegg', 'Tesla', 'Volkswagen', 'BMW', 'Mercedes-Benz', 'Audi', 'Toyota', 'Nissan', 'Kia', 'Hyundai', 'Ford', 'Peugeot', 'Renault', 'Skoda', 'Mazda', 'Honda', 'Mitsubishi', 'Subaru', 'Jaguar', 'Land Rover', 'Porsche', 'Polestar', 'BYD'],
    model: ['XC40', 'XC60', 'XC90', 'V60', 'V90', 'S60', 'S90', '9-3', '9-5', 'Model 3', 'Model Y', 'ID.4', 'e-Golf', 'i3', 'iX3', 'EQC', 'e-tron', 'Leaf', 'Ariya', 'e-Niro', 'Kona Electric', 'Ioniq 5', 'Mach-E', 'e-208', 'Zoe'],
    type: ['Sedan', 'SUV', 'Kombi', 'Coupé', 'Cabriolet', 'Skåpbil', 'Pickup', 'Sportbil', 'Elbil', 'Hybrid', 'Laddhybrid', 'Vätgasbil', 'Småbil', 'Mellanklass', 'Stor', 'Liten SUV', 'Mellanklass SUV', 'Stor SUV', 'Minibuss', 'Flak'],
    fuel: ['Bensin', 'Diesel', 'El', 'Vätgas', 'Hybrid', 'Laddhybrid', 'Biodiesel', 'Etanol', 'Gas', 'Biogas'],
    bicycle: ['Mountainbike', 'Landsväg', 'Hybrid', 'Stadscykel', 'BMX', 'Fixie', 'Cruiser', 'Elcykel', 'Hopfällbar cykel', 'Barncykel', 'Touring', 'Gravel', 'Cyclocross', 'Bana', 'Liggcykel', 'Tandem', 'Trehjuling', 'Sparkcykel', 'Elsparkcykel', 'Lastcykel'],
  },
  word: {
    adjective: ['vacker', 'stor', 'liten', 'bra', 'dålig', 'snabb', 'långsam', 'hög', 'låg', 'ny', 'gammal', 'varm', 'kall', 'ljus', 'mörk', 'glad', 'ledsen', 'lycklig', 'arg', 'rädd', 'modig', 'stark', 'svag', 'smart', 'dum', 'fin', 'ful', 'ren', 'smutsig', 'rik'],
    adverb: ['snabbt', 'långsamt', 'tyst', 'högt', 'lågt', 'mycket', 'lite', 'alltid', 'aldrig', 'ofta', 'sällan', 'kanske', 'säkert', 'verkligen', 'mycket', 'ganska', 'lite', 'extremt', 'nästan', 'ungefär', 'precis', 'plötsligt', 'gradvis', 'omedelbart', 'genast', 'senare', 'tidigare', 'nu', 'då'],
    conjunction: ['och', 'eller', 'men', 'dock', 'eftersom', 'om', 'när', 'medan', 'sedan', 'även om', 'antingen', 'både', 'så', 'därför', 'därmed', 'ändå', 'emellertid', 'dessutom', 'däremot', 'nämligen'],
    interjection: ['Å', 'Oj', 'Aj', 'Uff', 'Puh', 'Hurra', 'Jaså', 'Jaha', 'Nämen', 'Fy', 'Hej', 'Ha', 'Hm', 'Jo', 'Nej', 'Ja', 'Jösses', 'Usch', 'Åh', 'Hoppsan'],
    noun: ['person', 'hus', 'träd', 'blomma', 'vatten', 'eld', 'vind', 'himmel', 'jord', 'berg', 'flod', 'hav', 'sol', 'måne', 'stjärna', 'moln', 'regn', 'snö', 'åska', 'blixt', 'bok', 'skola', 'lärare', 'elev', 'vän', 'familj', 'far', 'mor', 'syster', 'bror'],
    preposition: ['i', 'på', 'till', 'från', 'med', 'utan', 'för', 'över', 'under', 'vid', 'hos', 'mellan', 'bland', 'genom', 'runt', 'mot', 'om', 'av', 'efter', 'före'],
    verb: ['gå', 'komma', 'äta', 'dricka', 'sova', 'vakna', 'sitta', 'stå', 'ligga', 'springa', 'hoppa', 'prata', 'lyssna', 'se', 'läsa', 'skriva', 'lära', 'undervisa', 'tänka', 'veta', 'känna', 'tycka om', 'älska', 'hata', 'skratta', 'gråta', 'leka', 'arbeta', 'vila'],
  },
  hacker: {
    abbreviation: ['AI', 'ML', 'IoT', 'API', 'SDK', 'IDE', 'OS', 'DB', 'SQL', 'HTTP', 'HTTPS', 'REST', 'JSON', 'XML', 'HTML', 'CSS', 'JS', 'UI', 'UX', 'CI/CD', 'DevOps', 'AWS', 'GCP', 'Azure', 'K8s', 'Docker', 'Git', 'SVN', 'FTP', 'SSH'],
    adjective: ['distribuerad', 'molnbaserad', 'kvant', 'neural', 'djupinlärning', 'maskininlärning', 'blockkedja', 'krypterad', 'hashad', 'komprimerad', 'optimerad', 'skalbar', 'högttillgänglig', 'feltolerant', 'realtid', 'asynkron', 'synkron', 'parallell', 'distribuerad', 'centraliserad'],
    noun: ['algoritm', 'datastruktur', 'protokoll', 'gränssnitt', 'modul', 'paket', 'bibliotek', 'ramverk', 'mellanvara', 'databas', 'server', 'klient', 'nätverk', 'säkerhet', 'kryptering', 'hash', 'token', 'session', 'cookie', 'cache', 'kö', 'stack', 'heap', 'träd', 'graf', 'array', 'lista', 'karta', 'mängd'],
    verb: ['köra', 'kompilera', 'debugga', 'deploya', 'bygga', 'testa', 'optimera', 'refaktorera', 'integrera', 'synkronisera', 'kryptera', 'dekryptera', 'hasha', 'komprimera', 'dekomprimera', 'serialisera', 'deserialisera', 'parsa', 'validera', 'autentisera'],
    ingverb: ['kodning', 'programmering', 'utveckling', 'design', 'analys', 'testning', 'debugging', 'deployment', 'övervakning', 'loggning', 'profilering', 'benchmarking', 'skalning', 'migrering', 'refaktorering', 'optimering', 'dokumentation', 'granskning', 'integration', 'automatisering'],
    phrase: ['AI förändrar framtiden', 'Big data ger insikter', 'Molnet ger oändliga möjligheter', 'Blockkedja bygger förtroende', 'Kvantdatorer kommer', 'Maskininlärning förutsäger', 'Djupinlärning lär sig', 'IoT kopplar samman allt', '5G förändrar allt', 'Metaverse väntar', 'Web3 leder vägen', 'NFT är digitala tillgångar', 'Smarta kontrakt automatiserar', 'DeFi innoverar finans', 'DAO decentraliserar', 'Korsplattform ger effektivitet', 'Mikrotjänster ger skalbarhet', 'Containrar förenklar deployment', 'CI/CD för snabb leverans', 'DevOps stärker samarbete'],
  },
  system: {
    fileName: ['dokument', 'rapport', 'presentation', 'kalkylblad', 'bild', 'video', 'ljud', 'arkiv', 'körbar', 'konfiguration', 'logg', 'backup', 'tillfällig', 'cache', 'data', 'installation', 'uppdatering', 'drivrutin', 'bibliotek', 'skript'],
    fileType: ['dokument', 'bild', 'video', 'ljud', 'arkiv', 'körbar', 'konfiguration', 'data', 'backup', 'logg', 'cache', 'tillfällig', 'system', 'bibliotek', 'drivrutin', 'uppdatering', 'installation', 'typsnitt', 'tema', 'plugin'],
  },
  science: {
    chemicalElement: ['Väte', 'Helium', 'Litium', 'Beryllium', 'Bor', 'Kol', 'Kväve', 'Syre', 'Fluor', 'Neon', 'Natrium', 'Magnesium', 'Aluminium', 'Kisel', 'Fosfor', 'Svavel', 'Klor', 'Argon', 'Kalium', 'Kalcium', 'Järn', 'Koppar', 'Zink', 'Silver', 'Guld', 'Kvicksilver', 'Bly', 'Uran', 'Plutonium', 'Radon'],
    unit: ['meter', 'kilogram', 'sekund', 'ampere', 'kelvin', 'mol', 'candela', 'newton', 'pascal', 'joule', 'watt', 'coulomb', 'volt', 'ohm', 'hertz', 'liter', 'gram', 'centimeter', 'millimeter', 'kilometer', 'millisekund', 'mikrosekund', 'nanosekund'],
    constant: ['ljusets hastighet', 'gravitationskonstanten', 'Plancks konstant', 'Boltzmanns konstant', 'Avogadros tal', 'gaskonstanten', 'permittiviteten i vakuum', 'permeabiliteten i vakuum', 'elementarladdningen', 'protonmassan', 'elektronmassan', 'neutronmassan', 'finstrukturkonstanten', 'Rydbergs konstant', 'Stefan-Boltzmanns konstant'],
    field: ['Fysik', 'Kemi', 'Biologi', 'Astronomi', 'Geologi', 'Meteorologi', 'Oceanografi', 'Ekologi', 'Genetik', 'Molekylärbiologi', 'Cellbiologi', 'Neurovetenskap', 'Psykologi', 'Matematik', 'Statistik', 'Datavetenskap', 'Ingenjörsvetenskap', 'Medicin', 'Farmaci', 'Veterinärmedicin', 'Jordbruk', 'Miljövetenskap', 'Nanoteknik', 'Materialvetenskap', 'Energiforskning'],
  },
  color: {
    name: ['röd', 'orange', 'gul', 'grön', 'blå', 'indigo', 'violett', 'rosa', 'svart', 'vit', 'grå', 'brun', 'beige', 'grädde', 'elfenben', 'guld', 'silver', 'brons', 'koppar', 'oliv', 'khaki', 'marinblå', 'mint', 'turkos', 'magenta', 'lila', 'limegrön', 'himmelsblå', 'marinblå', 'kastanjebrun'],
  },
}
