import type { DeepPartial, LocaleDefinition } from '@stacksjs/ts-faker'

/**
 * English (United States) locale
 * Extends the base 'en' locale with US-specific data
 */
export const en_US: DeepPartial<LocaleDefinition> = {
  title: 'English (United States)',

  // Override US-specific address data
  address: {
    city: [
      'New York',
      'Los Angeles',
      'Chicago',
      'Houston',
      'Phoenix',
      'Philadelphia',
      'San Antonio',
      'San Diego',
      'Dallas',
      'San Jose',
      'Austin',
      'Jacksonville',
      'Fort Worth',
      'Columbus',
      'San Francisco',
      'Charlotte',
      'Indianapolis',
      'Seattle',
      'Denver',
      'Boston',
      'Portland',
      'Las Vegas',
      'Miami',
      'Atlanta',
      'Detroit',
    ],
    state: [
      'Alabama',
      'Alaska',
      'Arizona',
      'Arkansas',
      'California',
      'Colorado',
      'Connecticut',
      'Delaware',
      'Florida',
      'Georgia',
      'Hawaii',
      'Idaho',
      'Illinois',
      'Indiana',
      'Iowa',
      'Kansas',
      'Kentucky',
      'Louisiana',
      'Maine',
      'Maryland',
      'Massachusetts',
      'Michigan',
      'Minnesota',
      'Mississippi',
      'Missouri',
      'Montana',
      'Nebraska',
      'Nevada',
      'New Hampshire',
      'New Jersey',
      'New Mexico',
      'New York',
      'North Carolina',
      'North Dakota',
      'Ohio',
      'Oklahoma',
      'Oregon',
      'Pennsylvania',
      'Rhode Island',
      'South Carolina',
      'South Dakota',
      'Tennessee',
      'Texas',
      'Utah',
      'Vermont',
      'Virginia',
      'Washington',
      'West Virginia',
      'Wisconsin',
      'Wyoming',
    ],
    stateAbbr: [
      'AL',
      'AK',
      'AZ',
      'AR',
      'CA',
      'CO',
      'CT',
      'DE',
      'FL',
      'GA',
      'HI',
      'ID',
      'IL',
      'IN',
      'IA',
      'KS',
      'KY',
      'LA',
      'ME',
      'MD',
      'MA',
      'MI',
      'MN',
      'MS',
      'MO',
      'MT',
      'NE',
      'NV',
      'NH',
      'NJ',
      'NM',
      'NY',
      'NC',
      'ND',
      'OH',
      'OK',
      'OR',
      'PA',
      'RI',
      'SC',
      'SD',
      'TN',
      'TX',
      'UT',
      'VT',
      'VA',
      'WA',
      'WV',
      'WI',
      'WY',
    ],
    country: ['United States', 'USA', 'United States of America'],
    zipCode: ['#####', '#####-####'],
    buildingNumber: ['###', '####', '#####'],
  },

  // US phone number formats
  phone: {
    formats: [
      '###-###-####',
      '(###) ###-####',
      '1-###-###-####',
      '+1-###-###-####',
    ],
  },

  // US-specific cuisine
  food: {
    dish: [
      'Hamburger',
      'Cheeseburger',
      'Hot Dog',
      'BBQ Ribs',
      'Fried Chicken',
      'Mac and Cheese',
      'Buffalo Wings',
      'Philly Cheesesteak',
      'New York Pizza',
      'Chicago Deep Dish',
      'Clam Chowder',
      'Lobster Roll',
      'Pulled Pork',
      'Jambalaya',
      'Gumbo',
      'Key Lime Pie',
      'Apple Pie',
      'Brownies',
      'Southern Biscuits',
      'Pancakes',
      'Waffles',
      'Bagel with Lox',
      'Cobb Salad',
      'Reuben Sandwich',
      'BLT',
      'Club Sandwich',
      'Tex-Mex Tacos',
      'Nachos',
      'Chili',
      'Cornbread',
    ],
    cuisine: [
      'American',
      'Southern',
      'Tex-Mex',
      'BBQ',
      'Cajun',
      'Soul Food',
      'New American',
      'California Cuisine',
      'Pacific Northwest',
    ],
  },
}
