import type { LocaleDefinition } from '@stacksjs/ts-faker'

export const de: LocaleDefinition = {
  title: 'German',
  person: {
    firstNameMale: [
      'Alexander',
      'Andreas',
      'Anton',
      'Benjamin',
      'Christian',
      'Daniel',
      'David',
      'Elias',
      'Emil',
      'Felix',
      'Finn',
      'Friedrich',
      'Gabriel',
      'Georg',
      'Hans',
      'Heinrich',
      'Jakob',
      'Johannes',
      'Jonas',
      'Jonathan',
      'Josef',
      'Julius',
      'Karl',
      'Konstantin',
      'Leon',
      'Levi',
      'Liam',
      'Louis',
      'Luca',
      'Lukas',
      'Markus',
      'Martin',
      'Matthias',
      'Maximilian',
      'Michael',
      'Moritz',
      'Niklas',
      'Noah',
      'Oliver',
      'Oskar',
      'Paul',
      'Peter',
      'Philipp',
      'Rafael',
      'Robert',
      'Samuel',
      'Sebastian',
      'Simon',
      'Stefan',
      'Theodor',
      'Thomas',
      'Tim',
      'Tobias',
      'Valentin',
      'Vincent',
      'Wilhelm',
      'Wolfgang',
      'Klaus',
      'Günther',
      'Helmut',
      'Werner',
      'Ralf',
      'Jörg',
      'Bernd',
      'Dieter',
      'Uwe',
      'Rainer',
      'Horst',
      'Jürgen',
      'Manfred',
    ],
    firstNameFemale: [
      'Alexandra',
      'Amelie',
      'Andrea',
      'Angela',
      'Anita',
      'Anja',
      'Anna',
      'Anne',
      'Barbara',
      'Birgit',
      'Britta',
      'Charlotte',
      'Christina',
      'Christine',
      'Claudia',
      'Diana',
      'Doris',
      'Elisabeth',
      'Ella',
      'Emma',
      'Emilia',
      'Eva',
      'Franziska',
      'Gisela',
      'Hannah',
      'Heike',
      'Helena',
      'Helga',
      'Ingrid',
      'Irmgard',
      'Isabella',
      'Jana',
      'Johanna',
      'Julia',
      'Karin',
      'Katharina',
      'Katrin',
      'Laura',
      'Lea',
      'Lena',
      'Lina',
      'Lisa',
      'Luisa',
      'Maria',
      'Marie',
      'Martina',
      'Melanie',
      'Mia',
      'Monika',
      'Nadine',
      'Nicole',
      'Nina',
      'Petra',
      'Rosa',
      'Sabine',
      'Sandra',
      'Sara',
      'Sarah',
      'Silke',
      'Sofia',
      'Sophia',
      'Sophie',
      'Stefanie',
      'Susanne',
      'Tanja',
      'Theresa',
      'Ursula',
      'Vanessa',
      'Vera',
      'Renate',
      'Gabriele',
      'Kerstin',
      'Ute',
      'Christa',
      'Erika',
      'Bettina',
      'Simone',
      'Margit',
      'Ilse',
      'Greta',
    ],
    firstNameNeutral: [
      'Kim',
      'Sasha',
      'Alex',
      'Toni',
      'Robin',
      'Jona',
      'Luca',
      'Noah',
      'Andrea',
      'Nicola',
    ],
    lastName: [
      'Müller',
      'Schmidt',
      'Schneider',
      'Fischer',
      'Weber',
      'Meyer',
      'Wagner',
      'Becker',
      'Schulz',
      'Hoffmann',
      'Schäfer',
      'Koch',
      'Bauer',
      'Richter',
      'Klein',
      'Wolf',
      'Schröder',
      'Neumann',
      'Schwarz',
      'Zimmermann',
      'Braun',
      'Krüger',
      'Hofmann',
      'Hartmann',
      'Lange',
      'Schmitt',
      'Werner',
      'Schmitz',
      'Krause',
      'Meier',
      'Lehmann',
      'Schmid',
      'Schulze',
      'Maier',
      'Köhler',
      'Herrmann',
      'König',
      'Walter',
      'Mayer',
      'Huber',
      'Kaiser',
      'Fuchs',
      'Peters',
      'Lang',
      'Scholz',
      'Möller',
      'Weiß',
      'Jung',
      'Hahn',
      'Schubert',
      'Vogel',
      'Friedrich',
      'Keller',
      'Günther',
      'Frank',
      'Berger',
      'Winkler',
      'Roth',
      'Beck',
      'Lorenz',
      'Baumann',
      'Franke',
      'Albrecht',
      'Schuster',
      'Simon',
      'Ludwig',
      'Böhm',
      'Winter',
      'Kraus',
      'Martin',
    ],
    prefix: ['Herr', 'Frau', 'Dr.', 'Prof.', 'Dr. med.', 'Dr. phil.', 'Dipl.-Ing.'],
    suffix: ['Jr.', 'Sr.', 'I', 'II', 'III', 'IV', 'V', 'B.Sc.', 'M.Sc.', 'MBA', 'PhD'],
    gender: ['Männlich', 'Weiblich', 'Nicht-binär', 'Divers', 'Genderfluid', 'Agender'],
    jobTitle: [
      'Software-Ingenieur',
      'Produktmanager',
      'Designer',
      'Datenwissenschaftler',
      'DevOps-Ingenieur',
      'Marketingmanager',
      'Vertriebsmitarbeiter',
      'Buchhalter',
      'Personalleiter',
      'Geschäftsführer',
      'Technischer Leiter',
      'Projektmanager',
      'Entwickler',
      'Systemadministrator',
      'Qualitätsmanager',
      'Berater',
      'Analyst',
      'Koordinator',
      'Architekt',
      'Techniker',
      'Assistent',
      'Spezialist',
      'Abteilungsleiter',
      'Teamleiter',
      'Controller',
      'Sachbearbeiter',
      'Ingenieur',
      'Direktor',
    ],
  },
  address: {
    street: [
      'Haupt',
      'Bahnhof',
      'Schul',
      'Kirch',
      'Markt',
      'Ring',
      'Park',
      'Berg',
      'Wald',
      'Feld',
      'Garten',
      'Wiesen',
      'Mühl',
      'Bach',
      'See',
      'Dorf',
      'Schloss',
      'Turm',
      'Brücken',
      'Brunnen',
      'Kaiser',
      'König',
      'Bismarck',
      'Goethe',
      'Schiller',
      'Mozart',
      'Bach',
      'Beethoven',
      'Wagner',
      'Friedrich',
      'Wilhelm',
      'Karl',
      'Ludwig',
      'Heinrich',
      'Albert',
      'Neue',
      'Alte',
      'Lange',
      'Kurze',
    ],
    city: [
      'Berlin',
      'Hamburg',
      'München',
      'Köln',
      'Frankfurt am Main',
      'Stuttgart',
      'Düsseldorf',
      'Dortmund',
      'Essen',
      'Leipzig',
      'Bremen',
      'Dresden',
      'Hannover',
      'Nürnberg',
      'Duisburg',
      'Bochum',
      'Wuppertal',
      'Bielefeld',
      'Bonn',
      'Münster',
      'Karlsruhe',
      'Mannheim',
      'Augsburg',
      'Wiesbaden',
      'Gelsenkirchen',
      'Mönchengladbach',
      'Braunschweig',
      'Chemnitz',
      'Kiel',
      'Aachen',
      'Halle',
      'Magdeburg',
      'Freiburg',
      'Krefeld',
      'Lübeck',
      'Oberhausen',
      'Erfurt',
      'Mainz',
      'Rostock',
      'Kassel',
      'Hagen',
      'Hamm',
      'Saarbrücken',
      'Mülheim',
      'Potsdam',
      'Ludwigshafen',
      'Oldenburg',
      'Leverkusen',
      'Osnabrück',
    ],
    state: [
      'Baden-Württemberg',
      'Bayern',
      'Berlin',
      'Brandenburg',
      'Bremen',
      'Hamburg',
      'Hessen',
      'Mecklenburg-Vorpommern',
      'Niedersachsen',
      'Nordrhein-Westfalen',
      'Rheinland-Pfalz',
      'Saarland',
      'Sachsen',
      'Sachsen-Anhalt',
      'Schleswig-Holstein',
      'Thüringen',
    ],
    stateAbbr: [
      'BW',
      'BY',
      'BE',
      'BB',
      'HB',
      'HH',
      'HE',
      'MV',
      'NI',
      'NW',
      'RP',
      'SL',
      'SN',
      'ST',
      'SH',
      'TH',
    ],
    country: [
      'Deutschland',
      'Österreich',
      'Schweiz',
      'Liechtenstein',
      'Luxemburg',
      'Belgien',
      'Niederlande',
      'Frankreich',
      'Italien',
      'Polen',
      'Tschechien',
      'Dänemark',
      'Spanien',
      'Vereinigtes Königreich',
    ],
    countryCode: ['DE', 'AT', 'CH', 'LI', 'LU', 'BE', 'NL', 'FR', 'IT', 'PL', 'CZ', 'DK', 'ES', 'GB'],
    zipCode: ['#####'],
    buildingNumber: ['###', '##', '#', '####'],
    direction: ['Nord', 'Ost', 'Süd', 'West', 'Nordost', 'Nordwest', 'Südost', 'Südwest'],
    streetSuffix: [
      'Straße',
      'Weg',
      'Allee',
      'Platz',
      'Gasse',
      'Ring',
      'Damm',
      'Chaussee',
      'Ufer',
      'Pfad',
      'Promenade',
      'Boulevard',
      'Passage',
      'Zeile',
      'Hof',
      'Berg',
      'Tal',
      'Steig',
    ],
  },
  company: {
    name: [
      'TechnikAG',
      'GlobalSoft',
      'DatenSysteme',
      'CloudNetz',
      'InnovationGmbH',
      'DigitalLösungen',
      'NächsteGeneration',
      'ZukunftsTech',
      'SmartSysteme',
      'KernTech',
      'PrimeSoft',
      'AlphaTech',
      'BayernTech',
      'NordSoft',
      'OstTech',
      'WestSysteme',
      'SüdSoft',
      'RheinTech',
      'ElbeSoft',
      'DonauTech',
      'AlpenSoft',
      'HansaTech',
      'SpreeDigital',
      'IsarSoft',
      'NeckarTech',
    ],
    suffix: ['GmbH', 'AG', 'KG', 'GmbH & Co. KG', 'SE', 'UG', 'Technologies', 'Solutions', 'Systems'],
    industry: [
      'Technologie',
      'Finanzen',
      'Gesundheitswesen',
      'Bildung',
      'Einzelhandel',
      'Fertigung',
      'Telekommunikation',
      'Energie',
      'Immobilien',
      'Transport',
      'Medien',
      'Gastgewerbe',
      'Maschinenbau',
      'Automobilindustrie',
      'Pharmazie',
      'Chemie',
      'Logistik',
      'Versicherung',
    ],
    buzzwords: [
      'synergisieren',
      'nutzen',
      'innovieren',
      'revolutionieren',
      'optimieren',
      'transformieren',
      'ermächtigen',
      'ermöglichen',
      'erleichtern',
      'orchestrieren',
      'integrieren',
      'digitalisieren',
    ],
    adjective: [
      'revolutionär',
      'innovativ',
      'fortschrittlich',
      'führend',
      'erstklassig',
      'unternehmenstauglich',
      'skalierbar',
      'robust',
      'agil',
      'sicher',
      'effizient',
      'intelligent',
      'modern',
      'nachhaltig',
    ],
    descriptor: [
      'global',
      'digital',
      'cloudbasiert',
      'KI-gestützt',
      'datengesteuert',
      'benutzerzentriert',
      'automatisiert',
      'integriert',
      'vernetzt',
      'intelligent',
      'maßgeschneidert',
      'zukunftssicher',
    ],
    noun: [
      'Lösung',
      'Plattform',
      'System',
      'Dienst',
      'Technologie',
      'Framework',
      'Infrastruktur',
      'Anwendung',
      'Netzwerk',
      'Portal',
      'Ökosystem',
      'Architektur',
      'Engine',
      'Suite',
    ],
  },
  internet: {
    domainSuffix: ['de', 'com', 'net', 'org', 'eu', 'at', 'ch', 'info', 'biz'],
    freeEmail: ['gmail.com', 'gmx.de', 'web.de', 't-online.de', 'outlook.de', 'yahoo.de', 'freenet.de'],
  },
  phone: {
    formats: [
      '0###-########',
      '0###/########',
      '(0###) ########',
      '+49-###-########',
      '+49 ### ########',
    ],
  },
  food: {
    dish: ['Bratwurst', 'Schnitzel', 'Sauerkraut', 'Spätzle', 'Kartoffelsalat', 'Brezel', 'Sauerbraten', 'Rouladen', 'Eisbein', 'Currywurst', 'Döner Kebab', 'Leberkäse', 'Maultaschen', 'Flammkuchen', 'Gulasch'],
    ingredient: ['Kartoffel', 'Kohl', 'Zwiebel', 'Knoblauch', 'Tomate', 'Mehl', 'Zucker', 'Salz', 'Pfeffer', 'Butter', 'Sahne', 'Milch', 'Eier', 'Senf', 'Essig'],
    cuisine: ['Deutsch', 'Italienisch', 'Chinesisch', 'Türkisch', 'Griechisch', 'Indisch', 'Thailändisch', 'Französisch', 'Spanisch', 'Mexikanisch'],
    dessert: ['Schwarzwälder Kirschtorte', 'Apfelstrudel', 'Bienenstich', 'Käsekuchen', 'Pfannkuchen', 'Berliner', 'Lebkuchen', 'Stollen', 'Marzipan', 'Quarkbällchen'],
    fruit: ['Apfel', 'Birne', 'Erdbeere', 'Kirsche', 'Pfirsich', 'Aprikose', 'Pflaume', 'Traube', 'Orange', 'Zitrone', 'Banane'],
    vegetable: ['Tomate', 'Kartoffel', 'Zwiebel', 'Knoblauch', 'Karotte', 'Kohl', 'Gurke', 'Paprika', 'Salat', 'Spinat', 'Brokkoli'],
    meat: ['Schweinefleisch', 'Rindfleisch', 'Hähnchen', 'Lamm', 'Ente', 'Truthahn', 'Wurst', 'Schinken', 'Speck', 'Bratwurst'],
    spice: ['Pfeffer', 'Salz', 'Senf', 'Paprika', 'Kümmel', 'Muskatnuss', 'Zimt', 'Nelke', 'Petersilie', 'Schnittlauch'],
  },
  animal: {
    dog: ['Deutscher Schäferhund', 'Dackel', 'Rottweiler', 'Dobermann', 'Boxer', 'Labrador', 'Golden Retriever', 'Pudel', 'Beagle', 'Yorkshire Terrier'],
    cat: ['Perser', 'Siamkatze', 'Maine Coon', 'Britisch Kurzhaar', 'Bengal', 'Ragdoll', 'Sphynx', 'Abessinier', 'Birma', 'Russisch Blau'],
    bird: ['Adler', 'Falke', 'Eule', 'Papagei', 'Kanarienvogel', 'Sperling', 'Taube', 'Schwan', 'Ente', 'Gans'],
    fish: ['Goldfisch', 'Betta', 'Guppy', 'Neon', 'Karpfen', 'Forelle', 'Lachs', 'Thunfisch', 'Barsch', 'Hecht'],
    horse: ['Araber', 'Vollblut', 'Hannoveraner', 'Holsteiner', 'Westfale', 'Friese', 'Haflinger', 'Isländer', 'Quarter Horse'],
    rabbit: ['Zwergkaninchen', 'Löwenkopf', 'Rex', 'Angora', 'Riesenflandern', 'Widder', 'Holländer', 'Kalifornier'],
    insect: ['Schmetterling', 'Biene', 'Ameise', 'Käfer', 'Marienkäfer', 'Libelle', 'Heuschrecke', 'Grille', 'Glühwürmchen'],
    type: ['Hund', 'Katze', 'Vogel', 'Fisch', 'Kaninchen', 'Hamster', 'Meerschweinchen', 'Maus', 'Schildkröte', 'Eidechse'],
  },
  sport: {
    sport: ['Fußball', 'Basketball', 'Tennis', 'Handball', 'Schwimmen', 'Leichtathletik', 'Volleyball', 'Hockey', 'Boxen', 'Ski', 'Radfahren'],
    team: ['Bayern München', 'Borussia Dortmund', 'RB Leipzig', 'Bayer Leverkusen', 'FC Köln', 'Eintracht Frankfurt', 'Schalke 04'],
    athlete: ['Michael Schumacher', 'Boris Becker', 'Steffi Graf', 'Franz Beckenbauer', 'Dirk Nowitzki', 'Sebastian Vettel', 'Katarina Witt'],
  },
  music: {
    genre: ['Klassik', 'Rock', 'Pop', 'Schlager', 'Techno', 'Hip Hop', 'Jazz', 'Metal', 'Elektronische Musik', 'Volksmusik'],
    artist: ['Beethoven', 'Bach', 'Rammstein', 'Kraftwerk', 'Nena', 'Herbert Grönemeyer', 'Die Toten Hosen', 'Scorpions'],
    song: ['99 Luftballons', 'Wind of Change', 'Du Hast', 'Atemlos', 'Major Tom', 'Über den Wolken', 'An Tagen wie diesen'],
    instrument: ['Klavier', 'Gitarre', 'Schlagzeug', 'Bass', 'Geige', 'Saxophon', 'Trompete', 'Flöte', 'Akkordeon', 'Harfe'],
  },
  commerce: {
    product: ['Stuhl', 'Tisch', 'Lampe', 'Sofa', 'Bett', 'Schreibtisch', 'Computer', 'Telefon', 'Uhr', 'Schuhe'],
    productAdjective: ['Klein', 'Groß', 'Ergonomisch', 'Rustikal', 'Modern', 'Elegant', 'Praktisch', 'Fantastisch', 'Langlebig', 'Hochwertig'],
    productMaterial: ['Stahl', 'Holz', 'Plastik', 'Baumwolle', 'Leder', 'Glas', 'Aluminium', 'Metall', 'Seide', 'Wolle'],
    department: ['Elektronik', 'Kleidung', 'Haus und Garten', 'Sport', 'Bücher', 'Spielzeug', 'Gesundheit', 'Lebensmittel'],
    color: ['Rot', 'Blau', 'Grün', 'Gelb', 'Schwarz', 'Weiß', 'Grau', 'Rosa', 'Orange', 'Lila'],
  },
  book: {
    title: ['Der Prozess', 'Die Verwandlung', 'Faust', 'Der Steppenwolf', 'Siddhartha', 'Die Blechtrommel', 'Im Westen nichts Neues', 'Das Parfum', 'Der Vorleser', 'Effi Briest', 'Die Leiden des jungen Werthers', 'Das Glasperlenspiel', 'Buddenbrooks', 'Berlin Alexanderplatz', 'Der Zauberberg'],
    author: ['Franz Kafka', 'Johann Wolfgang von Goethe', 'Hermann Hesse', 'Thomas Mann', 'Günter Grass', 'Erich Maria Remarque', 'Patrick Süskind', 'Bernhard Schlink', 'Theodor Fontane', 'Friedrich Schiller', 'Bertolt Brecht', 'Heinrich Böll', 'Stefan Zweig', 'Robert Musil', 'Friedrich Dürrenmatt'],
    publisher: ['Suhrkamp', 'Fischer', 'Rowohlt', 'Hanser', 'dtv', 'Ullstein', 'Kiepenheuer & Witsch', 'Diogenes', 'Piper', 'Aufbau'],
    genre: ['Roman', 'Krimi', 'Thriller', 'Fantasy', 'Science-Fiction', 'Historischer Roman', 'Biografie', 'Sachbuch', 'Lyrik', 'Drama', 'Kinderbuch', 'Jugendbuch', 'Ratgeber', 'Philosophie'],
    series: ['Die Känguru-Chroniken', 'Der Herr der Ringe', 'Harry Potter', 'Das Lied von Eis und Feuer', 'Die Unendliche Geschichte', 'Die drei Fragezeichen', 'TKKG', 'Eragon'],
    review: ['Ein Meisterwerk der deutschen Literatur', 'Absolut fesselnd von Anfang bis Ende', 'Ein Muss für jeden Leser', 'Brillant geschrieben und tiefgründig', 'Unvergesslich und bewegend', 'Eines der besten Bücher, die ich je gelesen habe'],
  },
  vehicle: {
    manufacturer: ['Volkswagen', 'Mercedes-Benz', 'BMW', 'Audi', 'Porsche', 'Opel', 'Ford', 'Toyota', 'Renault', 'Peugeot', 'Fiat', 'Skoda', 'Seat', 'Volvo', 'Mazda'],
    model: ['Golf', 'Passat', 'Polo', 'Tiguan', 'A-Klasse', 'C-Klasse', 'E-Klasse', '3er', '5er', 'X3', 'A3', 'A4', 'Q5', '911', 'Cayenne', 'Corsa', 'Astra', 'Fiesta', 'Focus'],
    type: ['Limousine', 'Kombi', 'SUV', 'Coupé', 'Cabrio', 'Kleinwagen', 'Van', 'Geländewagen', 'Sportwagen', 'Kompaktklasse', 'Mittelklasse', 'Oberklasse'],
    fuel: ['Benzin', 'Diesel', 'Elektro', 'Hybrid', 'Plug-in-Hybrid', 'Erdgas', 'Autogas', 'Wasserstoff'],
    bicycle: ['Mountainbike', 'Rennrad', 'Citybike', 'E-Bike', 'BMX', 'Faltrad', 'Trekkingrad', 'Crossrad', 'Gravelbike'],
  },
  word: {
    adjective: ['gut', 'groß', 'klein', 'neu', 'alt', 'schön', 'hässlich', 'schnell', 'langsam', 'hoch', 'niedrig', 'lang', 'kurz', 'breit', 'schmal', 'dick', 'dünn', 'schwer', 'leicht', 'hell', 'dunkel', 'warm', 'kalt', 'hart', 'weich', 'laut', 'leise', 'stark', 'schwach', 'reich', 'arm', 'gesund', 'krank', 'jung', 'alt', 'klug', 'dumm', 'fleißig', 'faul'],
    adverb: ['sehr', 'gut', 'schlecht', 'schnell', 'langsam', 'oft', 'selten', 'immer', 'nie', 'manchmal', 'heute', 'gestern', 'morgen', 'jetzt', 'später', 'früher', 'hier', 'dort', 'oben', 'unten', 'vorne', 'hinten', 'links', 'rechts', 'gerne', 'ungern', 'vielleicht', 'bestimmt', 'wahrscheinlich'],
    conjunction: ['und', 'oder', 'aber', 'denn', 'sondern', 'weil', 'dass', 'ob', 'wenn', 'als', 'während', 'bevor', 'nachdem', 'obwohl', 'damit', 'sodass', 'falls', 'sobald'],
    interjection: ['ach', 'oh', 'ah', 'hey', 'hallo', 'tschüss', 'ja', 'nein', 'autsch', 'hurra', 'pfui', 'pst', 'bravo', 'hoppla', 'oje'],
    noun: ['Haus', 'Baum', 'Tisch', 'Stuhl', 'Buch', 'Auto', 'Hund', 'Katze', 'Mann', 'Frau', 'Kind', 'Wasser', 'Feuer', 'Luft', 'Erde', 'Sonne', 'Mond', 'Stern', 'Berg', 'Fluss', 'See', 'Meer', 'Stadt', 'Dorf', 'Straße', 'Weg', 'Tür', 'Fenster', 'Garten', 'Blume'],
    preposition: ['in', 'an', 'auf', 'über', 'unter', 'vor', 'hinter', 'neben', 'zwischen', 'bei', 'von', 'zu', 'nach', 'aus', 'mit', 'ohne', 'durch', 'für', 'gegen', 'um', 'seit', 'während', 'bis', 'wegen', 'trotz'],
    verb: ['sein', 'haben', 'werden', 'können', 'müssen', 'sollen', 'wollen', 'dürfen', 'mögen', 'machen', 'gehen', 'kommen', 'sehen', 'sagen', 'geben', 'nehmen', 'finden', 'wissen', 'denken', 'glauben', 'leben', 'arbeiten', 'spielen', 'essen', 'trinken', 'schlafen', 'laufen', 'fahren', 'liegen', 'stehen'],
  },
  hacker: {
    abbreviation: ['TCP', 'IP', 'HTTP', 'HTTPS', 'FTP', 'SSH', 'SSL', 'TLS', 'DNS', 'VPN', 'API', 'SQL', 'HTML', 'CSS', 'JS', 'PHP', 'RAM', 'ROM', 'CPU', 'GPU', 'SSD', 'HDD', 'USB', 'LAN', 'WAN', 'WLAN', 'IoT', 'AI', 'ML'],
    adjective: ['digital', 'virtuell', 'verschlüsselt', 'entschlüsselt', 'sicher', 'unsicher', 'online', 'offline', 'drahtlos', 'kabelgebunden', 'lokal', 'remote', 'automatisiert', 'manuell', 'synchron', 'asynchron', 'öffentlich', 'privat'],
    noun: ['Protokoll', 'Algorithmus', 'Schnittstelle', 'Server', 'Client', 'Netzwerk', 'System', 'Prozess', 'Thread', 'Cache', 'Buffer', 'Socket', 'Port', 'Paket', 'Firewall', 'Router', 'Switch', 'Virus', 'Malware', 'Exploit', 'Patch', 'Bug', 'Pixel', 'Byte', 'Bit'],
    verb: ['kompilieren', 'ausführen', 'debuggen', 'verschlüsseln', 'entschlüsseln', 'hashen', 'authentifizieren', 'autorisieren', 'verbinden', 'trennen', 'herunterladen', 'hochladen', 'synchronisieren', 'sichern', 'wiederherstellen', 'scannen', 'monitoren', 'deployen', 'patchen'],
    ingverb: ['kompilierend', 'ausführend', 'debuggend', 'verschlüsselnd', 'entschlüsselnd', 'hashend', 'authentifizierend', 'autorisierend', 'verbindend', 'trennend', 'herunterladend', 'hochladend', 'synchronisierend', 'sichernd', 'wiederherstellend', 'scannend', 'monitorend', 'deployend', 'patchend'],
    phrase: ['Sicherheitslücke erkannt', 'Zugriff verweigert', 'Verbindung hergestellt', 'Server kompromittiert', 'Daten exfiltriert', 'Firewall umgangen', 'Exploit erfolgreich', 'System gehackt', 'Zero-Day-Schwachstelle', 'SQL-Injection erfolgreich', 'Reverse-Shell aktiv'],
  },
  system: {
    fileName: ['dokument', 'bericht', 'präsentation', 'tabelle', 'bild', 'video', 'audio', 'archiv', 'backup', 'daten', 'konfiguration', 'einstellungen', 'log', 'cache', 'projekt', 'entwurf', 'final', 'version'],
    fileType: ['audio', 'bild', 'text', 'video', 'anwendung', 'dokument', 'tabelle', 'präsentation', 'archiv', 'code'],
  },
  science: {
    chemicalElement: ['Wasserstoff', 'Helium', 'Lithium', 'Kohlenstoff', 'Stickstoff', 'Sauerstoff', 'Fluor', 'Neon', 'Natrium', 'Magnesium', 'Aluminium', 'Silizium', 'Phosphor', 'Schwefel', 'Chlor', 'Eisen', 'Kupfer', 'Zink', 'Silber', 'Gold', 'Quecksilber', 'Blei', 'Uran', 'Plutonium'],
    unit: ['Meter', 'Kilogramm', 'Sekunde', 'Ampere', 'Kelvin', 'Mol', 'Candela', 'Newton', 'Pascal', 'Joule', 'Watt', 'Volt', 'Ohm', 'Hertz', 'Celsius', 'Liter', 'Gramm'],
    constant: ['Lichtgeschwindigkeit', 'Gravitationskonstante', 'Plancksches Wirkungsquantum', 'Boltzmann-Konstante', 'Avogadro-Konstante', 'Elementarladung', 'Gaskonstante'],
    field: ['Physik', 'Chemie', 'Biologie', 'Astronomie', 'Geologie', 'Ökologie', 'Genetik', 'Neurowissenschaft', 'Biochemie', 'Mikrobiologie', 'Botanik', 'Zoologie', 'Mathematik', 'Informatik'],
  },
}
