import type { LocaleDefinition } from '@stacksjs/ts-faker'

export const fi: LocaleDefinition = {
  title: 'Finnish',
  person: {
    firstNameMale: [
      'Juhani',
      'Johannes',
      'Olavi',
      'Antero',
      'Tapani',
      'Kalevi',
      'Jari',
      'Matti',
      'Mikael',
      'Petri',
      'Timo',
      'Mika',
      'Juha',
      'Pekka',
      'Markku',
      'Marko',
      'Ville',
      'Jukka',
      'Antti',
      'Sami',
      'Oskari',
      'Eetu',
      'Onni',
      'Väinö',
      'Elias',
      'Leo',
      'Aleksi',
      'Oliver',
      'Eino',
      'Aatos',
      'Aarne',
      'Pentti',
      'Veikko',
      'Tapio',
      'Hannu',
      'Kari',
      'Seppo',
      'Jukka',
      'Heikki',
      'Risto',
      'Joonas',
      'Matias',
      'Lauri',
      'Valtteri',
      'Joona',
      'Rasmus',
      'Julius',
      'Emil',
      'Leevi',
      'Niko',
    ],
    firstNameFemale: [
      'Maria',
      'Helena',
      'Johanna',
      'Anneli',
      'Kaarina',
      'Marjatta',
      'Pirjo',
      'Sari',
      'Päivi',
      'Tarja',
      'Anne',
      'Marja',
      'Leena',
      'Minna',
      'Liisa',
      'Tuula',
      'Eeva',
      'Katri',
      'Anna',
      'Hanna',
      'Sofia',
      'Emilia',
      'Aino',
      'Helmi',
      'Olivia',
      'Emma',
      'Isla',
      'Lilja',
      'Elli',
      'Venla',
      'Aada',
      'Ellen',
      'Iida',
      'Linnea',
      'Pihla',
      'Siiri',
      'Viivi',
      'Ella',
      'Alma',
      'Amanda',
      'Sanni',
      'Sara',
      'Laura',
      'Katja',
      'Riikka',
      'Susanna',
      'Jenni',
      'Maija',
      'Pauliina',
      'Tiina',
    ],
    firstNameNeutral: [
      'Kalle',
      'Sade',
      'Lumikki',
      'Suvi',
      'Pilvi',
      'Varpu',
      'Taika',
      'Lumi',
      'Aurinko',
      'Tuuli',
    ],
    lastName: ['Korhonen', 'Virtanen', 'Mäkinen', 'Nieminen', 'Mäkelä', 'Hämäläinen', 'Laine', 'Heikkilä', 'Koskinen', 'Järvinen', 'Lehtonen', 'Lehtinen', 'Saarinen', 'Salminen', 'Heinonen', 'Niemi', 'Heikkinen', 'Kinnunen', 'Salonen', 'Tuominen', 'Laitinen', 'Turunen', 'Mattila', 'Rinne', 'Karjalainen', 'Savolainen', 'Laaksonen', 'Ahonen', 'Ojala', 'Kallio', 'Rantanen', 'Vanhanen', 'Repo', 'Seppälä', 'Nurmi', 'Leppänen', 'Ruotsalainen', 'Haapala', 'Aho', 'Toivonen'],
    prefix: ['Herra', 'Rouva', 'Neiti', 'Tri', 'Prof.', 'Ins.', 'Arkkitehti'],
    suffix: ['nuorempi', 'vanhempi', 'II', 'III', 'IV'],
    gender: ['Mies', 'Nainen', 'Muu'],
    jobTitle: ['Ohjelmistokehittäjä', 'Projektipäällikkö', 'Suunnittelija', 'Markkinointipäällikkö', 'Myyntipäällikkö', 'Kirjanpitäjä', 'Lakimies', 'Lääkäri', 'Sairaanhoitaja', 'Opettaja', 'Professori', 'Tutkija', 'Data-analyytikko', 'Tuotepäällikkö', 'HR-päällikkö', 'Konsultti', 'Arkkitehti', 'Insinööri', 'Teknikko', 'Kokki', 'Kirjailija', 'Toimittaja', 'Valokuvaaja', 'Taiteilija', 'Muusikko'],
  },
  address: {
    street: ['Mannerheimintie', 'Hämeentie', 'Aleksanterinkatu', 'Esplanadi', 'Pohjoisesplanadi', 'Eteläesplanadi', 'Unioninkatu', 'Bulevardi', 'Iso Roobertinkatu', 'Fredrikinkatu', 'Annankatu', 'Mechelininkatu', 'Runeberginkatu', 'Töölönkatu', 'Kallio', 'Sörnäinen', 'Vallila', 'Pasila', 'Kamppi', 'Punavuori', 'Eira', 'Ullanlinna', 'Kruununhaka', 'Katajanokka', 'Hakaniemi', 'Kalasatama', 'Jätkäsaari', 'Lauttasaari', 'Munkkiniemi', 'Pitäjänmäki'],
    city: ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu', 'Turku', 'Jyväskylä', 'Lahti', 'Kuopio', 'Pori', 'Kouvola', 'Joensuu', 'Lappeenranta', 'Hämeenlinna', 'Vaasa', 'Seinäjoki', 'Rovaniemi', 'Mikkeli', 'Kotka', 'Salo', 'Porvoo', 'Kokkola', 'Hyvinkää', 'Lohja', 'Järvenpää', 'Rauma', 'Kirkkonummi', 'Kajaani', 'Kerava', 'Savonlinna'],
    state: ['Uusimaa', 'Varsinais-Suomi', 'Satakunta', 'Kanta-Häme', 'Pirkanmaa', 'Päijät-Häme', 'Kymenlaakso', 'Etelä-Karjala', 'Etelä-Savo', 'Pohjois-Savo', 'Pohjois-Karjala', 'Keski-Suomi', 'Etelä-Pohjanmaa', 'Pohjanmaa', 'Keski-Pohjanmaa', 'Pohjois-Pohjanmaa', 'Kainuu', 'Lappi', 'Ahvenanmaa'],
    country: ['Suomi', 'Ruotsi', 'Norja', 'Viro', 'Venäjä'],
    zipCode: ['#####'],
    direction: ['Pohjoinen', 'Etelä', 'Itä', 'Länsi', 'Koillinen', 'Luode', 'Kaakko', 'Lounas'],
  },
  company: {
    name: ['Nokia', 'Rovio', 'Supercell', 'Kone', 'Wärtsilä', 'UPM', 'Stora Enso', 'Neste', 'Fortum', 'Kesko', 'S-ryhmä', 'K-ryhmä', 'Nordea', 'OP', 'Sampo', 'Finnair', 'Wolt', 'Fazer', 'Valio', 'Fiskars', 'Marimekko', 'Iittala', 'Arabia', 'Moomin', 'Angry Birds', 'Linux', 'MySQL', 'SSH', 'Sisu Auto', 'Valmet'],
    suffix: ['Oy', 'Oyj', 'Ab', 'Oy Ab', 'Tmi', 'Ky', 'Ay', 'Osuuskunta', 'Yhdistys', 'Säätiö'],
    industry: ['Teknologia', 'Metsäteollisuus', 'Metalliteollisuus', 'Telekommunikaatio', 'Pelit', 'Energia', 'Kaivostoiminta', 'Elintarvike', 'Kauppa', 'Pankki', 'Vakuutus', 'Matkailu', 'Hotelli', 'Ravintola', 'Kuljetus', 'Logistiikka', 'Rakentaminen', 'Kiinteistö', 'Terveydenhuolto', 'Koulutus', 'Media', 'Mainonta', 'Konsultointi', 'Muotoilu', 'Valmistus'],
    buzzword: ['innovaatio', 'kestävyys', 'digitalisaatio', 'murros', 'automaatio', 'tekoäly', 'data-analytiikka', 'pilvi', 'IoT', 'keikkatalous', 'jakamistalous', 'alustatalous', 'startup', 'scale-up', 'yksisarvinen', 'häiriö', 'ketterä', 'lean', 'scrum', 'DevOps', 'fintech', 'cleantech', 'biotech', 'medtech', 'sähköistäminen'],
    adjective: ['innovatiivinen', 'kestävä', 'digitaalinen', 'ketterä', 'tehokas', 'luotettava', 'dynaaminen', 'moderni', 'edistykselliinen', 'huipputason'],
    descriptor: ['ratkaisu', 'palvelu', 'tuote', 'järjestelmä', 'alusta', 'sovellus', 'teknologia', 'konsepti', 'verkosto', 'ekosysteemi'],
    noun: ['liiketoiminta', 'innovaatio', 'tulevaisuus', 'kumppani', 'asiakas', 'yhteistyö', 'menestys', 'kasvu', 'kehitys', 'mahdollisuus'],
    buzzwords: ['innovaatio', 'kestävyys', 'digitalisaatio', 'murros', 'automaatio', 'tekoäly', 'data-analytiikka', 'pilvi', 'IoT', 'synergy', 'disruptio', 'transformaatio', 'optimointi', 'skalaus', 'ketteryys'],
  },
  internet: {
    domainName: ['yle.fi', 'hs.fi', 'is.fi', 'iltalehti.fi', 'mtv.fi', 'suomi24.fi', 'tori.fi', 'huuto.net', 'oikotie.fi', 'etuovi.com', 'fonecta.fi', 'sanomalehdet.fi', 'vauva.fi', 'tekniikkatalous.fi', 'kauppalehti.fi', 'talouselama.fi', 'taloussanomat.fi', 'suomenpankki.fi', 'vero.fi', 'kela.fi', 'te-palvelut.fi', 'mol.fi', 'traficom.fi', 'tulli.fi'],
    domainSuffix: ['.fi', '.com', '.net', '.org'],
    freeEmail: ['gmail.com', 'outlook.com', 'hotmail.com', 'yahoo.com', 'icloud.com', 'proton.me'],
  },
  phone: {
    number: ['09-### ####', '040-### ####', '050-### ####', '+358 9 ### ####', '+358 40 ### ####', '09-########', '040-#######'],
  },
  food: {
    dish: ['Karjalanpiirakka', 'Kalakukko', 'Poronkäristys', 'Lohikeitto', 'Hernekeitto', 'Mustamakkara', 'Siskonmakkara', 'Leipäjuusto', 'Graavilohi', 'Mämmi', 'Ruisleipä', 'Karelian stew', 'Riisipuuro', 'Lanttulaatikko', 'Perunalaatikko', 'Porkkanalaatikko', 'Rosolli', 'Silakka', 'Muikku', 'Lohipiirakka', 'Karjalanpaisti', 'Maksalaatikko', 'Lihapullat', 'Lihasoppa', 'Kesäkeitto', 'Pinaattiohukaiset', 'Pannukakku', 'Munkit', 'Pulla', 'Korvapuusti'],
    ingredient: ['Lohi', 'Siika', 'Muikku', 'Hauki', 'Ahven', 'Poronliha', 'Hirvenliha', 'Karjalanpiirakka', 'Ruisjauhot', 'Vehnäjauhot', 'Peruna', 'Porkkana', 'Lanttu', 'Sipuli', 'Kerma', 'Voi', 'Maito', 'Piimä', 'Viili', 'Juusto', 'Muna', 'Puolukka', 'Mustikka', 'Lakka', 'Vadelma', 'Mansikka', 'Tyrni', 'Mesimarja', 'Karpalo', 'Tilli'],
    cuisine: ['Suomalainen', 'Skandinaavinen', 'Italialainen', 'Ranskalainen', 'Aasialainen', 'Thaimaalainen', 'Intialainen', 'Kiinalainen', 'Japanilainen', 'Meksikolainen', 'Amerikkalainen', 'Kreikkalainen', 'Turkkilainen', 'Espanjalainen', 'Kasvisruoka', 'Vegaaninen', 'Gluteeniton', 'Äyriäisruoka', 'Grillaus', 'Kotiruoka'],
    dessert: ['Mustikkapiirakka', 'Vadelmapiirakka', 'Omenapiirakka', 'Karjalanpiirakka', 'Korvapuusti', 'Pulla', 'Munkki', 'Voisilmäpulla', 'Pannukakku', 'Letut', 'Vohvelit', 'Jäätelö', 'Rahkapiirakka', 'Marjapiirakka', 'Puolukkapiirakka', 'Mustikkakiisseli', 'Marjakiisseli', 'Mansikkakakku', 'Kinuski', 'Lakritsi'],
    fruit: ['Omena', 'Päärynä', 'Luumu', 'Kirsikka', 'Mansikka', 'Vadelma', 'Mustikka', 'Puolukka', 'Lakka', 'Karpalo', 'Mesimarja', 'Tyrni', 'Herukat', 'Karviainen', 'Banaani', 'Appelsiini', 'Sitruuna', 'Mango', 'Ananas', 'Viinirypäleet', 'Vesimeloni', 'Kiivi'],
    vegetable: ['Peruna', 'Porkkana', 'Lanttu', 'Nauris', 'Valkokaali', 'Kukkakaali', 'Parsakaali', 'Ruusukaali', 'Sipuli', 'Valkosipuli', 'Purjosipuli', 'Selleri', 'Paprika', 'Tomaatti', 'Kurkku', 'Salaatti', 'Pinaatti', 'Lehtikaali', 'Kesäkurpitsa', 'Kurpitsa', 'Herne', 'Papu', 'Maissi', 'Retiisi', 'Parsa', 'Sieni'],
    meat: ['Lammas', 'Sianliha', 'Naudanliha', 'Kana', 'Kalkkuna', 'Ankka', 'Hirvi', 'Poro', 'Kauris', 'Villisika', 'Kotletti', 'Pihvi', 'Filee', 'Ulkofilee', 'Sisäfilee', 'Kylki', 'Jauheliha', 'Makkara', 'Kinkku', 'Pekoni'],
    spice: ['Suola', 'Pippuri', 'Curry', 'Paprika', 'Chili', 'Inkivääri', 'Valkosipuli', 'Sipuli', 'Persilja', 'Tilli', 'Timjami', 'Rosmariini', 'Basilika', 'Oregano', 'Muskottipähkinä', 'Neilikka', 'Kardemumma', 'Kaneli', 'Vanilja', 'Laakerinlehti'],
  },
  animal: {
    dog: ['Suomenpystykorva', 'Karjalankarhukoira', 'Lapinporokoira', 'Suomenlapinkoira', 'Suomenajokoira', 'Suomenpystykorva', 'Labradorinnoutaja', 'Golden retriever', 'Saksanpaimenkoira', 'Rottweiler', 'Bokseri', 'Beagle', 'Cockerspanieli', 'Jack Russell terrieri', 'Bordercollie', 'Sheltie', 'Cavalier King Charles spanieli', 'Chihuahua', 'Villakoira', 'Yorkshirenterrieri', 'Bichon frisé', 'Mopsi'],
    cat: ['Kotikissa', 'Persialainen', 'Maine coon', 'Ragdoll', 'Birma', 'Siamilainen', 'Bengalikissa', 'Abessinialainen', 'Venäjänsininen', 'Sphynx', 'British shorthair', 'Scottish fold', 'Burmalainen', 'Chartreaux', 'Devon rex', 'Cornish rex', 'Singapura', 'Tonkinilainen', 'Korat', 'Eurooppalainen lyhytkarva'],
    bird: ['Lokki', 'Tiira', 'Merimetso', 'Haikara', 'Joutsen', 'Hanhi', 'Sorsa', 'Kurki', 'Kattohaikara', 'Tikka', 'Kiuru', 'Rastas', 'Kottarainen', 'Varis', 'Harakka', 'Pähkinänakkeli', 'Sinitiainen', 'Talitiainen', 'Punatulkku', 'Viherpeippo', 'Keltasirkku', 'Peippo', 'Punarinta', 'Västäräkki', 'Tuulihaukka'],
    fish: ['Ahven', 'Hauki', 'Kuha', 'Lahna', 'Siika', 'Nieriä', 'Taimen', 'Lohi', 'Turska', 'Seiti', 'Kolja', 'Silli', 'Silakka', 'Makrilli', 'Tonnikala', 'Kampela', 'Punakampela', 'Piikkinilkka', 'Ankerias', 'Särkikala', 'Särki', 'Säyne', 'Salakka', 'Kivinilkka', 'Hauen'],
    horse: ['Suomenhevonen', 'Islanninhevonen', 'Shetlanninponi', 'Walesinponi', 'Arabialainen', 'Täysiverinen', 'Lipitsalainen', 'Friisiläinen', 'Andalusialainen', 'Hannoverinhevonen', 'Oldenburginhevonen', 'Trakehner', 'Holsteiner', 'Westfal', 'KWPN'],
    rabbit: ['Kotikaniini', 'Villakaniini', 'Jänis', 'Kääpiökaniini', 'Leijonankääpiökaniini', 'Angora', 'Rex', 'Lop', 'Chinchilla', 'Fläminläisjätti', 'Himalaja', 'Hollannin lop', 'Minilop', 'Hollannin kääpiö', 'Ranskan widder'],
    insect: ['Perhonen', 'Sudenkorento', 'Heinäsirkka', 'Kovakuoriainen', 'Kimalainen', 'Mehiläinen', 'Ampiainen', 'Muurahainen', 'Punkki', 'Hämähäkki', 'Hyttynen', 'Kärpänen', 'Mäkäräinen', 'Täi', 'Kirppu', 'Korvamato', 'Päivänkorento', 'Leppäkerttu', 'Koi', 'Toukka'],
  },
  sport: {
    sport: ['Jalkapallo', 'Jääkiekko', 'Käsipallo', 'Salibandy', 'Murtomaahiihto', 'Ampumahiihto', 'Alppihiihto', 'Mäkihyppy', 'Lumilautailu', 'Yleisurheilu', 'Uinti', 'Pyöräily', 'Golf', 'Tennis', 'Lentopallo', 'Koripallo', 'Pöytätennis', 'Sulkapallo', 'Kiipeily', 'Purjehdus', 'Soutu', 'Melonta', 'Paini', 'Suunnistus', 'Pesäpallo'],
    team: ['HJK', 'FC Inter', 'HIFK', 'FC Honka', 'KuPS', 'IFK Mariehamn', 'SJK', 'VPS', 'Ilves', 'TPS', 'KTP', 'RoPS', 'HIFK', 'Tappara', 'Kärpät', 'Lukko', 'JYP', 'Pelicans', 'SaiPa', 'Sport'],
    athlete: ['Teemu Selänne', 'Jari Kurri', 'Saku Koivu', 'Jari Litmanen', 'Sami Hyypiä', 'Paavo Nurmi', 'Lasse Virén', 'Mika Häkkinen', 'Kimi Räikkönen', 'Valtteri Bottas', 'Kaisa Mäkäräinen', 'Krista Pärmäkoski', 'Iivo Niskanen', 'Matti Nykänen', 'Janne Ahonen', 'Toni Nieminen', 'Mika Myllylä', 'Juha Mieto', 'Eero Mäntyranta', 'Veikko Hakulinen'],
  },
  music: {
    genre: ['Pop', 'Rock', 'Iskelmä', 'Elektroninen', 'Hip-hop', 'Jazz', 'Klassinen', 'Kansanmusiikki', 'Country', 'Blues', 'Metalli', 'Punk', 'Indie', 'R&B', 'Soul', 'Reggae', 'Tekno', 'House', 'Trance', 'Drum and bass', 'Dubstep', 'Tango', 'Humppa', 'EDM', 'Ambient'],
    artist: ['Nightwish', 'HIM', 'The Rasmus', 'Apocalyptica', 'Children of Bodom', 'Sonata Arctica', 'Stratovarius', 'Poets of the Fall', 'Darude', 'Bomfunk MCs', 'Eläkeläiset', 'Leevi and the Leavings', 'Eppu Normaali', 'CMX', 'Juice Leskinen', 'Olavi Virta', 'Katri Helena', 'Vesa-Matti Loiri', 'Jari Sillanpää', 'Jenni Vartiainen', 'Antti Tuisku', 'Alma', 'Vesala', 'Chisu', 'Robin'],
    song: ['Sandstorm', 'Freestyler', 'Nemo', 'Wish I Had an Angel', 'In the Shadows', 'First Day of My Life', 'Unforgivable Sinner', 'I Walk Alone', 'Levoton tuhkimo', 'Ihmisten edessä', 'Hölmö rakkaus', 'Kädet siipinä', 'Sinä lähdit pois', 'Satumaa', 'Kuin kaksi puuta', 'Surun pyyhit silmistäni', 'Vanhat pojat', 'Karjalan kunnailla', 'Finlandia', 'Ievan polkka'],
    instrument: ['Kitara', 'Basso', 'Rummut', 'Piano', 'Koskettimet', 'Syntetisaattori', 'Viulu', 'Sello', 'Alttoviulu', 'Kontrabasso', 'Huilu', 'Klarinetti', 'Oboe', 'Fagotti', 'Saksofoni', 'Trumpetti', 'Pasuuna', 'Tuuba', 'Käyrätorvi', 'Harmonikka', 'Huuliharppu', 'Ukulele', 'Mandoliini', 'Kantele', 'Harmonikka'],
  },
  commerce: {
    productName: ['Älypuhelin', 'Kannettava', 'Tabletti', 'Kuulokkeet', 'Kaiutin', 'Hiiri', 'Näppäimistö', 'Näyttö', 'Verkkokamera', 'Laturi', 'Kaapeli', 'Varavirtalähde', 'Älykello', 'Kengät', 'Laukku', 'Lompakko', 'Vyö', 'Kello', 'Aurinkolasit', 'Lippalakki', 'T-paita', 'Huppari', 'Farkut', 'Takki', 'Päällystakki'],
    productAdjective: ['Älykäs', 'Premium', 'Luksus', 'Paras', 'Suosittu', 'Uusi', 'Rajoitettu', 'Tarjous', 'Alennus', 'Ale', 'Suositeltu', 'Bestseller', 'Uutuus', 'Viimeisin', 'Eksklusiivinen', 'Käytännöllinen', 'Edullinen', 'Tuotemerkki', 'Alkuperäinen', 'Tuonti', 'Suomalainen', 'Ympäristöystävällinen', 'Ilmainen toimitus', 'Toimitus samana päivänä'],
    productMaterial: ['Nahka', 'Puuvilla', 'Polyesteri', 'Nailon', 'Silikoni', 'Muovi', 'Metalli', 'Ruostumaton teräs', 'Alumiini', 'Titaani', 'Keramiikka', 'Lasi', 'Puu', 'Bambu', 'Paperi', 'Kumi', 'Vaahto', 'Lateksi', 'Villa', 'Kashmir'],
    department: ['Elektroniikka', 'Vaatteet', 'Kauneus', 'Ruoka ja terveys', 'Koti ja keittiö', 'Huonekalut', 'Urheilu', 'Kirjat', 'Lelut', 'Digitaalinen', 'Vauva', 'Lemmikki', 'Auto', 'Työkalut', 'Matkailu', 'Lahjat', 'Lapset', 'Tietokone ja pelit', 'Valokuvaus ja ääni', 'Korut'],
    color: ['Punainen', 'Oranssi', 'Keltainen', 'Vihreä', 'Sininen', 'Violetti', 'Vaaleanpunainen', 'Musta', 'Valkoinen', 'Harmaa', 'Ruskea', 'Beige', 'Laivastonsininen', 'Khaki', 'Minttu', 'Laventeli', 'Koralli', 'Burgundy', 'Viininpunainen', 'Kermanvärinen'],
  },
  book: {
    title: ['Tuntematon sotilas', 'Seitsemän veljestä', 'Sinuhe egyptiläinen', 'Täällä Pohjantähden alla', 'Kalevala', 'Sota ja rauha', 'Rikos ja rangaistus', 'Anna Karenina', 'Vieras mies', 'Tie tähtiin', 'Maa-ilma', 'Myrskyluodon Maija', 'Jäähyväiset aseille', 'Vanha mies ja meri', 'Auringon valtakunta', 'Kuolema Venetsiassa', 'Buddenbrookit', 'Vuosikymmenen tarina', 'Pariisin Notre Dame', 'Köyhät syntiset ihmiset'],
    author: ['Väinö Linna', 'Aleksis Kivi', 'Mika Waltari', 'F.E. Sillanpää', 'Frans Eemil Sillanpää', 'Elias Lönnrot', 'Sofi Oksanen', 'Arto Paasilinna', 'Kalle Päätalo', 'Tove Jansson', 'Eino Leino', 'Juhani Aho', 'Joel Lehtonen', 'Veijo Meri', 'Paavo Haavikko', 'Pentti Saarikoski', 'Hannu Salama', 'Antti Tuuri', 'Leena Lander', 'Kjell Westö'],
    publisher: ['WSOY', 'Otava', 'Tammi', 'Siltala', 'Like', 'Atena', 'Karisto', 'Gummerus', 'Minerva', 'Into', 'Readme.fi', 'Art House', 'Kumma', 'Kosmos', 'Aviador'],
    genre: ['Romaani', 'Dekkari', 'Trilleri', 'Fantasia', 'Tieteiskirjallisuus', 'Historiallinen', 'Elämäkerta', 'Runous', 'Essee', 'Tietokirja', 'Omaelämäkerta', 'Matkakertomus', 'Keittokirja', 'Terveys', 'Lapset', 'Nuoret', 'Sarjakuva', 'Huumori', 'Draama', 'Tietokirja'],
    series: ['Muumilaakso', 'Tuntematon sotilas', 'Täällä Pohjantähden alla', 'Ihmiskunnan taru', 'Kotikatu', 'Seitsemän veljestä', 'Komisario Palmu', 'Raid', 'Vares', 'Keisari Aarnio', 'Panu Makkonen', 'Risto Räppääjä', 'Tatu ja Patu', 'Ella', 'Tiitus', 'Peppi Pitkätossu', 'Harry Potter', 'Taru sormusten herrasta', 'Nälkäpeli', 'Hobitti'],
    review: ['Erittäin suositeltava', 'Fantastinen', 'Pakko lukea', 'Koskettava', 'Unohtumaton', 'Vangitseva', 'Mestariteos', 'Loistava', 'Vankka', 'Viihdyttävä', 'Jännittävä', 'Hauska', 'Surullinen', 'Ajatuksia herättävä', 'Vaikuttava', 'Mielenkiintoinen', 'Tylsä', 'Sekava', 'Yllättävä'],
  },
  vehicle: {
    manufacturer: ['Valmet Automotive', 'Sisu Auto', 'Saab', 'Volvo', 'Tesla', 'Volkswagen', 'BMW', 'Mercedes-Benz', 'Audi', 'Toyota', 'Nissan', 'Kia', 'Hyundai', 'Ford', 'Peugeot', 'Renault', 'Skoda', 'Mazda', 'Honda', 'Mitsubishi', 'Subaru', 'Jaguar', 'Land Rover', 'Porsche', 'Polestar'],
    model: ['V60', 'V90', 'XC40', 'XC60', 'XC90', 'Model 3', 'Model Y', 'ID.4', 'e-Golf', 'i3', 'iX3', 'EQC', 'e-tron', 'Leaf', 'Ariya', 'e-Niro', 'Kona Electric', 'Ioniq 5', 'Mach-E', 'e-208', 'Zoe', 'Enyaq', 'MX-30', 'e', 'bZ4X'],
    type: ['Sedan', 'Maastoauto', 'Farmari', 'Coupé', 'Avoauto', 'Pakettiauto', 'Pickup', 'Urheiluauto', 'Sähköauto', 'Hybridi', 'Ladattava hybridi', 'Vetysähköauto', 'Pikkuauto', 'Keskiluokka', 'Iso', 'Pieni maastoauto', 'Keskikokoinen maastoauto', 'Iso maastoauto', 'Tila-auto', 'Lavetti'],
    fuel: ['Bensiini', 'Diesel', 'Sähkö', 'Vety', 'Hybridi', 'Ladattava hybridi', 'Biodiesel', 'Etanoli', 'Kaasu', 'Biokaasu'],
    bicycle: ['Maastopyörä', 'Maantie', 'Hybridi', 'Kaupunkipyörä', 'BMX', 'Fixie', 'Cruiser', 'Sähköpyörä', 'Taitettava pyörä', 'Lasten pyörä', 'Touring', 'Gravel', 'Cyclocross', 'Rata', 'Selkänoja', 'Tandem', 'Kolmipyörä', 'Potkupyörä', 'Sähköpotkulauta', 'Lastenpyörä'],
  },
  word: {
    adjective: ['kaunis', 'suuri', 'pieni', 'hyvä', 'huono', 'nopea', 'hidas', 'korkea', 'matala', 'uusi', 'vanha', 'lämmin', 'kylmä', 'valoisa', 'pimeä', 'iloinen', 'surullinen', 'onnellinen', 'vihainen', 'peloissaan', 'rohkea', 'vahva', 'heikko', 'älykäs', 'tyhmä', 'hieno', 'ruma', 'puhdas', 'likainen', 'rikas'],
    adverb: ['nopeasti', 'hitaasti', 'hiljaa', 'äänekkäästi', 'matalasti', 'paljon', 'vähän', 'aina', 'ei koskaan', 'usein', 'harvoin', 'ehkä', 'varmasti', 'todella', 'hyvin', 'melko', 'vähän', 'äärimmäisen', 'melkein', 'noin', 'juuri', 'yhtäkkiä', 'vähitellen', 'välittömästi', 'heti', 'myöhemmin', 'aikaisemmin', 'nyt', 'silloin'],
    conjunction: ['ja', 'tai', 'mutta', 'kuitenkin', 'koska', 'jos', 'kun', 'samalla kun', 'sen jälkeen', 'vaikka', 'joko', 'sekä', 'niin', 'siksi', 'näin ollen', 'silti', 'kuitenkin', 'lisäksi', 'sitä vastoin', 'nimittäin'],
    interjection: ['Oi', 'Oho', 'Ai', 'Uh', 'Puh', 'Hurraa', 'Jaa', 'Jaha', 'No niin', 'Hyi', 'Hei', 'Ha', 'Hmm', 'Joo', 'Ei', 'Kyllä', 'Jestas', 'Äh', 'Voi', 'Hups'],
    noun: ['henkilö', 'talo', 'puu', 'kukka', 'vesi', 'tuli', 'tuuli', 'taivas', 'maa', 'vuori', 'joki', 'meri', 'aurinko', 'kuu', 'tähti', 'pilvi', 'sade', 'lumi', 'ukkonen', 'salama', 'kirja', 'koulu', 'opettaja', 'opiskelija', 'ystävä', 'perhe', 'isä', 'äiti', 'sisko', 'veli'],
    preposition: ['sisällä', 'päällä', 'luokse', 'luota', 'kanssa', 'ilman', 'varten', 'yli', 'alla', 'vieressä', 'luona', 'välillä', 'joukossa', 'kautta', 'ympäri', 'kohti', 'noin', 'jälkeen', 'ennen'],
    verb: ['mennä', 'tulla', 'syödä', 'juoda', 'nukkua', 'herätä', 'istua', 'seistä', 'maata', 'juosta', 'hypätä', 'puhua', 'kuunnella', 'nähdä', 'lukea', 'kirjoittaa', 'oppia', 'opettaa', 'ajatella', 'tietää', 'tuntea', 'pitää', 'rakastaa', 'vihata', 'nauraa', 'itkeä', 'leikkiä', 'työskennellä', 'levätä'],
  },
  hacker: {
    abbreviation: ['AI', 'ML', 'IoT', 'API', 'SDK', 'IDE', 'OS', 'DB', 'SQL', 'HTTP', 'HTTPS', 'REST', 'JSON', 'XML', 'HTML', 'CSS', 'JS', 'UI', 'UX', 'CI/CD', 'DevOps', 'AWS', 'GCP', 'Azure', 'K8s', 'Docker', 'Git', 'SVN', 'FTP', 'SSH'],
    adjective: ['hajautettu', 'pilvipohjainen', 'kvantti', 'neuraalinen', 'syväoppiminen', 'koneoppiminen', 'lohkoketju', 'salattu', 'hajautettu', 'pakattu', 'optimoitu', 'skaalautuva', 'korkea saatavuus', 'virhesietoinen', 'reaaliaikainen', 'asynkroninen', 'synkroninen', 'rinnakkainen', 'hajautettu', 'keskitetty'],
    noun: ['algoritmi', 'tietorakenne', 'protokolla', 'rajapinta', 'moduuli', 'paketti', 'kirjasto', 'kehys', 'väliohjelmisto', 'tietokanta', 'palvelin', 'asiakas', 'verkko', 'turvallisuus', 'salaus', 'hajautus', 'tunnus', 'istunto', 'eväste', 'välimuisti', 'jono', 'pino', 'keko', 'puu', 'verkko', 'taulukko', 'lista', 'kartta', 'joukko'],
    verb: ['suorittaa', 'kääntää', 'debugata', 'julkaista', 'rakentaa', 'testata', 'optimoida', 'refaktoroida', 'integroida', 'synkronoida', 'salata', 'purkaa', 'hajautaa', 'pakata', 'purkaa', 'sarjallistaa', 'deserialisoida', 'jäsentää', 'validoida', 'todentaa'],
    ingverb: ['koodaus', 'ohjelmointi', 'kehitys', 'suunnittelu', 'analyysi', 'testaus', 'debuggaus', 'julkaisu', 'valvonta', 'lokitus', 'profilointi', 'vertailu', 'skaalaus', 'migraatio', 'refaktorointi', 'optimointi', 'dokumentointi', 'arviointi', 'integrointi', 'automaatio'],
    phrase: ['AI muuttaa tulevaisuutta', 'Big data antaa oivalluksia', 'Pilvi tarjoaa rajattomat mahdollisuudet', 'Lohkoketju rakentaa luottamusta', 'Kvanttitietokoneet tulevat', 'Koneoppiminen ennustaa', 'Syväoppiminen oppii', 'IoT yhdistää kaiken', '5G muuttaa kaiken', 'Metaverse odottaa', 'Web3 johtaa tietä', 'NFT on digitaalinen omaisuus', 'Älykkäät sopimukset automatisoivat', 'DeFi innovoi rahoitusta', 'DAO hajauttaa', 'Monialustatuki antaa tehokkuutta', 'Mikropalvelut antavat skaalautuvuutta', 'Kontit yksinkertaistavat julkaisua', 'CI/CD nopeaan toimitukseen', 'DevOps vahvistaa yhteistyötä'],
  },
  system: {
    fileName: ['asiakirja', 'raportti', 'esitys', 'laskentataulukko', 'kuva', 'video', 'ääni', 'arkisto', 'suoritettava', 'asetukset', 'loki', 'varmuuskopio', 'väliaikainen', 'välimuisti', 'data', 'asennus', 'päivitys', 'ajuri', 'kirjasto', 'skripti'],
    fileType: ['asiakirja', 'kuva', 'video', 'ääni', 'arkisto', 'suoritettava', 'asetukset', 'data', 'varmuuskopio', 'loki', 'välimuisti', 'väliaikainen', 'järjestelmä', 'kirjasto', 'ajuri', 'päivitys', 'asennus', 'fontti', 'teema', 'laajennus'],
  },
  science: {
    chemicalElement: ['Vety', 'Helium', 'Litium', 'Beryllium', 'Boori', 'Hiili', 'Typpi', 'Happi', 'Fluori', 'Neon', 'Natrium', 'Magnesium', 'Alumiini', 'Pii', 'Fosfori', 'Rikki', 'Kloori', 'Argon', 'Kalium', 'Kalsium', 'Rauta', 'Kupari', 'Sinkki', 'Hopea', 'Kulta', 'Elohopea', 'Lyijy', 'Uraani', 'Plutonium', 'Radon'],
    unit: ['metri', 'kilogramma', 'sekunti', 'ampeeri', 'kelvin', 'mooli', 'kandela', 'newton', 'pascal', 'joule', 'watti', 'coulombi', 'voltti', 'ohmi', 'hertsi', 'litra', 'gramma', 'senttimetri', 'millimetri', 'kilometri', 'millisekunti', 'mikrosekunti', 'nanosekunti'],
    constant: ['valon nopeus', 'gravitaatiovakio', 'Planckin vakio', 'Boltzmannin vakio', 'Avogadron luku', 'kaasuvakio', 'tyhjiön permittiivisyys', 'tyhjiön permeabiliteetti', 'alkeisvaraus', 'protonin massa', 'elektronin massa', 'neutronin massa', 'hienorakennevakio', 'Rydbergin vakio', 'Stefan-Boltzmannin vakio'],
    field: ['Fysiikka', 'Kemia', 'Biologia', 'Tähtitiede', 'Geologia', 'Meteorologia', 'Meritutkimus', 'Ekologia', 'Genetiikka', 'Molekyylibiologia', 'Solubiologia', 'Neurotiede', 'Psykologia', 'Matematiikka', 'Tilastotiede', 'Tietojenkäsittelytiede', 'Insinöörityö', 'Lääketiede', 'Farmasia', 'Eläinlääketiede', 'Maatalous', 'Ympäristötiede', 'Nanoteknologia', 'Materiaalitutkimus', 'Energiatutkimus'],
  },
  color: {
    name: ['punainen', 'oranssi', 'keltainen', 'vihreä', 'sininen', 'indigo', 'violetti', 'pinkki', 'musta', 'valkoinen', 'harmaa', 'ruskea', 'beige', 'kerma', 'norsunluu', 'kulta', 'hopea', 'pronssi', 'kupari', 'oliivi', 'khaki', 'laivastonsininen', 'minttu', 'turkoosi', 'magenta', 'purppura', 'limenvihreä', 'taivaansininen', 'laivastonsininen', 'kastanjanruskea'],
  },
}
