import type { LocaleDefinition } from '@stacksjs/ts-faker'

export const eo: LocaleDefinition = {
  title: 'Esperanto',
  person: {
    firstNameMale: ['Mario', 'Johano', 'Petro', 'Paŭlo', 'Marko', 'Luko', 'Tomaso', 'Andreo', 'Miĥaelo', 'Davido'],
    firstNameFemale: ['Maria', 'Johana', 'Elizabeto', 'Ana', 'Sofia', 'Emma', 'Lucia', 'Klara', 'Helena', 'Katerina'],
    firstNameNeutral: ['Alex', 'Robin', 'Jordan', 'Casey', 'Taylor'],
    lastName: ['Zamenhof', 'Schmidt', 'Müller', 'Garcia', 'Martinez', 'Silva', 'Santos', 'Rossi', 'Novak', 'Kowalski'],
    prefix: ['S-ro', 'S-ino', 'D-ro', 'Prof.'],
    suffix: ['Jr.', 'Sr.'],
    gender: ['Vira', 'Ina', 'Neduuma'],
    jobTitle: ['Programisto', 'Inĝeniero', 'Instruisto', 'Kuracisto', 'Advokato', 'Arkitekto', 'Desegnisto'],
  },
  address: {
    street: ['Centra', 'Ĝardena', 'Arbara', 'Monta', 'Rivera', 'Paca', 'Luma', 'Nova'],
    city: ['Varsovio', 'Parizo', 'Berlino', 'Romo', 'Madrido', 'Londono', 'Moskvo', 'Vieno'],
    state: ['Nord-Regiono', 'Sud-Regiono', 'Okcident-Regiono', 'Orient-Regiono'],
    stateAbbr: ['NR', 'SR', 'OR', 'ER'],
    country: ['Esperantujo', 'Francio', 'Germanio', 'Hispanio', 'Italio', 'Pollando', 'Rusio', 'Britio'],
    countryCode: ['EO', 'FR', 'DE', 'ES', 'IT', 'PL', 'RU', 'GB'],
    zipCode: ['#####'],
    buildingNumber: ['###', '##', '#'],
    direction: ['Nordo', 'Sudo', 'Okcidento', 'Oriento'],
    streetSuffix: ['Strato', 'Aleo', 'Vojo', 'Placo', 'Bulvardo'],
  },
  company: {
    name: ['Esperanto-Firmao', 'Verda Stelo', 'Tutmonda Grupo', 'Nova Epoko', 'Ĝenerala Servo'],
    suffix: ['S.A.', 'KG', 'GmbH', 'Ltd', 'Inc'],
    industry: ['Teknologio', 'Edukado', 'Sano', 'Komerco', 'Transporto'],
    buzzwords: ['optimumigi', 'revolucii', 'transformi', 'simpligi'],
    adjective: ['nova', 'inteligenta', 'efika', 'moderna'],
    descriptor: ['tutmonda', 'digitala', 'ekologia'],
    noun: ['solvo', 'platformo', 'sistemo', 'servo'],
  },
  internet: {
    domainSuffix: ['eo', 'org', 'net', 'com'],
    freeEmail: ['gmail.com', 'yahoo.com', 'hotmail.com'],
  },
  phone: {
    formats: ['### ### ####', '+### ### ### ####'],
  },
  food: {
    dish: ['Pano', 'Fromaĝo', 'Supo', 'Salato', 'Fiŝo', 'Viando', 'Legomoj'],
    ingredient: ['Akvo', 'Salo', 'Sukero', 'Butero', 'Oleo', 'Lakto'],
    cuisine: ['Eŭropa', 'Azia', 'Mediteranea', 'Internacia'],
    dessert: ['Kuko', 'Torto', 'Glaciaĵo', 'Biskvito'],
    fruit: ['Pomo', 'Banano', 'Oranĝo', 'Frago'],
    vegetable: ['Tomato', 'Karoto', 'Brasiko', 'Salato'],
    meat: ['Viando', 'Fiŝo', 'Kokino', 'Porko'],
    spice: ['Salo', 'Pipro', 'Kanelo', 'Vanilo'],
  },
  animal: {
    dog: ['Hundo', 'Retrievero', 'Buldogo', 'Pudelo'],
    cat: ['Kato', 'Persa', 'Siama'],
    bird: ['Birdo', 'Aglo', 'Kolombo'],
    fish: ['Fiŝo', 'Karpo', 'Truto'],
    horse: ['Ĉevalo', 'Ponio'],
    rabbit: ['Kuniklo'],
    insect: ['Papilio', 'Abelo', 'Formiko'],
    type: ['Hundo', 'Kato', 'Birdo', 'Fiŝo'],
  },
  sport: {
    sport: ['Futbalo', 'Basketbalo', 'Teniso', 'Naĝado'],
    team: ['Esperanto FC', 'Verda Teamo'],
    athlete: ['Zamenhof'],
  },
  music: {
    genre: ['Roko', 'Ĵazo', 'Klasika', 'Popo'],
    artist: ['Muzikisto'],
    song: ['La Espero'],
    instrument: ['Piano', 'Gitaro', 'Violono'],
  },
  commerce: {
    product: ['Seĝo', 'Tablo', 'Lampo'],
    productAdjective: ['Bela', 'Granda', 'Malgranda'],
    productMaterial: ['Ligno', 'Metalo', 'Plasto'],
    department: ['Elektroniko', 'Vestoj', 'Hejmo'],
    color: ['Ruĝa', 'Blua', 'Verda', 'Flava'],
  },
  book: {
    title: ['Fundamento de Esperanto'],
    author: ['Zamenhof'],
    publisher: ['Esperanto-Eldonejo'],
    genre: ['Fikcio', 'Scienco'],
    series: [],
    review: ['Bonega libro'],
  },
  vehicle: {
    manufacturer: ['Volvo', 'Toyota', 'BMW'],
    model: ['Modelo A', 'Modelo B'],
    type: ['Aŭto', 'Kamiono'],
    fuel: ['Benzino', 'Elektro'],
    bicycle: ['Biciklo'],
  },
  word: {
    adjective: ['bona', 'malbona', 'granda', 'malgranda'],
    adverb: ['rapide', 'malrapide', 'bone'],
    conjunction: ['kaj', 'aŭ', 'sed'],
    interjection: ['ho', 'ha'],
    noun: ['persono', 'hejmo', 'tempo'],
    preposition: ['en', 'sur', 'sub', 'ĉe'],
    verb: ['esti', 'havi', 'iri', 'veni'],
  },
  hacker: {
    abbreviation: ['TCP', 'IP', 'HTTP', 'API'],
    adjective: ['sekura', 'rapida'],
    noun: ['sistemo', 'protokolo'],
    verb: ['programi', 'kompili'],
    ingverb: ['programante'],
    phrase: ['La sistemo funkcias'],
  },
  system: {
    fileName: ['dokumento', 'dosiero'],
    fileType: ['teksto', 'bildo'],
  },
  science: {
    chemicalElement: ['Hidrogeno', 'Oksigeno', 'Karbono'],
    unit: ['metro', 'kilogramo', 'sekundo'],
    constant: ['Rapideco de lumo'],
    field: ['Fiziko', 'Kemio', 'Biologio'],
  },
}
