import type { LocaleDefinition } from '@stacksjs/ts-faker'

export const it: LocaleDefinition = {
  title: 'Italian',
  person: {
    firstNameMale: [
      'Francesco',
      'Alessandro',
      'Andrea',
      'Matteo',
      'Lorenzo',
      'Gabriele',
      'Mattia',
      'Leonardo',
      'Davide',
      'Riccardo',
      'Federico',
      'Tommaso',
      'Giuseppe',
      'Antonio',
      'Marco',
      'Giovanni',
      'Luca',
      'Pietro',
      'Paolo',
      'Carlo',
      'Stefano',
      'Massimo',
      'Roberto',
      'Fabio',
      'Simone',
      'Daniele',
      'Emanuele',
      'Filippo',
      'Nicola',
      'Alessio',
      'Michele',
      'Vincenzo',
      'Giorgio',
      'Sergio',
      'Mario',
      'Angelo',
      'Salvatore',
      'Luigi',
      'Franco',
      'Enrico',
    ],
    firstNameFemale: [
      'Sofia',
      'Giulia',
      'Aurora',
      'Alice',
      'Ginevra',
      'Emma',
      'Giorgia',
      'Greta',
      'Beatrice',
      'Anna',
      'Chiara',
      'Sara',
      'Martina',
      'Francesca',
      'Alessia',
      'Elisa',
      'Valentina',
      'Silvia',
      'Elena',
      'Laura',
      'Federica',
      'Ilaria',
      'Arianna',
      'Camilla',
      'Serena',
      'Cristina',
      'Claudia',
      'Michela',
      'Antonella',
      'Daniela',
      'Maria',
      'Lucia',
      'Paola',
      'Roberta',
      'Giovanna',
      'Teresa',
      'Monica',
      'Barbara',
      'Simona',
      'Elisabetta',
      'Vittoria',
      'Ludovica',
      'Bianca',
      'Matilde',
      'Viola',
      'Nicole',
      'Rebecca',
      'Eleonora',
      'Margherita',
      'Caterina',
    ],
    firstNameNeutral: [
      'Andrea',
      'Celeste',
      'Diamante',
    ],
    lastName: [
      'Rossi',
      'Russo',
      'Ferrari',
      'Esposito',
      'Bianchi',
      'Romano',
      'Colombo',
      'Ricci',
      'Marino',
      'Greco',
      'Bruno',
      'Gallo',
      'Conti',
      'De Luca',
      'Costa',
      'Giordano',
      'Mancini',
      'Rizzo',
      'Lombardi',
      'Moretti',
      'Barbieri',
      'Fontana',
      'Santoro',
      'Mariani',
      'Rinaldi',
      'Caruso',
      'Ferrara',
      'Galli',
      'Martini',
      'Leone',
      'Longo',
      'Gentile',
      'Martinelli',
      'Vitale',
      'Lombardo',
      'Serra',
      'Coppola',
      'De Santis',
      'D\'Angelo',
      'Marchetti',
      'Parisi',
      'Villa',
      'Conte',
      'Ferraro',
      'Fabbri',
      'Bianco',
      'Marini',
      'Grasso',
      'Valentini',
      'Messina',
      'Sala',
      'De Angelis',
      'Gatti',
      'Pellegrini',
      'Palumbo',
      'Sanna',
      'Farina',
      'Monti',
      'Testa',
      'Grassi',
      'Carbone',
      'Giuliani',
      'Benedetti',
      'Barone',
      'Rossetti',
      'Caputo',
      'Montanari',
      'Guerra',
      'Palmieri',
      'Bernardi',
    ],
    prefix: ['Sig.', 'Sig.ra', 'Dott.', 'Dott.ssa', 'Prof.', 'Prof.ssa', 'Ing.', 'Avv.'],
    suffix: ['Jr.', 'Sr.', 'I', 'II', 'III', 'IV'],
    gender: ['Maschile', 'Femminile', 'Non-binario', 'Agender', 'Genderfluid'],
    jobTitle: [
      'Ingegnere del Software',
      'Product Manager',
      'Designer',
      'Data Scientist',
      'Ingegnere DevOps',
      'Responsabile Marketing',
      'Rappresentante Vendite',
      'Contabile',
      'Responsabile Risorse Umane',
      'Amministratore Delegato',
      'Direttore Tecnico',
      'Direttore Finanziario',
      'Project Manager',
      'Business Analyst',
      'Sviluppatore',
      'Architetto Software',
      'Consulente',
      'Analista',
      'Coordinatore',
      'Specialista',
      'Tecnico',
      'Assistente',
      'Responsabile Operazioni',
      'Responsabile Vendite',
    ],
  },
  address: {
    street: [
      'Roma',
      'Milano',
      'Garibaldi',
      'Vittorio Emanuele',
      'Dante',
      'Mazzini',
      'Cavour',
      'Verdi',
      'Marconi',
      'XX Settembre',
      'Umberto I',
      'Matteotti',
      'Kennedy',
      'Europa',
      'Libertà',
      'Nazionale',
      'Venezia',
      'Torino',
      'Napoli',
      'Firenze',
      'Bologna',
      'Genova',
      'Colombo',
      'IV Novembre',
    ],
    city: [
      'Roma',
      'Milano',
      'Napoli',
      'Torino',
      'Palermo',
      'Genova',
      'Bologna',
      'Firenze',
      'Bari',
      'Catania',
      'Venezia',
      'Verona',
      'Messina',
      'Padova',
      'Trieste',
      'Brescia',
      'Taranto',
      'Prato',
      'Parma',
      'Modena',
      'Reggio Calabria',
      'Reggio Emilia',
      'Perugia',
      'Ravenna',
      'Livorno',
      'Cagliari',
      'Foggia',
      'Rimini',
      'Salerno',
      'Ferrara',
      'Sassari',
      'Latina',
      'Giugliano in Campania',
      'Monza',
      'Siracusa',
      'Pescara',
      'Bergamo',
      'Forlì',
      'Trento',
      'Vicenza',
      'Terni',
      'Bolzano',
      'Novara',
      'Piacenza',
      'Ancona',
    ],
    state: [
      'Lazio',
      'Lombardia',
      'Campania',
      'Piemonte',
      'Sicilia',
      'Liguria',
      'Emilia-Romagna',
      'Toscana',
      'Puglia',
      'Veneto',
      'Calabria',
      'Sardegna',
      'Marche',
      'Abruzzo',
      'Friuli-Venezia Giulia',
      'Trentino-Alto Adige',
      'Umbria',
      'Basilicata',
      'Molise',
      'Valle d\'Aosta',
    ],
    stateAbbr: [
      'LZ',
      'LM',
      'CM',
      'PM',
      'SC',
      'LG',
      'ER',
      'TS',
      'PG',
      'VN',
      'CL',
      'SD',
      'MR',
      'AB',
      'FV',
      'TA',
      'UM',
      'BS',
      'ML',
      'VA',
    ],
    country: [
      'Italia',
      'Svizzera',
      'Francia',
      'Spagna',
      'Germania',
      'Austria',
      'Grecia',
      'Malta',
      'Slovenia',
      'Croazia',
      'San Marino',
      'Città del Vaticano',
      'Monaco',
      'Liechtenstein',
    ],
    countryCode: ['IT', 'CH', 'FR', 'ES', 'DE', 'AT', 'GR', 'MT', 'SI', 'HR', 'SM', 'VA', 'MC', 'LI'],
    zipCode: ['#####'],
    buildingNumber: ['###', '##', '#'],
    direction: ['Nord', 'Sud', 'Est', 'Ovest', 'Nord-Est', 'Nord-Ovest', 'Sud-Est', 'Sud-Ovest'],
    streetSuffix: [
      'Via',
      'Viale',
      'Corso',
      'Piazza',
      'Largo',
      'Vicolo',
      'Strada',
      'Lungomare',
      'Borgo',
      'Circonvallazione',
      'Passaggio',
      'Salita',
      'Discesa',
      'Rotonda',
      'Galleria',
    ],
  },
  company: {
    name: [
      'TechItalia',
      'ItalSoft',
      'RomaTech',
      'MilanoSoft',
      'DataSistemi',
      'CloudNet Italia',
      'InnovaSrl',
      'SoluzioniDigitali',
      'FuturoTech',
      'SmartSistemi',
      'PrimeSoft',
      'AlphaTech',
      'MediterraneoTech',
      'AdriaticSoft',
      'TirrenoTech',
      'AlpiSoft',
      'AppennineTech',
    ],
    suffix: ['S.p.A.', 'S.r.l.', 'S.n.c.', 'S.a.s.', 'S.r.l.s.', 'Technologies', 'Solutions', 'Systems'],
    industry: [
      'Tecnologia',
      'Finanza',
      'Sanità',
      'Istruzione',
      'Commercio',
      'Manifattura',
      'Telecomunicazioni',
      'Energia',
      'Immobiliare',
      'Trasporti',
      'Media',
      'Ospitalità',
      'Moda',
      'Alimentare',
      'Turismo',
      'Automotive',
      'Farmaceutica',
      'Chimica',
    ],
    buzzwords: [
      'sinergizzare',
      'sfruttare',
      'innovare',
      'rivoluzionare',
      'ottimizzare',
      'trasformare',
      'potenziare',
      'abilitare',
      'facilitare',
      'orchestrare',
      'integrare',
      'digitalizzare',
    ],
    adjective: [
      'rivoluzionario',
      'innovativo',
      'avanzato',
      'leader',
      'premium',
      'aziendale',
      'scalabile',
      'robusto',
      'agile',
      'sicuro',
      'efficiente',
      'intelligente',
      'moderno',
    ],
    descriptor: [
      'globale',
      'digitale',
      'cloud',
      'AI',
      'data-driven',
      'user-centric',
      'automatizzato',
      'integrato',
      'connesso',
      'intelligente',
      'personalizzato',
      'sostenibile',
    ],
    noun: [
      'soluzione',
      'piattaforma',
      'sistema',
      'servizio',
      'tecnologia',
      'framework',
      'infrastruttura',
      'applicazione',
      'rete',
      'portale',
      'ecosistema',
      'architettura',
      'motore',
    ],
  },
  internet: {
    domainSuffix: ['it', 'com', 'net', 'org', 'eu', 'info', 'biz'],
    freeEmail: ['gmail.com', 'libero.it', 'virgilio.it', 'hotmail.it', 'outlook.it', 'yahoo.it', 'tiscali.it'],
  },
  phone: {
    formats: [
      '0##-#######',
      '0##/#######',
      '+39 0## #######',
      '+39-0##-#######',
      '3## ### ####',
      '+39 3## ### ####',
    ],
  },
  food: {
    dish: ['Pasta Carbonara', 'Pizza Margherita', 'Risotto alla Milanese', 'Osso Buco', 'Lasagne', 'Tiramisù', 'Parmigiana', 'Arancini', 'Caprese', 'Bruschetta', 'Gnocchi', 'Ravioli', 'Tortellini', 'Fettuccine Alfredo', 'Saltimbocca', 'Vitello Tonnato', 'Bistecca alla Fiorentina', 'Polenta', 'Minestrone', 'Ribollita', 'Panzanella', 'Focaccia', 'Panettone', 'Cannoli', 'Gelato'],
    ingredient: ['Pomodoro', 'Basilico', 'Aglio', 'Olio d\'Oliva', 'Parmigiano', 'Mozzarella', 'Prosciutto', 'Pancetta', 'Farina', 'Uova', 'Burro', 'Panna', 'Vino', 'Limone', 'Origano', 'Rosmarino', 'Salvia', 'Timo', 'Peperoncino', 'Sale', 'Pepe', 'Zucchero', 'Aceto Balsamico', 'Cipolla', 'Melanzana'],
    cuisine: ['Italiana', 'Cinese', 'Giapponese', 'Indiana', 'Messicana', 'Greca', 'Francese', 'Spagnola', 'Tailandese', 'Turca'],
    dessert: ['Tiramisù', 'Panna Cotta', 'Cannoli', 'Gelato', 'Affogato', 'Zabaione', 'Biscotti', 'Amaretti', 'Panettone', 'Pandoro', 'Sfogliatelle', 'Cassata', 'Torta Caprese', 'Crostata', 'Profiterole'],
    fruit: ['Mela', 'Pera', 'Pesca', 'Albicocca', 'Ciliegia', 'Fragola', 'Uva', 'Arancia', 'Limone', 'Mandarino', 'Fico', 'Melone', 'Anguria', 'Prugna', 'Kiwi'],
    vegetable: ['Pomodoro', 'Zucchina', 'Melanzana', 'Peperone', 'Cipolla', 'Aglio', 'Carota', 'Patata', 'Spinaci', 'Cavolo', 'Broccoli', 'Cavolfiore', 'Funghi', 'Asparagi', 'Carciofi'],
    meat: ['Manzo', 'Maiale', 'Pollo', 'Vitello', 'Agnello', 'Coniglio', 'Anatra', 'Tacchino', 'Salsiccia', 'Prosciutto'],
    spice: ['Basilico', 'Origano', 'Rosmarino', 'Salvia', 'Timo', 'Prezzemolo', 'Peperoncino', 'Noce Moscata', 'Cannella', 'Zafferano'],
  },
  animal: {
    dog: ['Pastore Tedesco', 'Labrador', 'Golden Retriever', 'Bulldog', 'Beagle', 'Chihuahua', 'Barboncino', 'Boxer', 'Rottweiler', 'Dalmata', 'Pastore Belga', 'Setter Inglese', 'Bracco Italiano', 'Spinone Italiano', 'Cane Corso'],
    cat: ['Persiano', 'Siamese', 'Maine Coon', 'Bengala', 'Ragdoll', 'British Shorthair', 'Sphynx', 'Abissino', 'Birmano', 'Certosino', 'Europeo'],
    bird: ['Aquila', 'Falco', 'Gufo', 'Pappagallo', 'Canarino', 'Passero', 'Piccione', 'Colomba', 'Usignolo', 'Merlo', 'Cardellino', 'Rondine'],
    fish: ['Pesce Rosso', 'Betta', 'Guppy', 'Tetra', 'Carpa', 'Trota', 'Salmone', 'Tonno', 'Branzino', 'Orata', 'Sgombro'],
    horse: ['Arabo', 'Purosangue', 'Quarter Horse', 'Frisone', 'Mustang', 'Appaloosa', 'Andaluso', 'Lipizzano', 'Haflinger'],
    rabbit: ['Ariete', 'Nano', 'Rex', 'Angora', 'Gigante delle Fiandre', 'Olandese', 'Californiano'],
    insect: ['Farfalla', 'Ape', 'Formica', 'Scarabeo', 'Coccinella', 'Libellula', 'Cavalletta', 'Grillo', 'Lucciola', 'Mantide'],
    type: ['Cane', 'Gatto', 'Uccello', 'Pesce', 'Coniglio', 'Criceto', 'Porcellino d\'India', 'Topo', 'Tartaruga', 'Lucertola'],
  },
  sport: {
    sport: ['Calcio', 'Pallacanestro', 'Tennis', 'Pallavolo', 'Ciclismo', 'Nuoto', 'Atletica', 'Rugby', 'Scherma', 'Golf', 'Sci', 'Formula 1', 'MotoGP', 'Canottaggio', 'Pallanuoto'],
    team: ['Juventus', 'Milan', 'Inter', 'Roma', 'Napoli', 'Lazio', 'Fiorentina', 'Atalanta', 'Torino', 'Bologna', 'Sampdoria', 'Genoa'],
    athlete: ['Valentino Rossi', 'Francesco Totti', 'Paolo Maldini', 'Alessandro Del Piero', 'Gianluigi Buffon', 'Federica Pellegrini', 'Filippo Magnini', 'Stefano Baldini'],
  },
  music: {
    genre: ['Opera', 'Pop Italiano', 'Rock', 'Jazz', 'Classica', 'Rap', 'Elettronica', 'Folk', 'Blues', 'Reggae', 'Soul', 'Cantautore'],
    artist: ['Andrea Bocelli', 'Laura Pausini', 'Eros Ramazzotti', 'Luciano Pavarotti', 'Zucchero', 'Vasco Rossi', 'Ligabue', 'Tiziano Ferro', 'Gianna Nannini', 'Alessandra Amoroso'],
    song: ['Volare', 'O Sole Mio', 'Con te Partirò', 'Bella Ciao', 'La Solitudine', 'Caruso', 'Nel Blu Dipinto di Blu', 'Gloria'],
    instrument: ['Pianoforte', 'Chitarra', 'Violino', 'Batteria', 'Sassofono', 'Tromba', 'Flauto', 'Fisarmonica', 'Arpa', 'Violoncello', 'Mandolino'],
  },
  commerce: {
    product: ['Sedia', 'Tavolo', 'Lampada', 'Divano', 'Letto', 'Scrivania', 'Computer', 'Telefono', 'Orologio', 'Scarpe', 'Borsa', 'Zaino', 'Occhiali'],
    productAdjective: ['Piccolo', 'Grande', 'Ergonomico', 'Rustico', 'Moderno', 'Elegante', 'Pratico', 'Incredibile', 'Fantastico', 'Durevole', 'Lussuoso', 'Professionale'],
    productMaterial: ['Acciaio', 'Legno', 'Plastica', 'Cotone', 'Pelle', 'Vetro', 'Alluminio', 'Metallo', 'Seta', 'Lana', 'Ceramica', 'Marmo'],
    department: ['Elettronica', 'Abbigliamento', 'Casa e Giardino', 'Sport', 'Libri', 'Giocattoli', 'Salute e Bellezza', 'Alimentari', 'Moda', 'Arredamento'],
    color: ['Rosso', 'Blu', 'Verde', 'Giallo', 'Nero', 'Bianco', 'Grigio', 'Rosa', 'Arancione', 'Viola', 'Marrone', 'Azzurro'],
  },
  book: {
    title: ['I Promessi Sposi', 'La Divina Commedia', 'Decameron', 'Il Nome della Rosa', 'Se questo è un uomo', 'Il Gattopardo', 'Fontamara', 'La coscienza di Zeno', 'Il fu Mattia Pascal', 'Mastro-don Gesualdo', 'I Malavoglia', 'Orlando Furioso', 'Il Principe', 'Canzoniere', 'Le Avventure di Pinocchio'],
    author: ['Dante Alighieri', 'Alessandro Manzoni', 'Giovanni Boccaccio', 'Umberto Eco', 'Primo Levi', 'Giuseppe Tomasi di Lampedusa', 'Ignazio Silone', 'Italo Svevo', 'Luigi Pirandello', 'Giovanni Verga', 'Ludovico Ariosto', 'Niccolò Machiavelli', 'Francesco Petrarca', 'Carlo Collodi', 'Italo Calvino'],
    publisher: ['Mondadori', 'Einaudi', 'Feltrinelli', 'Rizzoli', 'Bompiani', 'Garzanti', 'Sellerio', 'Adelphi', 'Il Saggiatore', 'Laterza'],
    genre: ['Romanzo', 'Poesia', 'Teatro', 'Saggio', 'Giallo', 'Thriller', 'Fantasy', 'Fantascienza', 'Storico', 'Biografia', 'Autobiografia', 'Narrativa', 'Letteratura per ragazzi'],
    series: ['L\'Amica Geniale', 'Commissario Montalbano', 'Il Trono di Spade', 'Harry Potter', 'Il Signore degli Anelli', 'Le Cronache di Narnia', 'Geronimo Stilton', 'I Promessi Sposi'],
    review: ['Un capolavoro della letteratura italiana', 'Assolutamente coinvolgente', 'Lettura imprescindibile', 'Scritto magnificamente', 'Profondo ed emozionante', 'Uno dei migliori libri mai letti', 'Indimenticabile', 'Brillante e innovativo'],
  },
  vehicle: {
    manufacturer: ['Fiat', 'Ferrari', 'Lamborghini', 'Alfa Romeo', 'Maserati', 'Lancia', 'Iveco', 'Ducati', 'Aprilia', 'Piaggio', 'Volkswagen', 'BMW', 'Mercedes-Benz', 'Audi', 'Toyota'],
    model: ['Panda', '500', 'Tipo', 'Punto', 'Giulia', 'Stelvio', 'Ypsilon', 'Golf', 'Polo', 'Classe A', 'Serie 3', 'A3', 'Corolla', 'Yaris', 'Aygo'],
    type: ['Berlina', 'Station Wagon', 'SUV', 'Coupé', 'Cabriolet', 'Utilitaria', 'Monovolume', 'Sportiva', 'Fuoristrada', 'Citycar', 'Compatta'],
    fuel: ['Benzina', 'Diesel', 'Elettrico', 'Ibrido', 'Ibrido Plug-in', 'GPL', 'Metano', 'Idrogeno'],
    bicycle: ['Mountain Bike', 'Bici da Corsa', 'Bici da Città', 'Bici Elettrica', 'BMX', 'Bici Pieghevole', 'Gravel Bike', 'Bici da Trekking'],
  },
  word: {
    adjective: ['bello', 'grande', 'piccolo', 'nuovo', 'vecchio', 'buono', 'cattivo', 'alto', 'basso', 'lungo', 'corto', 'largo', 'stretto', 'veloce', 'lento', 'forte', 'debole', 'caldo', 'freddo', 'chiaro', 'scuro', 'pesante', 'leggero', 'duro', 'morbido', 'ricco', 'povero', 'giovane', 'anziano', 'felice', 'triste'],
    adverb: ['molto', 'poco', 'bene', 'male', 'sempre', 'mai', 'spesso', 'raramente', 'qui', 'lì', 'ora', 'dopo', 'prima', 'presto', 'tardi', 'velocemente', 'lentamente', 'insieme', 'forse', 'certamente', 'probabilmente', 'facilmente', 'difficilmente'],
    conjunction: ['e', 'o', 'ma', 'però', 'quindi', 'perché', 'se', 'quando', 'mentre', 'come', 'che', 'anche', 'né', 'oppure', 'tuttavia', 'dunque', 'infatti', 'cioè', 'ovvero'],
    interjection: ['ah', 'oh', 'ehi', 'wow', 'ops', 'ahi', 'evviva', 'bravo', 'ciao', 'salve', 'arrivederci', 'grazie', 'prego', 'scusa', 'forza', 'dai', 'basta', 'zitto', 'accidenti', 'cavolo'],
    noun: ['casa', 'uomo', 'donna', 'bambino', 'acqua', 'fuoco', 'terra', 'aria', 'sole', 'luna', 'stella', 'cielo', 'mare', 'montagna', 'fiume', 'albero', 'fiore', 'libro', 'tavolo', 'sedia', 'porta', 'finestra', 'strada', 'città', 'paese', 'mondo', 'tempo', 'giorno', 'notte', 'vita'],
    preposition: ['di', 'a', 'da', 'in', 'con', 'su', 'per', 'tra', 'fra', 'sotto', 'sopra', 'dentro', 'fuori', 'davanti', 'dietro', 'vicino', 'lontano', 'verso', 'contro', 'senza', 'durante', 'secondo', 'mediante'],
    verb: ['essere', 'avere', 'fare', 'andare', 'venire', 'dire', 'potere', 'dovere', 'volere', 'sapere', 'vedere', 'dare', 'prendere', 'mettere', 'stare', 'trovare', 'parlare', 'mangiare', 'bere', 'dormire', 'lavorare', 'studiare', 'giocare', 'leggere', 'scrivere', 'correre', 'camminare', 'pensare', 'credere', 'sentire'],
  },
  hacker: {
    abbreviation: ['TCP', 'IP', 'HTTP', 'HTTPS', 'FTP', 'SSH', 'SSL', 'TLS', 'DNS', 'VPN', 'API', 'SQL', 'HTML', 'CSS', 'JS', 'PHP', 'RAM', 'ROM', 'CPU', 'GPU', 'SSD', 'HDD', 'USB', 'LAN', 'WAN', 'WiFi', 'IoT', 'AI', 'ML'],
    adjective: ['digitale', 'virtuale', 'crittografato', 'decrittato', 'sicuro', 'vulnerabile', 'online', 'offline', 'wireless', 'locale', 'remoto', 'automatizzato', 'manuale', 'sincrono', 'asincrono', 'pubblico', 'privato', 'distribuito'],
    noun: ['protocollo', 'algoritmo', 'interfaccia', 'server', 'client', 'rete', 'sistema', 'processo', 'thread', 'cache', 'buffer', 'socket', 'porta', 'pacchetto', 'firewall', 'router', 'switch', 'virus', 'malware', 'exploit', 'patch', 'bug', 'pixel', 'byte', 'bit'],
    verb: ['compilare', 'eseguire', 'debuggare', 'crittografare', 'decrittare', 'hash', 'autenticare', 'autorizzare', 'connettere', 'disconnettere', 'scaricare', 'caricare', 'sincronizzare', 'salvare', 'ripristinare', 'scansionare', 'monitorare', 'deployare', 'patchare'],
    ingverb: ['compilando', 'eseguendo', 'debuggando', 'crittografando', 'decrittando', 'hashando', 'autenticando', 'autorizzando', 'connettendo', 'disconnettendo', 'scaricando', 'caricando', 'sincronizzando', 'salvando', 'ripristinando', 'scansionando', 'monitorando', 'deployando', 'patchando'],
    phrase: ['Vulnerabilità rilevata', 'Accesso negato', 'Connessione stabilita', 'Server compromesso', 'Dati esfiltrati', 'Firewall aggirato', 'Exploit riuscito', 'Sistema hackerato', 'Vulnerabilità zero-day', 'SQL injection riuscita', 'Reverse shell attiva'],
  },
  system: {
    fileName: ['documento', 'rapporto', 'presentazione', 'foglio', 'immagine', 'video', 'audio', 'archivio', 'backup', 'dati', 'configurazione', 'impostazioni', 'log', 'cache', 'progetto', 'bozza', 'finale', 'versione'],
    fileType: ['audio', 'immagine', 'testo', 'video', 'applicazione', 'documento', 'foglio di calcolo', 'presentazione', 'archivio', 'codice'],
  },
  science: {
    chemicalElement: ['Idrogeno', 'Elio', 'Litio', 'Carbonio', 'Azoto', 'Ossigeno', 'Fluoro', 'Neon', 'Sodio', 'Magnesio', 'Alluminio', 'Silicio', 'Fosforo', 'Zolfo', 'Cloro', 'Ferro', 'Rame', 'Zinco', 'Argento', 'Oro', 'Mercurio', 'Piombo', 'Uranio', 'Plutonio'],
    unit: ['metro', 'chilogrammo', 'secondo', 'ampere', 'kelvin', 'mole', 'candela', 'newton', 'pascal', 'joule', 'watt', 'volt', 'ohm', 'hertz', 'celsius', 'litro', 'grammo'],
    constant: ['Velocità della Luce', 'Costante Gravitazionale', 'Costante di Planck', 'Costante di Boltzmann', 'Numero di Avogadro', 'Carica Elementare', 'Costante dei Gas'],
    field: ['Fisica', 'Chimica', 'Biologia', 'Astronomia', 'Geologia', 'Ecologia', 'Genetica', 'Neuroscienze', 'Biochimica', 'Microbiologia', 'Botanica', 'Zoologia', 'Matematica', 'Informatica'],
  },
}
