import type { LocaleDefinition } from '@stacksjs/ts-faker'

export const cs: LocaleDefinition = {
  title: 'Czech',
  person: {
    firstNameMale: [
      'Jan',
      'Petr',
      'Josef',
      'Pavel',
      'Jaroslav',
      'Martin',
      'Tomáš',
      'Miroslav',
      'František',
      'Jiří',
      'Václav',
      'Karel',
      'Milan',
      'Michal',
      'Zdeněk',
      'Lukáš',
      'Jakub',
      'Stanislav',
      'Ondřej',
      'David',
      'Ladislav',
      'Roman',
      'Vojtěch',
      'Radek',
      'Marek',
      'Daniel',
      'Filip',
      'Aleš',
      'Vlastimil',
      'Adam',
      'Jindřich',
      'Antonín',
      'Matěj',
      'Rostislav',
      'Libor',
      'Vladimír',
      'Oldřich',
      'Radomír',
      'Miloslav',
      'Bohumil',
      'Patrik',
      'Dominik',
      'Štefan',
      'Ludvík',
      'Eduard',
      'Radim',
      'Vít',
      'René',
      'Igor',
      'Viktor',
    ],
    firstNameFemale: [
      'Marie',
      'Jana',
      'Eva',
      'Anna',
      'Hana',
      'Věra',
      'Lenka',
      'Alena',
      'Petra',
      'Kateřina',
      'Ludmila',
      'Jaroslava',
      'Helena',
      'Jitka',
      'Martina',
      'Ivana',
      'Zdeňka',
      'Veronika',
      'Monika',
      'Michaela',
      'Jiřina',
      'Marcela',
      'Kristýna',
      'Barbora',
      'Lucie',
      'Eliška',
      'Pavla',
      'Daniela',
      'Zuzana',
      'Tereza',
      'Simona',
      'Gabriela',
      'Adéla',
      'Natálie',
      'Nikola',
      'Karolína',
      'Andrea',
      'Božena',
      'Klára',
      'Miroslava',
      'Denisa',
      'Aneta',
      'Iveta',
      'Renata',
      'Šárka',
      'Radka',
      'Markéta',
      'Andrea',
      'Jarmila',
      'Olga',
    ],
    firstNameNeutral: [
      'Alex',
      'Saša',
      'Andrea',
      'Nikola',
      'Dominik',
      'René',
      'Kim',
      'Noa',
      'Andrea',
      'Jára',
    ],
    lastName: ['Novák', 'Svoboda', 'Novotný', 'Dvořák', 'Černý', 'Procházka', 'Kučera', 'Veselý', 'Horák', 'Němec', 'Marek', 'Pokorný', 'Pospíšil', 'Hájek', 'Jelínek', 'Král', 'Růžička', 'Beneš', 'Fiala', 'Sedláček', 'Doležal', 'Zeman', 'Kolář', 'Navrátil', 'Čermák', 'Urban', 'Vaněk', 'Blažek', 'Kříž', 'Kovář', 'Kratochvíl', 'Bartoš', 'Vlček', 'Polák', 'Musil', 'Kopecký', 'Šimek', 'Malý', 'Štěpánek', 'Holub'],
    prefix: ['Pan', 'Paní', 'Dr.', 'Prof.', 'Ing.', 'Mgr.', 'PhDr.', 'JUDr.', 'MUDr.'],
    suffix: ['ml.', 'st.', 'II', 'III', 'IV'],
    gender: ['Muž', 'Žena', 'Jiné'],
    jobTitle: ['Programátor', 'Projektový manažer', 'Designer', 'Marketingový ředitel', 'Obchodní ředitel', 'Účetní', 'Právník', 'Lékař', 'Zdravotní sestra', 'Učitel', 'Profesor', 'Výzkumník', 'Datový analytik', 'Product Manager', 'HR manažer', 'Konzultant', 'Architekt', 'Inženýr', 'Technik', 'Kuchař', 'Spisovatel', 'Novinář', 'Fotograf', 'Umělec', 'Hudebník'],
  },
  address: {
    street: ['Václavské náměstí', 'Karlova', 'Národní třída', 'Pařížská', 'Na Příkopě', 'Vinohradská', 'Wenceslas Square', 'Karlův most', 'Staroměstské náměstí', 'Malostranské náměstí', 'Nové Město', 'Hradčany', 'Josefov', 'Vinohrady', 'Žižkov', 'Smíchov', 'Dejvice', 'Holešovice', 'Karlín', 'Vršovice', 'Nusle', 'Podolí', 'Braník', 'Modřany', 'Libuš', 'Chodov', 'Háje', 'Opatov', 'Roztyly', 'Kačerov'],
    city: ['Praha', 'Brno', 'Ostrava', 'Plzeň', 'Liberec', 'Olomouc', 'České Budějovice', 'Hradec Králové', 'Ústí nad Labem', 'Pardubice', 'Zlín', 'Havířov', 'Kladno', 'Most', 'Opava', 'Frýdek-Místek', 'Karviná', 'Jihlava', 'Teplice', 'Děčín', 'Karlovy Vary', 'Chomutov', 'Přerov', 'Jablonec nad Nisou', 'Mladá Boleslav', 'Prostějov', 'Třebíč', 'Tábor', 'Znojmo', 'Příbram'],
    state: ['Hlavní město Praha', 'Středočeský kraj', 'Jihočeský kraj', 'Plzeňský kraj', 'Karlovarský kraj', 'Ústecký kraj', 'Liberecký kraj', 'Královéhradecký kraj', 'Pardubický kraj', 'Vysočina', 'Jihomoravský kraj', 'Olomoucký kraj', 'Zlínský kraj', 'Moravskoslezský kraj'],
    country: ['Česká republika', 'Slovensko', 'Německo', 'Polsko', 'Rakousko', 'Maďarsko', 'Velká Británie', 'Francie', 'Itálie', 'Španělsko'],
    zipCode: ['### ##'],
    direction: ['Sever', 'Jih', 'Východ', 'Západ', 'Severovýchod', 'Severozápad', 'Jihovýchod', 'Jihozápad'],
  },
  company: {
    name: ['ČEZ', 'Škoda Auto', 'O2', 'T-Mobile', 'Vodafone', 'Česká pošta', 'České dráhy', 'Avast', 'Seznam.cz', 'Alza.cz', 'Mall.cz', 'Rohlik.cz', 'Tesco', 'Kaufland', 'Lidl', 'Albert', 'Billa', 'Penny Market', 'Makro', 'IKEA', 'OBI', 'Baumax', 'Datart', 'Electro World', 'CZC.cz', 'Mironet', 'TSBohemia', 'Kofola', 'Pilsner Urquell', 'Budweiser Budvar'],
    suffix: ['s.r.o.', 'a.s.', 'v.o.s.', 'k.s.', 'družstvo', 'nadace', 'spolek', 'Holding', 'Group', 'Company'],
    industry: ['Technologie', 'Telekomunikace', 'Automobilový průmysl', 'Textil', 'Potravinářství', 'Stavebnictví', 'Energetika', 'Cestovní ruch', 'Zdravotnictví', 'Vzdělávání', 'Finance', 'Bankovnictví', 'Pojišťovnictví', 'Maloobchod', 'E-commerce', 'Logistika', 'Doprava', 'Média', 'Reklama', 'Poradenství', 'Software', 'Těžba', 'Zemědělství', 'Chov zvířat', 'Rybářství'],
    buzzword: ['digitální transformace', 'inovace', 'udržitelnost', 'podnikání', 'technologie', 'umělá inteligence', 'analýza dat', 'cloud', 'internet věcí', 'blockchain', 'automatizace', 'digitalizace', 'e-transformace', 'startup', 'scale-up', 'unicorn', 'fintech', 'edtech', 'healthtech', 'agritech', 'martech', 'adtech', 'regtech', 'insurtech', 'proptech'],
    adjective: ['inovativní', 'udržitelný', 'digitální', 'agilní', 'efektivní', 'spolehlivý', 'dynamický', 'moderní', 'pokrokový', 'vedoucí'],
    descriptor: ['řešení', 'služba', 'produkt', 'systém', 'platforma', 'aplikace', 'technologie', 'koncept', 'síť', 'ekosystém'],
    noun: ['podnikání', 'inovace', 'budoucnost', 'partner', 'zákazník', 'spolupráce', 'úspěch', 'růst', 'rozvoj', 'příležitost'],
    buzzwords: ['digitální transformace', 'inovace', 'udržitelnost', 'podnikání', 'technologie', 'umělá inteligence', 'analýza dat', 'cloud', 'IoT', 'blockchain', 'automatizace', 'digitalizace', 'startup', 'synergie', 'optimalizace'],
  },
  internet: {
    domainName: ['seznam.cz', 'novinky.cz', 'idnes.cz', 'aktualne.cz', 'lidovky.cz', 'blesk.cz', 'denik.cz', 'ihned.cz', 'sport.cz', 'stream.cz', 'alza.cz', 'mall.cz', 'czc.cz', 'heureka.cz', 'zbozi.cz', 'sreality.cz', 'sauto.cz', 'avast.com', 'skoda-auto.cz', 'cez.cz', 'o2.cz', 't-mobile.cz', 'vodafone.cz', 'ceskaposta.cz'],
    domainSuffix: ['.cz', '.com', '.net', '.org', '.eu'],
    freeEmail: ['gmail.com', 'outlook.com', 'hotmail.com', 'yahoo.com', 'seznam.cz', 'email.cz', 'centrum.cz', 'atlas.cz'],
  },
  phone: {
    format: ['+420 ### ### ###', '+420 ## ## ## ###', '### ### ###', '## ## ## ###'],
  },
  food: {
    dish: ['Svíčková', 'Vepřo-knedlo-zelo', 'Guláš', 'Smažený sýr', 'Řízek', 'Bramboráky', 'Kulajda', 'Česnečka', 'Knedlíky', 'Šišky', 'Ovocné knedlíky', 'Palačinky', 'Trdelník', 'Koláče', 'Buchty', 'Perník', 'Vánočka', 'Mazanec', 'Větrník', 'Kremrole', 'Lívance', 'Zelňačka', 'Hrachová polévka', 'Kulajda', 'Hovězí vývar', 'Dršťková polévka', 'Bramborová polévka', 'Smaženka', 'Tlačenka', 'Jitrnice'],
    ingredient: ['Zelí', 'Brambory', 'Houby', 'Okurky', 'Smetana', 'Tvaroh', 'Cibule', 'Mrkev', 'Petržel', 'Celer', 'Česnek', 'Kopr', 'Švestky', 'Jablka', 'Třešně', 'Maliny', 'Mouka', 'Mák', 'Vepřové maso', 'Klobása', 'Slanina', 'Vejce', 'Máslo', 'Mléko', 'Kyselé zelí', 'Řepa', 'Křen', 'Okurka', 'Hermelín', 'Eidam'],
    cuisine: ['Česká', 'Slovenská', 'Italská', 'Francouzská', 'Japonská', 'Čínská', 'Thajská', 'Mexická', 'Turecká', 'Řecká', 'Španělská', 'Americká', 'Indická', 'Korejská', 'Vietnamská', 'Arabská'],
    dessert: ['Trdelník', 'Koláče', 'Buchty', 'Větrník', 'Kremrole', 'Perník', 'Vánočka', 'Mazanec', 'Ovocné knedlíky', 'Palačinky', 'Lívance', 'Šišky', 'Závin', 'Medovník', 'Rakvičky'],
    fruit: ['Jablko', 'Hruška', 'Švestka', 'Třešeň', 'Višeň', 'Jahoda', 'Malina', 'Borůvka', 'Angrešt', 'Rybíz', 'Jeřabina', 'Kdoule', 'Meruňka', 'Broskev', 'Banán', 'Pomeranč', 'Citrón', 'Grapefruit', 'Kiwi', 'Mango'],
    vegetable: ['Brambor', 'Zelí', 'Mrkev', 'Petržel', 'Celer', 'Cibule', 'Česnek', 'Pórek', 'Řepa', 'Okurka', 'Rajče', 'Paprika', 'Cuketa', 'Dýně', 'Brokolice', 'Květák', 'Špenát', 'Salát', 'Ředkvička', 'Fazole'],
    meat: ['Vepřové', 'Hovězí', 'Kuře', 'Krocan', 'Kachna', 'Husa', 'Telecí', 'Jehněčí', 'Zajíc', 'Zvěřina', 'Klobása', 'Slanina', 'Pečeně', 'Svíčková', 'Koleno'],
    spice: ['Pepř', 'Sůl', 'Paprika', 'Majoránka', 'Kmín', 'Nové koření', 'Skořice', 'Muškátový oříšek', 'Zázvor', 'Bazalka', 'Oregano', 'Tymián', 'Rozmarýn', 'Saturejka', 'Libeček'],
  },
  animal: {
    dog: ['Německý ovčák', 'Labrador retriever', 'Golden retriever', 'Francouzský buldoček', 'Český teriér', 'Československý vlčák', 'Jezevčík', 'Kokršpaněl', 'Jorkšír', 'Sibiřský husky', 'Bernardýn', 'Boxer', 'Rotvajler', 'Belgický ovčák', 'Dobrman'],
    cat: ['Evropská kočka', 'Perská kočka', 'Britská kočka', 'Maine Coon', 'Sibiřská kočka', 'Ragdoll', 'Siamská kočka', 'Ruská modrá', 'Norská lesní', 'Sfynx'],
    bird: ['Vrabec', 'Straka', 'Vrána', 'Kavka', 'Vlaštovka', 'Hýl', 'Pěnkava', 'Sýkora', 'Datel', 'Čáp', 'Holub', 'Sokol', 'Káně', 'Kos', 'Červenka'],
    fish: ['Kapr', 'Pstruh', 'Štika', 'Okoun', 'Candát', 'Sumec', 'Cejn', 'Lín', 'Plotice', 'Úhoř', 'Losos', 'Treska', 'Sleď', 'Sardinka', 'Makrela'],
    horse: ['Kladrubský kůň', 'Český teplokrevník', 'Moravský teplokrevník', 'Hafling', 'Hucul', 'Arab', 'Fríský kůň', 'Andaluský kůň', 'Anglický plnokrevník', 'Hanoverský kůň'],
    rabbit: ['Kalifornský', 'Novozélandský bílý', 'Beran', 'Belgický obr', 'Činčila malá', 'Stříbřitý havana', 'Vídeňský modrý', 'Ter­mond­ský', 'Český luštič', 'Šedý obr'],
    insect: ['Beruška', 'Mravenec', 'Včela', 'Čmelák', 'Vosa', 'Motýl', 'Můra', 'Brouk', 'Šváb', 'Kobylka', 'Cvrček', 'Moucha', 'Komár', 'Blecha', 'Veš'],
  },
  sport: {
    sport: ['Fotbal', 'Hokej', 'Lední hokej', 'Tenis', 'Volejbal', 'Basketbal', 'Házená', 'Atletika', 'Plavání', 'Lyžování', 'Skoky na lyžích', 'Biatlon', 'Box', 'Šerm', 'Kanoistika', 'Veslování', 'Cyklistika', 'Stolní tenis', 'Florbal', 'MMA'],
    team: ['Sparta Praha', 'Slavia Praha', 'Viktoria Plzeň', 'Baník Ostrava', 'Slovan Liberec', 'Sparta Praha (hokej)', 'Slavia Praha (hokej)', 'HC Sparta Praha', 'HC Oceláři Třinec', 'Kometa Brno', 'Reprezentace České republiky', 'VK Dukla Liberec', 'ČZU Karlín', 'TJ Sokol', 'Bohemians 1905'],
    athlete: ['Jaromír Jágr', 'Dominik Hašek', 'Petra Kvitová', 'Karolína Plíšková', 'Tomáš Berdych', 'Jan Železný', 'Roman Šebrle', 'Martina Sáblíková', 'Ester Ledecká', 'Emil Zátopek', 'Věra Čáslavská', 'Patrik Schick', 'Tomáš Souček', 'Petr Čech', 'Pavel Nedvěd'],
  },
  music: {
    genre: ['Rock', 'Pop', 'Hip-hop', 'Jazz', 'Blues', 'Reggae', 'Country', 'Elektronická hudba', 'Punk', 'Metal', 'Folk', 'Lidová hudba', 'R&B', 'Soul', 'Klasická hudba'],
    artist: ['Karel Gott', 'Lucie', 'Kabát', 'Olympic', 'Chinaski', 'Čechomor', 'Jaromír Nohavica', 'Marta Kubišová', 'Helena Vondráčková', 'Wanastowi Vjecy', 'Škwor', 'Tomáš Klus', 'Aneta Langerová', 'Ewa Farna', 'Marek Ztracený', 'Barbora Poláková', 'Pokáč', 'MIG 21', 'Support Lesbiens', 'Kryštof'],
    song: ['Lady Carneval', 'Amerika', 'Já budu chodit po špičkách', 'Modlitba pro Martu', 'Cesta', 'Třešňová sedm', 'Holky z naší školky', 'Babičko, nauč mě', 'Tulák', 'Náměsíčná', 'Snad jsem to zavinil já', 'Být stále mlád', 'Léto', 'Láska je láska', 'Malá dáma', 'Ta třetí', 'Pár přátel', 'Proměny', 'Já chci být světlonoš', 'Anděl'],
    instrument: ['Kytara', 'Klavír', 'Bicí', 'Housle', 'Flétna', 'Saxofon', 'Trubka', 'Kontrabas', 'Viola', 'Violoncello', 'Harmonika', 'Akordeon', 'Varhany', 'Keyboard', 'Baskytara'],
  },
  commerce: {
    product: ['Počítač', 'Notebook', 'Telefon', 'Tablet', 'Sluchátka', 'Monitor', 'Klávesnice', 'Myš', 'Tiskárna', 'Fotoaparát', 'Televize', 'Konzole', 'Chytré hodinky', 'Router', 'Pevný disk', 'Flash disk', 'Powerbank', 'Nabíječka', 'Kabel', 'Pouzdro'],
    adjective: ['Moderní', 'Elegantní', 'Stylový', 'Funkční', 'Výkonný', 'Kompaktní', 'Luxusní', 'Praktický', 'Pohodlný', 'Odolný'],
    material: ['Kov', 'Plast', 'Dřevo', 'Sklo', 'Kůže', 'Látka', 'Bavlna', 'Len', 'Vlna', 'Hedvábí', 'Hliník', 'Ocel', 'Měď', 'Bronz', 'Kámen'],
    department: ['Elektronika', 'Oblečení', 'Obuv', 'Potraviny', 'Domácí spotřebiče', 'Audiotechnika', 'Hračky', 'Sport', 'Dům a zahrada', 'Zdraví a krása', 'Automoto', 'Knihy', 'Hudba', 'Filmy', 'Hry'],
    color: ['Červená', 'Modrá', 'Zelená', 'Žlutá', 'Černá', 'Bílá', 'Šedá', 'Hnědá', 'Růžová', 'Fialová', 'Oranžová', 'Tyrkysová', 'Námořnická modrá', 'Béžová', 'Stříbrná'],
  },
  book: {
    title: ['Babička', 'Osudy dobrého vojáka Švejka', 'Haškovy spisy', 'R.U.R.', 'Válka s mloky', 'Krakatit', 'Bílá nemoc', 'Továrna na absolutno', 'Tanec na zabíjačce', 'Slavnost sněženek', 'Ostře sledované vlaky', 'Postřižiny', 'Spalovač mrtvol', 'Němá barikáda', 'Nesnesitelná lehkost bytí', 'Žert', 'Smrt krásných srnců', 'Markéta Lazarová', 'Bylo nás pět', 'Saturnin'],
    author: ['Božena Němcová', 'Jaroslav Hašek', 'Karel Čapek', 'Bohumil Hrabal', 'Milan Kundera', 'Ladislav Fuks', 'Vladislav Vančura', 'Alois Jirásek', 'Karel Jaromír Erben', 'Jan Neruda', 'Václav Havel', 'Franz Kafka', 'Ivan Klíma', 'Pavel Kohout', 'Josef Škvorecký', 'Arnošt Lustig', 'Jan Werich', 'Jiří Wolker', 'Vítězslav Nezval', 'Jaroslav Seifert'],
    publisher: ['Albatros', 'Fragment', 'Host', 'Kniha Zlín', 'Mladá fronta', 'Paseka', 'Argo', 'Vyšehrad', 'Academia', 'Odeon', 'Portál', 'Motto', 'Euromedia', 'Knižní klub', 'Olympia'],
    genre: ['Fantasy', 'Sci-fi', 'Detektivka', 'Thriller', 'Romance', 'Horor', 'Drama', 'Komedie', 'Historický román', 'Biografie', 'Reportáž', 'Příručka', 'Esej', 'Poezie', 'Fakta'],
    series: ['Zaklínač', 'Pán prstenů', 'Harry Potter', 'Kroniky', 'Sága', 'Trilogie', 'Tetralogie', 'Pentalogie', 'Heptalog'],
    review: ['Skvělá kniha!', 'Nemohl jsem se od ní odtrhnout', 'Povinná četba', 'Doporučuji všem', 'Skvělý příběh', 'Vtahující děj', 'Nádherně napsané', 'Dojemné', 'Inspirující', 'Nesplnila má očekávání', 'Průměrná', 'Zklamání', 'Nudná', 'Nezajímavá', 'Ambiciózní pokus'],
  },
  vehicle: {
    manufacturer: ['Škoda', 'Tatra', 'Praga', 'Volkswagen', 'Ford', 'Renault', 'Toyota', 'Honda', 'Nissan', 'Mazda', 'Hyundai', 'Kia', 'BMW', 'Mercedes-Benz', 'Audi', 'Peugeot', 'Citroën', 'Volvo', 'Seat', 'Dacia'],
    model: ['Octavia', 'Fabia', 'Superb', 'Kodiaq', 'Karoq', 'Kamiq', 'Scala', 'Rapid', 'Felicia', 'Favorit', '105', '120', 'Forman', 'Golf', 'Passat', 'Polo', 'Tiguan', 'Touran', 'Corsa', 'Astra', 'Insignia', 'Fiesta', 'Focus', 'Mondeo', 'Clio', 'Megane', 'Scenic', 'Corolla', 'Yaris', 'Auris', 'Civic'],
    type: ['Sedan', 'Hatchback', 'Kombi', 'SUV', 'Crossover', 'Coupé', 'Kabriolet', 'Minivan', 'Pickup', 'Dodávka'],
    fuel: ['Benzín', 'Nafta', 'LPG', 'CNG', 'Hybrid', 'Elektřina', 'Vodík', 'Ethanol', 'Bionafta'],
    bicycle: ['Horské kolo', 'Silniční kolo', 'Městské kolo', 'Trekkové kolo', 'BMX', 'Skládací kolo', 'Elektrokolo', 'Dámské kolo', 'Cruiser', 'Gravel'],
  },
  word: {
    adjective: ['Krásný', 'Velký', 'Malý', 'Rychlý', 'Pomalý', 'Silný', 'Slabý', 'Vysoký', 'Nízký', 'Široký', 'Úzký', 'Dlouhý', 'Krátký', 'Těžký', 'Lehký', 'Světlý', 'Tmavý', 'Hlasitý', 'Tichý', 'Nový', 'Starý', 'Mladý', 'Bohatý', 'Chudý', 'Dobrý', 'Špatný'],
    adverb: ['Rychle', 'Pomalu', 'Dobře', 'Špatně', 'Hlasitě', 'Ticho', 'Brzy', 'Pozdě', 'Teď', 'Zítra', 'Včera', 'Vždy', 'Nikdy', 'Často', 'Zřídka', 'Tady', 'Tam', 'Všude', 'Nikde', 'Velmi'],
    conjunction: ['A', 'Nebo', 'Ale', 'Avšak', 'Nicméně', 'Proto', 'Tedy', 'Protože', 'Že', 'Jestli', 'Kdyby', 'Ačkoli', 'Přestože', 'Zatímco', 'Když'],
    interjection: ['Ach!', 'Jé!', 'Au!', 'Ále!', 'Wow!', 'Ahoj!', 'Nazdar!', 'Aha!', 'No!', 'Hm...', 'Ee...', 'Ups!', 'Jejda!', 'Kruci!'],
    noun: ['Dům', 'Auto', 'Kniha', 'Stůl', 'Židle', 'Počítač', 'Telefon', 'Strom', 'Květina', 'Pes', 'Kočka', 'Slunce', 'Měsíc', 'Hvězda', 'Moře', 'Hora', 'Řeka', 'Les', 'Město', 'Vesnice'],
    preposition: ['V', 'Na', 'Pod', 'Nad', 'Před', 'Za', 'Do', 'Od', 'Z', 'O', 'Pro', 'Bez', 'Přes', 'Při', 'Mezi', 'Mimo', 'Vůči', 'Kolem', 'Vedle', 'U'],
    verb: ['Být', 'Mít', 'Dělat', 'Jít', 'Jet', 'Mluvit', 'Vědět', 'Chtít', 'Moci', 'Muset', 'Dát', 'Brát', 'Dívat se', 'Vidět', 'Slyšet', 'Myslet', 'Cítit', 'Milovat', 'Nenávidět', 'Pracovat'],
  },
  hacker: {
    abbreviation: ['API', 'CPU', 'GPU', 'RAM', 'ROM', 'SSD', 'HDD', 'USB', 'HDMI', 'WiFi', 'LAN', 'WAN', 'VPN', 'DNS', 'IP', 'TCP', 'UDP', 'HTTP', 'HTTPS', 'FTP', 'SSH', 'SQL', 'HTML', 'CSS', 'JS'],
    adjective: ['Digitální', 'Virtuální', 'Mobilní', 'Bezdrátový', 'Kvantový', 'Neuronový', 'Redundantní', 'Škálovatelný', 'Optimalizovaný', 'Šifrovaný'],
    noun: ['Protokol', 'Port', 'Rozhraní', 'Komponenta', 'Bajt', 'Paket', 'Firewall', 'Bandwidth', 'Systém', 'Algoritmus', 'Matice', 'Uzel', 'Síť', 'Databáze', 'Server'],
    verb: ['Komprimovat', 'Generovat', 'Parsovat', 'Kalkulovat', 'Přepsat', 'Obejít', 'Hackovat', 'Přenášet', 'Indexovat', 'Renderovat', 'Navigovat', 'Programovat', 'Syntetizovat', 'Transmitovat', 'Připojit'],
    ingverb: ['Komprimování', 'Generování', 'Parsování', 'Kalkulování', 'Přepisování', 'Obcházení', 'Hackování', 'Přenášení', 'Indexování', 'Renderování', 'Navigování', 'Programování', 'Syntetizování', 'Transmitování', 'Připojování'],
    phrase: [
      'Pokud zkomprimujeme port, můžeme se dostat k panelu přes redundantní rozhraní!',
      'Musíme obejít firewall, abychom získali přístup!',
      'Zkuste zkomprimovat TCP protokol, možná to odblokuje server!',
      'Nemůžeme hackovat systém bez obejití bezdrátového protokolu!',
      'Použijte virtuální rozhraní a pak můžete hackovat všechny sítě!',
    ],
  },
  system: {
    fileName: ['zprava.pdf', 'dokument.docx', 'prezentace.pptx', 'tabulka.xlsx', 'obrazek.jpg', 'fotka.png', 'hudba.mp3', 'video.mp4', 'stranka.html', 'skript.js', 'styl.css', 'kod.py', 'program.exe', 'knihovna.dll', 'konfigurace.ini', 'data.json', 'text.txt', 'archiv.zip', 'zaloha.tar.gz', 'instalator.msi'],
    fileType: ['pdf', 'docx', 'pptx', 'xlsx', 'jpg', 'png', 'gif', 'mp3', 'mp4', 'avi', 'html', 'css', 'js', 'py', 'java', 'cpp', 'exe', 'dll', 'zip', 'rar'],
  },
  science: {
    chemicalElement: ['Vodík', 'Helium', 'Lithium', 'Beryllium', 'Bor', 'Uhlík', 'Dusík', 'Kyslík', 'Fluor', 'Neon', 'Sodík', 'Hořčík', 'Hliník', 'Křemík', 'Fosfor', 'Síra', 'Chlor', 'Argon', 'Draslík', 'Vápník', 'Železo', 'Měď', 'Zinek', 'Stříbro', 'Zlato'],
    unit: ['Metr', 'Kilogram', 'Sekunda', 'Ampér', 'Kelvin', 'Mol', 'Kandela', 'Litr', 'Newton', 'Pascal', 'Joule', 'Watt', 'Volt', 'Ohm', 'Hertz', 'Stupeň Celsia'],
    constant: ['Rychlost světla', 'Planckova konstanta', 'Gravitační konstanta', 'Avogadrova konstanta', 'Boltzmannova konstanta', 'Elementární náboj', 'Hmotnost elektronu', 'Hmotnost protonu'],
    field: ['Fyzika', 'Chemie', 'Biologie', 'Matematika', 'Astronomie', 'Geologie', 'Meteorologie', 'Oceanografie', 'Ekologie', 'Genetika', 'Mikrobiologie', 'Botanika', 'Zoologie', 'Biochemie', 'Biofyzika'],
  },
  color: {
    human: ['Červená', 'Modrá', 'Zelená', 'Žlutá', 'Černá', 'Bílá', 'Šedá', 'Hnědá', 'Růžová', 'Fialová', 'Oranžová', 'Tyrkysová', 'Námořnická modrá', 'Béžová', 'Stříbrná', 'Zlatá', 'Bordó', 'Limetková', 'Azurová', 'Purpurová'],
  },
}
